BEGIN;

INSERT INTO public.search_locations (code, name_th, name_en, location_type, priority)
VALUES
    ('province-krabi', 'กระบี่', 'Krabi', 'province', 50),
    ('province-bangkok', 'กรุงเทพมหานคร', 'Bangkok', 'province', 100),
    ('province-kanchanaburi', 'กาญจนบุรี', 'Kanchanaburi', 'province', 50),
    ('province-kalasin', 'กาฬสินธุ์', 'Kalasin', 'province', 50),
    ('province-kamphaeng-phet', 'กำแพงเพชร', 'Kamphaeng Phet', 'province', 50),
    ('province-khon-kaen', 'ขอนแก่น', 'Khon Kaen', 'province', 65),
    ('province-chanthaburi', 'จันทบุรี', 'Chanthaburi', 'province', 50),
    ('province-chachoengsao', 'ฉะเชิงเทรา', 'Chachoengsao', 'province', 55),
    ('province-chon-buri', 'ชลบุรี', 'Chon Buri', 'province', 85),
    ('province-chai-nat', 'ชัยนาท', 'Chai Nat', 'province', 50),
    ('province-chaiyaphum', 'ชัยภูมิ', 'Chaiyaphum', 'province', 50),
    ('province-chumphon', 'ชุมพร', 'Chumphon', 'province', 50),
    ('province-chiang-rai', 'เชียงราย', 'Chiang Rai', 'province', 60),
    ('province-chiang-mai', 'เชียงใหม่', 'Chiang Mai', 'province', 90),
    ('province-trang', 'ตรัง', 'Trang', 'province', 50),
    ('province-trat', 'ตราด', 'Trat', 'province', 50),
    ('province-tak', 'ตาก', 'Tak', 'province', 50),
    ('province-nakhon-nayok', 'นครนายก', 'Nakhon Nayok', 'province', 50),
    ('province-nakhon-pathom', 'นครปฐม', 'Nakhon Pathom', 'province', 60),
    ('province-nakhon-phanom', 'นครพนม', 'Nakhon Phanom', 'province', 50),
    ('province-nakhon-ratchasima', 'นครราชสีมา', 'Nakhon Ratchasima', 'province', 65),
    ('province-nakhon-si-thammarat', 'นครศรีธรรมราช', 'Nakhon Si Thammarat', 'province', 55),
    ('province-nakhon-sawan', 'นครสวรรค์', 'Nakhon Sawan', 'province', 55),
    ('province-nonthaburi', 'นนทบุรี', 'Nonthaburi', 'province', 75),
    ('province-narathiwat', 'นราธิวาส', 'Narathiwat', 'province', 50),
    ('province-nan', 'น่าน', 'Nan', 'province', 50),
    ('province-bueng-kan', 'บึงกาฬ', 'Bueng Kan', 'province', 50),
    ('province-buri-ram', 'บุรีรัมย์', 'Buri Ram', 'province', 55),
    ('province-pathum-thani', 'ปทุมธานี', 'Pathum Thani', 'province', 70),
    ('province-prachuap-khiri-khan', 'ประจวบคีรีขันธ์', 'Prachuap Khiri Khan', 'province', 55),
    ('province-prachin-buri', 'ปราจีนบุรี', 'Prachin Buri', 'province', 55),
    ('province-pattani', 'ปัตตานี', 'Pattani', 'province', 50),
    ('province-phra-nakhon-si-ayutthaya', 'พระนครศรีอยุธยา', 'Phra Nakhon Si Ayutthaya', 'province', 60),
    ('province-phayao', 'พะเยา', 'Phayao', 'province', 50),
    ('province-phang-nga', 'พังงา', 'Phang Nga', 'province', 55),
    ('province-phatthalung', 'พัทลุง', 'Phatthalung', 'province', 50),
    ('province-phichit', 'พิจิตร', 'Phichit', 'province', 50),
    ('province-phitsanulok', 'พิษณุโลก', 'Phitsanulok', 'province', 55),
    ('province-phetchaburi', 'เพชรบุรี', 'Phetchaburi', 'province', 55),
    ('province-phetchabun', 'เพชรบูรณ์', 'Phetchabun', 'province', 50),
    ('province-phrae', 'แพร่', 'Phrae', 'province', 50),
    ('province-phuket', 'ภูเก็ต', 'Phuket', 'province', 85),
    ('province-maha-sarakham', 'มหาสารคาม', 'Maha Sarakham', 'province', 50),
    ('province-mukdahan', 'มุกดาหาร', 'Mukdahan', 'province', 50),
    ('province-mae-hong-son', 'แม่ฮ่องสอน', 'Mae Hong Son', 'province', 50),
    ('province-yasothon', 'ยโสธร', 'Yasothon', 'province', 50),
    ('province-yala', 'ยะลา', 'Yala', 'province', 50),
    ('province-roi-et', 'ร้อยเอ็ด', 'Roi Et', 'province', 50),
    ('province-ranong', 'ระนอง', 'Ranong', 'province', 50),
    ('province-rayong', 'ระยอง', 'Rayong', 'province', 70),
    ('province-ratchaburi', 'ราชบุรี', 'Ratchaburi', 'province', 55),
    ('province-lop-buri', 'ลพบุรี', 'Lop Buri', 'province', 50),
    ('province-lampang', 'ลำปาง', 'Lampang', 'province', 50),
    ('province-lamphun', 'ลำพูน', 'Lamphun', 'province', 50),
    ('province-loei', 'เลย', 'Loei', 'province', 50),
    ('province-si-sa-ket', 'ศรีสะเกษ', 'Si Sa Ket', 'province', 50),
    ('province-sakon-nakhon', 'สกลนคร', 'Sakon Nakhon', 'province', 50),
    ('province-songkhla', 'สงขลา', 'Songkhla', 'province', 60),
    ('province-satun', 'สตูล', 'Satun', 'province', 50),
    ('province-samut-prakan', 'สมุทรปราการ', 'Samut Prakan', 'province', 80),
    ('province-samut-songkhram', 'สมุทรสงคราม', 'Samut Songkhram', 'province', 50),
    ('province-samut-sakhon', 'สมุทรสาคร', 'Samut Sakhon', 'province', 60),
    ('province-sa-kaeo', 'สระแก้ว', 'Sa Kaeo', 'province', 50),
    ('province-saraburi', 'สระบุรี', 'Saraburi', 'province', 55),
    ('province-sing-buri', 'สิงห์บุรี', 'Sing Buri', 'province', 50),
    ('province-sukhothai', 'สุโขทัย', 'Sukhothai', 'province', 50),
    ('province-suphan-buri', 'สุพรรณบุรี', 'Suphan Buri', 'province', 50),
    ('province-surat-thani', 'สุราษฎร์ธานี', 'Surat Thani', 'province', 60),
    ('province-surin', 'สุรินทร์', 'Surin', 'province', 50),
    ('province-nong-khai', 'หนองคาย', 'Nong Khai', 'province', 50),
    ('province-nong-bua-lam-phu', 'หนองบัวลำภู', 'Nong Bua Lam Phu', 'province', 50),
    ('province-ang-thong', 'อ่างทอง', 'Ang Thong', 'province', 50),
    ('province-amnat-charoen', 'อำนาจเจริญ', 'Amnat Charoen', 'province', 50),
    ('province-udon-thani', 'อุดรธานี', 'Udon Thani', 'province', 60),
    ('province-uttaradit', 'อุตรดิตถ์', 'Uttaradit', 'province', 50),
    ('province-uthai-thani', 'อุทัยธานี', 'Uthai Thani', 'province', 50),
    ('province-ubon-ratchathani', 'อุบลราชธานี', 'Ubon Ratchathani', 'province', 60)
ON CONFLICT (code) DO UPDATE SET
    name_th = EXCLUDED.name_th,
    name_en = EXCLUDED.name_en,
    location_type = EXCLUDED.location_type,
    priority = EXCLUDED.priority,
    is_active = true,
    updated_at = now();

UPDATE public.search_locations location
SET aliases = (
    SELECT array_agg(DISTINCT alias)
    FROM unnest(location.aliases || ARRAY[
        location.name_th,
        lower(location.name_en),
        replace(lower(location.name_en), ' ', '')
    ]) AS alias
), updated_at = now()
WHERE location_type = 'province';

COMMIT;
