BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
 PERFORM pg_advisory_xact_lock(hashtext('sam-import-19382'));
 IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A0708' OR source_url ~ '[?&]id=19382(&|$)' OR source_url LIKE '%keyref=6007623%') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='93c08330-cdd1-4be3-81b2-1d81cbb5b092' OR slug='sam-direct-sale-land-motorway-7-bang-phli-noi-3a0708' OR description ILIKE '%3A0708%' OR (abs(latitude-13.625667461799871)<0.0001 AND abs(longitude-100.91426422959044)<0.0001 AND abs(land_area_sqm-19930.4)<1)) THEN
 RAISE NOTICE 'SAM 3A0708 already exists; skipping duplicate import'; RETURN; END IF;
 SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
 SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
 IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('93c08330-cdd1-4be3-81b2-1d81cbb5b092', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'residence', 'sale', 'land_plot', 'ขายตรง SAM ที่ดิน 12-1-82.6 ไร่ ติดถนนคู่ขนานมอเตอร์เวย์ บางบ่อ มีแนวโครงการคลองผ่าน', 'ที่ดินเปล่า 7 แปลงติดต่อกัน ตำบลบางพลีน้อย อำเภอบางบ่อ จังหวัดสมุทรปราการ ติดถนนคู่ขนานทางหลวงพิเศษหมายเลข 7 เนื้อที่รวม 12 ไร่ 1 งาน 82.6 ตร.ว. หรือ 4,982.6 ตร.ว. (19,930.4 ตร.ม.) ราคาเสนอขายจาก SAM 29,418,000 บาท ประมาณ 5,904 บาท/ตร.ว. รหัสทรัพย์ 3A0708

แปลงที่ดินมีรูปคล้ายสี่เหลี่ยมคางหมู ด้านทิศตะวันตกติดถนนหน้ากว้างประมาณ 76 เมตร ลึกสุดประมาณ 380 เมตร ระดับที่ดินต่ำกว่าถนนประมาณ 1 เมตร ถนนคู่ขนานหน้าทรัพย์เป็นทางสาธารณประโยชน์ ผิวลาดยางกว้างประมาณ 6 เมตร เขตทางประมาณ 10 เมตร ตามข้อมูล SAM

ข้อมูลสำคัญ: SAM ระบุว่ามีแนวโครงการคลองระบายน้ำหลากป่าสัก–อ่าวไทย ระยะที่ 1 ผ่านที่ตั้งทรัพย์บริเวณสะพานข้ามคลอง โดยเกี่ยวข้องกับโฉนด 27053 เต็มทั้งแปลง และโฉนด 27054 รวมเนื้อที่ตามหมายเหตุประมาณ 1 ไร่ 1 งาน 68.7 ตร.ว. (2,274.8 ตร.ม.) ต้องยืนยันแนวโครงการ ขอบเขตที่ได้รับผลกระทบ สถานะดำเนินการ สิทธิที่เกี่ยวข้อง และพื้นที่คงเหลือล่าสุดกับ SAM และหน่วยงานเจ้าของโครงการก่อนเสนอซื้อ

โฉนดที่ดินทั้งหมด 7 ฉบับ: 26361, 27053, 27054, 27055, 27056, 27057 และ 27058 ต้นทางระบุเขตผังเมืองสีเขียว อยู่ในย่านเกษตรกรรม และใช้ประโยชน์ทำนา พื้นที่รอบข้างเป็นนาข้าวและบ่อปลา ข้อมูลนี้เป็นการใช้ประโยชน์ตามต้นทาง ผู้สนใจควรตรวจข้อกำหนดการใช้ที่ดินตามแผนที่ผังเมืองปัจจุบันและลักษณะโครงการที่ต้องการพัฒนา

การเดินทาง: ใช้ถนนคู่ขนานมอเตอร์เวย์จากกรุงเทพฯ มุ่งหน้าอำเภอบางปะกง ข้ามคลองพระยานาคราช ผ่านบริเวณ กม.35 ก่อนถึงแยกถนนสายบ้านคลองพระยานาคประมาณ 850 เมตร ทรัพย์อยู่ด้านซ้ายมือ ใช้พิกัดที่ผู้ดูแลให้ 13.625667461799871, 100.91426422959044 ซึ่งอยู่ห่างจากหมุด SAM ประมาณ 6 เมตร หมุดใช้บอกตำแหน่งโดยประมาณ ไม่ใช่แนวเขตที่ดิน

หน้า SAM แสดงสถานะซื้อตรงและราคาประกาศขายข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อฝ่ายขาย SAM โทร 02-686-1888 หรือ LINE @samline พร้อมแจ้งรหัส 3A0708 เพื่อยืนยันสถานะพร้อมขาย ราคา และเงื่อนไขล่าสุด

ภาพจริงจาก SAM แสดงวันที่ 12 มีนาคม 2564 พร้อมผังแปลง ภาพตำแหน่ง และแผนที่การเดินทาง ควรนัดดูสภาพปัจจุบันและตรวจระดับดิน การระบายน้ำ ทางเข้าออก และการใช้ประโยชน์จริงก่อนตัดสินใจ', 29418000, false, 19930.4, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ที่ดิน 7 แปลง ติดถนนคู่ขนานมอเตอร์เวย์ กม.35', 'ข้ามคลองพระยานาคราช มุ่งหน้าบางปะกง', 'ถนนคู่ขนานทางหลวงพิเศษหมายเลข 7', 13.625667461799871, 100.91426422959044, 'สมุทรปราการ', 'บางบ่อ', 'บางพลีน้อย', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-land-motorway-7-bang-phli-noi-3a0708') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'agriculture') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 29418000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"ที่ดินเปล่า","official_page_reference_code":"3A0708","source_page_id":19382,"title_document_type":"chanote","title_deed_numbers":["26361","27053","27054","27055","27056","27057","27058"],"title_document_count":7,"plot_count":7,"land_area_rai":12,"land_area_ngan":1,"land_area_square_wah_remainder":82.6,"land_area_square_wah":4982.6,"land_area_sqm":19930.4,"vacant_land":true,"plot_shape":"approximately_trapezoidal","west_road_frontage_m_approx":76,"maximum_depth_m_approx":380,"land_level_below_road_m_approx":1,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":10,"planning_zone_th":"เขตสีเขียว","current_use_th":"นาข้าว","canal_project_corridor_reported":true,"canal_project_name_th":"โครงการคลองระบายน้ำหลากป่าสัก–อ่าวไทย ระยะที่ 1","source_affected_title_deeds":["27053","27054"],"source_deed_27053_entire_plot_affected":true,"source_reported_combined_affected_area_sqm":2274.8,"source_reported_combined_affected_area_square_wah":568.7,"project_status_requires_confirmation":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","price_per_square_wah":5904,"status_checked_on":"2026-09-11","source_property_photo_dates_displayed":["2021-03-12"],"administrator_coordinates_used":true,"source_coordinates_rounded":"13.625700,100.914303","online_pin_not_boundary_evidence":true}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM asset page 19382 identifies SAM as direct-sale publisher and contact for 3A0708.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรงจาก SAM รหัส 3A0708', 'Direct purchase from SAM, reference 3A0708', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'announced_sale_price', 'ราคาประกาศขาย', 'Announced price', '29,418,000 บาท ประมาณ 5,904 บาท/ตร.ว.', 'THB 29,418,000, approximately THB 5,904 per sq.wah', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'canal_project_corridor', 'มีแนวโครงการคลองระบายน้ำผ่านทรัพย์', 'Canal project corridor crosses the property', 'SAM ระบุโฉนด 27053 เต็มทั้งแปลงและโฉนด 27054 รวมประมาณ 1 ไร่ 1 งาน 68.7 ตร.ว. ต้องยืนยันแนวและสถานะล่าสุด', 'SAM names all of deed 27053 and deed 27054, with a combined stated area of approximately 568.7 sq.wah; confirm the latest corridor and status', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'frontage', 'หน้ากว้างและถนน', 'Frontage and road', 'หน้ากว้างด้านตะวันตกประมาณ 76 ม. ถนนลาดยางกว้างประมาณ 6 ม. เขตทางประมาณ 10 ม.', 'Approx. 76 m western frontage, 6 m asphalt road and 10 m right of way', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'land_level', 'ระดับดินและการใช้ประโยชน์', 'Land level and use', 'ต่ำกว่าถนนประมาณ 1 ม. ต้นทางระบุใช้ทำนา เขตผังเมืองสีเขียว', 'Approx. 1 m below road; SAM reports rice cultivation and green planning zoning', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ที่ดินและถนนคู่ขนานมอเตอร์เวย์หน้าทรัพย์', 'ที่ดินและถนนคู่ขนานมอเตอร์เวย์หน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/19382/20211008092340_3A0708P2_64.jpg', '/listing-media/sam/3a0708/01.webp', 'image/webp', 32562, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวที่ดินติดถนนอีกมุม', 'แนวที่ดินติดถนนอีกมุม', 'https://npa.sam.or.th/site/images/npa/19382/3A0708P1_64.jpg', '/listing-media/sam/3a0708/02.webp', 'image/webp', 40768, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพพื้นที่เกษตรภายในแปลง', 'สภาพพื้นที่เกษตรภายในแปลง', 'https://npa.sam.or.th/site/images/npa/19382/3A0708P3_64.jpg', '/listing-media/sam/3a0708/03.webp', 'image/webp', 45050, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณที่ดินและป้ายขาย SAM', 'บริเวณที่ดินและป้ายขาย SAM', 'https://npa.sam.or.th/site/images/npa/19382/3A0708P4_64.jpg', '/listing-media/sam/3a0708/04.webp', 'image/webp', 40636, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดิน 7 แปลงติดต่อกัน', 'ผังที่ดิน 7 แปลงติดต่อกัน', 'https://npa.sam.or.th/site/images/npa/19382/3A0708C1_64.jpg', '/listing-media/sam/3a0708/05.webp', 'image/webp', 12764, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแนวโครงการคลองระบายน้ำที่เกี่ยวข้องกับทรัพย์', 'ผังแนวโครงการคลองระบายน้ำที่เกี่ยวข้องกับทรัพย์', 'https://npa.sam.or.th/site/images/npa/19382/20251015143917_3A0708C3_67.jpg', '/listing-media/sam/3a0708/06.webp', 'image/webp', 34706, 478, 480, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ภาพตำแหน่งแปลงที่ดินจาก SAM', 'ภาพตำแหน่งแปลงที่ดินจาก SAM', 'https://npa.sam.or.th/site/images/npa/19382/20251015131337_3A0708C2_67.jpg', '/listing-media/sam/3a0708/07.webp', 'image/webp', 96816, 647, 517, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางไปทรัพย์ 3A0708', 'แผนที่การเดินทางไปทรัพย์ 3A0708', 'https://npa.sam.or.th/site/images/npa/19382/20211008092340_3A0708M1_64.jpg', '/listing-media/sam/3a0708/08.webp', 'image/webp', 35668, 785, 600, 80, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=19382&keyref=6007623', '3A0708', now(), 'Official SAM page captured 2026-09-11. Seven adjoining agricultural land plots, direct purchase THB 29,418,000. Material canal project note retained in both languages and terms. The stated combined area for deeds 27053 and 27054 is recorded as source-reported, not independently surveyed. Eight original images retained with captions and dates; optimized WebP copies, no added watermark or visual retouching. Duplicate search included every listing status and deleted records, source code, page ID, keyref, title deeds, area and nearby coordinates; no matches before import. Import has a duplicate guard and advisory transaction lock.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 12 Rai Land by Motorway 7, Bang Bo, with Canal Project Corridor', 'Seven adjoining vacant land plots in Bang Phli Noi, Bang Bo, Samut Prakan, beside the Motorway 7 frontage road. Total area: 12 rai 1 ngan 82.6 sq.wah, equivalent to 4,982.6 sq.wah or 19,930.4 sq.m. SAM announced price: THB 29,418,000, approximately THB 5,904 per sq.wah. Asset reference: 3A0708.

The approximately trapezoidal site has 76 metres of western road frontage and a maximum depth of approximately 380 metres. Land is approximately one metre below the road. SAM describes the public asphalt frontage road as approximately six metres wide within a ten-metre right of way.

Material source note: the Pa Sak–Gulf of Thailand flood diversion canal project, Phase 1, crosses the property near a canal bridge. SAM names the entirety of title deed 27053 and deed 27054, with a stated combined area of approximately 1 rai 1 ngan 68.7 sq.wah (2,274.8 sq.m.). Confirm the project corridor, affected extent, current implementation stage, relevant rights and remaining area with SAM and the responsible authority before submitting an offer.

Seven title deeds: 26361, 27053, 27054, 27055, 27056, 27057 and 27058. SAM identifies green planning zoning, agricultural surroundings and rice cultivation on the land, with rice fields and fish ponds nearby. Confirm current planning provisions for any intended development.

Directions from Bangkok toward Bang Pakong follow the Motorway 7 frontage road across Khlong Phraya Nakkharat, past kilometre 35. The site is on the left approximately 850 metres before the Ban Khlong Phraya Nak road junction. Administrator coordinates are used, approximately six metres from the SAM pin; the pin is not a boundary survey.

SAM showed direct-purchase status and this announced price on 11 September 2026. Contact SAM Sales at 02-686-1888 or LINE @samline, quoting 3A0708, to confirm availability, current price and terms. Original property photos display 12 March 2021. Inspect current site conditions, land level, drainage, access and use.', 'Seven plots by Motorway 7 frontage road, km 35', 'Across Khlong Phraya Nakkharat toward Bang Pakong', 'Motorway 7 Frontage Road', 'Bang Phli Noi', 'Bang Bo', 'Samut Prakan', 'SAM Land by Motorway 7, Bang Bo — THB 29.418M', 'Seven plots, 12 rai 1 ngan 82.6 sq.wah, 76 m frontage. SAM 3A0708. A canal project corridor affects the site; see details and plans.', 'published', 'ai_assisted', now(), 'sam direct sale: 12 rai land by motorway 7, bang bo, with canal project corridor seven adjoining vacant land plots in bang phli noi, bang bo, samut prakan, beside the motorway 7 frontage road. total area: 12 rai 1 ngan 82.6 sq.wah, equivalent to 4,982.6 sq.wah or 19,930.4 sq.m. sam announced price: thb 29,418,000, approximately thb 5,904 per sq.wah. asset reference: 3a0708.

the approximately trapezoidal site has 76 metres of western road frontage and a maximum depth of approximately 380 metres. land is approximately one metre below the road. sam describes the public asphalt frontage road as approximately six metres wide within a ten-metre right of way.

material source note: the pa sak–gulf of thailand flood diversion canal project, phase 1, crosses the property near a canal bridge. sam names the entirety of title deed 27053 and deed 27054, with a stated combined area of approximately 1 rai 1 ngan 68.7 sq.wah (2,274.8 sq.m.). confirm the project corridor, affected extent, current implementation stage, relevant rights and remaining area with sam and the responsible authority before submitting an offer.

seven title deeds: 26361, 27053, 27054, 27055, 27056, 27057 and 27058. sam identifies green planning zoning, agricultural surroundings and rice cultivation on the land, with rice fields and fish ponds nearby. confirm current planning provisions for any intended development.

directions from bangkok toward bang pakong follow the motorway 7 frontage road across khlong phraya nakkharat, past kilometre 35. the site is on the left approximately 850 metres before the ban khlong phraya nak road junction. administrator coordinates are used, approximately six metres from the sam pin; the pin is not a boundary survey.

sam showed direct-purchase status and this announced price on 11 september 2026. contact sam sales at 02-686-1888 or line @samline, quoting 3a0708, to confirm availability, current price and terms. original property photos display 12 march 2021. inspect current site conditions, land level, drainage, access and use.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=19382&keyref=6007623', 'Official SAM NPA page identifies SAM as direct-sale publisher for 3A0708; verified against the source page on 2026-09-11.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '93c08330-cdd1-4be3-81b2-1d81cbb5b092', '{"reference_code":"3A0708","source_page_id":19382,"source_image_count":8,"canal_project_corridor_reported":true,"duplicate_check":"no matches; source, deeds, area, nearby coordinates; all statuses"}'::jsonb) ;
END $$;
COMMIT;
