BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-23249'));
-- keyref is shared across different SAM properties; it is not a property identifier.
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='BL0106' OR source_url ~ '[?&]id=23249(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='a5cb59ce-bd39-4010-abf6-d98b4dc3e3e1' OR slug='sam-direct-sale-factory-office-houses-ban-chang-bl0106' OR description ILIKE '%BL0106%' OR (abs(latitude-12.722569906166047)<0.0001 AND abs(longitude-101.00134685755232)<0.0001 AND abs(land_area_sqm-5584.8)<1)) THEN RAISE NOTICE 'SAM BL0106 already exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('a5cb59ce-bd39-4010-abf6-d98b4dc3e3e1', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'factory', 'business', 'sale', 'whole_property', '96/60, 96/62', 'ขายตรง SAM โรงงานพร้อมสำนักงานและบ้านพัก บ้านฉาง ระยอง 3-1-96.2 ไร่ ราคา 22.337 ล้านบาท', 'โรงงาน/โกดังพร้อมสำนักงานและบ้านพัก เลขที่ 96/60 และ 96/62 ตำบลสำนักท้อน อำเภอบ้านฉาง จังหวัดระยอง บนที่ดิน 3 แปลงติดต่อกัน เนื้อที่รวม 3 ไร่ 1 งาน 96.2 ตร.ว. หรือ 1,396.2 ตร.ว. (5,584.8 ตร.ม.) โฉนดเลขที่ 14450, 14451 และ 46654 ราคาประกาศขายจาก SAM 22,337,000 บาท รหัสทรัพย์ BL0106

ที่ดินรูปคล้ายสี่เหลี่ยมผืนผ้า ด้านทิศเหนือติดซอยเทศบาล 48 (ซอยสระแก้ว ซอย 2) หน้ากว้างประมาณ 56 เมตร ลึกสุดประมาณ 105 เมตร ถนนสาธารณประโยชน์ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 8 เมตร ต้นทางระบุเขตผังเมืองสีส้ม อยู่ในย่านที่อยู่อาศัยและเกษตรกรรม

รายการตามทะเบียนที่ SAM รับโอนมี 6 รายการ: บ้านพักอาศัยตึกชั้นครึ่งเลขที่ 96/62, โรงจอดรถ, ตึกแถวชั้นเดียว 5 คูหาไม่ปรากฏเลขทะเบียน, บ้านพักอาศัยตึกชั้นเดียวเลขที่ 96/60, อาคารสำนักงานชั้นเดียวไม่ปรากฏเลขทะเบียน และห้องน้ำ

ส่วนการสำรวจสภาพทรัพย์พบ 6 รายการ: อาคารโรงงานพร้อมสำนักงาน 1 ชั้น, อาคารสำนักงาน 1 ชั้น, บ้านพักอาศัยชั้นครึ่ง, อาคารห้องน้ำ, อาคารบ้านพักคนงาน 1 ชั้น และส่วนโล่งหลังคาคลุมจอดรถ รายการสำรวจต่างจากรายการทะเบียน โดย SAM ระบุว่าจะโอนให้ผู้ซื้อตามรายการสิ่งปลูกสร้างที่จดทะเบียนรับโอนเท่านั้น จึงต้องตรวจทะเบียน แบบแปลน ใบอนุญาต และรายการที่จะได้รับโอนให้ตรงกัน

ข้อควรทราบเรื่องการครอบครอง: SAM ระบุข้อมูล ณ วันที่ 7 มีนาคม 2568 ว่ามีผู้ใช้ประโยชน์ในทรัพย์ และขายตามสภาพ การเข้าครอบครองอาจต้องเจรจาหรือดำเนินการทางกฎหมายด้วยค่าใช้จ่ายของผู้ซื้อ ตามเงื่อนไขต้นทางไม่สามารถนำประเด็นนี้มาเป็นเหตุยกเลิกการเสนอซื้อหรือสัญญา หรือเรียกร้องจาก SAM ได้ ต้องสอบถามสถานะปัจจุบันและเงื่อนไขฉบับล่าสุดก่อนเสนอซื้อ

ข้อกำหนดด้านความสูงตามข้อมูล SAM: ทรัพย์อยู่ในเขตปลอดภัยในราชการทหารแห่งกองทัพเรือ ซึ่งต้นทางอ้างอิงข้อกำหนด พ.ศ.2536 และระบุความสูงอาคารไม่เกิน 45 เมตร อีกทั้งอยู่ในบริเวณใกล้เคียงสนามบินอู่ตะเภาตามประกาศที่ต้นทางอ้างอิง พ.ศ.2538 โดยต้องยื่นคำขอให้สำนักงานการบินพลเรือนแห่งประเทศไทยตรวจสอบข้อกำหนดความสูงที่ถูกต้อง ข้อมูล 45 เมตรนี้จึงไม่ใช่การรับรองว่าสามารถก่อสร้างได้ถึงระดับดังกล่าว และไม่ได้ยืนยันใบอนุญาตประกอบกิจการโรงงาน

การเดินทางตาม SAM: จากถนนสุขุมวิท (ทล.3) แยกอู่ตะเภา ใช้ถนนเลี่ยงเมืองสัตหีบ (ทล.332) มุ่งหน้าแยกเกษมพล ผ่านโรงเรียนพัฒเวชศึกษาและวิทยาลัยเทคโนโลยีพัฒนเวช เลี้ยวขวาเข้าถนนสำนักท้อน–สระแก้วประมาณ 960 เมตร แล้วเลี้ยวซ้ายเข้าซอยเทศบาล 48 ประมาณ 660 เมตร ทรัพย์อยู่ซ้ายมือ สถานที่ใกล้เคียงที่ต้นทางระบุ ได้แก่ โรงเรียนวัดสระแก้ว วัดสระแก้ว วิทยาลัยเทคโนโลยีพัฒนเวช และโรงเรียนพัฒเวชศึกษา

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อฝ่ายขาย SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส BL0106 เพื่อยืนยันสถานะพร้อมขาย การนัดชม ราคา การเข้าครอบครอง และเงื่อนไขล่าสุด

ใช้พิกัดผู้ดูแล 12.722569906166047, 101.00134685755232 ซึ่งใกล้เคียงหมุด SAM ภาพต้นทางแสดงวันที่ 7 มีนาคม 2568 แม้ชื่อไฟล์มีรหัสปี 69 รูปใช้ประกอบการดูสภาพในวันถ่าย ไม่ยืนยันสภาพหรือการครอบครองปัจจุบัน ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนห้องนอน จำนวนห้องน้ำ จำนวนที่จอดรถ กำลังไฟฟ้า ใบอนุญาตโรงงาน หรือรายการเครื่องจักรที่รวมในการขาย จึงควรตรวจข้อมูลเหล่านี้กับ SAM โดยตรง', 22337000, false, 5584.8, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '96/60, 96/62 ซอยเทศบาล 48 (ซอยสระแก้ว ซอย 2)', 'เข้าจากถนนสำนักท้อน–สระแก้ว', 'ซอยเทศบาล 48', 12.722569906166047, 101.00134685755232, 'ระยอง', 'บ้านฉาง', 'สำนักท้อน', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-factory-office-houses-ban-chang-bl0106') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'industrial') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'storage') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 22337000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'factory', 1, '{"source_property_category":"โรงงาน/โกดัง","official_page_reference_code":"BL0106","source_page_id":23249,"title_document_type":"chanote","title_deed_numbers":["14450","14451","46654"],"title_document_count":3,"plot_count":3,"land_area_rai":3,"land_area_ngan":1,"land_area_square_wah_remainder":96.2,"land_area_square_wah":1396.2,"land_area_sqm":5584.8,"plot_shape":"approximately_rectangular","north_road_frontage_m_approx":56,"maximum_depth_m_approx":105,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":8,"planning_zone_th":"เขตสีส้ม","registered_structure_descriptions":["บ้านพักอาศัยตึกชั้นครึ่ง 96/62","โรงจอดรถ","ตึกแถวชั้นเดียว 5 คูหา ไม่ปรากฏเลขทะเบียน","บ้านพักอาศัยตึกชั้นเดียว 96/60","อาคารสำนักงานชั้นเดียว ไม่ปรากฏเลขทะเบียน","ห้องน้ำ"],"surveyed_structure_descriptions":["อาคารโรงงานพร้อมสำนักงาน 1 ชั้น","อาคารสำนักงาน 1 ชั้น","บ้านพักอาศัยชั้นครึ่ง","อาคารห้องน้ำ","อาคารบ้านพักคนงาน 1 ชั้น","ส่วนโล่งหลังคาคลุมจอดรถ"],"registered_and_surveyed_structure_discrepancy":true,"transfer_according_to_registered_structures_only":true,"source_occupancy_status":"in_use_by_occupants","source_occupancy_note_date":"2025-03-07","buyer_responsible_for_possession_costs":true,"military_safety_zone_reported":true,"source_reported_building_height_limit_m":45,"airport_vicinity_restrictions_reported":true,"caat_height_confirmation_required":true,"factory_licence_not_published":true,"machinery_inclusion_not_published":true,"usable_area_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_property_photo_dates_displayed":["2025-03-07"],"source_photo_filename_year_code":69,"administrator_coordinates_used":true,"source_coordinates_rounded":"12.722571,101.001349","online_pin_not_boundary_evidence":true}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 23249 identifies SAM as direct-sale publisher for BL0106. Occupancy, registered/surveyed building discrepancy and military/airport restrictions are retained.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรงจาก SAM รหัส BL0106 ราคา 22,337,000 บาท', 'Direct purchase from SAM, BL0106, THB 22,337,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'occupancy', 'มีผู้ใช้ประโยชน์ในทรัพย์', 'Occupancy disclosed', 'ข้อมูล SAM ณ 7 มี.ค. 2568 ขายตามสภาพ ผู้ซื้อรับภาระเจรจาหรือดำเนินคดีเพื่อเข้าครอบครอง ต้องยืนยันสถานะและเงื่อนไขล่าสุด', 'SAM note dated 7 March 2025: sold as-is; buyer bears negotiation or legal costs for possession; confirm current status and terms', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'transfer_inventory', 'รายการทะเบียนต่างจากที่สำรวจ', 'Registered and surveyed structures differ', 'SAM โอนตามรายการสิ่งปลูกสร้างที่จดทะเบียนรับโอนเท่านั้น ตรวจรายการทั้ง 6 ในรายละเอียดประกาศ', 'SAM transfers only the registered acquired structures; check both six-item lists in the description', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'height_restrictions', 'เขตทหารและบริเวณใกล้สนามบิน', 'Military and airport restrictions', 'ต้นทางระบุเพดานความสูง 45 ม. และต้องขอ CAAT ตรวจความสูงที่ถูกต้อง ไม่ใช่การรับรองสิทธิก่อสร้าง', 'Source cites 45 m and requires CAAT assessment of the applicable height; no construction entitlement is implied', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'permits', 'ใบอนุญาตและเครื่องจักร', 'Permits and machinery', 'ต้นทางไม่ระบุใบอนุญาตโรงงาน กำลังไฟฟ้า หรือเครื่องจักรที่รวมในการขาย ต้องยืนยันกับ SAM', 'Factory permits, electrical capacity and machinery included in the sale are not published; confirm with SAM', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'อาคารโรงงานพร้อมสำนักงานและลานด้านหน้า', 'อาคารโรงงานพร้อมสำนักงานและลานด้านหน้า', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P8_69.jpg', '/listing-media/sam/bl0106/06.webp', 'image/webp', 40880, 709, 529, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในส่วนอาคารโรงงานหลังคาสูง', 'ภายในส่วนอาคารโรงงานหลังคาสูง', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P9_69.jpg', '/listing-media/sam/bl0106/07.webp', 'image/webp', 67530, 708, 529, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านนอกสำนักงานติดอาคารโรงงาน', 'ด้านนอกสำนักงานติดอาคารโรงงาน', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P10_69.jpg', '/listing-media/sam/bl0106/08.webp', 'image/webp', 46768, 708, 527, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานภายในมองไปยังอาคารโรงงาน', 'ลานภายในมองไปยังอาคารโรงงาน', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P7_69.jpg', '/listing-media/sam/bl0106/05.webp', 'image/webp', 70148, 1020, 438, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าภายในและแนวอาคาร', 'ทางเข้าภายในและแนวอาคาร', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P6_69.jpg', '/listing-media/sam/bl0106/04.webp', 'image/webp', 98798, 1019, 412, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารสำนักงานภายในทรัพย์', 'อาคารสำนักงานภายในทรัพย์', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P12_69.jpg', '/listing-media/sam/bl0106/09.webp', 'image/webp', 97170, 708, 528, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและระเบียงอาคาร', 'โถงและระเบียงอาคาร', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P13_69.jpg', '/listing-media/sam/bl0106/10.webp', 'image/webp', 49482, 709, 529, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บ้านพักอาศัยภายในทรัพย์', 'บ้านพักอาศัยภายในทรัพย์', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P15_69.jpg', '/listing-media/sam/bl0106/12.webp', 'image/webp', 82746, 709, 529, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านข้างบ้านพักและพื้นที่ร่มรื่น', 'ด้านข้างบ้านพักและพื้นที่ร่มรื่น', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P16_69.jpg', '/listing-media/sam/bl0106/13.webp', 'image/webp', 81140, 709, 529, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารบ้านพักคนงาน', 'อาคารบ้านพักคนงาน', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P19_69.jpg', '/listing-media/sam/bl0106/16.webp', 'image/webp', 48320, 705, 527, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอาคารบ้านพัก', 'ห้องภายในอาคารบ้านพัก', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P20_69.jpg', '/listing-media/sam/bl0106/17.webp', 'image/webp', 14102, 707, 528, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่จอดรถมีหลังคาคลุม', 'พื้นที่จอดรถมีหลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P21_69.jpg', '/listing-media/sam/bl0106/18.webp', 'image/webp', 65500, 709, 528, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำภายในอาคาร', 'ห้องน้ำภายในอาคาร', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P14_69.jpg', '/listing-media/sam/bl0106/11.webp', 'image/webp', 52578, 709, 527, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารห้องน้ำแยก', 'อาคารห้องน้ำแยก', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P17_69.jpg', '/listing-media/sam/bl0106/14.webp', 'image/webp', 80478, 708, 528, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สุขภัณฑ์และทางเดินในอาคารห้องน้ำ', 'สุขภัณฑ์และทางเดินในอาคารห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P18_69.jpg', '/listing-media/sam/bl0106/15.webp', 'image/webp', 35404, 708, 528, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ประตูทางเข้าทรัพย์บนซอยเทศบาล 48', 'ประตูทางเข้าทรัพย์บนซอยเทศบาล 48', 'https://npa.sam.or.th/site/images/npa/23249/20260427105659_BL0106P3_69.jpg', '/listing-media/sam/bl0106/01.webp', 'image/webp', 44208, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวรั้วและถนนหน้าทรัพย์', 'แนวรั้วและถนนหน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P4_69.jpg', '/listing-media/sam/bl0106/02.webp', 'image/webp', 89058, 1020, 454, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ถนนหน้าทรัพย์อีกทิศทาง', 'ถนนหน้าทรัพย์อีกทิศทาง', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P5_69.jpg', '/listing-media/sam/bl0106/03.webp', 'image/webp', 99652, 1020, 454, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าจากถนนเลี่ยงเมืองสัตหีบ', 'ทางเข้าจากถนนเลี่ยงเมืองสัตหีบ', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P1_69.jpg', '/listing-media/sam/bl0106/19.webp', 'image/webp', 20912, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แยกเข้าซอยเทศบาล 48', 'แยกเข้าซอยเทศบาล 48', 'https://npa.sam.or.th/site/images/npa/23249/BL0106P2_69.jpg', '/listing-media/sam/bl0106/20.webp', 'image/webp', 23580, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดิน 3 แปลงและแนวถนน', 'ผังที่ดิน 3 แปลงและแนวถนน', 'https://npa.sam.or.th/site/images/npa/23249/20260427105659_BL0106C1_69.jpg', '/listing-media/sam/bl0106/21.webp', 'image/webp', 15496, 450, 450, 210, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งอาคารจากการสำรวจ SAM', 'ผังตำแหน่งอาคารจากการสำรวจ SAM', 'https://npa.sam.or.th/site/images/npa/23249/20260427105659_BL0106C2_69.jpg', '/listing-media/sam/bl0106/22.webp', 'image/webp', 41396, 785, 600, 220, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางไปทรัพย์ BL0106', 'แผนที่การเดินทางไปทรัพย์ BL0106', 'https://npa.sam.or.th/site/images/npa/23249/20260427105659_BL0106M_69.jpg', '/listing-media/sam/bl0106/23.webp', 'image/webp', 55734, 785, 600, 230, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=23249&keyref=6007623', 'BL0106', now(), 'Official SAM page captured 2026-09-11. Direct purchase THB 22,337,000, three plots, 5,584.8 sq.m. Registered and surveyed building inventories differ; SAM transfers registered structures only. Occupancy note dated 2025-03-07 and buyer possession obligations retained. Military safety zone, source-stated 45 m limit and separate CAAT airport height assessment retained as source claims. Photos display 2025-03-07 despite filenames using year code 69. All 23 images preserved and optimized without retouching; factory image chosen as cover. All-status duplicate search by property code, page ID, deeds, address, area and nearby coordinates found no matches. keyref=6007623 is shared with other properties and is deliberately not used as a unique identifier.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Factory, Offices and Houses on 3 Rai in Ban Chang, THB 22.337M', 'Factory/warehouse premises with offices and residential buildings at 96/60 and 96/62, Samnak Thon, Ban Chang, Rayong. Three adjoining plots, deeds 14450, 14451 and 46654, total 3 rai 1 ngan 96.2 sq.wah (1,396.2 sq.wah / 5,584.8 sq.m.). SAM announced price THB 22,337,000; asset BL0106.

The roughly rectangular site has approximately 56 metres of northern frontage and a maximum depth of approximately 105 metres. The public concrete road, Soi Thetsaban 48 (Sa Kaeo Soi 2), is approximately six metres wide within an eight-metre right of way. SAM reports orange planning zoning and residential and agricultural surroundings.

Registered transferred structures: a one-and-a-half-storey house at 96/62; a garage; five single-storey shophouse units without a stated registration number; a single-storey house at 96/60; a single-storey office without a stated registration number; and a bathroom building.

Surveyed structures: a single-storey factory with office; a separate single-storey office; a one-and-a-half-storey house; a bathroom building; single-storey worker accommodation; and an open-sided covered parking area. These descriptions differ. SAM states that transfer to the buyer follows only the registered structures it acquired. Check registration, approved plans, permits and the exact transfer inventory.

Occupancy: SAM''s note dated 7 March 2025 states that people use the property. It is sold as-is. Obtaining possession may require negotiation or legal action at the buyer''s expense. Under the source terms, this issue does not entitle the buyer to cancel the offer or sale agreement or claim against SAM. Confirm current occupancy and the latest sale terms.

Height restrictions: SAM places the site within a Royal Thai Navy military safety zone, citing 1993 provisions and a stated 45-metre building height limit. It also cites 1995 provisions for the U-Tapao Airport vicinity and instructs relevant parties to request a precise height assessment from the Civil Aviation Authority of Thailand. The source''s 45-metre figure is not a guarantee of permitted construction height or confirmation of a factory operating licence.

From the U-Tapao junction on Sukhumvit Road (Highway 3), take the Sattahip bypass (Highway 332) toward Kasem Phon. Turn right into Samnak Thon–Sa Kaeo Road for approximately 960 metres, then left into Soi Thetsaban 48 for approximately 660 metres; the property is on the left. Nearby source-listed places include Wat Sa Kaeo, Wat Sa Kaeo School, Phatthanawet Technology College and Phatthawet Suksa School.

SAM showed direct-purchase status and this announced price on 11 September 2026. Contact SAM Sales at 02-686-1888, sales@sam.or.th or LINE @samline, quoting BL0106. Administrator coordinates are used. Source photos display 7 March 2025 despite filenames containing a 2026 year code. Total usable area, bedrooms, bathroom count, parking capacity, electrical supply capacity, factory permits and machinery included in the sale are not published.', '96/60, 96/62, Soi Thetsaban 48 (Sa Kaeo Soi 2)', 'Access from Samnak Thon–Sa Kaeo Road', 'Soi Thetsaban 48', 'Samnak Thon', 'Ban Chang', 'Rayong', 'SAM Factory, Offices and Houses in Ban Chang — THB 22.337M', 'SAM BL0106: factory premises on 5,584.8 sq.m. in Ban Chang. Occupancy, registered-building discrepancies and airport height restrictions disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: factory, offices and houses on 3 rai in ban chang, thb 22.337m factory/warehouse premises with offices and residential buildings at 96/60 and 96/62, samnak thon, ban chang, rayong. three adjoining plots, deeds 14450, 14451 and 46654, total 3 rai 1 ngan 96.2 sq.wah (1,396.2 sq.wah / 5,584.8 sq.m.). sam announced price thb 22,337,000; asset bl0106.

the roughly rectangular site has approximately 56 metres of northern frontage and a maximum depth of approximately 105 metres. the public concrete road, soi thetsaban 48 (sa kaeo soi 2), is approximately six metres wide within an eight-metre right of way. sam reports orange planning zoning and residential and agricultural surroundings.

registered transferred structures: a one-and-a-half-storey house at 96/62; a garage; five single-storey shophouse units without a stated registration number; a single-storey house at 96/60; a single-storey office without a stated registration number; and a bathroom building.

surveyed structures: a single-storey factory with office; a separate single-storey office; a one-and-a-half-storey house; a bathroom building; single-storey worker accommodation; and an open-sided covered parking area. these descriptions differ. sam states that transfer to the buyer follows only the registered structures it acquired. check registration, approved plans, permits and the exact transfer inventory.

occupancy: sam''s note dated 7 march 2025 states that people use the property. it is sold as-is. obtaining possession may require negotiation or legal action at the buyer''s expense. under the source terms, this issue does not entitle the buyer to cancel the offer or sale agreement or claim against sam. confirm current occupancy and the latest sale terms.

height restrictions: sam places the site within a royal thai navy military safety zone, citing 1993 provisions and a stated 45-metre building height limit. it also cites 1995 provisions for the u-tapao airport vicinity and instructs relevant parties to request a precise height assessment from the civil aviation authority of thailand. the source''s 45-metre figure is not a guarantee of permitted construction height or confirmation of a factory operating licence.

from the u-tapao junction on sukhumvit road (highway 3), take the sattahip bypass (highway 332) toward kasem phon. turn right into samnak thon–sa kaeo road for approximately 960 metres, then left into soi thetsaban 48 for approximately 660 metres; the property is on the left. nearby source-listed places include wat sa kaeo, wat sa kaeo school, phatthanawet technology college and phatthawet suksa school.

sam showed direct-purchase status and this announced price on 11 september 2026. contact sam sales at 02-686-1888, sales@sam.or.th or line @samline, quoting bl0106. administrator coordinates are used. source photos display 7 march 2025 despite filenames containing a 2026 year code. total usable area, bedrooms, bathroom count, parking capacity, electrical supply capacity, factory permits and machinery included in the sale are not published.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=23249&keyref=6007623', 'Official SAM NPA page 23249 identifies SAM as asset holder and direct-sale contact for BL0106.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'a5cb59ce-bd39-4010-abf6-d98b4dc3e3e1', '{"reference_code":"BL0106","source_page_id":23249,"source_image_count":23,"occupancy_disclosed":true,"building_discrepancy_disclosed":true,"height_restrictions_disclosed":true,"duplicate_check":"no matches; keyref is not unique"}'::jsonb) ;
END $$;
COMMIT;
