BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-22441'));
-- keyref is shared across different SAM assets, not a unique identifier.
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code) IN ('HL0330','3A0248') OR source_url ~ '[?&]id=22441(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='51c603c8-9858-412b-a3d3-5eb3f6a661df' OR slug='sam-direct-sale-house-warehouse-office-ban-suan-chonburi-hl0330' OR description ILIKE '%HL0330%' OR (abs(latitude-13.363208337180431)<0.0001 AND abs(longitude-101.0021857853247)<0.0001 AND abs(land_area_sqm-2868)<1)) THEN RAISE NOTICE 'SAM HL0330 or alternate map reference exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('51c603c8-9858-412b-a3d3-5eb3f6a661df', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'detached_house', 'residence', 'sale', 'whole_property', '28/3', 'ขายตรง SAM บ้านเดี่ยวพร้อมโกดังและสำนักงาน บ้านสวน ชลบุรี 717 ตร.ว. ราคา 18.733 ล้านบาท', 'บ้านเดี่ยวชั้นเดียวเลขที่ 28/3 พร้อมอาคารประกอบ บนที่ดิน 1 ไร่ 3 งาน 17 ตร.ว. หรือ 717 ตร.ว. (2,868 ตร.ม.) ตำบลบ้านสวน อำเภอเมืองชลบุรี จังหวัดชลบุรี โฉนดเลขที่ 45115 จำนวน 1 ฉบับ ราคาประกาศขายจาก SAM 18,733,000 บาท รหัสทรัพย์ HL0330

ที่ดินรูปคล้ายสี่เหลี่ยมผืนผ้า ติดถนน 2 ด้าน ต้นทางระบุด้านทิศตะวันตกกว้างประมาณ 48 เมตร และด้านทิศใต้ลึกสุดประมาณ 68 เมตร ถนนหน้าทรัพย์เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 8 เมตร อยู่ในเขตผังเมืองสีแดงตามข้อมูล SAM ควรตรวจทิศทางและขนาดแปลงกับโฉนดและผังรังวัด เพราะตัวเลขบนผังภาพประกอบมีรายละเอียดต่างจากข้อความสรุป

รายการสิ่งปลูกสร้างตามทะเบียนที่ SAM รับโอนมี 5 รายการ: บ้านพักอาศัยตึกชั้นเดียวเลขที่ 28/3, ระเบียงบ้าน 2 รายการ, โกดัง และอาคารสำนักงาน ส่วนการสำรวจสภาพทรัพย์ระบุ 3 รายการ ได้แก่ บ้านพักอาศัยตึกชั้นเดียวเลขที่ 28/3, อาคารคอนกรีตเสริมเหล็กชั้นเดียว และอาคารคลังสินค้า

ข้อมูลสำคัญ: SAM ระบุว่าจะโอนให้ผู้ซื้อตามรายการสิ่งปลูกสร้างที่จดทะเบียนรับโอนเท่านั้น รายการทะเบียนกับรายการสำรวจจึงต้องตรวจเทียบให้ตรงกัน รวมทั้งทะเบียนอาคาร แบบแปลน ใบอนุญาต และขอบเขตสิ่งปลูกสร้างที่จะได้รับโอน

ต้นทางระบุว่าอยู่ในย่านที่อยู่อาศัย สาธารณูปโภคครบครัน และเดินทางสะดวก แต่ไม่ได้ระบุกำลังไฟฟ้าหรือรายละเอียดระบบภายใน การมีโกดังและสำนักงานตามทะเบียนไม่ใช่การยืนยันว่าใช้งานเชิงพาณิชย์ได้ทุกประเภท ผู้สนใจควรตรวจข้อกำหนดผังเมืองและใบอนุญาตให้ตรงกับการใช้งานที่ต้องการ

การเดินทาง: จากถนนสุขุมวิท (ทล.3) ใช้ถนนเศรษฐกิจ (ทล.344) มุ่งหน้าถนนเลี่ยงเมืองชลบุรี (ทล.361) เลี้ยวซ้ายเข้าซอยบ้านสวน–เศรษฐกิจ 10 ประมาณ 1 กิโลเมตร จากนั้นเลี้ยวขวาประมาณ 170 เมตร ทรัพย์อยู่ด้านขวามือ สถานที่ใกล้เคียงที่ SAM ระบุ ได้แก่ โรงเรียนเมรี่อิมมาคุเลตคอนแวนต์ วิทยาลัยอาชีวศึกษาชลบุรี ไทวัสดุ ชลบุรี และศูนย์ฝึกอบรมตำรวจภูธรภาค 2

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อฝ่ายขาย SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส HL0330 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม และเงื่อนไขล่าสุด

ใช้พิกัดผู้ดูแล 13.363208337180431, 101.0021857853247 ซึ่งใกล้เคียงหมุดต้นทาง ภาพ SAM แสดงวันที่ 9 กรกฎาคม 2567 เป็นภาพภายนอก แนวรั้ว ทางเข้า ผังแปลง ผังอาคาร และแผนที่ ไม่มีภาพภายใน ต้นทางไม่ระบุจำนวนห้องนอน ห้องน้ำ พื้นที่ใช้สอย จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงควรนัดตรวจสภาพปัจจุบันกับ SAM

หมายเหตุแหล่งภาพ: ชื่อไฟล์แผนที่มีรหัส 3A0248 ในวงเล็บ ขณะที่หน้าประกาศและภาพทรัพย์ใช้ HL0330 ให้ใช้อ้างอิงรหัส HL0330 และหน้า id 22441 เมื่อติดต่อ SAM และขอให้ยืนยันความเกี่ยวข้องของรหัสในแผนที่', 18733000, false, 2868, 1, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '28/3 เข้าจากซอยบ้านสวน–เศรษฐกิจ 10', 'เข้าซอยประมาณ 1 กม. แล้วเลี้ยวขวาประมาณ 170 ม.', 'ซอยบ้านสวน–เศรษฐกิจ 10', 13.363208337180431, 101.0021857853247, 'ชลบุรี', 'เมืองชลบุรี', 'บ้านสวน', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-house-warehouse-office-ban-suan-chonburi-hl0330') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 18733000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'detached_house', 1, '{"source_property_category":"บ้านเดี่ยว","official_page_reference_code":"HL0330","source_page_id":22441,"alternate_reference_code_in_map_filename":"3A0248","source_reference_discrepancy":true,"title_document_type":"chanote","title_deed_number":"45115","title_document_count":1,"land_area_rai":1,"land_area_ngan":3,"land_area_square_wah_remainder":17,"land_area_square_wah":717,"land_area_sqm":2868,"plot_shape":"approximately_rectangular","two_road_frontages_reported":true,"source_west_side_width_m_approx":48,"source_south_maximum_depth_m_approx":68,"plot_measurement_confirmation_required":true,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":8,"planning_zone_th":"เขตสีแดง","registered_structure_descriptions":["บ้านพักอาศัยตึกชั้นเดียว 28/3","ระเบียงบ้าน","ระเบียงบ้าน","โกดัง","อาคารสำนักงาน"],"surveyed_structure_descriptions":["บ้านพักอาศัยตึกชั้นเดียว 28/3","อาคาร ค.ส.ล. ชั้นเดียว","อาคารคลังสินค้า"],"registered_and_surveyed_structure_discrepancy":true,"transfer_according_to_registered_structures_only":true,"source_utilities_available_reported":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"bedroom_count_not_published":true,"bathroom_count_not_published":true,"source_interior_images_published":false,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_property_photo_dates_displayed":["2024-07-09"],"administrator_coordinates_used":true,"source_coordinates_rounded":"13.363211,101.002186"}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 22441 identifies SAM as direct-sale publisher for HL0330. Registered/surveyed building inventories and alternate map reference are disclosed.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรงจาก SAM รหัส HL0330 ราคา 18,733,000 บาท', 'Direct purchase from SAM, HL0330, THB 18,733,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'transfer_inventory', 'รายการทะเบียนต่างจากที่สำรวจ', 'Registered and surveyed structures differ', 'ทะเบียน 5 รายการ สำรวจ 3 รายการ SAM โอนตามทะเบียนที่รับโอนเท่านั้น', 'Five registered items versus three surveyed structures; transfer follows SAM registered acquisition only', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'two_road_frontages', 'ที่ดินติดถนน 2 ด้าน', 'Two road frontages', 'ข้อความ SAM ระบุกว้างประมาณ 48 ม. ลึกสุดประมาณ 68 ม. ต้องตรวจเทียบผังและรังวัด', 'SAM text states approximately 48 m width and 68 m depth; confirm against the plan and survey', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพปัจจุบัน', 'Current inspection', 'ภาพภายนอกวันที่ 9 ก.ค. 2567 ไม่มีภาพภายใน และไม่ระบุสถานะผู้ครอบครอง', 'Exterior photos dated 9 July 2024; no interior photos or published occupancy status', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'source_map_reference', 'รหัสในชื่อไฟล์แผนที่', 'Map filename reference', 'ชื่อไฟล์แผนที่มี 3A0248 แต่หน้าประกาศใช้ HL0330 ให้ SAM ยืนยันความเกี่ยวข้อง', 'Map filename contains 3A0248 while the page uses HL0330; ask SAM to confirm the relationship', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'มุมทางเข้าและแนวรั้วบ้านบนแปลงหัวมุม', 'มุมทางเข้าและแนวรั้วบ้านบนแปลงหัวมุม', 'https://npa.sam.or.th/site/images/npa/22441/20250325153436_HL0330P2_68.jpg', '/listing-media/sam/hl0330/01.webp', 'image/webp', 21122, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ประตูทางเข้าและตัวบ้านด้านหลัง', 'ประตูทางเข้าและตัวบ้านด้านหลัง', 'https://npa.sam.or.th/site/images/npa/22441/HL0330P6_68.jpg', '/listing-media/sam/hl0330/02.webp', 'image/webp', 23918, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวรั้วและถนนข้างทรัพย์', 'แนวรั้วและถนนข้างทรัพย์', 'https://npa.sam.or.th/site/images/npa/22441/HL0330P3_68.jpg', '/listing-media/sam/hl0330/03.webp', 'image/webp', 23320, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ที่ดินหัวมุมติดถนนสองด้าน', 'ที่ดินหัวมุมติดถนนสองด้าน', 'https://npa.sam.or.th/site/images/npa/22441/HL0330P4_68.jpg', '/listing-media/sam/hl0330/04.webp', 'image/webp', 25566, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวรั้วอีกด้านของทรัพย์', 'แนวรั้วอีกด้านของทรัพย์', 'https://npa.sam.or.th/site/images/npa/22441/HL0330P5_68.jpg', '/listing-media/sam/hl0330/05.webp', 'image/webp', 24170, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าซอยบ้านสวน–เศรษฐกิจ 10', 'ทางเข้าซอยบ้านสวน–เศรษฐกิจ 10', 'https://npa.sam.or.th/site/images/npa/22441/HL0330P1_68.jpg', '/listing-media/sam/hl0330/06.webp', 'image/webp', 25232, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด 45115 และแปลงข้างเคียง', 'ผังแปลงโฉนด 45115 และแปลงข้างเคียง', 'https://npa.sam.or.th/site/images/npa/22441/20250325153436_HL0330C2_68.jpg', '/listing-media/sam/hl0330/07.webp', 'image/webp', 23428, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังอาคารตามการสำรวจ SAM', 'ผังอาคารตามการสำรวจ SAM', 'https://npa.sam.or.th/site/images/npa/22441/20250325153436_HL0330C1_68.jpg', '/listing-media/sam/hl0330/08.webp', 'image/webp', 33014, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/22441/20250325153436_HL0330M_68(3A0248).jpg', '/listing-media/sam/hl0330/09.webp', 'image/webp', 49058, 785, 600, 90, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=22441&keyref=6007623', 'HL0330', now(), 'Official SAM page captured 2026-09-11. Direct sale THB 18,733,000, 717 sq.wah. Five registered acquired items versus three surveyed buildings; registered-only transfer disclosed. Plot measurements need title/survey confirmation. Nine original exterior/access/plan images retained; property photos display 2024-07-09. No interior photos, occupancy or usable area published. Map filename includes 3A0248; alternate reference recorded without treating it as proven identity. Duplicate search uses code, page ID, deeds, address, area and nearby coordinates across all statuses. Shared keyref is not a property identifier.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: House with Warehouse and Office, Ban Suan, THB 18.733M', 'Single-storey detached house at 28/3 with ancillary buildings in Ban Suan, Mueang Chon Buri, Chon Buri. One title deed, no. 45115, covers 1 rai 3 ngan 17 sq.wah, equivalent to 717 sq.wah or 2,868 sq.m. SAM announced price THB 18,733,000; asset HL0330.

The roughly rectangular plot fronts two roads. SAM''s text states approximately 48 metres on the west and a maximum depth of approximately 68 metres on the south. The public concrete road is approximately six metres wide within an eight-metre right of way. SAM reports red planning zoning. Check the dimensions and directions against the title and survey because the illustration contains measurements that differ from the summary.

Registered structures acquired by SAM: single-storey house 28/3; two separately listed house verandas; a warehouse; and an office. The survey instead lists three structures: single-storey house 28/3, a single-storey reinforced-concrete building and a warehouse. SAM states that transfer follows only its registered acquisition inventory. Verify the building registration, plans, permits and exact structures included.

SAM describes residential surroundings, available utilities and convenient transport, but publishes no electrical capacity or internal system details. Registered warehouse and office structures do not establish permission for every commercial use; confirm the applicable planning provisions and permits.

From Sukhumvit Road (Highway 3), take Setthakit Road (Highway 344) toward the Chon Buri bypass (Highway 361). Turn left into Ban Suan–Setthakit Soi 10 for approximately one kilometre, then right for approximately 170 metres. The property is on the right. Source-listed nearby places include Mary Immaculate Convent School, Chonburi Vocational College, Thai Watsadu Chonburi and Provincial Police Region 2 Training Center.

SAM showed direct-purchase status and this announced price on 11 September 2026. Contact SAM Sales at 02-686-1888, sales@sam.or.th or LINE @samline, quoting HL0330, to confirm availability, price, viewing and current terms.

Administrator coordinates are used. Source photographs display 9 July 2024 and show only the exterior, boundary walls and access, plus plot/building plans and a navigation map. Interior photographs, bedroom and bathroom counts, usable area, parking capacity, building age and occupancy status are not published. Arrange a current inspection.

Source-media note: the navigation map filename also contains 3A0248, while the property page and photos use HL0330. Quote HL0330 and page id 22441 and ask SAM to confirm the alternate map reference.', '28/3, access from Ban Suan–Setthakit Soi 10', 'Approximately 1 km into the soi, then right for 170 m', 'Ban Suan–Setthakit Soi 10', 'Ban Suan', 'Mueang Chon Buri', 'Chon Buri', 'SAM House with Warehouse in Ban Suan — THB 18.733M', 'SAM HL0330: house and ancillary buildings on 717 sq.wah, two road frontages in Ban Suan. Registered and surveyed structures differ; see details.', 'published', 'ai_assisted', now(), 'sam direct sale: house with warehouse and office, ban suan, thb 18.733m single-storey detached house at 28/3 with ancillary buildings in ban suan, mueang chon buri, chon buri. one title deed, no. 45115, covers 1 rai 3 ngan 17 sq.wah, equivalent to 717 sq.wah or 2,868 sq.m. sam announced price thb 18,733,000; asset hl0330.

the roughly rectangular plot fronts two roads. sam''s text states approximately 48 metres on the west and a maximum depth of approximately 68 metres on the south. the public concrete road is approximately six metres wide within an eight-metre right of way. sam reports red planning zoning. check the dimensions and directions against the title and survey because the illustration contains measurements that differ from the summary.

registered structures acquired by sam: single-storey house 28/3; two separately listed house verandas; a warehouse; and an office. the survey instead lists three structures: single-storey house 28/3, a single-storey reinforced-concrete building and a warehouse. sam states that transfer follows only its registered acquisition inventory. verify the building registration, plans, permits and exact structures included.

sam describes residential surroundings, available utilities and convenient transport, but publishes no electrical capacity or internal system details. registered warehouse and office structures do not establish permission for every commercial use; confirm the applicable planning provisions and permits.

from sukhumvit road (highway 3), take setthakit road (highway 344) toward the chon buri bypass (highway 361). turn left into ban suan–setthakit soi 10 for approximately one kilometre, then right for approximately 170 metres. the property is on the right. source-listed nearby places include mary immaculate convent school, chonburi vocational college, thai watsadu chonburi and provincial police region 2 training center.

sam showed direct-purchase status and this announced price on 11 september 2026. contact sam sales at 02-686-1888, sales@sam.or.th or line @samline, quoting hl0330, to confirm availability, price, viewing and current terms.

administrator coordinates are used. source photographs display 9 july 2024 and show only the exterior, boundary walls and access, plus plot/building plans and a navigation map. interior photographs, bedroom and bathroom counts, usable area, parking capacity, building age and occupancy status are not published. arrange a current inspection.

source-media note: the navigation map filename also contains 3a0248, while the property page and photos use hl0330. quote hl0330 and page id 22441 and ask sam to confirm the alternate map reference.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=22441&keyref=6007623', 'Official SAM NPA page 22441 identifies SAM as asset holder and direct-sale contact for HL0330.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '51c603c8-9858-412b-a3d3-5eb3f6a661df', '{"reference_code":"HL0330","source_page_id":22441,"source_image_count":9,"building_discrepancy_disclosed":true,"alternate_map_reference":"3A0248","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
