BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-14257'));
-- Shared keyref is not a property identifier.
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='1P0017' OR source_url ~ '[?&]id=14257(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='1626e0d6-40b1-4127-a96f-1e420638e729' OR slug='sam-direct-sale-shophouse-land-laem-thong-si-racha-1p0017' OR description ILIKE '%1P0017%' OR (abs(latitude-13.091330505220354)<0.0001 AND abs(longitude-100.9283292588632)<0.0001 AND abs(land_area_sqm-3924)<1)) THEN RAISE NOTICE 'SAM 1P0017 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('1626e0d6-40b1-4127-a96f-1e420638e729', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', '138/18', 'ขายตรง SAM อาคารพาณิชย์ 3 ชั้นพร้อมชั้นลอยและที่ดิน 981 ตร.ว. ถนนแหลมทอง ศรีราชา', 'อาคารพาณิชย์เลขที่ 138/18 ถนนแหลมทอง ตำบลทุ่งศุขลา อำเภอศรีราชา จังหวัดชลบุรี พร้อมที่ดิน 5 แปลงติดต่อกัน เนื้อที่รวม 2 ไร่ 1 งาน 81 ตร.ว. หรือ 981 ตร.ว. (3,924 ตร.ม.) โฉนดเลขที่ 37238, 48959, 48960, 48961 และ 48962 ราคาประกาศขายจาก SAM 16,652,000 บาท รหัสทรัพย์ 1P0017

ที่ดินรูปหลายเหลี่ยม ด้านทิศใต้กว้างรวมประมาณ 98.5 เมตร โดยมีส่วนติดถนนประมาณ 5 เมตรและ 4 เมตร ลึกประมาณ 56 เมตร จึงไม่ใช่ที่ดินหน้ากว้างติดถนนตลอด 98.5 เมตร ถนนแหลมทองเป็นทางสาธารณประโยชน์ ผิวจราจรกว้างประมาณ 12 เมตร เขตทางประมาณ 14 เมตร ต้นทางระบุเขตผังเมืองสีส้ม อยู่ในย่านที่อยู่อาศัยและพาณิชยกรรม

ข้อมูลอาคารที่ต้องตรวจ: SAM รับโอนตามทะเบียนเป็นตึกแถว 3 ชั้น เลขที่ 138/18 แต่การสำรวจพบอาคาร 3 ชั้นพร้อมชั้นลอย นอกจากนี้มีสิ่งปลูกสร้างอื่นซึ่งต้นทางระบุว่ายังไม่พบหลักฐานว่าเป็นส่วนควบของที่ดินหรือไม่ การโอนให้ผู้ซื้อจึงดำเนินการตามรายการที่ SAM จดทะเบียนรับโอนเท่านั้น ต้องตรวจทะเบียนอาคาร แบบแปลน ใบอนุญาต และสิทธิในสิ่งปลูกสร้างอื่นก่อนเสนอซื้อ

ผังแปลงต้นทางแสดงที่ดินขนาดใหญ่ด้านหลังอาคารแถว พร้อมส่วนแคบเชื่อมออกถนน และแสดงตำแหน่งอาคารที่เกี่ยวข้องด้วยสีแยกกัน ผู้ซื้อควรยืนยันแนวเขตแต่ละโฉนด ทางเข้าออกทั้งสองช่วง สิทธิทาง และขอบเขตอาคารที่รวมในการขายกับ SAM และสำนักงานที่ดิน

การเดินทางตาม SAM: ใช้ถนนสุขุมวิท (ทล.3) จากเมืองพัทยามุ่งหน้าเมืองชลบุรี ผ่านฮาร์เบอร์มอลล์และโรงพยาบาลวิภารามแหลมฉบัง เข้าถนนแหลมทองฝั่งขวามือ ผ่านตลาดสี่มุมเมืองแหลมฉบังประมาณ 1.3 กิโลเมตร ทรัพย์อยู่ซ้ายมือ สถานที่ใกล้เคียงที่ SAM ระบุ ได้แก่ วัดแหลมทอง วัดแหลมฉบัง และโรงเรียนเทศบาลตำบลแหลมฉบัง

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 1P0017 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม และเงื่อนไขล่าสุด

ใช้พิกัดผู้ดูแล 13.091330505220354, 100.9283292588632 ซึ่งใกล้เคียงหมุด SAM ภาพภายนอกต้นทางแสดงวันที่ 5 มีนาคม 2564 ส่วนภาพภายในแสดงวันที่ 13 มกราคม 2567 มีภาพโถง ชั้นลอย บันได พื้นที่ชั้นบน และดาดฟ้า ควรนัดตรวจสภาพปัจจุบันก่อนตัดสินใจ ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนห้องนอน จำนวนห้องน้ำ จำนวนที่จอดรถ อายุอาคาร สถานะผู้ครอบครอง หรือรายละเอียดสาธารณูปโภค จึงเว้นข้อมูลเหล่านี้ไว้เพื่อยืนยันกับ SAM', 16652000, false, 3924, 3, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '138/18 ถนนแหลมทอง', 'เข้าจากถนนสุขุมวิท ผ่านตลาดสี่มุมเมืองแหลมฉบัง', 'ถนนแหลมทอง', 13.091330505220354, 100.9283292588632, 'ชลบุรี', 'ศรีราชา', 'ทุ่งศุขลา', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-shophouse-land-laem-thong-si-racha-1p0017') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 16652000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"1P0017","source_page_id":14257,"title_document_type":"chanote","title_deed_numbers":["37238","48959","48960","48961","48962"],"title_document_count":5,"plot_count":5,"land_area_rai":2,"land_area_ngan":1,"land_area_square_wah_remainder":81,"land_area_square_wah":981,"land_area_sqm":3924,"plot_shape":"polygon","south_side_width_m_approx":98.5,"road_frontage_sections_m_approx":[5,4],"maximum_depth_m_approx":56,"front_road_width_m_approx":12,"front_right_of_way_width_m_approx":14,"planning_zone_th":"เขตสีส้ม","registered_floor_count":3,"surveyed_floor_count":3,"surveyed_mezzanine_present":true,"registered_transfer_description":"ตึกแถวสามชั้น เลขที่ 138/18","other_structures_legal_inclusion_unconfirmed":true,"transfer_according_to_registered_structures_only":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"bedroom_count_not_published":true,"bathroom_count_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_exterior_photo_date":"2021-03-05","source_interior_photo_date":"2024-01-13","administrator_coordinates_used":true,"source_coordinates_rounded":"13.09133,100.92833","source_image_url_count":17,"unique_source_image_count":16}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 14257 identifies SAM as direct-sale publisher for 1P0017. Mezzanine and unconfirmed legal inclusion of other structures are disclosed.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 1P0017 ราคา 16,652,000 บาท', 'SAM direct purchase, 1P0017, THB 16,652,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'transfer_inventory', 'ทะเบียนอาคารและสิ่งปลูกสร้างอื่น', 'Registered building and other structures', 'ทะเบียนระบุ 3 ชั้น สำรวจพบชั้นลอยเพิ่ม สิ่งปลูกสร้างอื่นยังไม่ยืนยันว่าเป็นส่วนควบ โอนตามทะเบียนที่ SAM รับโอนเท่านั้น', 'Three storeys registered; mezzanine surveyed. Other structures are not confirmed as part of the land. Transfer follows registered acquisition only', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'frontage_sections', 'ส่วนติดถนนประมาณ 5 ม. และ 4 ม.', 'Approx. 5 m and 4 m frontage sections', 'ด้านใต้ยาวรวมประมาณ 98.5 ม. ไม่ได้ติดถนนตลอดแนว ตรวจสิทธิทางและผังแปลง', 'The 98.5 m southern side is not continuous road frontage; confirm access rights and the plot plan', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'สภาพและภาพต้นทาง', 'Condition and source photographs', 'ภาพภายนอก 5 มี.ค. 2564 ภายใน 13 ม.ค. 2567 ต้องตรวจสภาพและผู้ครอบครองปัจจุบัน', 'Exterior photos: 5 March 2021; interior: 13 January 2024. Verify current condition and occupancy', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารเลขที่ 138/18', 'ด้านหน้าอาคารเลขที่ 138/18', 'https://npa.sam.or.th/site/images/npa/14257/20230731144519_P1.jpg', '/listing-media/sam/1p0017/01.webp', 'image/webp', 38214, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารพาณิชย์และแนวถนนอีกมุม', 'อาคารพาณิชย์และแนวถนนอีกมุม', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P2_64.jpg', '/listing-media/sam/1p0017/02.webp', 'image/webp', 31404, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นล่างและชั้นลอย', 'โถงชั้นล่างและชั้นลอย', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P3_67.jpg', '/listing-media/sam/1p0017/04.webp', 'image/webp', 19856, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่โถงชั้นล่าง', 'พื้นที่โถงชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P4_67.jpg', '/listing-media/sam/1p0017/05.webp', 'image/webp', 22548, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชานบันไดและพื้นที่ชั้นบน', 'ชานบันไดและพื้นที่ชั้นบน', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P6_67.jpg', '/listing-media/sam/1p0017/06.webp', 'image/webp', 21020, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดเชื่อมระหว่างชั้น', 'บันไดเชื่อมระหว่างชั้น', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P7_67.jpg', '/listing-media/sam/1p0017/07.webp', 'image/webp', 23390, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในชั้นบน', 'โถงภายในชั้นบน', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P8_67.jpg', '/listing-media/sam/1p0017/08.webp', 'image/webp', 21902, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในติดบันได', 'พื้นที่ภายในติดบันได', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P9_67.jpg', '/listing-media/sam/1p0017/09.webp', 'image/webp', 16094, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอาคาร', 'ห้องภายในอาคาร', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P10_67.jpg', '/listing-media/sam/1p0017/10.webp', 'image/webp', 21256, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดขึ้นดาดฟ้า', 'บันไดขึ้นดาดฟ้า', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P11_67.jpg', '/listing-media/sam/1p0017/11.webp', 'image/webp', 20278, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ดาดฟ้า', 'พื้นที่ดาดฟ้า', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P12_67.jpg', '/listing-media/sam/1p0017/12.webp', 'image/webp', 33328, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ดาดฟ้าและห้องบันได', 'ดาดฟ้าและห้องบันได', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P13_67.jpg', '/listing-media/sam/1p0017/13.webp', 'image/webp', 34596, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าถนนแหลมทองจากสุขุมวิท', 'ทางเข้าถนนแหลมทองจากสุขุมวิท', 'https://npa.sam.or.th/site/images/npa/14257/1P0017P1_64.jpg', '/listing-media/sam/1p0017/14.webp', 'image/webp', 47414, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังโฉนด 5 แปลงและส่วนเชื่อมถนน', 'ผังโฉนด 5 แปลงและส่วนเชื่อมถนน', 'https://npa.sam.or.th/site/images/npa/14257/20190318092802_1P0017C1_62.jpg', '/listing-media/sam/1p0017/15.webp', 'image/webp', 19698, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งอาคารและที่ดิน', 'ผังตำแหน่งอาคารและที่ดิน', 'https://npa.sam.or.th/site/images/npa/14257/20190318092802_1P0017C2_62.jpg', '/listing-media/sam/1p0017/16.webp', 'image/webp', 18976, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/14257/20190318092802_1P0017M1_62.jpg', '/listing-media/sam/1p0017/17.webp', 'image/webp', 41120, 785, 600, 160, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=14257&keyref=6007623', '1P0017', now(), 'Official source captured 2026-09-11. Five plots totaling 981 sq.wah; THB 16,652,000 direct purchase. Approximately 98.5 m south side has only 5 m and 4 m road-fronting sections. Registered three-storey shophouse, surveyed mezzanine, unconfirmed legal inclusion of other structures and registered-only transfer disclosed. Exterior photos display 2021-03-05; interiors 2024-01-13. 17 source image URLs yield 16 unique images; 20230731144519_P1.jpg and 1P0017P4_64.jpg have identical SHA256 469ba0477118b0d293cc6d9d9b815682c514b705a7ba5afb3065523b1f97ce08, retained once. No retouching or added watermark. All-status duplicate search found no matches for reference/page/deeds/address/area/nearby coordinates.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 3-Storey Shophouse with Mezzanine and 981 Sq.Wah Land, Si Racha', 'Shophouse at 138/18, Laem Thong Road, Thung Sukhla, Si Racha, Chon Buri, with five adjoining land plots. Total area 2 rai 1 ngan 81 sq.wah, equivalent to 981 sq.wah or 3,924 sq.m. Deeds 37238, 48959, 48960, 48961 and 48962. SAM announced price THB 16,652,000; asset 1P0017.

The polygonal site has an approximately 98.5-metre southern side, but only approximately five-metre and four-metre sections adjoin the road. It does not have 98.5 metres of continuous road frontage. Depth is approximately 56 metres. SAM describes Laem Thong Road as public, with approximately 12 metres of carriageway and a 14-metre right of way. Orange planning zoning and residential/commercial surroundings are reported.

Registered acquisition identifies a three-storey shophouse numbered 138/18; the physical survey found three storeys plus a mezzanine. SAM also reports other structures without evidence confirming whether they legally form part of the land. Transfer follows only the property inventory that SAM acquired by registration. Check building registration, plans, permits and rights to other structures.

The source plan shows a large rear land parcel and narrow connections to the road, with the identified building separately marked. Confirm every title boundary, both access sections, access rights and the exact building included with SAM and the land office.

Travel from Pattaya toward Chon Buri on Sukhumvit Road (Highway 3), passing Harbor Mall and Vibharam Laemchabang Hospital. Enter Laem Thong Road on the right, passing Si Mum Mueang Laem Chabang Market, for approximately 1.3 kilometres; the property is on the left. Source-listed nearby places are Wat Laem Thong, Wat Laem Chabang and Laem Chabang Municipality School.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 1P0017, to confirm availability, current price, viewing and terms. Administrator coordinates are used.

Exterior photographs display 5 March 2021; interior photographs display 13 January 2024. Images include the hall, mezzanine, stairs, upper floors and roof terrace. Inspect current conditions. Usable area, bedrooms, bathroom count, parking capacity, age, occupancy and detailed utilities are not published.', '138/18, Laem Thong Road', 'Access from Sukhumvit Road via Si Mum Mueang Laem Chabang Market', 'Laem Thong Road', 'Thung Sukhla', 'Si Racha', 'Chon Buri', 'SAM Shophouse and 981 Sq.Wah Land in Si Racha — THB 16.652M', 'SAM 1P0017: three-storey shophouse with surveyed mezzanine and five land plots. Narrow road connections and registered-only transfer disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: 3-storey shophouse with mezzanine and 981 sq.wah land, si racha shophouse at 138/18, laem thong road, thung sukhla, si racha, chon buri, with five adjoining land plots. total area 2 rai 1 ngan 81 sq.wah, equivalent to 981 sq.wah or 3,924 sq.m. deeds 37238, 48959, 48960, 48961 and 48962. sam announced price thb 16,652,000; asset 1p0017.

the polygonal site has an approximately 98.5-metre southern side, but only approximately five-metre and four-metre sections adjoin the road. it does not have 98.5 metres of continuous road frontage. depth is approximately 56 metres. sam describes laem thong road as public, with approximately 12 metres of carriageway and a 14-metre right of way. orange planning zoning and residential/commercial surroundings are reported.

registered acquisition identifies a three-storey shophouse numbered 138/18; the physical survey found three storeys plus a mezzanine. sam also reports other structures without evidence confirming whether they legally form part of the land. transfer follows only the property inventory that sam acquired by registration. check building registration, plans, permits and rights to other structures.

the source plan shows a large rear land parcel and narrow connections to the road, with the identified building separately marked. confirm every title boundary, both access sections, access rights and the exact building included with sam and the land office.

travel from pattaya toward chon buri on sukhumvit road (highway 3), passing harbor mall and vibharam laemchabang hospital. enter laem thong road on the right, passing si mum mueang laem chabang market, for approximately 1.3 kilometres; the property is on the left. source-listed nearby places are wat laem thong, wat laem chabang and laem chabang municipality school.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 1p0017, to confirm availability, current price, viewing and terms. administrator coordinates are used.

exterior photographs display 5 march 2021; interior photographs display 13 january 2024. images include the hall, mezzanine, stairs, upper floors and roof terrace. inspect current conditions. usable area, bedrooms, bathroom count, parking capacity, age, occupancy and detailed utilities are not published.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=14257&keyref=6007623', 'Official SAM NPA page 14257 identifies SAM as asset holder and direct-sale contact for 1P0017.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '1626e0d6-40b1-4127-a96f-1e420638e729', '{"reference_code":"1P0017","source_page_id":14257,"unique_source_image_count":16,"building_discrepancy_disclosed":true,"road_frontage_sections_disclosed":true,"duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
