BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-22520'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='BL0065' OR source_url ~ '[?&]id=22520(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='f52380e4-20ad-43d5-9c4f-993d83abf2b3' OR slug='sam-direct-sale-office-mit-samphan-14-ban-puek-bl0065' OR description ILIKE '%BL0065%' OR (abs(latitude-13.314642445141104)<0.0001 AND abs(longitude-100.93312353033842)<0.0001 AND abs(land_area_sqm-908)<1)) THEN RAISE NOTICE 'SAM BL0065 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('f52380e4-20ad-43d5-9c4f-993d83abf2b3', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'office', 'business', 'sale', 'whole_property', '32/5', 'ขายตรง SAM สำนักงาน 2 ชั้น ซอยมิตรสัมพันธ์ 14 บ้านปึก ชลบุรี 227 ตร.ว. ราคา 12.868 ล้านบาท', 'อาคารสำนักงานเลขที่ 32/5 ซอยมิตรสัมพันธ์ 14 ตำบลบ้านปึก อำเภอเมืองชลบุรี จังหวัดชลบุรี บนที่ดิน 2 แปลงติดต่อกัน เนื้อที่รวม 2 งาน 27 ตร.ว. หรือ 227 ตร.ว. (908 ตร.ม.) โฉนดเลขที่ 43334 และ 60179 ราคาประกาศขายจาก SAM 12,868,000 บาท รหัสทรัพย์ BL0065

ที่ดินรูปสี่เหลี่ยมคางหมู ด้านทิศเหนือติดถนน หน้ากว้างประมาณ 22 เมตร ลึกสุดประมาณ 48 เมตร ถนนหน้าทรัพย์คือซอยมิตรสัมพันธ์ 14 เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 8 เมตร เขตทางประมาณ 10 เมตร ต้นทางระบุเขตผังเมืองสีส้ม อยู่ในย่านที่อยู่อาศัย

รายการสิ่งปลูกสร้างตามทะเบียนที่ SAM รับโอนมี 2 รายการ ได้แก่ โรงจอดรถ และสำนักงานความสูง 2 ชั้น เลขที่ 32/5 ส่วนการสำรวจสภาพทรัพย์ระบุ 4 รายการ ได้แก่ อาคารพักอาศัยพร้อมสำนักงาน 2 ชั้น, อาคารโรงงาน 2 ชั้น, โรงจอดรถ และป้อมยาม

ข้อมูลสำคัญ: SAM ระบุว่าจะโอนให้ผู้ซื้อตามรายการสิ่งปลูกสร้างที่จดทะเบียนรับโอนเท่านั้น อาคารโรงงานและป้อมยามที่ปรากฏในการสำรวจจึงต้องตรวจสอบสิทธิและรายการที่จะได้รับโอนก่อนเสนอซื้อ รวมถึงทะเบียนอาคาร แบบแปลน ใบอนุญาต และความสอดคล้องกับสภาพจริง การจัดหมวดประกาศนี้ยึดสำนักงานตามต้นทาง ไม่ได้ยืนยันใบอนุญาตประกอบกิจการโรงงาน

SAM ระบุว่าสาธารณูปโภคครบครันและเดินทางสะดวก แต่ไม่ได้ระบุกำลังไฟฟ้าหรือรายละเอียดระบบภายใน สถานที่ใกล้เคียงที่ต้นทางระบุ ได้แก่ วัดใหม่เกตุงาม โรงเรียนวัดใหม่เกตุงาม และโรงเรียนวัดเตาปูน

การเดินทางมี 2 ทางตาม SAM: จากถนนสุขุมวิท (ทล.3) มุ่งหน้าพัทยา ผ่านบิ๊กซี ชลบุรี 2 ถึงแยกอ่างศิลา เลี้ยวขวาเข้าถนนหมายเลข 3134 ผ่านโรงพยาบาลเอกชล 2 แล้วเลี้ยวซ้ายเข้าซอยมิตรสัมพันธ์ 14 ผ่านโรงเรียนวัดเตาปูน ทรัพย์อยู่ซ้ายมือ หรือเข้าจากถนนมิตรสัมพันธ์สู่ซอยมิตรสัมพันธ์ 14 ประมาณ 200 เมตร ทรัพย์อยู่ขวามือ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส BL0065 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม และเงื่อนไขล่าสุด

ใช้พิกัดผู้ดูแล 13.314642445141104, 100.93312353033842 ซึ่งใกล้เคียงหมุด SAM ภาพต้นทางแสดงวันที่ 26 มกราคม 2568 เป็นภาพภายนอก บริเวณอาคาร ทางเข้า พื้นที่หลังคาคลุม ผังแปลง ผังอาคาร และแผนที่ ต้นทางไม่มีภาพภายในห้อง และไม่ระบุพื้นที่ใช้สอยรวม จำนวนห้องน้ำ จำนวนที่จอดรถ อายุอาคาร สถานะผู้ครอบครอง หรือใบอนุญาตกิจการ ผู้สนใจควรนัดตรวจสภาพปัจจุบันกับ SAM', 12868000, false, 908, 2, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '32/5 ซอยมิตรสัมพันธ์ 14', 'เข้าจากถนนมิตรสัมพันธ์ประมาณ 200 เมตร', 'ซอยมิตรสัมพันธ์ 14', 13.314642445141104, 100.93312353033842, 'ชลบุรี', 'เมืองชลบุรี', 'บ้านปึก', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-office-mit-samphan-14-ban-puek-bl0065') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'office') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 12868000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'office', 1, '{"source_property_category":"อาคารสำนักงาน","official_page_reference_code":"BL0065","source_page_id":22520,"title_document_type":"chanote","title_deed_numbers":["43334","60179"],"title_document_count":2,"land_area_rai":0,"land_area_ngan":2,"land_area_square_wah_remainder":27,"land_area_square_wah":227,"land_area_sqm":908,"plot_shape":"trapezoid","north_road_frontage_m_approx":22,"maximum_depth_m_approx":48,"front_road_width_m_approx":8,"front_right_of_way_width_m_approx":10,"planning_zone_th":"เขตสีส้ม","registered_structure_descriptions":["โรงจอดรถ","สำนักงาน 2 ชั้น เลขที่ 32/5"],"surveyed_structure_descriptions":["อาคารพักอาศัยพร้อมสำนักงาน 2 ชั้น","อาคารโรงงาน 2 ชั้น","โรงจอดรถ","ป้อมยาม"],"registered_and_surveyed_structure_discrepancy":true,"transfer_according_to_registered_structures_only":true,"source_utilities_available_reported":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"source_room_interior_images_published":false,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_property_photo_dates_displayed":["2025-01-26"],"administrator_coordinates_used":true,"source_coordinates_rounded":"13.314643,100.933123"}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 22520 identifies SAM as direct-sale publisher for BL0065; registered/surveyed inventories differ and are disclosed.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส BL0065 ราคา 12,868,000 บาท', 'SAM direct purchase, BL0065, THB 12,868,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'transfer_inventory', 'ทะเบียน 2 รายการ สำรวจพบ 4 รายการ', 'Two registered items versus four surveyed structures', 'SAM รับโอนโรงจอดรถและสำนักงาน 2 ชั้นเท่านั้น ต้องตรวจสิทธิในโรงงานและป้อมยามที่สำรวจพบ', 'Registered garage and two-storey office; verify rights to the surveyed factory and guardhouse', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_frontage', 'ถนนและขนาดแปลง', 'Road and plot dimensions', 'หน้ากว้างด้านเหนือประมาณ 22 ม. ลึกสุด 48 ม. ถนนคอนกรีตกว้าง 8 ม. เขตทาง 10 ม.', 'Approx. 22 m north frontage, 48 m maximum depth, 8 m concrete road and 10 m right of way', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'สภาพและข้อมูลที่ต้องยืนยัน', 'Condition and information to confirm', 'ภาพวันที่ 26 ม.ค. 2568 ไม่ระบุพื้นที่ใช้สอย การครอบครอง หรือใบอนุญาตกิจการ ต้องตรวจสภาพปัจจุบัน', 'Photos dated 26 January 2025; usable area, occupancy and operating permits not published; inspect current condition', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารและถนนซอยมิตรสัมพันธ์ 14', 'ด้านหน้าอาคารและถนนซอยมิตรสัมพันธ์ 14', 'https://npa.sam.or.th/site/images/npa/22520/20250609090139_BL0065P2_68.jpg', '/listing-media/sam/bl0065/01.webp', 'image/webp', 49540, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณทางเข้าและอาคารด้านหน้า', 'บริเวณทางเข้าและอาคารด้านหน้า', 'https://npa.sam.or.th/site/images/npa/22520/BL0065P3_68.jpg', '/listing-media/sam/bl0065/02.webp', 'image/webp', 35956, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานภายในและประตูทางเข้า', 'ลานภายในและประตูทางเข้า', 'https://npa.sam.or.th/site/images/npa/22520/BL0065P4_68.jpg', '/listing-media/sam/bl0065/03.webp', 'image/webp', 33134, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณอาคารภายในทรัพย์', 'บริเวณอาคารภายในทรัพย์', 'https://npa.sam.or.th/site/images/npa/22520/BL0065P5_68.jpg', '/listing-media/sam/bl0065/04.webp', 'image/webp', 31538, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่หลังคาคลุมและอาคารประกอบ', 'พื้นที่หลังคาคลุมและอาคารประกอบ', 'https://npa.sam.or.th/site/images/npa/22520/BL0065P6_68.jpg', '/listing-media/sam/bl0065/05.webp', 'image/webp', 23862, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าซอยมิตรสัมพันธ์ 14', 'ทางเข้าซอยมิตรสัมพันธ์ 14', 'https://npa.sam.or.th/site/images/npa/22520/BL0065P1.1_68.jpg', '/listing-media/sam/bl0065/06.webp', 'image/webp', 35700, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดินโฉนด 43334 และ 60179', 'ผังที่ดินโฉนด 43334 และ 60179', 'https://npa.sam.or.th/site/images/npa/22520/20250609090139_BL0065C1_68.jpg', '/listing-media/sam/bl0065/07.webp', 'image/webp', 12136, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งอาคารตามการสำรวจ SAM', 'ผังตำแหน่งอาคารตามการสำรวจ SAM', 'https://npa.sam.or.th/site/images/npa/22520/20250609090139_BL0065C2_68.jpg', '/listing-media/sam/bl0065/08.webp', 'image/webp', 17136, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/22520/20250609090139_BL0065M_68.jpg', '/listing-media/sam/bl0065/09.webp', 'image/webp', 50474, 785, 600, 90, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=22520&keyref=6007623', 'BL0065', now(), 'Official SAM source captured 2026-09-11. Direct purchase THB 12,868,000, 227 sq.wah. Registered garage and two-storey office versus surveyed residential/office, factory, garage and guardhouse. Registered-only transfer disclosed; no factory licence inferred. Nine source exterior/covered-area/access/plan images retained with source dates 2025-01-26; no retouching. All-status code/page/deed/area/nearby-coordinate duplicate search found no matches. Shared keyref is not unique identity.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 2-Storey Office on 227 Sq.Wah, Mit Samphan 14, THB 12.868M', 'Office building numbered 32/5 in Soi Mit Samphan 14, Ban Puek, Mueang Chon Buri, Chon Buri. Two adjoining plots, deeds 43334 and 60179, total 2 ngan 27 sq.wah, equivalent to 227 sq.wah or 908 sq.m. SAM announced price THB 12,868,000; asset BL0065.

The trapezoidal site has approximately 22 metres of northern road frontage and a maximum depth of approximately 48 metres. Soi Mit Samphan 14 is described as a public concrete road approximately eight metres wide within a ten-metre right of way. SAM reports orange planning zoning and residential surroundings.

Registered acquired structures comprise a garage and a two-storey office numbered 32/5. The physical survey lists four structures: a two-storey residential/office building, a two-storey factory building, a garage and a guardhouse. SAM states that transfer follows only its registered acquisition inventory. Verify rights to the surveyed factory and guardhouse, building registration, plans, permits and the exact transfer inventory. This office listing does not confirm a factory operating licence.

SAM describes available utilities and convenient transport but gives no electrical capacity or internal system specifications. Nearby source-listed places include Wat Mai Ket Ngam, Wat Mai Ket Ngam School and Wat Tao Pun School.

From Sukhumvit Road (Highway 3) toward Pattaya, pass Big C Chonburi 2 and turn right at Ang Sila junction onto Highway 3134. Pass Aikchol 2 Hospital and turn left into Soi Mit Samphan 14, passing Wat Tao Pun School; the site is on the left. Alternatively, enter Soi Mit Samphan 14 from Mit Samphan Road for approximately 200 metres; the site is on the right.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting BL0065, to confirm availability, price, viewing and terms. Administrator coordinates are used.

Source images display 26 January 2025 and show exterior building areas, access, covered areas and plot/building plans. No room-interior photographs, total usable area, bathroom count, parking capacity, building age, occupancy status or operating permits are published. Arrange a current inspection.', '32/5, Soi Mit Samphan 14', 'Approximately 200 metres from Mit Samphan Road', 'Soi Mit Samphan 14', 'Ban Puek', 'Mueang Chon Buri', 'Chon Buri', 'SAM Office in Mit Samphan 14 — THB 12.868M', 'SAM BL0065: two-storey office on 227 sq.wah in Ban Puek. Registered and surveyed building inventories differ; see transfer details.', 'published', 'ai_assisted', now(), 'sam direct sale: 2-storey office on 227 sq.wah, mit samphan 14, thb 12.868m office building numbered 32/5 in soi mit samphan 14, ban puek, mueang chon buri, chon buri. two adjoining plots, deeds 43334 and 60179, total 2 ngan 27 sq.wah, equivalent to 227 sq.wah or 908 sq.m. sam announced price thb 12,868,000; asset bl0065.

the trapezoidal site has approximately 22 metres of northern road frontage and a maximum depth of approximately 48 metres. soi mit samphan 14 is described as a public concrete road approximately eight metres wide within a ten-metre right of way. sam reports orange planning zoning and residential surroundings.

registered acquired structures comprise a garage and a two-storey office numbered 32/5. the physical survey lists four structures: a two-storey residential/office building, a two-storey factory building, a garage and a guardhouse. sam states that transfer follows only its registered acquisition inventory. verify rights to the surveyed factory and guardhouse, building registration, plans, permits and the exact transfer inventory. this office listing does not confirm a factory operating licence.

sam describes available utilities and convenient transport but gives no electrical capacity or internal system specifications. nearby source-listed places include wat mai ket ngam, wat mai ket ngam school and wat tao pun school.

from sukhumvit road (highway 3) toward pattaya, pass big c chonburi 2 and turn right at ang sila junction onto highway 3134. pass aikchol 2 hospital and turn left into soi mit samphan 14, passing wat tao pun school; the site is on the left. alternatively, enter soi mit samphan 14 from mit samphan road for approximately 200 metres; the site is on the right.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting bl0065, to confirm availability, price, viewing and terms. administrator coordinates are used.

source images display 26 january 2025 and show exterior building areas, access, covered areas and plot/building plans. no room-interior photographs, total usable area, bathroom count, parking capacity, building age, occupancy status or operating permits are published. arrange a current inspection.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=22520&keyref=6007623', 'Official SAM page 22520 identifies SAM as direct-sale contact and asset holder for BL0065.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'f52380e4-20ad-43d5-9c4f-993d83abf2b3', '{"reference_code":"BL0065","source_page_id":22520,"source_image_count":9,"building_discrepancy_disclosed":true,"duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
