BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-21176'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A2042' OR source_url ~ '[?&]id=21176(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='c08df6ac-17f1-437a-a5a6-1e9172dff2c7' OR slug='sam-direct-sale-three-shophouses-chonburi-bypass-na-pa-3a2042' OR description ILIKE '%3A2042%' OR (abs(latitude-13.391641)<0.0001 AND abs(longitude-101.011376)<0.0001 AND abs(land_area_sqm-240)<1)) THEN RAISE NOTICE 'SAM 3A2042 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('c08df6ac-17f1-437a-a5a6-1e9172dff2c7', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', '88/24–26', 'ขายตรง SAM อาคารพาณิชย์ 3 คูหา ถนนเลี่ยงเมืองชลบุรี นาป่า 60 ตร.ว. ราคา 11.883 ล้านบาท', 'อาคารพาณิชย์ 3 คูหาติดต่อกัน เลขที่ 88/24–26 ตำบลนาป่า อำเภอเมืองชลบุรี จังหวัดชลบุรี ที่ดิน 3 แปลงรวม 60 ตร.ว. (240 ตร.ม.) โฉนดเลขที่ 167704, 167705 และ 167722 ราคาเสนอขายจาก SAM 11,883,000 บาท รหัสทรัพย์ 3A2042 หน้า SAM ระบุรวม 8 ห้องนอน 2 ห้องน้ำ

ที่ดินรูปสี่เหลี่ยมผืนผ้า ด้านทิศเหนือกว้างประมาณ 12 เมตร ลึกประมาณ 20 เมตร ติดถนนส่วนบุคคลและทางเชื่อมถนนสาธารณะ อยู่ในเขตผังเมืองสีส้มและย่านพาณิชยกรรมตามข้อมูล SAM

รายการอาคารตามทะเบียนที่ SAM รับโอนเป็นตึกแถว 4 ชั้น จำนวน 3 คูหา: เลขที่ 88/24 บนโฉนด 167704, เลขที่ 88/25 บนโฉนด 167705 และเลขที่ 88/26 บนโฉนด 167722 แต่การสำรวจระบุอาคารพาณิชย์ 3 ชั้น มีชั้นลอยและต่อเติมชั้นดาดฟ้า โดยพื้นที่ภายในทั้ง 3 คูหาเชื่อมทะลุถึงกัน ต้องตรวจเทียบทะเบียน แบบแปลน ใบอนุญาตและสภาพอาคารจริง

ข้อควรทราบสำคัญ: SAM ระบุว่าส่วนต่อเติมส่วนโล่งหลังคาคลุมด้านหน้าอาคารปลูกสร้างรุกล้ำแนวเขตถนน ผู้สนใจควรตรวจแนวเขต ใบอนุญาต ภาระในการแก้ไขหรือรื้อถอน และค่าใช้จ่ายที่เกี่ยวข้องกับ SAM และหน่วยงานที่รับผิดชอบก่อนเสนอซื้อ

ทางเข้าออกเป็นถนนส่วนบุคคล ซึ่ง SAM ระบุว่าจดภาระจำยอมให้แปลงทรัพย์แล้ว เชื่อมกับถนนเลี่ยงเมืองชลบุรี (ทล.361) ผิวคอนกรีตกว้างประมาณ 8 เมตร ผู้ซื้อควรตรวจเอกสารภาระจำยอม ขอบเขต สิทธิใช้ทางและการใช้จริง ไม่ควรเข้าใจว่าถนนหน้าทรัพย์เป็นถนนสาธารณะโดยตรง

การเดินทางตาม SAM: จากถนนสุขุมวิท (ทล.3) ใช้ถนนศุขประยูร (ทล.315) มุ่งหน้าอำเภอพนัสนิคม ผ่านห้างเฉลิมไทย ค่ายนวมินทราชินี วัดธรรมนิมิตต์ และกองพันทหารราบที่ 21 รักษาพระองค์ จากนั้นเลี้ยวซ้ายเข้าถนนเลี่ยงเมืองชลบุรี (ทล.361) ประมาณ 620 เมตร ทรัพย์อยู่ซ้ายมือ ต้นทางระบุสถานที่ใกล้เคียงคือกองพันทหารปืนใหญ่

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A2042 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม สิทธิใช้ทาง และเงื่อนไขล่าสุด

พิกัด 13.391641, 101.011376 ดึงโดยตรงจาก href ของปุ่มระบบนำทางในหน้า SAM และตรวจว่าตรงกับปุ่ม Google Map ใช้สำหรับตำแหน่งโดยประมาณ ไม่ใช่แนวเขตที่ดิน ภาพส่วนใหญ่แสดงวันที่ 7 มิถุนายน 2567 และภาพภายนอกอีกมุมแสดงวันที่ 13 มกราคม 2567 มีภาพโถง ห้อง บันได ห้องน้ำ และส่วนต่อเติมดาดฟ้า ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงควรนัดตรวจสภาพปัจจุบันก่อนตัดสินใจ', 11883000, false, 240, 4, 8, 2, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '88/24–26 ถนนเลี่ยงเมืองชลบุรี (ทล.361)', 'เข้าทางถนนส่วนบุคคลที่ต้นทางระบุว่าจดภาระจำยอมแล้ว', 'ถนนเลี่ยงเมืองชลบุรี (ทล.361)', 13.391641, 101.011376, 'ชลบุรี', 'เมืองชลบุรี', 'นาป่า', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-three-shophouses-chonburi-bypass-na-pa-3a2042') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 11883000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"3A2042","source_page_id":21176,"title_document_type":"chanote","title_deed_numbers":["167704","167705","167722"],"title_document_count":3,"land_area_square_wah":60,"land_area_sqm":240,"plot_shape":"rectangle","north_frontage_m_approx":12,"depth_m_approx":20,"private_road_width_m_approx":8,"registered_access_easement_reported":true,"front_road_legal_status":"private_with_registered_easement_reported_by_sam","planning_zone_th":"เขตสีส้ม","registered_floor_count":4,"surveyed_floor_count":3,"surveyed_mezzanine_present":true,"surveyed_roof_addition_present":true,"connected_unit_count":3,"registered_and_surveyed_structure_discrepancy":true,"front_covered_extension_encroaches_road_boundary":true,"bedroom_count_source":8,"bathroom_count_source":2,"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_dates":["2024-06-07","2024-01-13"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.391641,101.011376","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 21176 identifies SAM as direct-sale publisher for 3A2042. Private-road easement, road encroachment and differing floor descriptions disclosed.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 3A2042 ราคา 11,883,000 บาท', 'Direct SAM purchase, 3A2042, THB 11,883,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'building_floors', 'จำนวนชั้นตามทะเบียนและสำรวจ', 'Registered and surveyed floors', 'ทะเบียน 4 ชั้นทั้ง 3 คูหา สำรวจพบ 3 ชั้น มีชั้นลอยและต่อเติมดาดฟ้า', 'Four storeys registered per unit; survey reports three storeys, mezzanine and roof addition', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_encroachment', 'ส่วนต่อเติมรุกล้ำแนวเขตถนน', 'Extension encroaches on road boundary', 'SAM ระบุหลังคาคลุมด้านหน้ารุกล้ำแนวถนน ต้องตรวจแนวเขตและภาระแก้ไข', 'SAM reports front covered extension encroachment; verify boundaries and corrective obligations', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'private_access_easement', 'ถนนส่วนบุคคลและภาระจำยอม', 'Private road and easement', 'ต้นทางระบุจดภาระจำยอมแล้ว ถนนคอนกรีตกว้างประมาณ 8 ม. ต้องตรวจสิทธิใช้ทาง', 'Source reports registered easement; approximately 8 m concrete road; verify actual access rights', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารพาณิชย์ 3 คูหา', 'ด้านหน้าอาคารพาณิชย์ 3 คูหา', 'https://npa.sam.or.th/site/images/npa/21176/20240703151607_3A2042P1_67.jpg', '/listing-media/sam/3a2042/01.webp', 'image/webp', 37266, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านข้างและแนวอาคาร', 'ด้านข้างและแนวอาคาร', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P4_67.jpg', '/listing-media/sam/3a2042/02.webp', 'image/webp', 36246, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและบันไดชั้นล่าง', 'โถงและบันไดชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P2_67.jpg', '/listing-media/sam/3a2042/03.webp', 'image/webp', 22214, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในด้านหน้าอาคาร', 'พื้นที่ภายในด้านหน้าอาคาร', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P3._67.jpg', '/listing-media/sam/3a2042/04.webp', 'image/webp', 41346, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงเชื่อมและบันได', 'โถงเชื่อมและบันได', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P4._67.jpg', '/listing-media/sam/3a2042/05.webp', 'image/webp', 24928, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำ', 'ห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P5_67.jpg', '/listing-media/sam/3a2042/06.webp', 'image/webp', 25510, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงด้านหน้าอีกมุม', 'โถงด้านหน้าอีกมุม', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P7_67.jpg', '/listing-media/sam/3a2042/07.webp', 'image/webp', 33810, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ชั้นลอย', 'พื้นที่ชั้นลอย', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P8_67.jpg', '/listing-media/sam/3a2042/08.webp', 'image/webp', 17196, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงเชื่อมระหว่างคูหา', 'โถงเชื่อมระหว่างคูหา', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P9_67.jpg', '/listing-media/sam/3a2042/09.webp', 'image/webp', 25402, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในข้างบันได', 'พื้นที่ภายในข้างบันได', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P10_67.jpg', '/listing-media/sam/3a2042/10.webp', 'image/webp', 16040, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่หน้าร้านภายใน', 'พื้นที่หน้าร้านภายใน', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P11_67.jpg', '/listing-media/sam/3a2042/11.webp', 'image/webp', 33534, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นบน', 'โถงชั้นบน', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P12_67.jpg', '/listing-media/sam/3a2042/12.webp', 'image/webp', 27082, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ชั้นบนอีกมุม', 'พื้นที่ชั้นบนอีกมุม', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P13_67.jpg', '/listing-media/sam/3a2042/13.webp', 'image/webp', 25320, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายใน', 'ห้องภายใน', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P14_67.jpg', '/listing-media/sam/3a2042/14.webp', 'image/webp', 22690, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชานบันได', 'ชานบันได', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P15_67.jpg', '/listing-media/sam/3a2042/15.webp', 'image/webp', 25676, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินเชื่อมห้อง', 'ทางเดินเชื่อมห้อง', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P16_67.jpg', '/listing-media/sam/3a2042/16.webp', 'image/webp', 18274, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและบันได', 'ห้องและบันได', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P17_67.jpg', '/listing-media/sam/3a2042/17.webp', 'image/webp', 24744, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพร้อมหน้าต่าง', 'ห้องพร้อมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P18_67.jpg', '/listing-media/sam/3a2042/18.webp', 'image/webp', 21170, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินภายใน', 'ทางเดินภายใน', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P19_67.jpg', '/listing-media/sam/3a2042/19.webp', 'image/webp', 13170, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักภายใน', 'ห้องพักภายใน', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P20_67.jpg', '/listing-media/sam/3a2042/20.webp', 'image/webp', 19602, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องผนังสีชมพู', 'ห้องผนังสีชมพู', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P21_67.jpg', '/listing-media/sam/3a2042/21.webp', 'image/webp', 37334, 450, 450, 210, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำพร้อมอ่างล้างหน้า', 'ห้องน้ำพร้อมอ่างล้างหน้า', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P22_67.jpg', '/listing-media/sam/3a2042/22.webp', 'image/webp', 14336, 450, 450, 220, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและประตูระเบียง', 'ห้องและประตูระเบียง', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P23_67.jpg', '/listing-media/sam/3a2042/23.webp', 'image/webp', 18760, 450, 450, 230, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและทางเดิน', 'โถงและทางเดิน', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P24_67.jpg', '/listing-media/sam/3a2042/24.webp', 'image/webp', 24432, 450, 450, 240, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องผนังสีเหลือง', 'ห้องผนังสีเหลือง', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P25_67.jpg', '/listing-media/sam/3a2042/25.webp', 'image/webp', 24960, 450, 450, 250, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในมองผ่านทางเชื่อม', 'โถงภายในมองผ่านทางเชื่อม', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P26_67.jpg', '/listing-media/sam/3a2042/26.webp', 'image/webp', 22538, 450, 450, 260, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องผนังสีเขียว', 'ห้องผนังสีเขียว', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P27_67.jpg', '/listing-media/sam/3a2042/27.webp', 'image/webp', 24672, 450, 450, 270, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำปูกระเบื้อง', 'ห้องน้ำปูกระเบื้อง', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P28_67.jpg', '/listing-media/sam/3a2042/28.webp', 'image/webp', 18460, 450, 450, 280, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องผนังสีชมพูอีกห้อง', 'ห้องผนังสีชมพูอีกห้อง', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P29_67.jpg', '/listing-media/sam/3a2042/29.webp', 'image/webp', 23782, 450, 450, 290, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ส่วนต่อเติมดาดฟ้ามีหลังคา', 'ส่วนต่อเติมดาดฟ้ามีหลังคา', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P30_67.jpg', '/listing-media/sam/3a2042/30.webp', 'image/webp', 46402, 450, 450, 300, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ใต้หลังคาดาดฟ้า', 'พื้นที่ใต้หลังคาดาดฟ้า', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P31_67.jpg', '/listing-media/sam/3a2042/31.webp', 'image/webp', 50634, 450, 450, 310, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ส่วนต่อเติมชั้นดาดฟ้าอีกมุม', 'ส่วนต่อเติมชั้นดาดฟ้าอีกมุม', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P32_67.jpg', '/listing-media/sam/3a2042/32.webp', 'image/webp', 49766, 450, 450, 320, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ดาดฟ้าภายใน', 'พื้นที่ดาดฟ้าภายใน', 'https://npa.sam.or.th/site/images/npa/21176/3A2042P33_67.jpg', '/listing-media/sam/3a2042/33.webp', 'image/webp', 51622, 450, 450, 330, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดินและถนนภาระจำยอม', 'ผังที่ดินและถนนภาระจำยอม', 'https://npa.sam.or.th/site/images/npa/21176/20240410134931_3A2042C2_67.jpg', '/listing-media/sam/3a2042/34.webp', 'image/webp', 20622, 450, 450, 340, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังอาคารและส่วนต่อเติม', 'ผังอาคารและส่วนต่อเติม', 'https://npa.sam.or.th/site/images/npa/21176/20240219103726_3A2042C1_67.jpg', '/listing-media/sam/3a2042/35.webp', 'image/webp', 23786, 450, 450, 350, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทาง', 'แผนที่การเดินทาง', 'https://npa.sam.or.th/site/images/npa/21176/20240219103726_3A2042M_67.jpg', '/listing-media/sam/3a2042/36.webp', 'image/webp', 69114, 785, 600, 360, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=21176&keyref=6007623', '3A2042', now(), 'Official source captured 2026-09-11. Direct purchase THB 11,883,000, 60 sq.wah, three connected units, source counts 8 bedrooms/2 bathrooms. Registered four storeys versus surveyed three plus mezzanine and roof addition. Front covered extension encroaches road; private road has registered easement according to SAM. Both disclosures retained. Coordinates extracted from navigation href and independently matched to show_map.php parameters, without administrator-provided coordinates. 36 original images retained. All-status duplicate search found no matches; shared keyref not used as identity.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 3 Connected Shophouses, Na Pa, Chon Buri, THB 11.883M', 'Three adjoining internally connected shophouses at 88/24–26, Na Pa, Mueang Chon Buri, Chon Buri. Three plots, deeds 167704, 167705 and 167722, total 60 sq.wah (240 sq.m.). SAM announced price THB 11,883,000; asset 3A2042. The page reports eight bedrooms and two bathrooms for the listing.

The rectangular plot measures approximately 12 metres across its northern frontage and 20 metres deep, adjoining a private road and public-road connection. SAM reports orange planning zoning and commercial surroundings.

Registered acquisitions are three four-storey shophouses: 88/24 on deed 167704, 88/25 on deed 167705 and 88/26 on deed 167722. The survey instead describes three storeys, a mezzanine and a roof-level addition, with all three units internally connected. Verify registration, plans, permits and actual floor configuration.

Material source disclosure: the open-sided covered extension at the front encroaches on the road boundary. Confirm boundaries, permits, corrective or removal obligations and related costs with SAM and the responsible authority before purchase.

The frontage road is private. SAM states that an easement has been registered for the property plots. It connects to the Chon Buri bypass (Highway 361) and has an approximately eight-metre concrete carriageway. Verify the easement instrument, extent, rights and actual access; the frontage road is not represented as public.

From Sukhumvit Road (Highway 3), take Suk Prayun Road (Highway 315) toward Phanat Nikhom, passing Chalerm Thai, Nawamin Rachini Camp, Wat Thammanimit and the 21st Infantry Regiment. Turn left onto the Chon Buri bypass (Highway 361) for approximately 620 metres; the property is on the left. SAM lists an artillery battalion nearby.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A2042, to confirm availability, price, viewing, access rights and terms.

Coordinates 13.391641, 101.011376 were extracted from the SAM navigation link and agree with its Google Map link. They are a location pin, not a boundary survey. Most images display 7 June 2024; one exterior view displays 13 January 2024. Images include rooms, halls, stairs, bathrooms and the roof addition. Total usable area, parking capacity, age and occupancy are not published.', '88/24–26, Chon Buri Bypass (Highway 361)', 'Via private road with registered easement reported by SAM', 'Chon Buri Bypass (Highway 361)', 'Na Pa', 'Mueang Chon Buri', 'Chon Buri', 'SAM 3 Connected Shophouses in Na Pa — THB 11.883M', 'SAM 3A2042: 60 sq.wah, 8 bedrooms and 2 bathrooms. Private-road easement, front extension encroachment and differing floor counts disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: 3 connected shophouses, na pa, chon buri, thb 11.883m three adjoining internally connected shophouses at 88/24–26, na pa, mueang chon buri, chon buri. three plots, deeds 167704, 167705 and 167722, total 60 sq.wah (240 sq.m.). sam announced price thb 11,883,000; asset 3a2042. the page reports eight bedrooms and two bathrooms for the listing.

the rectangular plot measures approximately 12 metres across its northern frontage and 20 metres deep, adjoining a private road and public-road connection. sam reports orange planning zoning and commercial surroundings.

registered acquisitions are three four-storey shophouses: 88/24 on deed 167704, 88/25 on deed 167705 and 88/26 on deed 167722. the survey instead describes three storeys, a mezzanine and a roof-level addition, with all three units internally connected. verify registration, plans, permits and actual floor configuration.

material source disclosure: the open-sided covered extension at the front encroaches on the road boundary. confirm boundaries, permits, corrective or removal obligations and related costs with sam and the responsible authority before purchase.

the frontage road is private. sam states that an easement has been registered for the property plots. it connects to the chon buri bypass (highway 361) and has an approximately eight-metre concrete carriageway. verify the easement instrument, extent, rights and actual access; the frontage road is not represented as public.

from sukhumvit road (highway 3), take suk prayun road (highway 315) toward phanat nikhom, passing chalerm thai, nawamin rachini camp, wat thammanimit and the 21st infantry regiment. turn left onto the chon buri bypass (highway 361) for approximately 620 metres; the property is on the left. sam lists an artillery battalion nearby.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a2042, to confirm availability, price, viewing, access rights and terms.

coordinates 13.391641, 101.011376 were extracted from the sam navigation link and agree with its google map link. they are a location pin, not a boundary survey. most images display 7 june 2024; one exterior view displays 13 january 2024. images include rooms, halls, stairs, bathrooms and the roof addition. total usable area, parking capacity, age and occupancy are not published.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=21176&keyref=6007623', 'Official SAM page 21176 identifies SAM as asset holder and direct-sale contact for 3A2042.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'c08df6ac-17f1-437a-a5a6-1e9172dff2c7', '{"reference_code":"3A2042","source_page_id":21176,"source_image_count":36,"coordinate_source":"sam_navigation_href","road_encroachment_disclosed":true,"private_road_disclosed":true,"duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
