BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-21863'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='BL0042' OR source_url ~ '[?&]id=21863(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='512f5013-cd09-4e54-8e85-e506f151f82b' OR slug='sam-direct-sale-land-open-storage-shed-bang-lamung-1-bl0042' OR description ILIKE '%BL0042%' OR (abs(latitude-13.042709)<0.0001 AND abs(longitude-100.935201)<0.0001 AND abs(land_area_sqm-1884)<1)) THEN RAISE NOTICE 'SAM BL0042 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('512f5013-cd09-4e54-8e85-e506f151f82b', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'warehouse', 'business', 'sale', 'whole_property', 'ขายตรง SAM ที่ดินพร้อมโรงเก็บของโล่งหลังคาคลุม ซอยบางละมุง 1 ชลบุรี 471 ตร.ว.', 'ที่ดินพร้อมโรงเก็บของลักษณะส่วนโล่งหลังคาคลุม ไม่มีเลขที่ ซอยบางละมุง 1 ตำบลบางละมุง อำเภอบางละมุง จังหวัดชลบุรี โฉนดเลขที่ 36333 จำนวน 1 ฉบับ เนื้อที่ 1 ไร่ 71 ตร.ว. หรือ 471 ตร.ว. (1,884 ตร.ม.) ราคาประกาศขายจาก SAM 9,422,000 บาท รหัสทรัพย์ BL0042

ที่ดินรูปสี่เหลี่ยมคางหมู ด้านทิศเหนือติดถนน หน้ากว้างประมาณ 15 เมตร ลึกสุดประมาณ 120 เมตร ถนนหน้าทรัพย์คือซอยบางละมุง 1 เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 8 เมตร ต้นทางระบุเขตผังเมืองสีส้มและย่านที่อยู่อาศัย

รายการสิ่งปลูกสร้างตามทะเบียนที่ SAM รับโอนระบุโรงเก็บของชั้นเดียวไม่มีเลขที่ ส่วนการสำรวจระบุส่วนโล่งหลังคาคลุมไม่ติดเลขที่ ภาพแสดงอาคารหลังคาโครงเหล็กเปิดโล่ง จัดอยู่ในหมวดโกดัง/คลังสินค้าเพื่อค้นหา โดยต้องตรวจสภาพโครงสร้าง หลังคา พื้น และความเหมาะสมกับสินค้าที่จะจัดเก็บก่อนซื้อ ต้นทางไม่ระบุพื้นที่ใช้สอยหรือพื้นที่ใต้หลังคา

ผังแปลงแสดงโรงเก็บของอยู่ช่วงท้ายแปลง และมีแนวพื้นที่ยาวเชื่อมจากถนนด้านหน้า ควรตรวจแนวเขต ทางเข้าออก ความกว้างที่ใช้งานจริงและการกลับรถกับ SAM ไม่อนุมานว่ารถบรรทุกทุกขนาดเข้าออกได้

ต้นทางระบุว่าทรัพย์ห่างจากแนวโครงการต่อขยายรถไฟความเร็วสูงทางด้านตะวันออกประมาณ 530 เมตร ข้อมูลนี้เป็นระยะถึงแนวโครงการตาม SAM ไม่ใช่ระยะถึงสถานีหรือการยืนยันกำหนดเปิดบริการ ผู้สนใจควรตรวจตำแหน่งและสถานะโครงการปัจจุบันกับหน่วยงานเจ้าของโครงการ

การเดินทางตาม SAM: ใช้ถนนสุขุมวิท (ทล.3) จากตำบลทุ่งศุขลามุ่งหน้ามอเตอร์เวย์ชลบุรี–พัทยา ผ่านวัดศรีวนารามและโรงเรียนบ้านทุ่งกราด ถึงบริเวณ กม.132 เลี้ยวซ้ายเข้าซอยบางละมุง 1 ประมาณ 1 กิโลเมตร ทรัพย์อยู่ขวามือ สถานที่ใกล้เคียงที่ต้นทางระบุ ได้แก่ วัดท่ากระดาน โรงเรียนบ้านบางละมุง และโรงเรียนบ้านทุ่งกราด

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส BL0042 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม และเงื่อนไขล่าสุด

พิกัด 13.042709, 100.935201 ดึงจาก href ปุ่มระบบนำทางของ SAM และตรงกับปุ่ม Google Map ภาพจริงแสดงวันที่ 18 กรกฎาคม 2567 มีภาพหน้าแปลง แนวทางภายใน โรงเก็บของ ผัง และแผนที่ ต้นทางไม่ระบุสถานะผู้ครอบครอง กำลังไฟฟ้า ระบบประปา จำนวนที่จอดรถ อายุอาคาร ความสูงใต้หลังคา หรือกำลังรับน้ำหนักพื้น จึงควรตรวจข้อมูลเหล่านี้และสภาพปัจจุบันก่อนตัดสินใจ', 9422000, false, 1884, 1, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ซอยบางละมุง 1', 'เข้าจากถนนสุขุมวิท กม.132 ประมาณ 1 กิโลเมตร', 'ซอยบางละมุง 1', 13.042709, 100.935201, 'ชลบุรี', 'บางละมุง', 'บางละมุง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-land-open-storage-shed-bang-lamung-1-bl0042') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'storage') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 9422000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'warehouse', 1, '{"source_property_category":"ส่วนโล่งหลังคาคลุม","official_page_reference_code":"BL0042","source_page_id":21863,"title_document_type":"chanote","title_deed_number":"36333","title_document_count":1,"land_area_rai":1,"land_area_ngan":0,"land_area_square_wah_remainder":71,"land_area_square_wah":471,"land_area_sqm":1884,"plot_shape":"trapezoid","north_road_frontage_m_approx":15,"maximum_depth_m_approx":120,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":8,"planning_zone_th":"เขตสีส้ม","registered_structure_description":"โรงเก็บของชั้นเดียว ไม่มีเลขที่","surveyed_structure_description":"ส่วนโล่งหลังคาคลุม ไม่ติดเลขที่","open_sided_storage_shed":true,"enclosed_warehouse":false,"usable_area_not_published":true,"occupancy_status_not_published":true,"railway_extension_alignment_source_distance_m_approx":530,"railway_alignment_source_direction":"east","railway_station_distance_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_date":"2024-07-18","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.042709,100.935201","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 21863 identifies SAM as asset holder and direct-sale contact for BL0042; source describes an open covered storage structure.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส BL0042 ราคา 9,422,000 บาท', 'SAM direct purchase, BL0042, THB 9,422,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'building_condition', 'โรงเก็บของลักษณะโล่งหลังคาคลุม', 'Open-sided covered storage structure', 'ทะเบียนโรงเก็บของชั้นเดียว สำรวจเป็นส่วนโล่งหลังคาคลุม ไม่ระบุพื้นที่ใช้สอย', 'Registered single-storey storage building; surveyed open covered area; usable area not published', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_frontage', 'ขนาดแปลงและถนน', 'Plot and road', 'หน้ากว้างประมาณ 15 ม. ลึกสุด 120 ม. ถนนคอนกรีตกว้าง 6 ม. เขตทาง 8 ม.', 'Approx. 15 m frontage, 120 m depth, 6 m concrete road, 8 m right of way', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'railway_alignment', 'แนวโครงการรถไฟตามข้อมูล SAM', 'Source-reported railway alignment', 'ต้นทางระบุแนวโครงการห่างประมาณ 530 ม. ทางตะวันออก ไม่ใช่ระยะถึงสถานี ต้องตรวจสถานะล่าสุด', 'SAM reports project alignment approx. 530 m east; not station distance; confirm current status', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'โรงเก็บของลักษณะโล่งหลังคาคลุม', 'โรงเก็บของลักษณะโล่งหลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/21863/BL0042P6_67.jpg', '/listing-media/sam/bl0042/05.webp', 'image/webp', 41806, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'หน้าแปลงติดซอยบางละมุง 1', 'หน้าแปลงติดซอยบางละมุง 1', 'https://npa.sam.or.th/site/images/npa/21863/20240806145149_BL0042P3_67.jpg', '/listing-media/sam/bl0042/01.webp', 'image/webp', 43880, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวรั้วและถนนหน้าแปลง', 'แนวรั้วและถนนหน้าแปลง', 'https://npa.sam.or.th/site/images/npa/21863/BL0042P2_67.jpg', '/listing-media/sam/bl0042/02.webp', 'image/webp', 48066, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวพื้นที่จากหน้าทรัพย์', 'แนวพื้นที่จากหน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/21863/BL0042P4_67.jpg', '/listing-media/sam/bl0042/03.webp', 'image/webp', 58418, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางภายในและแนวรั้ว', 'ทางภายในและแนวรั้ว', 'https://npa.sam.or.th/site/images/npa/21863/BL0042P5_67.jpg', '/listing-media/sam/bl0042/04.webp', 'image/webp', 60274, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าซอยบางละมุง 1 จากสุขุมวิท', 'ทางเข้าซอยบางละมุง 1 จากสุขุมวิท', 'https://npa.sam.or.th/site/images/npa/21863/BL0042P1_67.jpg', '/listing-media/sam/bl0042/06.webp', 'image/webp', 21618, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด 36333', 'ผังแปลงโฉนด 36333', 'https://npa.sam.or.th/site/images/npa/21863/20240806145149_BL0042C2_67.jpg', '/listing-media/sam/bl0042/07.webp', 'image/webp', 13820, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งโรงเก็บของช่วงท้ายแปลง', 'ผังตำแหน่งโรงเก็บของช่วงท้ายแปลง', 'https://npa.sam.or.th/site/images/npa/21863/20240806145149_BL0042C1_67.jpg', '/listing-media/sam/bl0042/08.webp', 'image/webp', 18112, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/21863/20240809153919_BL0042M_67.jpg', '/listing-media/sam/bl0042/09.webp', 'image/webp', 54162, 785, 600, 90, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=21863&keyref=6007623', 'BL0042', now(), 'Official source captured 2026-09-11. Direct purchase THB 9,422,000, 471 sq.wah. Registered single-storey storage building, surveyed open covered structure. Classified warehouse/storage, explicitly open-sided. Nine original images retained with dates 2024-07-18; actual shed image selected as cover. Source-reported 530 m distance is to railway project alignment, not station. Coordinates extracted from navigation href and cross-checked against map href. All-status duplicate check by code/page/deed/area/nearby coordinates found no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Land with Open Storage Shed, Bang Lamung 1, THB 9.422M', 'Land with an unnumbered open-sided covered storage structure in Soi Bang Lamung 1, Bang Lamung, Chon Buri. One title deed, no. 36333, covers 1 rai 71 sq.wah, equivalent to 471 sq.wah or 1,884 sq.m. SAM announced price THB 9,422,000; asset BL0042.

The trapezoidal plot has approximately 15 metres of northern frontage and a maximum depth of approximately 120 metres. Soi Bang Lamung 1 is a public concrete road approximately six metres wide within an eight-metre right of way. SAM reports orange planning zoning and residential surroundings.

SAM''s registered acquired structure is an unnumbered single-storey storage building. The survey describes an open-sided covered area, and photographs show an open steel-roof structure. It is listed under warehouse/storage for discovery. Check the structure, roof, floor and suitability for intended goods. Usable area and covered floor area are not published.

The source plan places the shed toward the rear, with a long approach from the front road. Confirm boundaries, access width and turning space; access for every truck size is not established.

SAM states that a high-speed railway extension alignment is approximately 530 metres to the east. This is a source-reported distance to a project alignment, not a station or an opening-date commitment. Confirm the current alignment and project status with the responsible authority.

Take Sukhumvit Road (Highway 3) from Thung Sukhla toward the Chon Buri–Pattaya motorway, passing Wat Si Wanaram and Ban Thung Krat School. Around kilometre 132, turn left into Soi Bang Lamung 1 for approximately one kilometre; the property is on the right. Source-listed nearby places include Wat Tha Kradan, Ban Bang Lamung School and Ban Thung Krat School.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting BL0042, to confirm availability, price, viewing and terms.

Coordinates 13.042709, 100.935201 come directly from the SAM navigation href and agree with its map link. Photos display 18 July 2024. Occupancy, electrical capacity, water supply, parking count, age, clear height and floor loading are not published; inspect current conditions.', 'Soi Bang Lamung 1', 'Approx. 1 km from Sukhumvit Road at km 132', 'Soi Bang Lamung 1', 'Bang Lamung', 'Bang Lamung', 'Chon Buri', 'SAM Land with Open Storage Shed, Bang Lamung — THB 9.422M', 'SAM BL0042: 471 sq.wah with an open-sided storage shed in Soi Bang Lamung 1. Approx. 15 m frontage and 120 m maximum depth.', 'published', 'ai_assisted', now(), 'sam direct sale: land with open storage shed, bang lamung 1, thb 9.422m land with an unnumbered open-sided covered storage structure in soi bang lamung 1, bang lamung, chon buri. one title deed, no. 36333, covers 1 rai 71 sq.wah, equivalent to 471 sq.wah or 1,884 sq.m. sam announced price thb 9,422,000; asset bl0042.

the trapezoidal plot has approximately 15 metres of northern frontage and a maximum depth of approximately 120 metres. soi bang lamung 1 is a public concrete road approximately six metres wide within an eight-metre right of way. sam reports orange planning zoning and residential surroundings.

sam''s registered acquired structure is an unnumbered single-storey storage building. the survey describes an open-sided covered area, and photographs show an open steel-roof structure. it is listed under warehouse/storage for discovery. check the structure, roof, floor and suitability for intended goods. usable area and covered floor area are not published.

the source plan places the shed toward the rear, with a long approach from the front road. confirm boundaries, access width and turning space; access for every truck size is not established.

sam states that a high-speed railway extension alignment is approximately 530 metres to the east. this is a source-reported distance to a project alignment, not a station or an opening-date commitment. confirm the current alignment and project status with the responsible authority.

take sukhumvit road (highway 3) from thung sukhla toward the chon buri–pattaya motorway, passing wat si wanaram and ban thung krat school. around kilometre 132, turn left into soi bang lamung 1 for approximately one kilometre; the property is on the right. source-listed nearby places include wat tha kradan, ban bang lamung school and ban thung krat school.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting bl0042, to confirm availability, price, viewing and terms.

coordinates 13.042709, 100.935201 come directly from the sam navigation href and agree with its map link. photos display 18 july 2024. occupancy, electrical capacity, water supply, parking count, age, clear height and floor loading are not published; inspect current conditions.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=21863&keyref=6007623', 'Official SAM page 21863 identifies SAM as asset holder and direct-sale contact for BL0042.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '512f5013-cd09-4e54-8e85-e506f151f82b', '{"reference_code":"BL0042","source_page_id":21863,"source_image_count":9,"coordinate_source":"sam_navigation_href","open_sided_structure_disclosed":true,"duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
