BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20397'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A1647' OR source_url ~ '[?&]id=20397(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='0280f160-f895-4b12-8a15-e4dd632d6693' OR slug='sam-direct-sale-two-shophouses-ai-oon-place-khiri-nakhon-3a1647' OR description ILIKE '%3A1647%' OR (abs(latitude-13.320796)<0.0001 AND abs(longitude-100.966027)<0.0001 AND abs(land_area_sqm-326)<1)) THEN RAISE NOTICE 'SAM 3A1647 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('0280f160-f895-4b12-8a15-e4dd632d6693', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', 'ไออุ่นเพลส', '25/46, 25/47', 'ขายตรง SAM อาคารพาณิชย์ 3 ชั้น 2 คูหา ไออุ่นเพลส ถนนคีรีนคร ชลบุรี 81.5 ตร.ว.', 'อาคารพาณิชย์ 3 ชั้น จำนวน 2 คูหา เลขที่ 25/46 และ 25/47 โครงการไออุ่นเพลส ถนนคีรีนคร ตำบลห้วยกะปิ อำเภอเมืองชลบุรี จังหวัดชลบุรี บนที่ดิน 2 แปลงติดต่อกัน โฉนดเลขที่ 11090 และ 142892 เนื้อที่รวม 81.5 ตร.ว. (326 ตร.ม.) ราคาประกาศขายจาก SAM 8,955,000 บาท รหัสทรัพย์ 3A1647

ที่ดินรูปคล้ายสี่เหลี่ยมคางหมู ด้านทิศเหนือติดถนน หน้ากว้างประมาณ 16 เมตร ลึกสุดประมาณ 25.5 เมตร รายการที่ SAM รับโอนกรรมสิทธิ์ระบุเป็นตึกแถว 3 ชั้น 2 คูหาตามเลขที่ข้างต้น ถนนหน้าทรัพย์คือถนนคีรีนคร เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 16 เมตร เขตทางประมาณ 20 เมตร

ต้นทางระบุเขตผังเมืองสีแดง อยู่ในย่านที่อยู่อาศัยและพาณิชยกรรม การคมนาคมสะดวก สถานที่ใกล้เคียงที่ SAM ระบุคือวิทยาลัยเทคโนโลยีชลบุรี ผู้สนใจควรตรวจข้อกำหนดการใช้อาคารและใบอนุญาตให้ตรงกับกิจการที่ต้องการ

การเดินทางตาม SAM: ใช้ถนนสุขุมวิท (ทล.3) จากกรุงเทพฯ มุ่งหน้าหนองมน ถึงแยกคีรี เลี้ยวซ้ายเข้าถนนคีรีนครประมาณ 400 เมตร ทรัพย์อยู่ด้านขวามือ

ภาพมีทั้งด้านหน้าและด้านข้างอาคาร โถงชั้นล่าง พื้นที่ชั้นบน บันได และห้องน้ำ โดยภาพภายนอกบางภาพแสดงวันที่ 1 กันยายน 2565 และภาพภายนอกอีกชุดกับภาพภายในแสดงวันที่ 12 มีนาคม 2566 ควรนัดตรวจสภาพปัจจุบัน โดยเฉพาะพื้น ผนัง ฝ้า หลังคา ระบบไฟฟ้าและประปา ก่อนตัดสินใจ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A1647 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม และเงื่อนไขล่าสุด

ใช้พิกัด 13.320796, 100.966027 ซึ่งดึงจาก href ปุ่มระบบนำทางของ SAM และตรวจว่าตรงกับปุ่ม Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนห้องนอน จำนวนห้องน้ำ จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงเว้นข้อมูลเหล่านี้ไว้เพื่อยืนยันกับ SAM การเห็นห้องน้ำหรืออุปกรณ์ในภาพไม่ใช่ข้อมูลจำนวนรวมของทรัพย์', 8955000, false, 326, 3, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '25/46, 25/47 โครงการไออุ่นเพลส ถนนคีรีนคร', 'เข้าจากแยกคีรีประมาณ 400 เมตร', 'ถนนคีรีนคร', 13.320796, 100.966027, 'ชลบุรี', 'เมืองชลบุรี', 'ห้วยกะปิ', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-two-shophouses-ai-oon-place-khiri-nakhon-3a1647') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 8955000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"3A1647","source_page_id":20397,"project_name":"ไออุ่นเพลส","title_document_type":"chanote","title_deed_numbers":["11090","142892"],"title_document_count":2,"land_area_square_wah":81.5,"land_area_sqm":326,"plot_shape":"approximately_trapezoidal","north_road_frontage_m_approx":16,"maximum_depth_m_approx":25.5,"front_road_width_m_approx":16,"front_right_of_way_width_m_approx":20,"planning_zone_th":"เขตสีแดง","registered_floor_count":3,"registered_unit_count":2,"registered_unit_numbers":["25/46","25/47"],"usable_area_not_published":true,"occupancy_status_not_published":true,"bedroom_count_not_published":true,"bathroom_count_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_dates":["2022-09-01","2023-03-12"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.320796,100.966027","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20397 identifies SAM as direct-sale contact for 3A1647, two three-storey shophouses in Ai Oon Place.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 3A1647 ราคา 8,955,000 บาท', 'SAM direct purchase, 3A1647, THB 8,955,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_buildings', 'อาคารตามทะเบียน', 'Registered buildings', 'ตึกแถว 3 ชั้น 2 คูหา เลขที่ 25/46 และ 25/47 โฉนด 11090 และ 142892', 'Two three-storey shophouses, 25/46 and 25/47; deeds 11090 and 142892', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_frontage', 'ถนนและขนาดแปลง', 'Road and plot', 'หน้ากว้างประมาณ 16 ม. ลึกสุด 25.5 ม. ถนนคอนกรีตกว้าง 16 ม. เขตทาง 20 ม.', 'Approx. 16 m frontage, 25.5 m depth, 16 m concrete carriageway and 20 m right of way', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพปัจจุบัน', 'Current inspection', 'ภาพปี 2565–2566 ต้องตรวจสภาพและยืนยันพื้นที่ใช้สอย จำนวนห้องและการครอบครอง', 'Photos from 2022–2023; inspect current condition and confirm usable area, rooms and occupancy', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าและด้านข้างอาคาร 2 คูหา', 'ด้านหน้าและด้านข้างอาคาร 2 คูหา', 'https://npa.sam.or.th/site/images/npa/20397/20240130103755_3A1647P3_65.jpg', '/listing-media/sam/3a1647/01.webp', 'image/webp', 34156, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารและถนนคีรีนคร', 'อาคารและถนนคีรีนคร', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P4_65.jpg', '/listing-media/sam/3a1647/02.webp', 'image/webp', 30696, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านหน้าอาคารมุมตรง', 'ด้านหน้าอาคารมุมตรง', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P1_66.jpg', '/listing-media/sam/3a1647/03.webp', 'image/webp', 25784, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นล่างผนังสีฟ้า', 'โถงชั้นล่างผนังสีฟ้า', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P2_66_12.jpg', '/listing-media/sam/3a1647/04.webp', 'image/webp', 13210, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดและชานพัก', 'บันไดและชานพัก', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P3_66_11.jpg', '/listing-media/sam/3a1647/05.webp', 'image/webp', 17844, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำพร้อมสุขภัณฑ์', 'ห้องน้ำพร้อมสุขภัณฑ์', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P4_66_10.jpg', '/listing-media/sam/3a1647/06.webp', 'image/webp', 10278, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและบันไดชั้นล่าง', 'โถงและบันไดชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P5_66_09.jpg', '/listing-media/sam/3a1647/07.webp', 'image/webp', 18352, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในมองสู่หน้าร้าน', 'พื้นที่ภายในมองสู่หน้าร้าน', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P6_66_08.jpg', '/listing-media/sam/3a1647/08.webp', 'image/webp', 13246, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ชั้นบน', 'พื้นที่ชั้นบน', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P7_66_07.jpg', '/listing-media/sam/3a1647/09.webp', 'image/webp', 14510, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นบนและแนวหน้าต่าง', 'โถงชั้นบนและแนวหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P8_66_06.jpg', '/listing-media/sam/3a1647/10.webp', 'image/webp', 21386, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่โล่งภายในอาคาร', 'พื้นที่โล่งภายในอาคาร', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P9_66_05.jpg', '/listing-media/sam/3a1647/11.webp', 'image/webp', 18148, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นบนอีกมุม', 'โถงชั้นบนอีกมุม', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P10_66_04.jpg', '/listing-media/sam/3a1647/12.webp', 'image/webp', 15966, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชานบันไดและห้องภายใน', 'ชานบันไดและห้องภายใน', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P11_66_03.jpg', '/listing-media/sam/3a1647/13.webp', 'image/webp', 13046, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดขึ้นชั้นบน', 'บันไดขึ้นชั้นบน', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P12_66_02.jpg', '/listing-media/sam/3a1647/14.webp', 'image/webp', 20544, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นล่างอีกมุม', 'โถงชั้นล่างอีกมุม', 'https://npa.sam.or.th/site/images/npa/20397/3A1647P13_66_01.jpg', '/listing-media/sam/3a1647/15.webp', 'image/webp', 18754, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด 11090 และ 142892', 'ผังแปลงโฉนด 11090 และ 142892', 'https://npa.sam.or.th/site/images/npa/20397/20221111100838_3A1647C2_65.jpg', '/listing-media/sam/3a1647/16.webp', 'image/webp', 14280, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งอาคาร 2 คูหา', 'ผังตำแหน่งอาคาร 2 คูหา', 'https://npa.sam.or.th/site/images/npa/20397/20221111100838_3A1647C1_65.jpg', '/listing-media/sam/3a1647/17.webp', 'image/webp', 17216, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/20397/20221111100838_3A1647M_65.jpg', '/listing-media/sam/3a1647/18.webp', 'image/webp', 49922, 785, 600, 180, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20397&keyref=6007623', '3A1647', now(), 'Official source captured 2026-09-11. Direct sale THB 8,955,000; two three-storey shophouses in Ai Oon Place, 81.5 sq.wah. Eighteen original images preserved; photos display 2022-09-01 and 2023-03-12. Unknown rooms, usable area and occupancy remain unset. Navigation href coordinates cross-checked against map link. All-status duplicate search by code/page/deeds/address/project/nearby coordinates found no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Two 3-Storey Shophouses, Ai Oon Place, THB 8.955M', 'Two three-storey shophouses numbered 25/46 and 25/47 in Ai Oon Place on Khiri Nakhon Road, Huai Kapi, Mueang Chon Buri, Chon Buri. Two adjoining land plots, deeds 11090 and 142892, total 81.5 sq.wah (326 sq.m.). SAM announced price THB 8,955,000; asset 3A1647.

The roughly trapezoidal plot has approximately 16 metres of northern road frontage and a maximum depth of approximately 25.5 metres. SAM''s registered acquisition describes two three-storey shophouses. Khiri Nakhon Road is described as public, with approximately 16 metres of concrete carriageway and a 20-metre right of way.

SAM reports red planning zoning, residential and commercial surroundings and convenient transport. The listed nearby place is Chonburi Technology College. Confirm permitted building use and any operating licences for the intended activity.

From Bangkok toward Nong Mon on Sukhumvit Road (Highway 3), turn left at Khiri junction into Khiri Nakhon Road for approximately 400 metres; the property is on the right.

Images show the front and side elevations, ground-floor halls, upper-floor space, stairs and a bathroom. Some exterior photos display 1 September 2022; another exterior view and interiors display 12 March 2023. Inspect current floors, walls, ceilings, roof, electrical and plumbing systems.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A1647, to confirm availability, price, viewing and terms.

Coordinates 13.320796, 100.966027 were extracted from the SAM navigation href and match its map link. Total usable area, bedrooms, bathroom count, parking capacity, building age and occupancy are not published. A photographed bathroom does not establish the total bathroom count.', '25/46, 25/47, Ai Oon Place, Khiri Nakhon Road', 'Approx. 400 metres from Khiri junction', 'Khiri Nakhon Road', 'Huai Kapi', 'Mueang Chon Buri', 'Chon Buri', 'SAM Ai Oon Place Shophouses — THB 8.955M', 'SAM 3A1647: two three-storey shophouses on 81.5 sq.wah, Khiri Nakhon Road, Huai Kapi. Direct sale THB 8,955,000.', 'published', 'ai_assisted', now(), 'sam direct sale: two 3-storey shophouses, ai oon place, thb 8.955m two three-storey shophouses numbered 25/46 and 25/47 in ai oon place on khiri nakhon road, huai kapi, mueang chon buri, chon buri. two adjoining land plots, deeds 11090 and 142892, total 81.5 sq.wah (326 sq.m.). sam announced price thb 8,955,000; asset 3a1647.

the roughly trapezoidal plot has approximately 16 metres of northern road frontage and a maximum depth of approximately 25.5 metres. sam''s registered acquisition describes two three-storey shophouses. khiri nakhon road is described as public, with approximately 16 metres of concrete carriageway and a 20-metre right of way.

sam reports red planning zoning, residential and commercial surroundings and convenient transport. the listed nearby place is chonburi technology college. confirm permitted building use and any operating licences for the intended activity.

from bangkok toward nong mon on sukhumvit road (highway 3), turn left at khiri junction into khiri nakhon road for approximately 400 metres; the property is on the right.

images show the front and side elevations, ground-floor halls, upper-floor space, stairs and a bathroom. some exterior photos display 1 september 2022; another exterior view and interiors display 12 march 2023. inspect current floors, walls, ceilings, roof, electrical and plumbing systems.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a1647, to confirm availability, price, viewing and terms.

coordinates 13.320796, 100.966027 were extracted from the sam navigation href and match its map link. total usable area, bedrooms, bathroom count, parking capacity, building age and occupancy are not published. a photographed bathroom does not establish the total bathroom count.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20397&keyref=6007623', 'Official SAM page 20397 identifies SAM as asset holder and direct-sale contact for 3A1647.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '0280f160-f895-4b12-8a15-e4dd632d6693', '{"reference_code":"3A1647","source_page_id":20397,"source_image_count":18,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
