BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20424'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A1681' OR source_url ~ '[?&]id=20424(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='1c94bba1-0c39-44b6-8a15-0f736802070e' OR slug='sam-direct-sale-shophouse-phraya-satcha-mangrove-notice-3a1681' OR description ILIKE '%3A1681%' OR (abs(latitude-13.335371)<0.0001 AND abs(longitude-100.942397)<0.0001 AND abs(land_area_sqm-192)<1)) THEN RAISE NOTICE 'SAM 3A1681 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('1c94bba1-0c39-44b6-8a15-0f736802070e', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', '178/9', 'ขายตรง SAM อาคารพาณิชย์ 3 ชั้น 2 คูหา ถนนพระยาสัจจา 48 ตร.ว. มีหมายเหตุเขตป่าชายเลน', 'อาคารพาณิชย์ 3 ชั้น 2 คูหา เลขที่ 178/9 ถนนพระยาสัจจา ตำบลเสม็ด อำเภอเมืองชลบุรี จังหวัดชลบุรี โฉนดเลขที่ 123145 จำนวน 1 ฉบับ เนื้อที่ 48 ตร.ว. (192 ตร.ม.) ราคาประกาศขายจาก SAM 8,838,000 บาท รหัสทรัพย์ 3A1681 การสำรวจระบุอาคาร 3 ชั้นมีดาดฟ้า

ที่ดินรูปสี่เหลี่ยมผืนผ้า ด้านทิศเหนือติดถนนกว้างประมาณ 8 เมตร ลึกประมาณ 24 เมตร ถนนพระยาสัจจาเป็นทางสาธารณประโยชน์ ผิวลาดยางกว้างประมาณ 18 เมตร เขตทางประมาณ 28 เมตร ต้นทางระบุเขตผังเมืองสีส้มและย่านที่อยู่อาศัยกับพาณิชยกรรม

ข้อมูลสำคัญเรื่องเอกสารสิทธิ์และเขตป่าชายเลน: หน้า SAM ระบุว่าการตรวจ DSI MAP พบทรัพย์อยู่ในแนวเขตป่าชายเลนตามข้อมูลปี 2543 และสรุปข้อมูลที่สอบถามหน่วยงานชายฝั่งว่าเป็นพื้นที่เขตเศรษฐกิจ ข. พร้อมอ้างถึงโฉนดแปลงคงเลขที่ 23044 ซึ่งออกเมื่อ 10 พฤษภาคม 2516 ก่อนมติที่เกี่ยวข้อง ข้อความนี้เป็นข้อมูลที่ SAM รายงาน ไม่ใช่การรับรองสิทธิหรือข้อสรุปว่าพัฒนาได้โดยไม่มีข้อจำกัด

เอกสารแนบ “ประกาศเพื่อทราบ เรื่อง แจ้งข้อจำกัดและข้อมูลเพิ่มเติม” ของ SAM จำนวน 2 หน้า ระบุทรัพย์โฉนด 123145 อยู่ในเขตพื้นที่ป่าชายเลนตามมติคณะรัฐมนตรีวันที่ 15 ธันวาคม 2530 และ 22 สิงหาคม 2543 ผู้สนใจมีหน้าที่ตรวจที่มาของเอกสารสิทธิ์ SAM ขายตามสภาพและเอกสารปัจจุบัน โดยไม่รับรองความสมบูรณ์หรือความชอบด้วยกฎหมายของการออกเอกสารสิทธิ์ และกำหนดให้ผู้ซื้อรับทราบความเสี่ยงจากการเพิกถอนสิทธิ

ประกาศแนบยังมีเงื่อนไขกรณีเวนคืน โอนไม่ได้ หรือเอกสารสิทธิ์ถูกยกเลิกหรือเพิกถอน รวมถึงสิทธิยกเลิกการขายของ SAM และกรณีคืนเงินภายใน 30 วันหลังสัญญาสิ้นสุดโดยไม่มีดอกเบี้ยหรือค่าชดเชยตามเงื่อนไขที่ระบุ ผู้สนใจต้องอ่านเอกสารฉบับเต็มและยืนยันกับ SAM และสำนักงานที่ดินก่อนเสนอซื้อ ตรวจทั้งโฉนดปัจจุบัน 123145 ความเกี่ยวข้องกับโฉนดแปลงคง 23044 และข้อกำหนดป่าชายเลนล่าสุด

เอกสารต้นทาง: https://npa.sam.or.th/site/attach/npa/20424/ATTACH%203A1681.pdf

การเดินทางตาม SAM: ใช้ถนนพระยาสัจจาจากตัวเมืองชลบุรีมุ่งหน้าถนนสายบ้านเสม็ด–อ่างศิลา (ทล.3134) ผ่านสวนหลวงชลบุรี ถึงแยกพระยาสัจจา–คีรี ตรงไปประมาณ 950 เมตร ทรัพย์อยู่ซ้ายมือ สถานที่ใกล้เคียงที่ระบุคือวัดเมืองใหม่

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A1681 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม และเงื่อนไขล่าสุด

พิกัด 13.335371, 100.942397 ดึงจากลิงก์นำทาง SAM และตรงกับปุ่ม Google Map ภาพภายนอกแสดงวันที่ 25 พฤษภาคม 2565 และ 9 มกราคม 2567 ส่วนภาพภายในแสดงวันที่ 1 กันยายน 2566 มีภาพโถง ห้อง บันไดและห้องน้ำ ต้นทางไม่ระบุจำนวนห้องรวม พื้นที่ใช้สอย ที่จอดรถ อายุอาคาร หรือผู้ครอบครองปัจจุบัน จึงควรนัดตรวจสภาพจริง

หมายเหตุภาพแผนที่: ชื่อไฟล์มีรหัส 2T0771 ในวงเล็บ ขณะที่หน้าประกาศใช้ 3A1681 ให้ SAM ยืนยันความเกี่ยวข้องของรหัสดังกล่าวเมื่อสอบถามทรัพย์', 8838000, false, 192, 3, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '178/9 ถนนพระยาสัจจา', 'เลยแยกพระยาสัจจา–คีรีประมาณ 950 เมตร', 'ถนนพระยาสัจจา', 13.335371, 100.942397, 'ชลบุรี', 'เมืองชลบุรี', 'เสม็ด', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-shophouse-phraya-satcha-mangrove-notice-3a1681') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 8838000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"3A1681","source_page_id":20424,"title_document_type":"chanote","title_deed_number":"123145","title_document_count":1,"parent_title_deed_number_reported":"23044","parent_deed_issue_date_reported":"1973-05-10","land_area_square_wah":48,"land_area_sqm":192,"registered_floor_count":3,"registered_unit_count":2,"surveyed_roof_terrace":true,"north_road_frontage_m_approx":8,"depth_m_approx":24,"front_road_width_m_approx":18,"front_right_of_way_width_m_approx":28,"planning_zone_th":"เขตสีส้ม","mangrove_boundary_disclosure":true,"mangrove_economic_zone_source":"B","title_validity_not_warranted_in_sam_notice":true,"title_revocation_risk_disclosed":true,"source_notice_url":"https://npa.sam.or.th/site/attach/npa/20424/ATTACH%203A1681.pdf","source_notice_pages":2,"alternate_map_filename_reference":"2T0771","source_photo_dates":["2022-05-25","2023-09-01","2024-01-09"],"purchase_method":"direct_purchase_from_sam","status_checked_on":"2026-09-11","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.335371,100.942397","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20424 identifies SAM as direct-sale contact for 3A1681, two shophouse units with a specific mangrove and title-risk notice.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 3A1681 ราคา 8,838,000 บาท', 'SAM direct purchase, 3A1681, THB 8,838,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'mangrove_title_notice', 'มีประกาศเขตป่าชายเลนและความเสี่ยงเอกสารสิทธิ์', 'Mangrove and title-risk notice', 'ต้องตรวจที่มาโฉนด 123145 และแปลงคง 23044 SAM ไม่รับรองความชอบด้วยกฎหมายของเอกสารสิทธิ์ตามประกาศแนบ', 'Investigate deed 123145 and parent deed 23044; SAM notice does not warrant lawful title issuance', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'notice_terms', 'อ่านเงื่อนไขในประกาศแนบ', 'Read the complete notice', 'ประกาศ 2 หน้าระบุความเสี่ยงเพิกถอนสิทธิและเงื่อนไขกรณีโอนไม่ได้ ยกเลิก หรือคืนเงิน ให้ยืนยันกับ SAM ก่อนเสนอซื้อ', 'Two-page notice covers revocation risk, failed transfer, cancellation and refund conditions; confirm with SAM', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'source_map_reference', 'รหัสในชื่อไฟล์แผนที่', 'Map filename reference', 'ชื่อไฟล์แผนที่มี 2T0771 ขณะที่หน้าประกาศใช้ 3A1681 ให้ SAM ยืนยัน', 'Map filename includes 2T0771 while page identifies 3A1681; confirm with SAM', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคาร 178/9', 'ด้านหน้าอาคาร 178/9', 'https://npa.sam.or.th/site/images/npa/20424/20240627135345_3A1681P3_67.jpg', '/listing-media/sam/3a1681/01.webp', 'image/webp', 37086, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารและถนนพระยาสัจจา', 'อาคารและถนนพระยาสัจจา', 'https://npa.sam.or.th/site/images/npa/20424/3A1681P2_65.jpg', '/listing-media/sam/3a1681/02.webp', 'image/webp', 34254, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในอาคาร', 'โถงภายในอาคาร', 'https://npa.sam.or.th/site/images/npa/20424/P14_66.jpg', '/listing-media/sam/3a1681/03.webp', 'image/webp', 28200, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ชั้นล่าง', 'พื้นที่ชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/20424/P13_66.jpg', '/listing-media/sam/3a1681/04.webp', 'image/webp', 40702, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณทางเชื่อมภายใน', 'บริเวณทางเชื่อมภายใน', 'https://npa.sam.or.th/site/images/npa/20424/P3_66.jpg', '/listing-media/sam/3a1681/05.webp', 'image/webp', 23190, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและพื้นที่ภายใน', 'ห้องและพื้นที่ภายใน', 'https://npa.sam.or.th/site/images/npa/20424/P5_66.jpg', '/listing-media/sam/3a1681/06.webp', 'image/webp', 20414, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องผนังสีเหลือง', 'ห้องผนังสีเหลือง', 'https://npa.sam.or.th/site/images/npa/20424/P9_66.jpg', '/listing-media/sam/3a1681/07.webp', 'image/webp', 19426, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและช่องทางเชื่อม', 'ห้องและช่องทางเชื่อม', 'https://npa.sam.or.th/site/images/npa/20424/P10_66.jpg', '/listing-media/sam/3a1681/08.webp', 'image/webp', 18326, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในอีกมุม', 'พื้นที่ภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/20424/P12_66.jpg', '/listing-media/sam/3a1681/09.webp', 'image/webp', 24888, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องขนาดเล็ก', 'ห้องขนาดเล็ก', 'https://npa.sam.or.th/site/images/npa/20424/P7_66.jpg', '/listing-media/sam/3a1681/10.webp', 'image/webp', 16988, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินและประตูห้อง', 'ทางเดินและประตูห้อง', 'https://npa.sam.or.th/site/images/npa/20424/P4_66.jpg', '/listing-media/sam/3a1681/11.webp', 'image/webp', 23508, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องปูกระเบื้องผนัง', 'ห้องปูกระเบื้องผนัง', 'https://npa.sam.or.th/site/images/npa/20424/P8_66.jpg', '/listing-media/sam/3a1681/12.webp', 'image/webp', 40960, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักภายใน', 'ห้องพักภายใน', 'https://npa.sam.or.th/site/images/npa/20424/P11_66.jpg', '/listing-media/sam/3a1681/13.webp', 'image/webp', 17660, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำพร้อมสุขภัณฑ์', 'ห้องน้ำพร้อมสุขภัณฑ์', 'https://npa.sam.or.th/site/images/npa/20424/P6_66.jpg', '/listing-media/sam/3a1681/14.webp', 'image/webp', 21282, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ถนนพระยาสัจจาอีกทิศทาง', 'ถนนพระยาสัจจาอีกทิศทาง', 'https://npa.sam.or.th/site/images/npa/20424/3A1681P1_65.jpg', '/listing-media/sam/3a1681/16.webp', 'image/webp', 34526, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังโฉนด 123145', 'ผังโฉนด 123145', 'https://npa.sam.or.th/site/images/npa/20424/20221111092545_3A1681C2_65.jpg', '/listing-media/sam/3a1681/17.webp', 'image/webp', 11306, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังอาคารตามต้นทาง', 'ผังอาคารตามต้นทาง', 'https://npa.sam.or.th/site/images/npa/20424/20221111092545_3A1681C1_65.jpg', '/listing-media/sam/3a1681/18.webp', 'image/webp', 16588, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทาง', 'แผนที่การเดินทาง', 'https://npa.sam.or.th/site/images/npa/20424/20221111092545_3A1681M_65 (2T0771).jpg', '/listing-media/sam/3a1681/19.webp', 'image/webp', 49092, 785, 600, 180, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20424&keyref=6007623', '3A1681', now(), 'Official source captured 2026-09-11. THB 8,838,000, 48 sq.wah, two three-storey shophouse units. Mangrove/title notice read visually in full (2 pages); disclosure retained in Thai/English and terms. Source page background is not treated as legal clearance. 19 URLs contain 18 unique images; identical cover duplicate excluded. Alternate map reference 2T0771 recorded. Navigation/map hrefs agree. All-status duplicate search found no matches.') ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://npa.sam.or.th/site/attach/npa/20424/ATTACH%203A1681.pdf', '3A1681-NOTICE', now(), 'Two-page specific notice for deed 123145. Mangrove boundary, title provenance and revocation risk, no warranty of lawful issuance, cancellation/refund conditions and buyer acknowledgement. Read full document before offering.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Phraya Satcha Shophouse, THB 8.838M, Mangrove/Title Notice', 'Two three-storey shophouse units numbered 178/9 on Phraya Satcha Road, Samet, Mueang Chon Buri, Chon Buri. One deed, 123145, covers 48 sq.wah (192 sq.m.). SAM announced price THB 8,838,000; asset 3A1681. The survey describes a roof terrace.

Rectangular plot with approximately eight metres of northern road frontage and 24 metres depth. Public asphalt road, approximately 18 metres wide within a 28-metre right of way. SAM reports orange planning zoning and residential/commercial surroundings.

Material mangrove and title disclosure: SAM reports that the property appears within a 2000 mangrove boundary dataset. Its page cites coastal-authority information about economic zone B and parent deed 23044 issued on 10 May 1973. This is source-reported background, not a title-validity guarantee or unrestricted development entitlement.

The attached two-page SAM notice specifically identifies deed 123145 within mangrove areas under Cabinet resolutions dated 15 December 1987 and 22 August 2000. Buyers must investigate title provenance. SAM sells as-is under current documents without warranting their completeness or lawful issuance; the notice allocates title-revocation risk to the buyer.

The notice includes conditions concerning expropriation, failed transfer, cancellation or revocation of title, SAM cancellation rights, and specified refunds within 30 days after contract termination without interest or compensation. Read the complete notice and verify current deed 123145, its relationship to parent deed 23044 and current restrictions with SAM and the land office before offering.

Source notice: https://npa.sam.or.th/site/attach/npa/20424/ATTACH%203A1681.pdf

From central Chon Buri take Phraya Satcha Road toward Highway 3134, pass Suan Luang Chonburi and continue approximately 950 metres beyond the Phraya Satcha–Khiri junction; the property is on the left. SAM lists Wat Mueang Mai nearby.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A1681. Navigation and map coordinates agree: 13.335371, 100.942397. Exterior photos display 25 May 2022 and 9 January 2024; interiors display 1 September 2023. Room counts, usable area, parking, age and current occupancy are not published. Map filename additionally contains 2T0771; confirm its relationship with SAM.', '178/9, Phraya Satcha Road', 'Approx. 950 metres beyond the Phraya Satcha–Khiri junction', 'Phraya Satcha Road', 'Samet', 'Mueang Chon Buri', 'Chon Buri', 'SAM Phraya Satcha Shophouse — THB 8.838M, Title Notice', 'SAM 3A1681: two shophouse units on 48 sq.wah, Phraya Satcha Road. Mangrove and title-risk notice disclosed. THB 8,838,000.', 'published', 'ai_assisted', now(), 'sam direct sale: phraya satcha shophouse, thb 8.838m, mangrove/title notice two three-storey shophouse units numbered 178/9 on phraya satcha road, samet, mueang chon buri, chon buri. one deed, 123145, covers 48 sq.wah (192 sq.m.). sam announced price thb 8,838,000; asset 3a1681. the survey describes a roof terrace.

rectangular plot with approximately eight metres of northern road frontage and 24 metres depth. public asphalt road, approximately 18 metres wide within a 28-metre right of way. sam reports orange planning zoning and residential/commercial surroundings.

material mangrove and title disclosure: sam reports that the property appears within a 2000 mangrove boundary dataset. its page cites coastal-authority information about economic zone b and parent deed 23044 issued on 10 may 1973. this is source-reported background, not a title-validity guarantee or unrestricted development entitlement.

the attached two-page sam notice specifically identifies deed 123145 within mangrove areas under cabinet resolutions dated 15 december 1987 and 22 august 2000. buyers must investigate title provenance. sam sells as-is under current documents without warranting their completeness or lawful issuance; the notice allocates title-revocation risk to the buyer.

the notice includes conditions concerning expropriation, failed transfer, cancellation or revocation of title, sam cancellation rights, and specified refunds within 30 days after contract termination without interest or compensation. read the complete notice and verify current deed 123145, its relationship to parent deed 23044 and current restrictions with sam and the land office before offering.

source notice: https://npa.sam.or.th/site/attach/npa/20424/attach%203a1681.pdf

from central chon buri take phraya satcha road toward highway 3134, pass suan luang chonburi and continue approximately 950 metres beyond the phraya satcha–khiri junction; the property is on the left. sam lists wat mueang mai nearby.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a1681. navigation and map coordinates agree: 13.335371, 100.942397. exterior photos display 25 may 2022 and 9 january 2024; interiors display 1 september 2023. room counts, usable area, parking, age and current occupancy are not published. map filename additionally contains 2t0771; confirm its relationship with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20424&keyref=6007623', 'Official SAM page 20424 identifies SAM as asset holder and direct-sale contact for 3A1681.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '1c94bba1-0c39-44b6-8a15-0f736802070e', '{"reference_code":"3A1681","source_page_id":20424,"source_image_count":18,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
