BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-19760'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A1362' OR source_url ~ '[?&]id=19760(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='9b30e6e7-bcce-4db0-bc2f-b13ccfe94d54' OR slug='sam-direct-sale-20-room-apartment-huai-kapi-16-3a1362' OR description ILIKE '%3A1362%' OR (abs(latitude-13.299642)<0.0001 AND abs(longitude-100.96105)<0.0001 AND abs(land_area_sqm-880)<1)) THEN RAISE NOTICE 'SAM 3A1362 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, accommodation_model, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('9b30e6e7-bcce-4db0-bc2f-b13ccfe94d54', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'apartment', 'standard', 'residence', 'sale', 'whole_property', 'ขายตรง SAM อาคารห้องเช่า 2 ชั้น 20 ห้อง ซอยห้วยกะปิ 16 ชลบุรี 220 ตร.ว.', 'อาคารห้องเช่า 2 ชั้น จำนวน 20 ห้อง ตามข้อมูลสำรวจของ SAM ไม่มีเลขที่ ตั้งอยู่ในซอยห้วยกะปิ 16 ตำบลห้วยกะปิ อำเภอเมืองชลบุรี จังหวัดชลบุรี โฉนดเลขที่ 138457 จำนวน 1 ฉบับ เนื้อที่ 2 งาน 20 ตร.ว. หรือ 220 ตร.ว. (880 ตร.ม.) ราคาประกาศขายจาก SAM 7,935,000 บาท รหัสทรัพย์ 3A1362 เป็นการขายทั้งทรัพย์ ไม่ใช่ประกาศให้เช่ารายห้อง

ที่ดินรูปสี่เหลี่ยมผืนผ้า ด้านทิศเหนือติดถนนกว้างประมาณ 49.2 เมตร ลึกประมาณ 18 เมตร รายการตามทะเบียนที่ SAM รับโอนประกอบด้วยอาคารอยู่อาศัยรวม 2 ชั้นไม่มีเลขที่ และโรงจอดรถไม่มีเลขที่ การสำรวจพบห้องเช่า 2 ชั้น 20 ห้อง โดยโครงสร้างบางส่วนติดกับส่วนโล่งหลังคาคลุม ควรตรวจความเชื่อมต่อของโครงสร้าง ทะเบียนและใบอนุญาตอาคารก่อนซื้อ

ข้อมูลสำคัญเรื่องทางเข้า: ถนนหน้าทรัพย์เป็นทางส่วนบุคคลบนโฉนดเลขที่ 138455 ซึ่ง SAM ระบุว่าจดภาระจำยอมให้แปลงทรัพย์แล้ว ครอบคลุมทางเดิน ทางรถยนต์ ไฟฟ้า ประปา โทรศัพท์ ท่อระบายน้ำ และสาธารณูปโภคอื่น ผิวคอนกรีตกว้างประมาณ 4 เมตร เขตทางประมาณ 6 เมตร ผู้ซื้อควรตรวจเอกสาร ขอบเขตสิทธิและการใช้ทางจริง ไม่ควรเข้าใจว่าถนนนี้เป็นถนนสาธารณะ

ต้นทางระบุเขตผังเมืองสีส้มอ่อนมีจุดสีขาว อยู่ในย่านที่อยู่อาศัย สถานที่ใกล้เคียง ได้แก่ วิทยาลัยสารพัดช่างชลบุรี ชุมสายบางแสน และตลาดนัดจตุจักร

การเดินทางตาม SAM: ใช้ถนนสุขุมวิท (ทล.3) จากตลาดหนองมนมุ่งหน้าตัวเมืองชลบุรี ผ่านวัดบางแป้งและตลาดนัดจตุจักร ผ่าน กม.102 เข้าซอยห้วยกะปิ 16 ฝั่งขวามือประมาณ 1.3 กิโลเมตร ทรัพย์อยู่ด้านขวามือ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A1362 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม ภาระจำยอม และเงื่อนไขล่าสุด

พิกัด 13.299642, 100.961050 ดึงจากลิงก์ระบบนำทางและตรงกับปุ่ม Google Map ภาพอาคารและภายในแสดงวันที่ 8 ตุลาคม 2566 มีภาพห้อง ทางเดิน บันไดและห้องน้ำ ต้นทางไม่ระบุพื้นที่ใช้สอย ขนาดแต่ละห้อง จำนวนห้องน้ำรวม จำนวนที่จอดรถ อายุอาคาร จำนวนผู้เช่าปัจจุบัน สัญญาเช่า ค่าเช่า รายได้ หรือค่าใช้จ่าย จึงไม่คำนวณผลตอบแทนจากข้อมูลที่ยังไม่ยืนยัน ควรนัดตรวจสภาพอาคารและข้อมูลการเช่าปัจจุบันกับ SAM', 7935000, false, 880, 2, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'อาคารห้องเช่า ไม่มีเลขที่ ซอยห้วยกะปิ 16', 'เข้าจากถนนสุขุมวิทประมาณ 1.3 กิโลเมตร', 'ซอยห้วยกะปิ 16', 13.299642, 100.96105, 'ชลบุรี', 'เมืองชลบุรี', 'ห้วยกะปิ', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-20-room-apartment-huai-kapi-16-3a1362') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 7935000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'apartment', 1, '{"source_property_category":"อาคารพักอาศัย","official_page_reference_code":"3A1362","source_page_id":19760,"accommodation_model":"standard","title_document_type":"chanote","title_deed_number":"138457","title_document_count":1,"land_area_square_wah":220,"land_area_sqm":880,"registered_floor_count":2,"surveyed_rental_room_count":20,"room_count":20,"registered_structures":["อาคารอยู่อาศัยรวม 2 ชั้น ไม่มีเลขที่","โรงจอดรถ ไม่มีเลขที่"],"structure_connected_to_open_covered_area":true,"north_road_frontage_m_approx":49.2,"depth_m_approx":18,"private_road_title_deed_number":"138455","private_road_width_m_approx":4,"right_of_way_width_m_approx":6,"registered_access_and_utilities_easement_reported":true,"easement_scope":["pedestrians","vehicles","electricity","water","telephone","drainage","other_utilities"],"planning_zone_th":"สีส้มอ่อนมีจุดสีขาว","occupancy_not_published":true,"rental_income_not_published":true,"rent_roll_not_published":true,"usable_area_not_published":true,"purchase_method":"direct_purchase_from_sam","status_checked_on":"2026-09-11","source_photo_date":"2023-10-08","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.299642,100.961050","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 19760 identifies SAM as direct-sale contact for 3A1362, two-storey residential building surveyed as 20 rental rooms, with a private-road easement.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'ขายทั้งทรัพย์', 'Whole-property sale', 'ซื้อตรง SAM รหัส 3A1362 ราคา 7,935,000 บาท ไม่ใช่ให้เช่ารายห้อง', 'SAM direct whole-property sale, THB 7,935,000; not individual room rental', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'rental_rooms', 'ห้องเช่าตามข้อมูลสำรวจ', 'Surveyed rental rooms', 'อาคาร 2 ชั้น 20 ห้อง ไม่ระบุจำนวนผู้เช่าหรือรายได้ปัจจุบัน', 'Two storeys, 20 surveyed rooms; current tenants and income not published', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'private_access_easement', 'ภาระจำยอมทางเข้าและสาธารณูปโภค', 'Private access and utilities easement', 'ถนนโฉนด 138455 จดภาระจำยอมตามข้อมูล SAM ต้องตรวจขอบเขตและการใช้จริง', 'SAM reports registered easement over deed 138455; verify scope and actual use', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'income_verification', 'ข้อมูลรายได้ต้องยืนยัน', 'Income requires verification', 'ไม่ระบุค่าเช่า สัญญาเช่า รายรับหรือรายจ่าย จึงไม่ประมาณผลตอบแทน', 'Rents, leases, income and expenses not published; no yield estimated', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'แนวอาคารห้องเช่า 2 ชั้น', 'แนวอาคารห้องเช่า 2 ชั้น', 'https://npa.sam.or.th/site/images/npa/19760/20240103134344_P3_66.jpg', '/listing-media/sam/3a1362/01.webp', 'image/webp', 31588, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านหน้าอาคารและพื้นที่จอดรถ', 'ด้านหน้าอาคารและพื้นที่จอดรถ', 'https://npa.sam.or.th/site/images/npa/19760/P1_66.jpg', '/listing-media/sam/3a1362/02.webp', 'image/webp', 22710, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าและบันไดอาคาร', 'ทางเข้าและบันไดอาคาร', 'https://npa.sam.or.th/site/images/npa/19760/P4_66.jpg', '/listing-media/sam/3a1362/03.webp', 'image/webp', 28588, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายใน', 'โถงภายใน', 'https://npa.sam.or.th/site/images/npa/19760/P5_66.jpg', '/listing-media/sam/3a1362/04.webp', 'image/webp', 18292, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องเช่าภายใน', 'ห้องเช่าภายใน', 'https://npa.sam.or.th/site/images/npa/19760/P12_66.jpg', '/listing-media/sam/3a1362/05.webp', 'image/webp', 19048, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องเช่าอีกมุม', 'ห้องเช่าอีกมุม', 'https://npa.sam.or.th/site/images/npa/19760/P16_66.jpg', '/listing-media/sam/3a1362/06.webp', 'image/webp', 17780, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและหน้าต่าง', 'ห้องและหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/19760/P17_66.jpg', '/listing-media/sam/3a1362/07.webp', 'image/webp', 16670, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดขึ้นชั้นบน', 'บันไดขึ้นชั้นบน', 'https://npa.sam.or.th/site/images/npa/19760/P9_66.jpg', '/listing-media/sam/3a1362/08.webp', 'image/webp', 18586, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชานพักและทางเดิน', 'ชานพักและทางเดิน', 'https://npa.sam.or.th/site/images/npa/19760/P7_66.jpg', '/listing-media/sam/3a1362/09.webp', 'image/webp', 23220, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ระเบียงทางเดินชั้นบน', 'ระเบียงทางเดินชั้นบน', 'https://npa.sam.or.th/site/images/npa/19760/P8_66.jpg', '/listing-media/sam/3a1362/10.webp', 'image/webp', 31984, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวห้องชั้นบน', 'แนวห้องชั้นบน', 'https://npa.sam.or.th/site/images/npa/19760/P6_66.jpg', '/listing-media/sam/3a1362/11.webp', 'image/webp', 33922, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอีกห้อง', 'ห้องภายในอีกห้อง', 'https://npa.sam.or.th/site/images/npa/19760/P14_66.jpg', '/listing-media/sam/3a1362/12.webp', 'image/webp', 19300, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและประตู', 'ห้องและประตู', 'https://npa.sam.or.th/site/images/npa/19760/P15_66.jpg', '/listing-media/sam/3a1362/13.webp', 'image/webp', 20654, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำ', 'ห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/19760/P13_66.jpg', '/listing-media/sam/3a1362/14.webp', 'image/webp', 15904, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องเช่าพื้นที่ภายใน', 'ห้องเช่าพื้นที่ภายใน', 'https://npa.sam.or.th/site/images/npa/19760/P10_66.jpg', '/listing-media/sam/3a1362/15.webp', 'image/webp', 20154, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำอีกมุม', 'ห้องน้ำอีกมุม', 'https://npa.sam.or.th/site/images/npa/19760/P11_66.jpg', '/listing-media/sam/3a1362/16.webp', 'image/webp', 21174, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าซอยห้วยกะปิ 16', 'ทางเข้าซอยห้วยกะปิ 16', 'https://npa.sam.or.th/site/images/npa/19760/3A1362P1_64.jpg', '/listing-media/sam/3a1362/17.webp', 'image/webp', 33162, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงและถนนภาระจำยอม', 'ผังแปลงและถนนภาระจำยอม', 'https://npa.sam.or.th/site/images/npa/19760/20210920145709_3A1362C1_64.jpg', '/listing-media/sam/3a1362/18.webp', 'image/webp', 9466, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังอาคารและส่วนหลังคาคลุม', 'ผังอาคารและส่วนหลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/19760/20210920145709_3A1362C2_64.jpg', '/listing-media/sam/3a1362/19.webp', 'image/webp', 12468, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทาง', 'แผนที่การเดินทาง', 'https://npa.sam.or.th/site/images/npa/19760/20210920145709_3A1362M1_64.jpg', '/listing-media/sam/3a1362/20.webp', 'image/webp', 37648, 785, 600, 200, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=19760&keyref=6007623', '3A1362', now(), 'Official SAM source captured 2026-09-11. Whole-property sale THB 7,935,000; 220 sq.wah; two-storey building surveyed as 20 rental rooms. Registered acquisitions residential building and garage. Private road deed 138455 with SAM-reported registered pedestrian/vehicle/utilities easement. No rent roll, income, tenancy or yields inferred. 20 source images retained, building photos dated 2023-10-08. Coordinates extracted from navigation and cross-checked with map. All-status duplicate search found no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 20-Room Apartment Building, Huai Kapi 16, THB 7.935M', 'Two-storey rental-room building with 20 rooms according to the SAM survey, without a stated house number, in Soi Huai Kapi 16, Huai Kapi, Mueang Chon Buri, Chon Buri. Deed 138457 covers 220 sq.wah (880 sq.m.). SAM announced price THB 7,935,000; asset 3A1362. This is a sale of the whole property, not an individual room rental offer.

Rectangular plot with approximately 49.2 metres of northern frontage and 18 metres depth. Registered acquisitions comprise an unnumbered two-storey collective residential building and an unnumbered garage. The survey reports 20 rental rooms and structural connections to an open-sided covered area. Verify structure, registration and permits.

Access is private land, deed 138455. SAM reports a registered easement benefiting the property for pedestrian and vehicle access, electricity, water, telephone, drainage and other utilities. The concrete carriageway is approximately four metres wide within a six-metre right of way. Verify the easement instrument, scope and actual access; this is not represented as a public road.

SAM reports light-orange planning zoning with white dots and residential surroundings. Nearby source-listed places include Chonburi Polytechnic College, Bang Saen Telephone Exchange and Chatuchak Market.

From Nong Mon Market toward Chon Buri on Sukhumvit Road, pass Wat Bang Paeng and Chatuchak Market. After kilometre 102, enter Soi Huai Kapi 16 on the right for approximately 1.3 kilometres; the property is on the right.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A1362, to confirm availability, price, viewing, easement and terms. Navigation and map links agree on 13.299642, 100.961050.

Building/interior photographs display 8 October 2023 and include rooms, corridors, stairs and bathrooms. Usable area, room sizes, bathroom total, parking, age, current tenants, leases, rents, income and expenses are not published. No rental yield is inferred; inspect current property and tenancy information.', 'Unnumbered rental-room building, Soi Huai Kapi 16', 'Approx. 1.3 km from Sukhumvit Road', 'Soi Huai Kapi 16', 'Huai Kapi', 'Mueang Chon Buri', 'Chon Buri', 'SAM 20-Room Building, Huai Kapi 16 — THB 7.935M', 'SAM 3A1362: two-storey 20-room building on 220 sq.wah, Huai Kapi 16. Whole-property sale THB 7,935,000; private-road easement disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: 20-room apartment building, huai kapi 16, thb 7.935m two-storey rental-room building with 20 rooms according to the sam survey, without a stated house number, in soi huai kapi 16, huai kapi, mueang chon buri, chon buri. deed 138457 covers 220 sq.wah (880 sq.m.). sam announced price thb 7,935,000; asset 3a1362. this is a sale of the whole property, not an individual room rental offer.

rectangular plot with approximately 49.2 metres of northern frontage and 18 metres depth. registered acquisitions comprise an unnumbered two-storey collective residential building and an unnumbered garage. the survey reports 20 rental rooms and structural connections to an open-sided covered area. verify structure, registration and permits.

access is private land, deed 138455. sam reports a registered easement benefiting the property for pedestrian and vehicle access, electricity, water, telephone, drainage and other utilities. the concrete carriageway is approximately four metres wide within a six-metre right of way. verify the easement instrument, scope and actual access; this is not represented as a public road.

sam reports light-orange planning zoning with white dots and residential surroundings. nearby source-listed places include chonburi polytechnic college, bang saen telephone exchange and chatuchak market.

from nong mon market toward chon buri on sukhumvit road, pass wat bang paeng and chatuchak market. after kilometre 102, enter soi huai kapi 16 on the right for approximately 1.3 kilometres; the property is on the right.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a1362, to confirm availability, price, viewing, easement and terms. navigation and map links agree on 13.299642, 100.961050.

building/interior photographs display 8 october 2023 and include rooms, corridors, stairs and bathrooms. usable area, room sizes, bathroom total, parking, age, current tenants, leases, rents, income and expenses are not published. no rental yield is inferred; inspect current property and tenancy information.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=19760&keyref=6007623', 'Official SAM page 19760 identifies SAM as asset holder and direct-sale contact for 3A1362.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '9b30e6e7-bcce-4db0-bc2f-b13ccfe94d54', '{"reference_code":"3A1362","source_page_id":19760,"source_image_count":20,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
