BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-22900'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='SL0184' OR source_url ~ '[?&]id=22900(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='4c92b592-21bd-4119-9fba-48cfde5f1840' OR slug='sam-direct-sale-shophouse-si-racha-nakhon-6-sl0184' OR description ILIKE '%SL0184%' OR (abs(latitude-13.168283)<0.0001 AND abs(longitude-100.928518)<0.0001 AND abs(land_area_sqm-64)<1)) THEN RAISE NOTICE 'SAM SL0184 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('4c92b592-21bd-4119-9fba-48cfde5f1840', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', 'ศรีราชานคร', '34', 'ขายตรง SAM อาคารพาณิชย์ 3 ชั้น มีชั้นลอยและดาดฟ้า ศรีราชานคร 6 ที่ดิน 16 ตร.ว.', 'อาคารพาณิชย์ 3 ชั้น มีชั้นลอยและดาดฟ้าตามข้อมูลสำรวจของ SAM เลขที่ 34 โครงการศรีราชานคร ถนนศรีราชานคร 6 ตำบลศรีราชา อำเภอศรีราชา จังหวัดชลบุรี ที่ดินโฉนดเลขที่ 84489 จำนวน 1 ฉบับ เนื้อที่ 16 ตร.ว. (64 ตร.ม.) ต้นทางระบุ 3 ห้องนอน 4 ห้องน้ำ ราคาประกาศขาย 7,634,000 บาท รหัสทรัพย์ SL0184

ที่ดินรูปสี่เหลี่ยมผืนผ้า ด้านทิศตะวันตกติดถนน หน้ากว้างประมาณ 4 เมตร ลึกประมาณ 16 เมตร ถนนหน้าทรัพย์คือถนนศรีราชานคร 6 เป็นทางในโครงการจัดสรรที่ได้รับอนุญาตแล้ว ผิวคอนกรีตกว้างประมาณ 8 เมตร เขตทางประมาณ 10 เมตร

รายการที่ SAM รับโอนกรรมสิทธิ์ระบุเป็นอาคารพาณิชย์ 3 ชั้น ไม่ปรากฏเลขที่ ขณะที่ข้อมูลที่ตั้งหน้าเว็บระบุเลขที่ 34 และข้อมูลสำรวจระบุอาคาร 3 ชั้น มีชั้นลอยและดาดฟ้า ผู้สนใจควรตรวจเลขที่อาคาร ทะเบียนสิ่งปลูกสร้างและใบอนุญาตส่วนต่อเติมให้ตรงกับสภาพจริงก่อนซื้อ

ต้นทางระบุเขตผังเมืองสีแดง ตั้งอยู่ในย่านที่อยู่อาศัยและย่านการค้าศูนย์กลางพาณิชยกรรมใจกลางเมืองศรีราชา ใกล้โรงพยาบาลพญาไท เหมาะสำหรับพิจารณาการใช้ประโยชน์ด้านอยู่อาศัยหรือการค้า โดยต้องตรวจข้อกำหนดและใบอนุญาตของกิจการที่ต้องการ

การเดินทางตาม SAM: ใช้ถนนสุขุมวิท (ทล.3) จากตัวเมืองชลบุรีมุ่งหน้าแหลมฉบัง ผ่านที่ว่าการอำเภอศรีราชา การไฟฟ้าส่วนภูมิภาคศรีราชา และศูนย์การค้าโรบินสัน เลี้ยวขวาเข้าถนนศรีราชานคร 3 และถนนศรีราชานคร 6 ประมาณ 385 เมตร ทรัพย์อยู่ด้านซ้ายมือ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส SL0184 เพื่อยืนยันราคา สถานะพร้อมขาย การนัดชม และเงื่อนไขล่าสุด

พิกัด 13.168283, 100.928518 ดึงจากลิงก์ระบบนำทาง SAM และตรงกับลิงก์ Google Map ภาพอาคารและภายในชุดล่าสุดแสดงวันที่ 4 มีนาคม 2569 พร้อมภาพถนน ผังชั้น ผังแปลงและแผนที่ รวม 14 ภาพ ต้นทางไม่ระบุพื้นที่ใช้สอยรวม อายุอาคาร จำนวนที่จอดรถ หรือสถานะผู้ครอบครอง จึงต้องยืนยันข้อมูลเหล่านี้และตรวจสภาพปัจจุบันกับ SAM', 7634000, false, 64, 3, 3, 4, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '34 โครงการศรีราชานคร ถนนศรีราชานคร 6', 'เข้าจากถนนสุขุมวิทผ่านถนนศรีราชานคร 3 ประมาณ 385 เมตร', 'ถนนศรีราชานคร 6', 13.168283, 100.928518, 'ชลบุรี', 'ศรีราชา', 'ศรีราชา', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-shophouse-si-racha-nakhon-6-sl0184') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 7634000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"SL0184","source_page_id":22900,"alternate_reference_code_in_map_filename":"3A0931","project_name":"ศรีราชานคร","title_document_type":"chanote","title_deed_number":"84489","title_document_count":1,"land_area_square_wah":16,"land_area_sqm":64,"plot_shape":"rectangular","west_road_frontage_m_approx":4,"depth_m_approx":16,"front_road_width_m_approx":8,"front_right_of_way_width_m_approx":10,"front_road_status":"road_in_approved_subdivision","planning_zone_th":"เขตสีแดง","registered_floor_count":3,"registered_building_number_not_stated":true,"source_address_number":"34","has_mezzanine":true,"has_roof_terrace":true,"source_bedroom_count":3,"source_bathroom_count":4,"registered_and_surveyed_structure_verification_required":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","latest_source_photo_date":"2026-03-04","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.168283,100.928518","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 22900 identifies SAM as direct-sale contact for SL0184, a three-storey shophouse in Si Racha Nakhon.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส SL0184 ราคา 7,634,000 บาท', 'SAM direct purchase SL0184, THB 7,634,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_buildings', 'ทะเบียนและสภาพอาคาร', 'Registered and surveyed building', 'ทะเบียนระบุอาคาร 3 ชั้นไม่ปรากฏเลขที่ หน้าเว็บระบุเลขที่ 34 สำรวจพบชั้นลอยและดาดฟ้า ต้องตรวจเอกสารและใบอนุญาต', 'Registered three-storey building has no stated number; web address is 34; surveyed mezzanine and roof terrace require document and permit checks', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_frontage', 'ถนนหน้าแปลง', 'Front road', 'ถนนศรีราชานคร 6 ทางในโครงการจัดสรรที่ได้รับอนุญาต ผิวคอนกรีต 8 ม. เขตทาง 10 ม. โดยประมาณ', 'Si Racha Nakhon 6, road in approved subdivision; approx. 8 m carriageway and 10 m right of way', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพปัจจุบัน', 'Current inspection', 'ภาพอาคารล่าสุดวันที่ 4 มีนาคม 2569 ต้องยืนยันพื้นที่ใช้สอยและสถานะผู้ครอบครอง', 'Latest building photos 4 March 2026; confirm usable area and occupancy', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารพาณิชย์ที่ประกาศขาย', 'ด้านหน้าอาคารพาณิชย์ที่ประกาศขาย', 'https://npa.sam.or.th/site/images/npa/22900/20260317113323_SL0184P1_69.jpg', '/listing-media/sam/sl0184/01.webp', 'image/webp', 24434, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นล่างและเคาน์เตอร์', 'โถงชั้นล่างและเคาน์เตอร์', 'https://npa.sam.or.th/site/images/npa/22900/SL0184P3_69.jpg', '/listing-media/sam/sl0184/02.webp', 'image/webp', 38990, 714, 536, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในชั้นล่างอีกมุม', 'พื้นที่ภายในชั้นล่างอีกมุม', 'https://npa.sam.or.th/site/images/npa/22900/SL0184P5_69.jpg', '/listing-media/sam/sl0184/03.webp', 'image/webp', 33668, 715, 536, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชานบันไดและทางเดิน', 'ชานบันไดและทางเดิน', 'https://npa.sam.or.th/site/images/npa/22900/SL0184P6_69.jpg', '/listing-media/sam/sl0184/04.webp', 'image/webp', 23894, 714, 536, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในผนังลายตาราง', 'ห้องภายในผนังลายตาราง', 'https://npa.sam.or.th/site/images/npa/22900/SL0184P7_69.jpg', '/listing-media/sam/sl0184/05.webp', 'image/webp', 39572, 714, 537, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินชั้นบน', 'ทางเดินชั้นบน', 'https://npa.sam.or.th/site/images/npa/22900/SL0184P9_69.jpg', '/listing-media/sam/sl0184/06.webp', 'image/webp', 20284, 716, 536, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดขึ้นดาดฟ้า', 'บันไดขึ้นดาดฟ้า', 'https://npa.sam.or.th/site/images/npa/22900/SL0184P10_69.jpg', '/listing-media/sam/sl0184/07.webp', 'image/webp', 24840, 714, 536, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ดาดฟ้าและส่วนหลังคาคลุม', 'ดาดฟ้าและส่วนหลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/22900/SL0184P11_69.jpg', '/listing-media/sam/sl0184/08.webp', 'image/webp', 44580, 716, 536, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าถนนศรีราชานคร 6', 'ทางเข้าถนนศรีราชานคร 6', 'https://npa.sam.or.th/site/images/npa/22900/SL0184P1_68.jpg', '/listing-media/sam/sl0184/09.webp', 'image/webp', 37354, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังชั้น 1 ชั้นลอยและชั้น 2', 'ผังชั้น 1 ชั้นลอยและชั้น 2', 'https://npa.sam.or.th/site/images/npa/22900/SL0184C3_68.jpg', '/listing-media/sam/sl0184/10.webp', 'image/webp', 14020, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังชั้น 3 และดาดฟ้า', 'ผังชั้น 3 และดาดฟ้า', 'https://npa.sam.or.th/site/images/npa/22900/SL0184C4_68.jpg', '/listing-media/sam/sl0184/11.webp', 'image/webp', 6624, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด 84489', 'ผังแปลงโฉนด 84489', 'https://npa.sam.or.th/site/images/npa/22900/20251215103100_SL0184C1_68.jpg', '/listing-media/sam/sl0184/12.webp', 'image/webp', 9508, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งอาคารบนแปลง', 'ผังตำแหน่งอาคารบนแปลง', 'https://npa.sam.or.th/site/images/npa/22900/20251215103100_SL0184C2_68.jpg', '/listing-media/sam/sl0184/13.webp', 'image/webp', 18664, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/22900/20251215103100_SL0184M_68 (3A0931).jpg', '/listing-media/sam/sl0184/14.webp', 'image/webp', 69216, 785, 600, 140, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=22900&keyref=6007684', 'SL0184', now(), 'Official source captured 2026-09-11. Direct sale THB 7,634,000; 16 sq.wah; three bedrooms/four bathrooms; three storeys plus surveyed mezzanine and roof terrace. Address 34 differs from registered acquisition with no number stated; disclosed. Approved-subdivision road. Fourteen source images, latest building photos 2026-03-04. Map filename contains alternate reference 3A0931; both codes and deed/nearby coordinates checked for duplicates with no matches. Coordinates extracted from navigation and cross-checked against map.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 3-Storey Shophouse, Si Racha Nakhon 6, THB 7.634M', 'Three-storey shophouse with a mezzanine and roof terrace according to SAM''s survey, address 34, Si Racha Nakhon project, Si Racha Nakhon 6 Road, Si Racha subdistrict and district, Chon Buri. One title deed, 84489, covers 16 sq.wah (64 sq.m.). SAM lists three bedrooms and four bathrooms. Announced sale price THB 7,634,000; asset SL0184.

Rectangular plot with approximately four metres of western road frontage and 16 metres depth. Si Racha Nakhon 6 is described as a road within an approved subdivision, with approximately eight metres of concrete carriageway and a ten-metre right of way.

SAM''s registered acquisition describes an unnumbered three-storey shophouse, while the web address states number 34 and the survey includes a mezzanine and roof terrace. Verify the building number, registered structures and permits for additions against the actual property.

SAM reports red planning zoning and residential/commercial surroundings in central Si Racha, near Phyathai Hospital. Check permitted uses and relevant operating licences for the intended activity.

From Chon Buri toward Laem Chabang on Sukhumvit Road, pass Si Racha district office, the Provincial Electricity Authority and Robinson. Turn right into Si Racha Nakhon 3 and Si Racha Nakhon 6 for approximately 385 metres; the property is on the left.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting SL0184, to confirm availability, price, viewing and terms.

Navigation and map links agree on 13.168283, 100.928518. The latest building and interior photographs display 4 March 2026. Fourteen source images include street views, floor plans, plot plans and a location map. Total usable area, building age, parking capacity and occupancy are not published; confirm these and inspect current condition with SAM.', '34, Si Racha Nakhon project, Si Racha Nakhon 6 Road', 'Approx. 385 metres via Si Racha Nakhon 3 from Sukhumvit Road', 'Si Racha Nakhon 6 Road', 'Si Racha', 'Si Racha', 'Chon Buri', 'SAM Si Racha Nakhon Shophouse — THB 7.634M', 'SAM SL0184: three-storey shophouse with mezzanine and roof terrace, 16 sq.wah, 3 bedrooms, 4 bathrooms. THB 7,634,000.', 'published', 'ai_assisted', now(), 'sam direct sale: 3-storey shophouse, si racha nakhon 6, thb 7.634m three-storey shophouse with a mezzanine and roof terrace according to sam''s survey, address 34, si racha nakhon project, si racha nakhon 6 road, si racha subdistrict and district, chon buri. one title deed, 84489, covers 16 sq.wah (64 sq.m.). sam lists three bedrooms and four bathrooms. announced sale price thb 7,634,000; asset sl0184.

rectangular plot with approximately four metres of western road frontage and 16 metres depth. si racha nakhon 6 is described as a road within an approved subdivision, with approximately eight metres of concrete carriageway and a ten-metre right of way.

sam''s registered acquisition describes an unnumbered three-storey shophouse, while the web address states number 34 and the survey includes a mezzanine and roof terrace. verify the building number, registered structures and permits for additions against the actual property.

sam reports red planning zoning and residential/commercial surroundings in central si racha, near phyathai hospital. check permitted uses and relevant operating licences for the intended activity.

from chon buri toward laem chabang on sukhumvit road, pass si racha district office, the provincial electricity authority and robinson. turn right into si racha nakhon 3 and si racha nakhon 6 for approximately 385 metres; the property is on the left.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting sl0184, to confirm availability, price, viewing and terms.

navigation and map links agree on 13.168283, 100.928518. the latest building and interior photographs display 4 march 2026. fourteen source images include street views, floor plans, plot plans and a location map. total usable area, building age, parking capacity and occupancy are not published; confirm these and inspect current condition with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=22900&keyref=6007684', 'Official SAM page 22900 identifies SAM as asset holder and direct-sale contact for SL0184.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '4c92b592-21bd-4119-9fba-48cfde5f1840', '{"reference_code":"SL0184","source_page_id":22900,"source_image_count":14,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
