BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-12905'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='8Z5730' OR source_url ~ '[?&]id=12905(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='44b35ad4-b427-4583-a993-449afeed5730' OR slug='sam-direct-sale-three-shophouses-thet-saban-8-sattahip-8z5730' OR description ILIKE '%8Z5730%' OR (abs(latitude-12.663136)<0.0001 AND abs(longitude-100.90164)<0.0001 AND abs(land_area_sqm-240)<1)) THEN RAISE NOTICE 'SAM 8Z5730 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('44b35ad4-b427-4583-a993-449afeed5730', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', '56/1-2-3', 'ขายตรง SAM อาคารพาณิชย์ 2 ชั้น 3 คูหา ถนนเทศบาล 8 สัตหีบ 60 ตร.ว.', 'อาคารพาณิชย์ 2 ชั้น 3 คูหาเชื่อมทะลุถึงกัน เลขที่ 56/1-2-3 ถนนเทศบาล 8 (ถนนควินนิน) ตำบลสัตหีบ อำเภอสัตหีบ จังหวัดชลบุรี ที่ดิน 60 ตร.ว. (240 ตร.ม.) เอกสารสิทธิ์เป็นโฉนดตราจองเลขที่ 1491 จำนวน 1 ฉบับ ราคาประกาศขายจาก SAM 7,478,000 บาท รหัสทรัพย์ 8Z5730

ประเด็นสำคัญจาก SAM: ด้านทิศเหนือของทรัพย์บางส่วนถูกใช้ประโยชน์โดยที่ดินข้างเคียง ซึ่งอาจเป็นการก่อสร้างรุกล้ำหรือใช้ประโยชน์บนทรัพย์ ผู้สนใจควรตรวจแนวเขตและสภาพการใช้พื้นที่จริงก่อนเสนอซื้อ

เอกสารสิทธิ์เป็นโฉนดตราจองที่ตราว่าได้ทำประโยชน์แล้ว SAM ระบุว่าการตรวจตำแหน่งไม่มีระวางรูปแผนที่ ใช้โฉนดตราจองแปลงแม่หรือแปลงคงเหลือในการระบุตำแหน่งได้เท่านั้น และเตือนว่ารูปแปลง ระยะ เนื้อที่ แนวเขตและตำแหน่งอาจคลาดเคลื่อน ผู้ซื้อควรตรวจเอกสารและตำแหน่งจริงกับสำนักงานที่ดิน พิกัดแผนที่ใช้เพื่อการนำทาง ไม่ใช่การรับรองแนวเขต

ข้อมูลเขตทรงสงวนตามที่ SAM เผยแพร่: โฉนดตราจอง 1491 ออกวันที่ 6 ตุลาคม 2535 แบ่งจากโฉนดตราจองเลขที่ 15 ออกปี 2480 จึงออกก่อนพระราชกฤษฎีกาเขตปลอดภัยในราชการทหารแห่งกองทัพเรือ พ.ศ.2536 SAM อ้างข้อมูลที่สอบถามสำนักงานที่ดินจังหวัดชลบุรี สาขาสัตหีบ และกองอสังหาริมทรัพย์ ฐานทัพเรือสัตหีบ ว่าหลักฐานการครอบครองก่อนประกาศดังกล่าวถือว่าถูกต้องตามกฎหมาย ข้อความนี้เป็นข้อมูลที่ต้นทางรายงาน ผู้ซื้อยังต้องตรวจสิทธิและเงื่อนไขปัจจุบันกับหน่วยงานโดยตรง

SAM ระบุเพิ่มเติมว่าที่ดินยังอยู่ในเขตทรงสงวนตามพระบรมราชโองการ พ.ศ.2465 แม้ได้รับอนุญาตให้จับจองแล้ว เจ้าของต้องยื่นเอกสารขออนุญาตจับจองต่อกองอสังหาริมทรัพย์ ฐานทัพเรือสัตหีบ หากภายหลังพบว่าไม่เป็นไปตามเงื่อนไข กองทัพเรืออาจเพิกถอนการอนุญาตและเสนอกรมที่ดินเพิกถอนหนังสือแสดงสิทธิ โดยต้นทางระบุว่าไม่มีสิทธิโต้แย้งหรือเรียกค่าเสียหาย ผู้ซื้อควรขอตรวจหลักฐานการอนุญาตของแปลงนี้ เงื่อนไขที่ต้องปฏิบัติ และขั้นตอนเมื่อเปลี่ยนเจ้าของก่อนตัดสินใจ

ที่ดินรูปสี่เหลี่ยมคางหมู ด้านตะวันตกติดถนน หน้ากว้างประมาณ 12 เมตร ลึกสุดประมาณ 21.5 เมตร รายการรับโอนระบุเป็นตึกแถว 2 ชั้น 3 คูหาตามเลขที่ข้างต้น ถนนเทศบาล 8 เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 10 เมตร เขตทางประมาณ 12 เมตร ต้นทางระบุเขตผังเมืองสีส้ม

การเดินทางตาม SAM: ถนนสุขุมวิท (ทล.3) จากบ้านฉางมุ่งหน้าบางเสร่ เลี้ยวซ้ายเข้าถนนเทศบาล 13 ประมาณ 1 กิโลเมตร เลี้ยวขวาถนนเทศบาล 10 ประมาณ 180 เมตร แล้วเลี้ยวขวาถนนเทศบาล 8 อีกประมาณ 15.5 เมตร ทรัพย์อยู่ด้านขวามือ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 8Z5730 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม เอกสารสิทธิ์ การอนุญาตในเขตทรงสงวน การใช้พื้นที่ด้านเหนือ และเงื่อนไขล่าสุด

พิกัด 12.663136, 100.901640 ดึงจากลิงก์นำทาง SAM และตรงกับ Google Map ภาพอาคารและภายในแสดงวันที่ 11 กรกฎาคม 2567 คัดภาพไม่ซ้ำ 22 ภาพ มีภาพโถง ห้องภายใน บันได ห้องน้ำ ระเบียง ถนนและแผนที่ ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนห้องนอนหรือห้องน้ำ ที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงต้องยืนยันกับ SAM และตรวจสภาพอาคารปัจจุบัน', 7478000, false, 240, 2, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '56/1-2-3 ถนนเทศบาล 8 (ถนนควินนิน)', 'เข้าทางถนนเทศบาล 13 และถนนเทศบาล 10', 'ถนนเทศบาล 8 (ถนนควินนิน)', 12.663136, 100.90164, 'ชลบุรี', 'สัตหีบ', 'สัตหีบ', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-three-shophouses-thet-saban-8-sattahip-8z5730') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 7478000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"8Z5730","source_page_id":12905,"title_document_type":"chanot_tra_chong","title_document_number":"1491","title_document_count":1,"title_issue_date":"1992-10-06","parent_title_document_number":"15","parent_title_issue_year":1937,"land_area_square_wah":60,"land_area_sqm":240,"plot_shape":"trapezoidal","west_road_frontage_m_approx":12,"maximum_depth_m_approx":21.5,"front_road_width_m_approx":10,"front_right_of_way_width_m_approx":12,"front_road_status":"public","planning_zone_th":"เขตสีส้ม","registered_floor_count":2,"registered_unit_count":3,"registered_unit_numbers":["56/1","56/2","56/3"],"units_interconnected":true,"northern_neighbour_use_or_possible_encroachment_reported":true,"royal_reserved_area_reported":true,"navy_permission_required_reported":true,"permission_revocation_and_title_revocation_risk_reported":true,"no_contest_or_compensation_wording_in_source":true,"plot_specific_permission_status_not_confirmed":true,"no_cadastral_map_sheet_reported":true,"parent_title_used_for_location_reported":true,"boundary_verification_required":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"bedroom_count_not_published":true,"bathroom_count_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_date":"2024-07-11","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//12.663136,100.901640","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 12905 identifies SAM as direct-sale contact for 8Z5730, three interconnected two-storey shophouses in Sattahip, with title and reserved-area disclosures.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 8Z5730 ราคา 7,478,000 บาท', 'SAM direct purchase 8Z5730, THB 7,478,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'title_and_boundary', 'โฉนดตราจองและแนวเขต', 'Tra Chong title and boundaries', 'โฉนดตราจอง 1491 ไม่มีระวางรูปแผนที่ตามข้อมูล SAM ต้องตรวจตำแหน่งและแนวเขตจริง', 'Tra Chong 1491; SAM reports no cadastral sheet; verify actual location and boundaries', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'royal_reserved_area', 'เขตทรงสงวนและการอนุญาต', 'Royal reserved area and permission', 'SAM ระบุว่าต้องขออนุญาตจากกองทัพเรือ และอาจเพิกถอนการอนุญาตรวมถึงเอกสารสิทธิหากผิดเงื่อนไข โดยต้นทางระบุไม่มีสิทธิโต้แย้งหรือเรียกค่าเสียหาย ต้องตรวจหลักฐานแปลงนี้', 'SAM reports Navy permission requirements and possible permission/title revocation for unmet conditions, with no contest or compensation; verify plot-specific records', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'northern_land_use', 'การใช้พื้นที่ด้านเหนือ', 'Northern land use', 'SAM ระบุข้างเคียงใช้พื้นที่ด้านเหนือบางส่วน อาจเป็นการก่อสร้างรุกล้ำหรือใช้ประโยชน์ ต้องตรวจสอบ', 'SAM reports neighbouring use of part of the northern land, potentially involving encroachment; investigate', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพปัจจุบัน', 'Current inspection', 'ภาพวันที่ 11 กรกฎาคม 2567 ไม่ระบุพื้นที่ใช้สอย จำนวนห้องหรือผู้ครอบครอง', 'Photos 11 July 2024; usable area, room counts and occupancy not published', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารพาณิชย์ 3 คูหา', 'ด้านหน้าอาคารพาณิชย์ 3 คูหา', 'https://npa.sam.or.th/site/images/npa/12905/20260106095440_8Z5730P004_67.jpg', '/listing-media/sam/8z5730/01.webp', 'image/webp', 34218, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในชั้นล่าง', 'โถงภายในชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P005_67.jpg', '/listing-media/sam/8z5730/03.webp', 'image/webp', 15832, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'เคาน์เตอร์และบันได', 'เคาน์เตอร์และบันได', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P006_67.jpg', '/listing-media/sam/8z5730/04.webp', 'image/webp', 15298, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงมองไปยังประตูหน้า', 'โถงมองไปยังประตูหน้า', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P007_67.jpg', '/listing-media/sam/8z5730/05.webp', 'image/webp', 14910, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ชั้นล่างเชื่อมกัน', 'พื้นที่ชั้นล่างเชื่อมกัน', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P008_67.jpg', '/listing-media/sam/8z5730/06.webp', 'image/webp', 13540, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในอีกมุม', 'พื้นที่ภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P009_67.jpg', '/listing-media/sam/8z5730/07.webp', 'image/webp', 14540, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายใต้ส่วนหลังคา', 'ห้องภายใต้ส่วนหลังคา', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P010_67.jpg', '/listing-media/sam/8z5730/08.webp', 'image/webp', 14230, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและเสาภายใน', 'โถงและเสาภายใน', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P011_67.jpg', '/listing-media/sam/8z5730/09.webp', 'image/webp', 13430, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในชั้นล่าง', 'ห้องภายในชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P012_67.jpg', '/listing-media/sam/8z5730/10.webp', 'image/webp', 14704, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและช่องเปิด', 'ห้องและช่องเปิด', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P013_67.jpg', '/listing-media/sam/8z5730/11.webp', 'image/webp', 12226, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชานบันไดและฝ้าเพดาน', 'ชานบันไดและฝ้าเพดาน', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P014_67.jpg', '/listing-media/sam/8z5730/12.webp', 'image/webp', 17954, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องชั้นบน', 'ห้องชั้นบน', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P015_67.jpg', '/listing-media/sam/8z5730/13.webp', 'image/webp', 12008, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมหน้าต่าง', 'ห้องริมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P016_67.jpg', '/listing-media/sam/8z5730/14.webp', 'image/webp', 15532, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในผนังสีขาว', 'ห้องภายในผนังสีขาว', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P017_67.jpg', '/listing-media/sam/8z5730/15.webp', 'image/webp', 9780, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องชั้นบนอีกมุม', 'ห้องชั้นบนอีกมุม', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P018_67.jpg', '/listing-media/sam/8z5730/16.webp', 'image/webp', 10312, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำ', 'ห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P019_67.jpg', '/listing-media/sam/8z5730/17.webp', 'image/webp', 15410, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและประตูระเบียง', 'ห้องและประตูระเบียง', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P020_67.jpg', '/listing-media/sam/8z5730/18.webp', 'image/webp', 13424, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ระเบียงและหลังคาคลุม', 'ระเบียงและหลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P021_67.jpg', '/listing-media/sam/8z5730/19.webp', 'image/webp', 37286, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าถนนเทศบาล 13', 'ทางเข้าถนนเทศบาล 13', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P111_67.jpg', '/listing-media/sam/8z5730/20.webp', 'image/webp', 24644, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าถนนเทศบาล 10', 'ทางเข้าถนนเทศบาล 10', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P222_67.jpg', '/listing-media/sam/8z5730/21.webp', 'image/webp', 27034, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าถนนเทศบาล 8', 'ทางเข้าถนนเทศบาล 8', 'https://npa.sam.or.th/site/images/npa/12905/8Z5730P333_67.jpg', '/listing-media/sam/8z5730/22.webp', 'image/webp', 39264, 450, 450, 210, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/12905/20170823160332_8Z5730M1_60.jpg', '/listing-media/sam/8z5730/23.webp', 'image/webp', 47974, 785, 600, 220, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=12905&keyref=6007684', '8Z5730', now(), 'Official source captured 2026-09-11. THB 7,478,000; 60 sq.wah; three interconnected two-storey shophouses. Tra Chong 1491, reserved-area permission/revocation and no contest/compensation wording, no cadastral sheet and neighbouring northern use/possible encroachment are disclosed as SAM-reported information. No independent legal conclusion or plot permission confirmation. 23 source image URLs reduced to 22 byte-unique images; duplicate cover omitted. Photos dated 2024-07-11. Navigation/map agree. All-status code/page/title/address/nearby duplicate search found no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Three 2-Storey Shophouses, Sattahip, THB 7.478M', 'Three interconnected two-storey shophouses numbered 56/1-2-3 on Thet Saban 8 (Khwin Nin) Road, Sattahip subdistrict and district, Chon Buri. Land 60 sq.wah (240 sq.m.), one Chanot Tra Chong document numbered 1491. SAM announced price THB 7,478,000; asset 8Z5730.

Material source disclosure: part of the northern property is used by neighbouring land, potentially involving encroaching construction or use. Verify boundaries and actual occupation before offering.

SAM describes the title as a Chanot Tra Chong stamped as land already put to use. It reports no cadastral map sheet for locating this plot, with the parent or remaining parent title used to identify its position. SAM warns that location, dimensions, area and boundaries may differ from the depicted parcel. Verify title and actual boundaries with the Land Office; navigation coordinates do not certify boundaries.

According to SAM, title 1491 was issued on 6 October 1992, subdivided from parent title 15 issued in 1937, before the 1993 Royal Decree on the Navy military safety zone. SAM reports that enquiries to the Sattahip Land Office and Sattahip Naval Base real-estate division described evidence of possession predating that decree as lawful. This is attributed source information; buyers must verify current rights and conditions directly.

SAM further reports that the land remains within the royal reserved area under the 1922 Royal Command even where permission to occupy has been granted. Owners must submit documents to seek permission from the Sattahip Naval Base real-estate division. If permission conditions are later found unmet, the Navy may revoke permission and request the Land Department to revoke the land-rights document; SAM states that the occupant would have no right to contest or claim compensation. Obtain the plot-specific permission record, conditions and ownership-transfer procedure before deciding.

The trapezoidal plot has approximately 12 metres of western frontage and a maximum depth of 21.5 metres. Registered acquisition describes the three two-storey shophouses. Thet Saban 8 is described as public, with approximately 10 metres of concrete carriageway and a 12-metre right of way. SAM reports orange planning zoning.

From Ban Chang toward Bang Sare on Sukhumvit Road, turn left into Thet Saban 13 for approximately one kilometre, right into Thet Saban 10 for 180 metres, then right into Thet Saban 8 for 15.5 metres; the property is on the right.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 8Z5730, to confirm availability, price, viewing, title, reserved-area permission, northern land use and terms.

Navigation and map agree on 12.663136, 100.901640. Building/interior photos display 11 July 2024; 22 unique photos include halls, rooms, stairs, bathroom, balcony, streets and map. Total usable area, bedroom/bathroom counts, parking, age and occupancy are not published. Confirm these and inspect current condition.', '56/1-2-3, Thet Saban 8 (Khwin Nin) Road', 'Via Thet Saban 13 and Thet Saban 10', 'Thet Saban 8 (Khwin Nin) Road', 'Sattahip', 'Sattahip', 'Chon Buri', 'SAM Sattahip Three Shophouses — THB 7.478M', 'SAM 8Z5730: three two-storey shophouses, 60 sq.wah, Sattahip, THB 7,478,000. Tra Chong title and reserved-area conditions disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: three 2-storey shophouses, sattahip, thb 7.478m three interconnected two-storey shophouses numbered 56/1-2-3 on thet saban 8 (khwin nin) road, sattahip subdistrict and district, chon buri. land 60 sq.wah (240 sq.m.), one chanot tra chong document numbered 1491. sam announced price thb 7,478,000; asset 8z5730.

material source disclosure: part of the northern property is used by neighbouring land, potentially involving encroaching construction or use. verify boundaries and actual occupation before offering.

sam describes the title as a chanot tra chong stamped as land already put to use. it reports no cadastral map sheet for locating this plot, with the parent or remaining parent title used to identify its position. sam warns that location, dimensions, area and boundaries may differ from the depicted parcel. verify title and actual boundaries with the land office; navigation coordinates do not certify boundaries.

according to sam, title 1491 was issued on 6 october 1992, subdivided from parent title 15 issued in 1937, before the 1993 royal decree on the navy military safety zone. sam reports that enquiries to the sattahip land office and sattahip naval base real-estate division described evidence of possession predating that decree as lawful. this is attributed source information; buyers must verify current rights and conditions directly.

sam further reports that the land remains within the royal reserved area under the 1922 royal command even where permission to occupy has been granted. owners must submit documents to seek permission from the sattahip naval base real-estate division. if permission conditions are later found unmet, the navy may revoke permission and request the land department to revoke the land-rights document; sam states that the occupant would have no right to contest or claim compensation. obtain the plot-specific permission record, conditions and ownership-transfer procedure before deciding.

the trapezoidal plot has approximately 12 metres of western frontage and a maximum depth of 21.5 metres. registered acquisition describes the three two-storey shophouses. thet saban 8 is described as public, with approximately 10 metres of concrete carriageway and a 12-metre right of way. sam reports orange planning zoning.

from ban chang toward bang sare on sukhumvit road, turn left into thet saban 13 for approximately one kilometre, right into thet saban 10 for 180 metres, then right into thet saban 8 for 15.5 metres; the property is on the right.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 8z5730, to confirm availability, price, viewing, title, reserved-area permission, northern land use and terms.

navigation and map agree on 12.663136, 100.901640. building/interior photos display 11 july 2024; 22 unique photos include halls, rooms, stairs, bathroom, balcony, streets and map. total usable area, bedroom/bathroom counts, parking, age and occupancy are not published. confirm these and inspect current condition.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=12905&keyref=6007684', 'Official SAM page 12905 identifies SAM as asset holder and direct-sale contact for 8Z5730.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '44b35ad4-b427-4583-a993-449afeed5730', '{"reference_code":"8Z5730","source_page_id":12905,"source_image_count":23,"unique_image_count":22,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
