BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-14598'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='8Z6607' OR source_url ~ '[?&]id=14598(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='edfa93c2-1d92-4bee-b88e-41e6c0aa6607' OR slug='sam-direct-sale-shophouse-patong-sap-saen-lan-8z6607' OR description ILIKE '%8Z6607%' OR (abs(latitude-7.898915)<0.0001 AND abs(longitude-98.306745)<0.0001 AND abs(land_area_sqm-97.2)<1)) THEN RAISE NOTICE 'SAM 8Z6607 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('edfa93c2-1d92-4bee-b88e-41e6c0aa6607', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', 'ทรัพย์แสนล้าน', '56/16', 'ขายตรง SAM อาคารพาณิชย์ 4 ชั้นพร้อมดาดฟ้า ป่าตอง ภูเก็ต 24.3 ตร.ว.', 'อาคารพาณิชย์ 4 ชั้นพร้อมดาดฟ้า เลขที่ 56/16 โครงการทรัพย์แสนล้าน ถนนราชปาทานุสรณ์ ตำบลป่าตอง อำเภอกะทู้ จังหวัดภูเก็ต โฉนดที่ดินเลขที่ 12449 จำนวน 1 ฉบับ เนื้อที่ 24.3 ตร.ว. (97.2 ตร.ม.) ต้นทางระบุ 4 ห้องนอน 4 ห้องน้ำ ราคาประกาศขายจาก SAM 7,372,000 บาท รหัสทรัพย์ 8Z6607

ที่ดินรูปหลายเหลี่ยม ด้านทิศเหนือติดถนน หน้ากว้างประมาณ 5 เมตร ลึกสุดประมาณ 14 เมตร รายการรับโอนกรรมสิทธิ์ระบุเป็นตึกแถว 4 ชั้น เลขที่ 56/16 ข้อมูลสำรวจระบุอาคารพาณิชย์ 4 ชั้นพร้อมดาดฟ้า ต้นทางระบุเขตผังเมืองสีส้ม

ประเด็นสำคัญเรื่องทางเข้า: SAM ระบุว่าโฉนดเลขที่ 12262 และ 12718 รวมถึง น.ส.3ก. เลขที่ 5169 ตกอยู่ในภาระจำยอมเรื่องทางเดิน ทางรถยนต์ ไฟฟ้า ประปา และสาธารณูปโภคต่าง ๆ ให้แก่แปลงทรัพย์สิน ผู้ซื้อควรตรวจเอกสารจดทะเบียนภาระจำยอม ขอบเขตสิทธิและการใช้ทางจริงให้เป็นที่พอใจก่อนเสนอซื้อ เอกสารสิทธิ์แปลงที่ขายเป็นโฉนดเลขที่ 12449 โดยเอกสารทางเข้าเป็นคนละแปลง

การเดินทางตาม SAM: ใช้ถนนพระบารมี (ทล.4029) จากหาดกมลามุ่งหน้าวัดสุวรรณคีรีวงศ์ ผ่านโรงเรียนวัดสุวรรณคีรีวงศ์ ถึงแยกวัดแล้วเลี้ยวขวาถนนพิศิษฐ์กรณีย์ เลี้ยวขวาถนนราชปาทานุสรณ์ประมาณ 290 เมตร เลี้ยวซ้ายเข้าซอยดับเพลิงประมาณ 70 เมตร จากนั้นเลี้ยวขวาไปสุดซอย ทรัพย์อยู่ด้านซ้ายมือ

ภาพต้นทางมีด้านหน้าอาคาร ห้องภายใน ห้องน้ำ ดาดฟ้า ทางเข้าซอย ผังแปลงและแผนที่ รวม 17 ภาพ วันที่บนภาพมีทั้ง 16 พฤศจิกายน 2565 และ 16 พฤศจิกายน 2566 ควรตรวจสภาพปัจจุบัน โดยเฉพาะดาดฟ้า การระบายน้ำ ผนัง ระบบไฟฟ้าและประปา รวมถึงทะเบียนอาคารและส่วนต่อเติมก่อนซื้อ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 8Z6607 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม ภาระจำยอม และเงื่อนไขล่าสุด

พิกัด 7.898915, 98.306745 ดึงจากลิงก์ระบบนำทาง SAM และตรงกับ Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงต้องยืนยันข้อมูลเหล่านี้กับ SAM', 7372000, false, 97.2, 4, 4, 4, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '56/16 โครงการทรัพย์แสนล้าน ถนนราชปาทานุสรณ์', 'เข้าทางซอยดับเพลิงแล้วเลี้ยวขวาไปสุดซอย', 'ถนนราชปาทานุสรณ์', 7.898915, 98.306745, 'ภูเก็ต', 'กะทู้', 'ป่าตอง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-shophouse-patong-sap-saen-lan-8z6607') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 7372000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"8Z6607","source_page_id":14598,"project_name":"ทรัพย์แสนล้าน","title_document_type":"chanote","title_deed_number":"12449","title_document_count":1,"land_area_square_wah":24.3,"land_area_sqm":97.2,"plot_shape":"polygonal","north_road_frontage_m_approx":5,"maximum_depth_m_approx":14,"planning_zone_th":"เขตสีส้ม","registered_floor_count":4,"registered_unit_number":"56/16","has_roof_terrace":true,"source_bedroom_count":4,"source_bathroom_count":4,"access_easement_reported":true,"access_chanote_numbers":["12262","12718"],"access_nor_sor_3_kor_numbers":["5169"],"easement_scope":["pedestrians","vehicles","electricity","water","other_utilities"],"access_rights_verification_required":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_dates":["2022-11-16","2023-11-16"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//7.898915,98.306745","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 14598 identifies SAM as direct-sale contact for 8Z6607, four-storey shophouse 56/16 in Patong with access easements.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 8Z6607 ราคา 7,372,000 บาท', 'SAM direct purchase 8Z6607, THB 7,372,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_buildings', 'รายการอาคาร', 'Building description', 'ตึกแถว 4 ชั้น เลขที่ 56/16 สำรวจมีดาดฟ้า ต้นทางระบุ 4 ห้องนอน 4 ห้องน้ำ', 'Registered four-storey shophouse 56/16; surveyed roof terrace; source lists 4 bedrooms and 4 bathrooms', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'private_access_easement', 'ภาระจำยอมทางเข้าและสาธารณูปโภค', 'Access and utility easements', 'โฉนด 12262, 12718 และ น.ส.3ก. 5169 มีภาระจำยอมตาม SAM ต้องตรวจสิทธิใช้ทางจริง', 'SAM reports easements over Chanote 12262/12718 and Nor Sor 3 Kor 5169; verify actual access rights', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพปัจจุบัน', 'Current inspection', 'ภาพมีวันที่ปี 2565 และ 2566 ต้องตรวจสภาพดาดฟ้า อาคารและการครอบครองปัจจุบัน', 'Photos show 2022 and 2023 dates; inspect current roof terrace, building and occupancy', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารพาณิชย์ 4 ชั้น', 'ด้านหน้าอาคารพาณิชย์ 4 ชั้น', 'https://npa.sam.or.th/site/images/npa/14598/20240708093549_8Z6607P2_66.jpg', '/listing-media/sam/8z6607/01.webp', 'image/webp', 35396, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'หน้าร้านและประตูทางเข้า', 'หน้าร้านและประตูทางเข้า', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P2_62.jpg', '/listing-media/sam/8z6607/02.webp', 'image/webp', 43548, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำพร้อมสุขภัณฑ์', 'ห้องน้ำพร้อมสุขภัณฑ์', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P4_66.jpg', '/listing-media/sam/8z6607/03.webp', 'image/webp', 14784, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในและช่องเปิด', 'ห้องภายในและช่องเปิด', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P5_66.jpg', '/listing-media/sam/8z6607/04.webp', 'image/webp', 15900, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและประตูระเบียง', 'ห้องและประตูระเบียง', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P6_66.jpg', '/listing-media/sam/8z6607/05.webp', 'image/webp', 14338, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอีกมุม', 'ห้องภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P7_66.jpg', '/listing-media/sam/8z6607/06.webp', 'image/webp', 12308, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมระเบียง', 'ห้องริมระเบียง', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P8_66.jpg', '/listing-media/sam/8z6607/07.webp', 'image/webp', 10724, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำและอ่างล้างหน้า', 'ห้องน้ำและอ่างล้างหน้า', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P9_66.jpg', '/listing-media/sam/8z6607/08.webp', 'image/webp', 23918, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ห้องภายใน', 'พื้นที่ห้องภายใน', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P10_66.jpg', '/listing-media/sam/8z6607/09.webp', 'image/webp', 10916, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำอีกห้อง', 'ห้องน้ำอีกห้อง', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P11_66.jpg', '/listing-media/sam/8z6607/10.webp', 'image/webp', 14158, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำมุมอ่างล้างหน้า', 'ห้องน้ำมุมอ่างล้างหน้า', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P12_66.jpg', '/listing-media/sam/8z6607/11.webp', 'image/webp', 14088, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางออกสู่ดาดฟ้า', 'ทางออกสู่ดาดฟ้า', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P13_66.jpg', '/listing-media/sam/8z6607/12.webp', 'image/webp', 34236, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ดาดฟ้า', 'พื้นที่ดาดฟ้า', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P14_66.jpg', '/listing-media/sam/8z6607/13.webp', 'image/webp', 54614, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าซอยดับเพลิง', 'ทางเข้าซอยดับเพลิง', 'https://npa.sam.or.th/site/images/npa/14598/8Z6607P1_65.jpg', '/listing-media/sam/8z6607/14.webp', 'image/webp', 39834, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงและเส้นทางภาระจำยอม', 'ผังแปลงและเส้นทางภาระจำยอม', 'https://npa.sam.or.th/site/images/npa/14598/20190626155455_8Z6607C1_62.jpg', '/listing-media/sam/8z6607/15.webp', 'image/webp', 20422, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งอาคาร', 'ผังตำแหน่งอาคาร', 'https://npa.sam.or.th/site/images/npa/14598/20190626155455_8Z6607C2_62.jpg', '/listing-media/sam/8z6607/16.webp', 'image/webp', 19500, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/14598/20190626155455_8Z6607M1_62.jpg', '/listing-media/sam/8z6607/17.webp', 'image/webp', 57434, 785, 600, 170, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=14598&keyref=6007684', '8Z6607', now(), 'Official source captured 2026-09-11. THB 7,372,000; Chanote 12449, 24.3 sq.wah; four storeys plus surveyed roof terrace; source four bedrooms/four bathrooms. Access easements over separate titles 12262/12718 and Nor Sor 3 Kor 5169 disclosed. Seventeen source photos, displayed dates 2022-11-16 and 2023-11-16. Navigation/map agree. Duplicate search found nearby 8Z7193, listing 1283, but different code/address/title/area identifies a separate property; no exact duplicate.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 4-Storey Patong Shophouse with Roof Terrace, THB 7.372M', 'Four-storey shophouse with roof terrace, number 56/16, Sap Saen Lan project, Ratchapathanuson Road, Patong, Kathu, Phuket. One Chanote title, 12449, covers 24.3 sq.wah (97.2 sq.m.). SAM lists four bedrooms and four bathrooms. Announced sale price THB 7,372,000; asset 8Z6607.

Polygonal plot with approximately five metres of northern road frontage and a maximum depth of 14 metres. Registered acquisition describes a four-storey shophouse numbered 56/16; the survey includes a roof terrace. SAM reports orange planning zoning.

Material access disclosure: SAM reports easements over Chanote titles 12262 and 12718 and Nor Sor 3 Kor 5169 benefiting the property for pedestrian and vehicle access, electricity, water and other utilities. Verify registered instruments, scope and actual access before offering. The sale plot itself has Chanote 12449; the access documents refer to separate land.

From Kamala toward Wat Suwan Khiri Wong on Phra Barami Road (Highway 4029), pass the temple school, turn right at the temple junction into Phisit Karani Road, then right into Ratchapathanuson Road for approximately 290 metres. Turn left into Soi Fire Station for 70 metres, then right to the end; the property is on the left.

Seventeen source images show the exterior, rooms, bathrooms, roof terrace, street access, plot plans and map. Displayed dates include 16 November 2022 and 16 November 2023. Inspect current condition, especially roof terrace drainage, walls, electrical and plumbing systems, as well as building registration and additions.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 8Z6607, to confirm availability, price, viewing, easements and terms.

Navigation and map links agree on 7.898915, 98.306745. Total usable area, parking capacity, building age and occupancy are not published; confirm with SAM.', '56/16, Sap Saen Lan, Ratchapathanuson Road', 'Via Soi Fire Station, then right to the end', 'Ratchapathanuson Road', 'Patong', 'Kathu', 'Phuket', 'SAM Patong Shophouse 56/16 — THB 7.372M', 'SAM 8Z6607: four-storey Patong shophouse with roof terrace, 24.3 sq.wah, 4 bedrooms and 4 bathrooms. THB 7,372,000; access easements disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: 4-storey patong shophouse with roof terrace, thb 7.372m four-storey shophouse with roof terrace, number 56/16, sap saen lan project, ratchapathanuson road, patong, kathu, phuket. one chanote title, 12449, covers 24.3 sq.wah (97.2 sq.m.). sam lists four bedrooms and four bathrooms. announced sale price thb 7,372,000; asset 8z6607.

polygonal plot with approximately five metres of northern road frontage and a maximum depth of 14 metres. registered acquisition describes a four-storey shophouse numbered 56/16; the survey includes a roof terrace. sam reports orange planning zoning.

material access disclosure: sam reports easements over chanote titles 12262 and 12718 and nor sor 3 kor 5169 benefiting the property for pedestrian and vehicle access, electricity, water and other utilities. verify registered instruments, scope and actual access before offering. the sale plot itself has chanote 12449; the access documents refer to separate land.

from kamala toward wat suwan khiri wong on phra barami road (highway 4029), pass the temple school, turn right at the temple junction into phisit karani road, then right into ratchapathanuson road for approximately 290 metres. turn left into soi fire station for 70 metres, then right to the end; the property is on the left.

seventeen source images show the exterior, rooms, bathrooms, roof terrace, street access, plot plans and map. displayed dates include 16 november 2022 and 16 november 2023. inspect current condition, especially roof terrace drainage, walls, electrical and plumbing systems, as well as building registration and additions.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 8z6607, to confirm availability, price, viewing, easements and terms.

navigation and map links agree on 7.898915, 98.306745. total usable area, parking capacity, building age and occupancy are not published; confirm with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=14598&keyref=6007684', 'Official SAM page 14598 identifies SAM as asset holder and direct-sale contact for 8Z6607.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'edfa93c2-1d92-4bee-b88e-41e6c0aa6607', '{"reference_code":"8Z6607","source_page_id":14598,"source_image_count":17,"coordinate_source":"sam_navigation_href","duplicate_check":"nearby 8Z7193 is a different property; no exact match"}'::jsonb) ;
END $$;
COMMIT;
