BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20966'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A0403' OR source_url ~ '[?&]id=20966(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='70d9f6d4-e781-4d97-b743-a9c50eb70403' OR slug='sam-direct-sale-warehouse-phanat-nikhom-si-wichai-3a0403' OR description ILIKE '%3A0403%' OR (abs(latitude-13.453929)<0.0001 AND abs(longitude-101.186926)<0.0001 AND abs(land_area_sqm-1012)<1)) THEN RAISE NOTICE 'SAM 3A0403 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('70d9f6d4-e781-4d97-b743-a9c50eb70403', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'warehouse', 'business', 'sale', 'whole_property', 'ขายตรง SAM โกดัง พนัสนิคม ถนนศรีวิชัย ที่ดิน 9 แปลงรวม 253 ตร.ว.', 'โกดังเก็บของในตำบลพนัสนิคม อำเภอพนัสนิคม จังหวัดชลบุรี ที่ตั้งต้นทางระบุถนนศรีวิชัย ไม่ปรากฏเลขทะเบียนอาคาร ที่ดิน 9 แปลงติดต่อกัน โฉนดเลขที่ 19655 และ 21239–21246 จำนวน 9 ฉบับ เนื้อที่รวม 2 งาน 53 ตร.ว. หรือ 253 ตร.ว. (1,012 ตร.ม.) ราคาประกาศขายจาก SAM 6,940,000 บาท รหัสทรัพย์ 3A0403

ที่ดินรูปคล้ายสี่เหลี่ยมผืนผ้า ติดถนน 2 ด้าน ด้านทิศตะวันตกกว้างประมาณ 20 เมตร ด้านทิศเหนือประมาณ 52 เมตร ด้านทิศตะวันออกติดร่องน้ำสาธารณประโยชน์กว้างประมาณ 17 เมตร และลึกสุดประมาณ 60 เมตร ถนนหน้าทรัพย์ที่ SAM ระบุคือถนนศรีวิชัย เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 12 เมตร ต้องตรวจแนวเขตด้านร่องน้ำและความเหมาะสมของทางเข้าสำหรับรถที่ต้องการใช้งาน

ข้อมูลอาคารที่ต้องตรวจสอบ: รายการรับโอนกรรมสิทธิ์ของ SAM ระบุโกดังชั้นเดียว ไม่ปรากฏเลขทะเบียน ขณะที่ผลสำรวจระบุว่าเป็นโกดังเก็บของสูง 2 ชั้น จึงใช้จำนวนชั้นตามรายการรับโอนและระบุคำบรรยายสำรวจแยกไว้ ไม่ถือว่ามีพื้นที่ใช้สอยสองชั้นที่ยืนยันแล้ว ผู้ซื้อควรตรวจแบบอาคาร ทะเบียน ใบอนุญาต ความสูงจริง และพื้นที่ใช้สอยกับ SAM

ข้อกำหนดการใช้อาคารตามข้อมูล SAM: ทรัพย์อยู่ในบริเวณที่ 2 ตามเทศบัญญัติเทศบาลเมืองพนัสนิคม เรื่องกำหนดบริเวณห้ามก่อสร้าง ดัดแปลง หรือเปลี่ยนการใช้อาคารบางชนิดหรือบางประเภท พ.ศ.2555 ต้นทางระบุผังเมืองสีส้มและย่านที่อยู่อาศัย ผู้ซื้อควรตรวจข้อกำหนดฉบับปัจจุบันและกิจการที่อนุญาตกับเทศบาลก่อนเสนอซื้อ การจัดเป็นหมวดโกดังไม่ใช่การยืนยันว่าใช้เป็นโรงงานหรือประกอบกิจการใดได้ทันที

สถานที่ใกล้เคียงตาม SAM ได้แก่ โรงเรียนเทศบาล 1 วัดพลับ ที่ว่าการอำเภอพนัสนิคม และสถานีตำรวจภูธรอำเภอพนัสนิคม

การเดินทางตาม SAM: ถนนหนองซาก–พนัสนิคม (ทล.315) จากฉะเชิงเทรามุ่งหน้าบ้านบึง ผ่านโรงพยาบาลพนัสนิคม ถึงสี่แยกพนัสนิคม เลี้ยวซ้ายเข้าถนนเมืองเก่าประมาณ 1.2 กิโลเมตร เลี้ยวซ้ายถนนศรีวิชัยประมาณ 200 เมตร แล้วเลี้ยวขวาถนนพาณิชพัฒนา 1 ประมาณ 150 เมตร ทรัพย์อยู่ด้านขวามือ ควรใช้แผนที่ประกอบเพราะต้นทางระบุชื่อถนนในที่ตั้งและขั้นตอนเดินทางต่างกัน

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A0403 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม รายการอาคารและข้อกำหนดการใช้ประโยชน์ SAM กล่าวถึงทรัพย์ใกล้เคียงรหัส 3A0404 และ 3A0405 ซึ่งไม่ได้รวมในประกาศนี้

พิกัด 13.453929, 101.186926 ดึงจากลิงก์ระบบนำทาง SAM และตรงกับ Google Map ภาพอาคารและภายในแสดงวันที่ 2 ตุลาคม 2567 คัดภาพไม่ซ้ำ 8 ภาพ รวมผังแปลง ผังอาคารและแผนที่ ต้นทางไม่ระบุพื้นที่ใช้สอย ความสูงเป็นเมตร น้ำหนักบรรทุกพื้น ระบบไฟฟ้า ใบอนุญาตกิจการ ขนาดรถที่รองรับ อายุอาคาร หรือสถานะผู้ครอบครอง จึงต้องยืนยันก่อนซื้อ', 6940000, false, 1012, 1, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'โกดัง ไม่ปรากฏเลขทะเบียน ถนนศรีวิชัย', 'เข้าทางถนนพาณิชพัฒนา 1 ตามแผนที่ SAM', 'ถนนศรีวิชัย', 13.453929, 101.186926, 'ชลบุรี', 'พนัสนิคม', 'พนัสนิคม', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-warehouse-phanat-nikhom-si-wichai-3a0403') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'industrial') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6940000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'warehouse', 1, '{"source_property_category":"โรงงาน/โกดัง","official_page_reference_code":"3A0403","source_page_id":20966,"title_document_type":"chanote","title_deed_numbers":["19655","21239","21240","21241","21242","21243","21244","21245","21246"],"title_document_count":9,"land_area_square_wah":253,"land_area_sqm":1012,"plot_shape":"approximately_rectangular","two_road_frontages_reported":true,"west_width_m_approx":20,"north_width_m_approx":52,"east_channel_boundary_length_m_approx":17,"maximum_depth_m_approx":60,"public_drainage_channel_on_east":true,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":12,"front_road_status":"public","planning_zone_th":"เขตสีส้ม","registered_floor_count":1,"survey_description_th":"โกดังเก็บของสูง 2 ชั้น","survey_height_in_storeys":2,"usable_second_floor_not_confirmed":true,"registered_and_surveyed_building_difference":true,"municipal_ordinance_year_be":2555,"municipal_ordinance_area":2,"construction_alteration_change_of_use_restrictions_reported":true,"current_permitted_use_verification_required":true,"nearby_sam_assets_not_included":["3A0404","3A0405"],"usable_area_not_published":true,"occupancy_status_not_published":true,"electrical_capacity_not_published":true,"floor_loading_not_published":true,"operating_licence_not_published":true,"truck_size_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_date":"2024-10-02","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.453929,101.186926","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20966 identifies SAM as direct-sale contact for 3A0403, a warehouse on nine adjoining plots in Phanat Nikhom.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 3A0403 ราคา 6,940,000 บาท เฉพาะทรัพย์นี้', 'SAM direct purchase 3A0403, THB 6,940,000; this asset only', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_buildings', 'ทะเบียนและคำบรรยายสำรวจ', 'Registration and survey wording', 'ทะเบียนโกดังชั้นเดียว สำรวจระบุสูง 2 ชั้น ต้องตรวจแบบและพื้นที่ใช้สอยจริง', 'Registered single-storey warehouse; survey says two storeys high; verify plans and usable floor area', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'municipal_use_restrictions', 'ข้อกำหนดเทศบาล', 'Municipal restrictions', 'SAM ระบุบริเวณที่ 2 ตามเทศบัญญัติพนัสนิคม พ.ศ.2555 ต้องตรวจข้อห้ามก่อสร้าง ดัดแปลง และเปลี่ยนการใช้ฉบับปัจจุบัน', 'SAM reports Area 2 under Phanat Nikhom 2012 ordinance; verify current construction, alteration and change-of-use restrictions', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'channel_boundary', 'แนวเขตด้านร่องน้ำ', 'Drainage-channel boundary', 'ด้านตะวันออกติดร่องน้ำสาธารณประโยชน์ ต้องตรวจแนวเขตและข้อกำหนดที่เกี่ยวข้อง', 'Eastern boundary adjoins public drainage channel; verify boundaries and applicable requirements', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพและระบบ', 'Condition and systems', 'ภาพวันที่ 2 ตุลาคม 2567 ต้องยืนยันพื้นที่ใช้สอย น้ำหนักบรรทุก ระบบไฟฟ้าและรถที่เข้าได้', 'Photos 2 October 2024; verify usable area, floor loading, power and vehicle access', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าโกดังที่ประกาศขาย', 'ด้านหน้าโกดังที่ประกาศขาย', 'https://npa.sam.or.th/site/images/npa/20966/20241010162835_3A0403P2_67.jpg', '/listing-media/sam/3a0403/01.webp', 'image/webp', 37304, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โกดังและถนนด้านข้าง', 'โกดังและถนนด้านข้าง', 'https://npa.sam.or.th/site/images/npa/20966/3A0403P3_67.jpg', '/listing-media/sam/3a0403/03.webp', 'image/webp', 36750, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในและโครงหลังคา', 'พื้นที่ภายในและโครงหลังคา', 'https://npa.sam.or.th/site/images/npa/20966/3A0403P4_67.jpg', '/listing-media/sam/3a0403/04.webp', 'image/webp', 46766, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในโกดังอีกมุม', 'พื้นที่ภายในโกดังอีกมุม', 'https://npa.sam.or.th/site/images/npa/20966/3A0403P5_67.jpg', '/listing-media/sam/3a0403/05.webp', 'image/webp', 48366, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าถนนศรีวิชัย', 'ทางเข้าถนนศรีวิชัย', 'https://npa.sam.or.th/site/images/npa/20966/3A0403P1_66.jpg', '/listing-media/sam/3a0403/06.webp', 'image/webp', 30698, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดิน 9 แปลง', 'ผังที่ดิน 9 แปลง', 'https://npa.sam.or.th/site/images/npa/20966/20230616160714_3A0403C1_66.jpg', '/listing-media/sam/3a0403/07.webp', 'image/webp', 25118, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งโกดัง', 'ผังตำแหน่งโกดัง', 'https://npa.sam.or.th/site/images/npa/20966/20230616160714_3A0403C2_66.jpg', '/listing-media/sam/3a0403/08.webp', 'image/webp', 24988, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/20966/20230616160714_3A0403M_66.jpg', '/listing-media/sam/3a0403/09.webp', 'image/webp', 47346, 785, 600, 80, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20966&keyref=6007684', '3A0403', now(), 'Official source captured 2026-09-11. THB 6,940,000; nine plots totaling 253 sq.wah. Registered single-storey warehouse versus survey two-storey-height wording disclosed; no confirmed second usable floor. SAM-reported municipal Area 2 restrictions under 2012 ordinance and eastern public drainage channel disclosed. Nearby 3A0404/3A0405 excluded. Eight unique images from nine URLs, exact duplicate cover excluded; building photos 2024-10-02. Navigation/map agree. All-status duplicate search found no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Phanat Nikhom Warehouse, 253 Sq.Wah, THB 6.94M', 'Storage warehouse in Phanat Nikhom subdistrict and district, Chon Buri, with the source address on Si Wichai Road and no stated building registration number. Nine adjoining plots, Chanote 19655 and 21239–21246, total 253 sq.wah (1,012 sq.m.). SAM announced price THB 6,940,000; asset 3A0403.

Approximately rectangular land with two road frontages. The source gives approximately 20 metres on the west, 52 metres on the north, 17 metres along the public drainage channel on the east, and a maximum depth of 60 metres. SAM describes Si Wichai Road as public, with a six-metre concrete carriageway and 12-metre right of way. Verify drainage-channel boundaries and access for the required vehicles.

Registered acquisition describes a single-storey warehouse without a stated registration number. The survey calls it a warehouse two storeys high. The listing uses the registered floor count and separately records the survey wording; two usable floors are not confirmed. Verify building plans, registration, permits, actual height and usable area.

SAM reports the property lies in Area 2 under the Phanat Nikhom municipal ordinance of 2012 restricting construction, alteration or change of use of certain buildings. It reports orange planning zoning and residential surroundings. Confirm current restrictions and permitted activities directly with the municipality. Warehouse categorisation does not confirm factory or business operating permission.

Source-listed nearby places are Municipal School 1, Wat Phlap, Phanat Nikhom district office and police station.

From Chachoengsao toward Ban Bueng on Highway 315, pass Phanat Nikhom Hospital, turn left at Phanat Nikhom intersection onto Mueang Kao Road for 1.2 kilometres, left onto Si Wichai Road for 200 metres, then right onto Phanit Phatthana 1 for 150 metres; the property is on the right. Check the map because the source address and final approach name different roads.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A0403, to confirm availability, price, viewing, buildings and permitted use. Nearby SAM assets 3A0404 and 3A0405 are mentioned by the source but are not included.

Navigation and map agree on 13.453929, 101.186926. Building/interior photos display 2 October 2024. Eight unique images include plot plans, building plan and map. Usable floor area, height in metres, floor loading, electrical capacity, operating licences, supported truck size, age and occupancy are not published; verify before purchase.', 'Warehouse without stated registration number, Si Wichai Road', 'Approach via Phanit Phatthana 1 according to SAM map', 'Si Wichai Road', 'Phanat Nikhom', 'Phanat Nikhom', 'Chon Buri', 'SAM Phanat Nikhom Warehouse — THB 6.94M', 'SAM 3A0403: Phanat Nikhom warehouse on nine plots, 253 sq.wah. THB 6,940,000; municipal use restrictions and building survey difference disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: phanat nikhom warehouse, 253 sq.wah, thb 6.94m storage warehouse in phanat nikhom subdistrict and district, chon buri, with the source address on si wichai road and no stated building registration number. nine adjoining plots, chanote 19655 and 21239–21246, total 253 sq.wah (1,012 sq.m.). sam announced price thb 6,940,000; asset 3a0403.

approximately rectangular land with two road frontages. the source gives approximately 20 metres on the west, 52 metres on the north, 17 metres along the public drainage channel on the east, and a maximum depth of 60 metres. sam describes si wichai road as public, with a six-metre concrete carriageway and 12-metre right of way. verify drainage-channel boundaries and access for the required vehicles.

registered acquisition describes a single-storey warehouse without a stated registration number. the survey calls it a warehouse two storeys high. the listing uses the registered floor count and separately records the survey wording; two usable floors are not confirmed. verify building plans, registration, permits, actual height and usable area.

sam reports the property lies in area 2 under the phanat nikhom municipal ordinance of 2012 restricting construction, alteration or change of use of certain buildings. it reports orange planning zoning and residential surroundings. confirm current restrictions and permitted activities directly with the municipality. warehouse categorisation does not confirm factory or business operating permission.

source-listed nearby places are municipal school 1, wat phlap, phanat nikhom district office and police station.

from chachoengsao toward ban bueng on highway 315, pass phanat nikhom hospital, turn left at phanat nikhom intersection onto mueang kao road for 1.2 kilometres, left onto si wichai road for 200 metres, then right onto phanit phatthana 1 for 150 metres; the property is on the right. check the map because the source address and final approach name different roads.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a0403, to confirm availability, price, viewing, buildings and permitted use. nearby sam assets 3a0404 and 3a0405 are mentioned by the source but are not included.

navigation and map agree on 13.453929, 101.186926. building/interior photos display 2 october 2024. eight unique images include plot plans, building plan and map. usable floor area, height in metres, floor loading, electrical capacity, operating licences, supported truck size, age and occupancy are not published; verify before purchase.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20966&keyref=6007684', 'Official SAM page 20966 identifies SAM as asset holder and direct-sale contact for 3A0403.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '70d9f6d4-e781-4d97-b743-a9c50eb70403', '{"reference_code":"3A0403","source_page_id":20966,"source_image_count":9,"unique_image_count":8,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
