BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20963'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A0404' OR source_url ~ '[?&]id=20963(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='02b49f38-627b-4149-bd65-36e58f340404' OR slug='sam-direct-sale-showroom-phanit-phatthana-phanat-nikhom-3a0404' OR (abs(latitude-13.454414)<0.0001 AND abs(longitude-101.188402)<0.0001 AND abs(land_area_sqm-804)<1)) THEN RAISE NOTICE 'SAM 3A0404 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('02b49f38-627b-4149-bd65-36e58f340404', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'retail_space', 'business', 'sale', 'whole_property', 'ขายตรง SAM โชว์รูม 2 ชั้น พนัสนิคม ถนนพาณิชพัฒนา 1 ที่ดิน 201 ตร.ว.', 'อาคารโชว์รูมแสดงสินค้า 2 ชั้น ไม่ปรากฏเลขทะเบียน ถนนพาณิชพัฒนา 1 ตำบลพนัสนิคม อำเภอพนัสนิคม จังหวัดชลบุรี ที่ดิน 2 แปลงติดต่อกัน โฉนดเลขที่ 19148 และ 19161 จำนวน 2 ฉบับ เนื้อที่รวม 2 งาน 1 ตร.ว. หรือ 201 ตร.ว. (804 ตร.ม.) ต้นทางระบุ 2 ห้องน้ำ ราคาประกาศขายจาก SAM 6,921,000 บาท รหัสทรัพย์ 3A0404

ที่ดินรูปสี่เหลี่ยมผืนผ้า ติดถนน 3 ด้าน ด้านทิศเหนือและทิศใต้กว้างด้านละประมาณ 20 เมตร ด้านทิศตะวันตกลึกประมาณ 44 เมตร ต้นทางระบุผังเมืองสีส้มและย่านที่อยู่อาศัย

รายการอาคารที่โอนต้องตรวจสอบ: SAM จดทะเบียนรับโอนเป็นอาคารโชว์รูมแสดงสินค้า 2 ชั้นไม่ปรากฏเลขทะเบียน แต่สำรวจพบอาคารแสดงสินค้าสูง 2 ชั้นและอาคารป้อมยาม SAM ระบุว่าจะโอนกรรมสิทธิ์ตามรายการสิ่งปลูกสร้างที่จดทะเบียนรับโอนทางทะเบียนเท่านั้น ผู้ซื้อควรขอรายการโอนและยืนยันสถานะป้อมยาม แบบอาคารและใบอนุญาตก่อนซื้อ

ทางเข้าเป็นประเด็นสำคัญ: ถนนพาณิชพัฒนา 1 เป็นถนนส่วนบุคคลในโครงการแบ่งขายที่ดินเอกชน SAM ระบุว่ามีการใช้เข้าออกโดยเปิดเผยมานานเกิน 10 ปี และเป็นสาธารณูปโภคที่จัดให้มีขึ้นซึ่งตกอยู่ในภาระจำยอมเพื่อประโยชน์แก่ที่ดินในโครงการ ผิวคอนกรีตและเขตทางกว้างประมาณ 6 เมตร ผู้ซื้อควรตรวจหลักฐานสิทธิใช้ทาง ขอบเขต ผู้รับประโยชน์และการใช้จริงก่อนเสนอซื้อ ข้อมูลนี้ไม่ได้ยืนยันว่ามีการจดทะเบียนภาระจำยอมไว้แล้ว

ชื่อพื้นที่ในเอกสารสิทธิ์แตกต่างจากที่ตั้งหน้าเว็บ: โฉนดระบุตำบลบ้านช้าง (วัดกลาง) อำเภอพนัสนิคม (พนัศ) จังหวัดชลบุรี ขณะที่หน้า SAM ระบุตำบลพนัสนิคม ควรตรวจตำแหน่งแปลงและข้อมูลที่อยู่กับสำนักงานที่ดินให้ตรงกัน

สถานที่ใกล้เคียงตาม SAM ได้แก่ โรงเรียนเทศบาล 1 วัดพลับ ที่ว่าการอำเภอพนัสนิคม และสถานีตำรวจภูธรอำเภอพนัสนิคม การเดินทางใช้ถนนหนองซาก–พนัสนิคม (ทล.315) จากฉะเชิงเทรามุ่งหน้าบ้านบึง ผ่านโรงพยาบาลพนัสนิคม ถึงสี่แยกพนัสนิคม เลี้ยวซ้ายถนนเมืองเก่าประมาณ 1.2 กิโลเมตร เลี้ยวซ้ายถนนศรีวิชัย 200 เมตร แล้วเลี้ยวขวาถนนพาณิชพัฒนา 1 อีก 150 เมตร ทรัพย์อยู่ด้านขวามือ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A0404 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม รายการอาคารและสิทธิใช้ทาง ทรัพย์ใกล้เคียง 3A0403 และ 3A0405 ที่ต้นทางกล่าวถึงไม่ได้รวมในประกาศนี้

พิกัด 13.454414, 101.188402 ดึงจากลิงก์นำทาง SAM และตรงกับ Google Map ภาพภายนอกมีวันที่ 19 สิงหาคม 2565 และภาพทางเข้าอาคารกับภายในมีวันที่ 8 พฤษภาคม 2567 รวม 16 ภาพ มีผังแปลง ผังอาคารและแผนที่ ต้นทางไม่ระบุพื้นที่ใช้สอย จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง ต้องยืนยันสภาพและการใช้ประโยชน์ที่อนุญาตก่อนซื้อ', 6921000, false, 804, 2, 2, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'อาคารโชว์รูม ไม่ปรากฏเลขทะเบียน ถนนพาณิชพัฒนา 1', 'โฉนดระบุตำบลบ้านช้าง (วัดกลาง) ต้องตรวจชื่อที่ตั้ง', 'ถนนพาณิชพัฒนา 1', 13.454414, 101.188402, 'ชลบุรี', 'พนัสนิคม', 'พนัสนิคม', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-showroom-phanit-phatthana-phanat-nikhom-3a0404') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6921000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'retail_space', 1, '{"source_property_category":"โชว์รูม","retail_space_type":"showroom","official_page_reference_code":"3A0404","source_page_id":20963,"title_document_type":"chanote","title_deed_numbers":["19148","19161"],"title_document_count":2,"land_area_square_wah":201,"land_area_sqm":804,"plot_shape":"rectangular","road_frontage_sides":3,"north_width_m_approx":20,"south_width_m_approx":20,"west_depth_m_approx":44,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":6,"front_road_status":"private_subdivision_road","open_access_over_ten_years_reported":true,"project_utility_easement_reported":true,"easement_registration_not_confirmed":true,"planning_zone_th":"เขตสีส้ม","registered_floor_count":2,"source_bathroom_count":2,"registered_structures":["อาคารโชว์รูมแสดงสินค้า 2 ชั้น ไม่ปรากฏเลขทะเบียน"],"surveyed_structures":["อาคารแสดงสินค้าสูง 2 ชั้น","อาคารป้อมยาม"],"transfer_registered_structures_only":true,"guardhouse_transfer_status_requires_confirmation":true,"title_subdistrict_th":"บ้านช้าง (วัดกลาง)","title_district_th":"พนัสนิคม (พนัศ)","source_address_and_title_location_difference":true,"nearby_sam_assets_not_included":["3A0403","3A0405"],"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_dates":["2022-08-19","2024-05-08"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.454414,101.188402","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20963 identifies SAM as direct-sale contact for 3A0404, two-storey showroom on two plots in Phanat Nikhom.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 3A0404 ราคา 6,921,000 บาท เฉพาะทรัพย์นี้', 'SAM direct purchase 3A0404, THB 6,921,000; this asset only', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'transfer_inventory', 'รายการสิ่งปลูกสร้างที่จะโอน', 'Transfer inventory', 'SAM โอนตามทะเบียนอาคารโชว์รูม 2 ชั้นเท่านั้น ต้องยืนยันสถานะป้อมยามที่พบจากสำรวจ', 'SAM transfers registered two-storey showroom inventory only; confirm surveyed guardhouse status', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'private_access_easement', 'ถนนส่วนบุคคลและสิทธิใช้ทาง', 'Private road and access', 'ต้นทางระบุใช้ทางเปิดเผยเกิน 10 ปีและเป็นสาธารณูปโภคภาระจำยอม ต้องตรวจหลักฐาน ไม่ยืนยันการจดทะเบียน', 'Source reports over 10 years open use and project utility easement; verify evidence, registration not confirmed', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'title_location', 'ชื่อที่ตั้งในโฉนด', 'Title location wording', 'โฉนดระบุตำบลบ้านช้าง (วัดกลาง) ต่างจากหน้าเว็บที่ใช้พนัสนิคม ต้องตรวจให้ตรงกัน', 'Title says Ban Chang (Wat Klang), website says Phanat Nikhom; verify consistency', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารโชว์รูมและถนน', 'ด้านหน้าอาคารโชว์รูมและถนน', 'https://npa.sam.or.th/site/images/npa/20963/20240731104222_3A0404P3_66.jpg', '/listing-media/sam/3a0404/01.webp', 'image/webp', 31978, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารโชว์รูมมุมด้านหน้า', 'อาคารโชว์รูมมุมด้านหน้า', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P8_66.jpg', '/listing-media/sam/3a0404/02.webp', 'image/webp', 33142, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านข้างอาคารและพื้นที่รอบแปลง', 'ด้านข้างอาคารและพื้นที่รอบแปลง', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P5_66.jpg', '/listing-media/sam/3a0404/03.webp', 'image/webp', 27288, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารด้านหลัง', 'อาคารด้านหลัง', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P2_66.jpg', '/listing-media/sam/3a0404/04.webp', 'image/webp', 23056, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารมุมหน้าตรง', 'อาคารมุมหน้าตรง', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P4_66.jpg', '/listing-media/sam/3a0404/05.webp', 'image/webp', 22402, 449, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ประตูทางเข้าโชว์รูม', 'ประตูทางเข้าโชว์รูม', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P9_67.jpg', '/listing-media/sam/3a0404/06.webp', 'image/webp', 45168, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงแสดงสินค้าและบันได', 'โถงแสดงสินค้าและบันได', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P10_67.jpg', '/listing-media/sam/3a0404/07.webp', 'image/webp', 25002, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในและแนวชั้นบน', 'โถงภายในและแนวชั้นบน', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P11_67.jpg', '/listing-media/sam/3a0404/08.webp', 'image/webp', 27772, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดขึ้นชั้นบน', 'บันไดขึ้นชั้นบน', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P12_67.jpg', '/listing-media/sam/3a0404/09.webp', 'image/webp', 17516, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำ', 'ห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P13_67.jpg', '/listing-media/sam/3a0404/10.webp', 'image/webp', 16020, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายใน', 'ห้องภายใน', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P14_67.jpg', '/listing-media/sam/3a0404/11.webp', 'image/webp', 12638, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ชั้นบนริมหน้าต่าง', 'พื้นที่ชั้นบนริมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P15_67.jpg', '/listing-media/sam/3a0404/12.webp', 'image/webp', 18036, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าถนนศรีวิชัย', 'ทางเข้าถนนศรีวิชัย', 'https://npa.sam.or.th/site/images/npa/20963/3A0404P1_66.jpg', '/listing-media/sam/3a0404/13.webp', 'image/webp', 30698, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดิน 2 แปลง', 'ผังที่ดิน 2 แปลง', 'https://npa.sam.or.th/site/images/npa/20963/20230614204106_3A0404C1_66.jpg', '/listing-media/sam/3a0404/14.webp', 'image/webp', 16960, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังอาคารโชว์รูมและป้อมยาม', 'ผังอาคารโชว์รูมและป้อมยาม', 'https://npa.sam.or.th/site/images/npa/20963/20230614204106_3A0404C2_66.jpg', '/listing-media/sam/3a0404/15.webp', 'image/webp', 21186, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/20963/20230614204106_3A0404M1_66.jpg', '/listing-media/sam/3a0404/16.webp', 'image/webp', 47716, 785, 600, 160, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20963&keyref=6007684', '3A0404', now(), 'Official source captured 2026-09-11. THB 6,921,000; two plots 201 sq.wah; two-storey showroom, two bathrooms. Transfer restricted to registered structures; surveyed guardhouse status unconfirmed. Private project road with source-reported over-ten-year open use and utility easement, not represented as registered. Title/website locality difference disclosed. Sixteen source photos dated 2022-08-19 and 2024-05-08. Nearby listing 1354/3A0403 mentions this code but is different by source/title/area/coordinates. No exact duplicate. Navigation/map agree.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 2-Storey Phanat Nikhom Showroom, THB 6.921M', 'Two-storey showroom without a stated registration number on Phanit Phatthana 1 Road, Phanat Nikhom subdistrict and district, Chon Buri. Two adjoining plots, Chanote 19148 and 19161, total 201 sq.wah (804 sq.m.). SAM lists two bathrooms. Announced sale price THB 6,921,000; asset 3A0404.

Rectangular land with roads on three sides. North and south sides are approximately 20 metres each; the western depth is approximately 44 metres. SAM reports orange planning zoning and residential surroundings.

Registered acquisition lists a two-storey showroom without a registration number. Surveyed structures are a two-storey-high display building and a guardhouse. SAM states that transfer follows only the structures in its registered acquisition schedule. Verify the transfer list, guardhouse status, building plans and permits.

Phanit Phatthana 1 is a private road in a privately subdivided land project. SAM reports open use for access for over ten years and describes the road as a provided utility subject to an easement benefiting project land. Concrete carriageway and right of way are approximately six metres wide. Verify evidence, scope, beneficiaries and actual access before offering. The source does not establish that an easement has been registered.

Title location wording differs from the website: the deeds state Ban Chang (Wat Klang), Phanat Nikhom (Phanat), Chon Buri, while the page uses Phanat Nikhom subdistrict. Confirm parcel location and address with the Land Office.

Nearby source-listed places include Municipal School 1, Wat Phlap, the district office and police station. From Chachoengsao toward Ban Bueng on Highway 315, pass Phanat Nikhom Hospital, turn left at the intersection into Mueang Kao Road for 1.2 kilometres, left into Si Wichai Road for 200 metres, then right into Phanit Phatthana 1 for 150 metres; the property is on the right.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A0404, to confirm availability, price, viewing, structures and access. Nearby 3A0403 and 3A0405 are separate assets and are not included.

Navigation and map agree on 13.454414, 101.188402. Exterior photos display 19 August 2022; entrance/interior photos display 8 May 2024. Sixteen images include plot/building plans and map. Usable area, parking, age and occupancy are not published; verify current condition and permitted use.', 'Showroom without stated registration number, Phanit Phatthana 1', 'Title locality: Ban Chang (Wat Klang); verify address', 'Phanit Phatthana 1 Road', 'Phanat Nikhom', 'Phanat Nikhom', 'Chon Buri', 'SAM Phanat Nikhom Showroom — THB 6.921M', 'SAM 3A0404: two-storey showroom, 201 sq.wah, roads on three sides, THB 6,921,000. Private access and transfer inventory disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: 2-storey phanat nikhom showroom, thb 6.921m two-storey showroom without a stated registration number on phanit phatthana 1 road, phanat nikhom subdistrict and district, chon buri. two adjoining plots, chanote 19148 and 19161, total 201 sq.wah (804 sq.m.). sam lists two bathrooms. announced sale price thb 6,921,000; asset 3a0404.

rectangular land with roads on three sides. north and south sides are approximately 20 metres each; the western depth is approximately 44 metres. sam reports orange planning zoning and residential surroundings.

registered acquisition lists a two-storey showroom without a registration number. surveyed structures are a two-storey-high display building and a guardhouse. sam states that transfer follows only the structures in its registered acquisition schedule. verify the transfer list, guardhouse status, building plans and permits.

phanit phatthana 1 is a private road in a privately subdivided land project. sam reports open use for access for over ten years and describes the road as a provided utility subject to an easement benefiting project land. concrete carriageway and right of way are approximately six metres wide. verify evidence, scope, beneficiaries and actual access before offering. the source does not establish that an easement has been registered.

title location wording differs from the website: the deeds state ban chang (wat klang), phanat nikhom (phanat), chon buri, while the page uses phanat nikhom subdistrict. confirm parcel location and address with the land office.

nearby source-listed places include municipal school 1, wat phlap, the district office and police station. from chachoengsao toward ban bueng on highway 315, pass phanat nikhom hospital, turn left at the intersection into mueang kao road for 1.2 kilometres, left into si wichai road for 200 metres, then right into phanit phatthana 1 for 150 metres; the property is on the right.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a0404, to confirm availability, price, viewing, structures and access. nearby 3a0403 and 3a0405 are separate assets and are not included.

navigation and map agree on 13.454414, 101.188402. exterior photos display 19 august 2022; entrance/interior photos display 8 may 2024. sixteen images include plot/building plans and map. usable area, parking, age and occupancy are not published; verify current condition and permitted use.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20963&keyref=6007684', 'Official SAM page 20963 identifies SAM as asset holder and direct-sale contact for 3A0404.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '02b49f38-627b-4149-bd65-36e58f340404', '{"reference_code":"3A0404","source_page_id":20963,"source_image_count":16,"coordinate_source":"sam_navigation_href","duplicate_check":"nearby 3A0403 is different property; no exact duplicate"}'::jsonb) ;
END $$;
COMMIT;
