BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-18850'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A0852' OR source_url ~ '[?&]id=18850(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='9e9b7b42-b2a5-448c-97d8-f6a9ff230852' OR slug='sam-direct-sale-pool-house-ban-suan-suwattana-nong-prue-3a0852' OR description ILIKE '%3A0852%' OR (abs(latitude-12.933123)<0.0001 AND abs(longitude-100.917287)<0.0001 AND abs(land_area_sqm-532)<1)) THEN RAISE NOTICE 'SAM 3A0852 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('9e9b7b42-b2a5-448c-97d8-f6a9ff230852', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'detached_house', 'residence', 'sale', 'whole_property', 'บ้านสวนสุวัฒนา เฟส 1', '38/197', 'ขายตรง SAM บ้าน 2 ชั้นพร้อมสระว่ายน้ำ บ้านสวนสุวัฒนา หนองปรือ 133 ตร.ว.', 'บ้านเดี่ยว 2 ชั้นพร้อมสระว่ายน้ำ เลขที่ 38/197 โครงการบ้านสวนสุวัฒนา เฟส 1 ซอย 12 ถนนเนินพลับหวาน ตำบลหนองปรือ อำเภอบางละมุง จังหวัดชลบุรี โฉนดเลขที่ 91288 จำนวน 1 ฉบับ เนื้อที่ 1 งาน 33 ตร.ว. หรือ 133 ตร.ว. (532 ตร.ม.) ต้นทางระบุ 4 ห้องนอน 5 ห้องน้ำ ราคาประกาศขายจาก SAM 6,920,000 บาท รหัสทรัพย์ 3A0852

ที่ดินรูปสี่เหลี่ยมผืนผ้า ด้านทิศตะวันออกกว้างประมาณ 24 เมตร แต่เฉพาะส่วนที่ติดถนนกว้างประมาณ 4 เมตร ลึกประมาณ 22 เมตร รายการรับโอนกรรมสิทธิ์ของ SAM ระบุบ้านพักอาศัยตึก 2 ชั้น เลขที่ 38/197 และสระว่ายน้ำ ต้นทางระบุเขตผังเมืองสีส้ม

สิทธิใช้ทางต้องตรวจสอบ: ถนนหมู่บ้านบ้านสวนสุวัฒนา เฟส 1 เป็นทางส่วนบุคคล ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 8 เมตร SAM ระบุโฉนดทางเข้า 100619 เลขที่ดิน 1763 เป็นถนนส่วนบุคคลที่มีเจตนาแบ่งไว้เพื่อใช้เข้าออกอย่างเปิดเผย ส่วนโฉนด 20098 เลขที่ดิน 731 เป็นถนนภายใต้การจัดสรรของโครงการ

SAM ระบุว่าแปลงที่ขายไม่ได้อยู่ภายใต้การจัดสรรเดิม แต่เป็นแปลงในโครงการที่แบ่งแยกภายหลังและใช้ถนนจัดสรรเข้าออกมานาน ผู้ซื้อควรตรวจหลักฐานสิทธิใช้ทางทั้งสองแปลง ขอบเขตทางและการใช้จริงก่อนเสนอซื้อ ไม่ควรสรุปจากการใช้ทางมานานว่ามีภาระจำยอมจดทะเบียนหรือสิทธิแบบเดียวกับแปลงจัดสรรเดิมแล้ว

ทรัพย์อยู่ในย่านที่อยู่อาศัย สถานที่ใกล้เคียงตาม SAM ได้แก่ โรงเรียนบ้านเนินพลับหวาน โรงเรียนสว่างบริบูรณ์วิทยา และวัดสุทธาวาส หนองปรือ การเดินทางใช้ถนนสุขุมวิทจากศรีราชามุ่งหน้าสัตหีบ ผ่านโฮมโปรพัทยาเหนือ บุญถาวรพัทยา และอินเด็กซ์ ลิฟวิ่งมอลล์พัทยา เลี้ยวซ้ายซอยสุขุมวิท 53 ข้ามถนนเลียบทางรถไฟเข้าสู่ถนนเนินพลับหวาน ผ่านมัสยิดดารุ้ลอับร้อร์ เลี้ยวซ้ายเข้าโครงการบ้านสวนสุวัฒนาประมาณ 140 เมตร แล้วเลี้ยวซ้ายถนนภายใน ทรัพย์อยู่ด้านหน้า

ภาพภายนอกและสระว่ายน้ำมีวันที่ 16 มีนาคม 2565 ส่วนภาพเฉลียงและภายในมีวันที่ 28 กุมภาพันธ์ 2567 รวม 19 ภาพ ภาพสระแสดงสภาพแห้งและพื้นที่รอบสระมีพืชขึ้น จึงควรตรวจสภาพสระ ระบบกรอง การรั่วซึมและตัวบ้านปัจจุบันก่อนซื้อ ไม่ได้ยืนยันว่าสระพร้อมใช้งาน

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A0852 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม สิทธิใช้ทาง รายการอาคารและเงื่อนไขล่าสุด

พิกัด 12.933123, 100.917287 ดึงจากลิงก์นำทาง SAM และตรงกับ Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวม ขนาดสระ จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงต้องยืนยันกับ SAM', 6920000, false, 532, 2, 4, 5, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '38/197 บ้านสวนสุวัฒนา เฟส 1 ซอย 12', 'เข้าจากถนนเนินพลับหวานตามแผนที่ SAM', 'ถนนเนินพลับหวาน', 12.933123, 100.917287, 'ชลบุรี', 'บางละมุง', 'หนองปรือ', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-pool-house-ban-suan-suwattana-nong-prue-3a0852') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6920000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'detached_house', 1, '{"source_property_category":"บ้านเดี่ยว","official_page_reference_code":"3A0852","source_page_id":18850,"project_name":"บ้านสวนสุวัฒนา เฟส 1","project_soi":"12","title_document_type":"chanote","title_deed_number":"91288","title_document_count":1,"land_area_square_wah":133,"land_area_sqm":532,"east_side_width_m_approx":24,"actual_road_frontage_m_approx":4,"depth_m_approx":22,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":8,"front_road_status":"private","access_title_deeds":["100619","20098"],"access_parcel_numbers":["1763","731"],"sale_plot_outside_original_subdivision_approval_reported":true,"later_subdivided_plot_reported":true,"long_term_use_of_project_road_reported":true,"registered_easement_not_confirmed":true,"planning_zone_th":"เขตสีส้ม","registered_floor_count":2,"registered_structures":["บ้านพักอาศัยตึก 2 ชั้น เลขที่ 38/197","สระว่ายน้ำ"],"has_private_pool":true,"pool_operability_not_confirmed":true,"source_bedroom_count":4,"source_bathroom_count":5,"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_dates":["2022-03-16","2024-02-28"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//12.933123,100.917287","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 18850 identifies SAM as direct-sale contact for 3A0852, two-storey house and pool in Ban Suan Suwattana, with private access rights requiring verification.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 3A0852 ราคา 6,920,000 บาท', 'SAM direct purchase 3A0852, THB 6,920,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'private_access_rights', 'สิทธิใช้ถนนโครงการ', 'Project road access rights', 'แปลงแบ่งแยกภายหลังอยู่นอกจัดสรรเดิม ใช้ทางโฉนด 100619 และ 20098 ต้องตรวจสิทธิ ไม่ยืนยันภาระจำยอมจดทะเบียน', 'Later-divided plot outside original subdivision approval uses titles 100619/20098; verify rights, registered easement not confirmed', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_frontage', 'ส่วนที่ติดถนน', 'Actual road frontage', 'ด้านตะวันออกกว้าง 24 ม. แต่ติดถนนเพียงประมาณ 4 ม.', 'East side approx. 24 m; only approx. 4 m fronts road', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'pool_condition', 'สระว่ายน้ำและสภาพปัจจุบัน', 'Pool and current condition', 'สระอยู่ในรายการรับโอน แต่ภาพเก่าแสดงสระแห้ง ต้องตรวจระบบและสภาพจริง', 'Pool included in registered acquisition; old image shows empty pool; inspect systems and current condition', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ประตูและแนวหน้าบ้าน', 'ประตูและแนวหน้าบ้าน', 'https://npa.sam.or.th/site/images/npa/18850/20240627131431_3A0852P2_65.jpg', '/listing-media/sam/3a0852/01.webp', 'image/webp', 32512, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานบ้านและส่วนหลังคาคลุม', 'ลานบ้านและส่วนหลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/18850/3A0852P3_65.jpg', '/listing-media/sam/3a0852/02.webp', 'image/webp', 51126, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สระว่ายน้ำและพื้นที่รอบบ้าน', 'สระว่ายน้ำและพื้นที่รอบบ้าน', 'https://npa.sam.or.th/site/images/npa/18850/3A0852P4_65.jpg', '/listing-media/sam/3a0852/03.webp', 'image/webp', 57932, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'เฉลียงทางเข้าบ้าน', 'เฉลียงทางเข้าบ้าน', 'https://npa.sam.or.th/site/images/npa/18850/P2_67update.jpg', '/listing-media/sam/3a0852/04.webp', 'image/webp', 22368, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงพักผ่อนภายใน', 'โถงพักผ่อนภายใน', 'https://npa.sam.or.th/site/images/npa/18850/P7_67update.jpg', '/listing-media/sam/3a0852/05.webp', 'image/webp', 16064, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในริมหน้าต่าง', 'ห้องภายในริมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/18850/P9_67update.jpg', '/listing-media/sam/3a0852/06.webp', 'image/webp', 12202, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและพื้นที่ตู้เสื้อผ้า', 'ห้องและพื้นที่ตู้เสื้อผ้า', 'https://npa.sam.or.th/site/images/npa/18850/P14_67update.jpg', '/listing-media/sam/3a0852/07.webp', 'image/webp', 16192, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอีกมุม', 'ห้องภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/18850/P16_67update.jpg', '/listing-media/sam/3a0852/08.webp', 'image/webp', 15716, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินและบันได', 'ทางเดินและบันได', 'https://npa.sam.or.th/site/images/npa/18850/P6_67update.jpg', '/listing-media/sam/3a0852/09.webp', 'image/webp', 15620, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องครัวพร้อมเคาน์เตอร์', 'ห้องครัวพร้อมเคาน์เตอร์', 'https://npa.sam.or.th/site/images/npa/18850/P8_67update.jpg', '/listing-media/sam/3a0852/10.webp', 'image/webp', 21974, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ล้างและเตรียมอาหาร', 'พื้นที่ล้างและเตรียมอาหาร', 'https://npa.sam.or.th/site/images/npa/18850/P5_67update.jpg', '/listing-media/sam/3a0852/11.webp', 'image/webp', 11714, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในทรงยาว', 'ห้องภายในทรงยาว', 'https://npa.sam.or.th/site/images/npa/18850/P18_67update.jpg', '/listing-media/sam/3a0852/12.webp', 'image/webp', 9850, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดขึ้นชั้นบน', 'บันไดขึ้นชั้นบน', 'https://npa.sam.or.th/site/images/npa/18850/P13_67update.jpg', '/listing-media/sam/3a0852/13.webp', 'image/webp', 14344, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำพร้อมอ่างอาบน้ำ', 'ห้องน้ำพร้อมอ่างอาบน้ำ', 'https://npa.sam.or.th/site/images/npa/18850/P12_67update.jpg', '/listing-media/sam/3a0852/14.webp', 'image/webp', 20374, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำและส่วนอาบน้ำ', 'ห้องน้ำและส่วนอาบน้ำ', 'https://npa.sam.or.th/site/images/npa/18850/P15_67update.jpg', '/listing-media/sam/3a0852/15.webp', 'image/webp', 17284, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าโครงการจากถนนเนินพลับหวาน', 'ทางเข้าโครงการจากถนนเนินพลับหวาน', 'https://npa.sam.or.th/site/images/npa/18850/3A0852P1_65.jpg', '/listing-media/sam/3a0852/16.webp', 'image/webp', 31052, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงและส่วนติดถนน', 'ผังแปลงและส่วนติดถนน', 'https://npa.sam.or.th/site/images/npa/18850/20210129092710_3A0852C1_64.jpg', '/listing-media/sam/3a0852/17.webp', 'image/webp', 12244, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งบ้านและสระว่ายน้ำ', 'ผังตำแหน่งบ้านและสระว่ายน้ำ', 'https://npa.sam.or.th/site/images/npa/18850/20210129092710_3A0852C2_64.jpg', '/listing-media/sam/3a0852/18.webp', 'image/webp', 18950, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/18850/20210128144201_3A0852M1_64.jpg', '/listing-media/sam/3a0852/19.webp', 'image/webp', 58416, 785, 600, 190, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=18850&keyref=6007684', '3A0852', now(), 'Official source captured 2026-09-11. THB 6,920,000; 133 sq.wah; registered two-storey house and pool, four bedrooms/five bathrooms. East side 24 m but actual road frontage only 4 m. Later-divided sale plot outside original subdivision approval uses private roads titles 100619/20098; no registered easement confirmation. Nineteen source photos dated 2022-03-16 and 2024-02-28; pool operability unconfirmed. Navigation/map agree. All-status duplicate search no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 2-Storey Pool House, Ban Suan Suwattana, THB 6.92M', 'Two-storey detached house with swimming pool, number 38/197, Ban Suan Suwattana Phase 1, Soi 12, Noen Phlap Wan Road, Nong Prue, Bang Lamung, Chon Buri. One Chanote title, 91288, covers 133 sq.wah (532 sq.m.). SAM lists four bedrooms and five bathrooms. Announced sale price THB 6,920,000; asset 3A0852.

Rectangular plot with an eastern side approximately 24 metres wide, of which only approximately four metres fronts the road, and depth approximately 22 metres. SAM''s registered acquisition lists the two-storey house numbered 38/197 and swimming pool. SAM reports orange planning zoning.

Material access issue: the village road is private, with approximately six metres of concrete carriageway and eight metres of right of way. SAM describes access title 100619, parcel 1763, as private land intentionally divided for open access. Title 20098, parcel 731, is road land within the project''s subdivision.

SAM states that the sale plot is not within the original subdivision approval: it was subdivided later within the project and has long used the subdivision road. Verify access-right evidence over both road plots, boundaries and actual use before offering. Long use is not presented here as proof of registered easement or rights equivalent to original subdivision plots.

Source-listed nearby places include Ban Noen Phlap Wan School, Sawang Boriboon Wittaya School and Wat Sutthawat Nong Prue. From Si Racha toward Sattahip on Sukhumvit Road, pass HomePro North Pattaya, Boonthavorn and Index Living Mall Pattaya, turn left into Sukhumvit 53, cross the railway-side road into Noen Phlap Wan Road, pass Darul Abror Mosque, then left into Ban Suan Suwattana for approximately 140 metres and left into the internal road; the property is ahead.

Exterior/pool photos display 16 March 2022, and porch/interior photos display 28 February 2024. Nineteen source images are retained. The pool photo shows an empty pool and vegetation around it; inspect current pool structure, filtration, leakage and house condition. Pool operability is not confirmed.

SAM showed direct-purchase status and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A0852, to confirm availability, price, viewing, access rights, buildings and terms.

Navigation and map links agree on 12.933123, 100.917287. Total usable area, pool size, parking capacity, building age and occupancy are not published; confirm with SAM.', '38/197, Ban Suan Suwattana Phase 1, Soi 12', 'Access from Noen Phlap Wan Road via SAM map', 'Noen Phlap Wan Road', 'Nong Prue', 'Bang Lamung', 'Chon Buri', 'SAM Ban Suan Suwattana Pool House — THB 6.92M', 'SAM 3A0852: two-storey house and pool, 133 sq.wah, 4 bedrooms, 5 bathrooms, Nong Prue. THB 6,920,000; private road access disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: 2-storey pool house, ban suan suwattana, thb 6.92m two-storey detached house with swimming pool, number 38/197, ban suan suwattana phase 1, soi 12, noen phlap wan road, nong prue, bang lamung, chon buri. one chanote title, 91288, covers 133 sq.wah (532 sq.m.). sam lists four bedrooms and five bathrooms. announced sale price thb 6,920,000; asset 3a0852.

rectangular plot with an eastern side approximately 24 metres wide, of which only approximately four metres fronts the road, and depth approximately 22 metres. sam''s registered acquisition lists the two-storey house numbered 38/197 and swimming pool. sam reports orange planning zoning.

material access issue: the village road is private, with approximately six metres of concrete carriageway and eight metres of right of way. sam describes access title 100619, parcel 1763, as private land intentionally divided for open access. title 20098, parcel 731, is road land within the project''s subdivision.

sam states that the sale plot is not within the original subdivision approval: it was subdivided later within the project and has long used the subdivision road. verify access-right evidence over both road plots, boundaries and actual use before offering. long use is not presented here as proof of registered easement or rights equivalent to original subdivision plots.

source-listed nearby places include ban noen phlap wan school, sawang boriboon wittaya school and wat sutthawat nong prue. from si racha toward sattahip on sukhumvit road, pass homepro north pattaya, boonthavorn and index living mall pattaya, turn left into sukhumvit 53, cross the railway-side road into noen phlap wan road, pass darul abror mosque, then left into ban suan suwattana for approximately 140 metres and left into the internal road; the property is ahead.

exterior/pool photos display 16 march 2022, and porch/interior photos display 28 february 2024. nineteen source images are retained. the pool photo shows an empty pool and vegetation around it; inspect current pool structure, filtration, leakage and house condition. pool operability is not confirmed.

sam showed direct-purchase status and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a0852, to confirm availability, price, viewing, access rights, buildings and terms.

navigation and map links agree on 12.933123, 100.917287. total usable area, pool size, parking capacity, building age and occupancy are not published; confirm with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=18850&keyref=6007684', 'Official SAM page 18850 identifies SAM as asset holder and direct-sale contact for 3A0852.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '9e9b7b42-b2a5-448c-97d8-f6a9ff230852', '{"reference_code":"3A0852","source_page_id":18850,"source_image_count":19,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
