BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-15865'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='8Z6770' OR source_url ~ '[?&]id=15865(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='87b95db6-2d30-4f63-86ec-4d49a2c56770' OR slug='sam-direct-sale-shophouse-su-charoen-patong-8z6770' OR description ILIKE '%8Z6770%' OR (abs(latitude-7.88469)<0.0001 AND abs(longitude-98.29789)<0.0001 AND abs(land_area_sqm-73.2)<1)) THEN RAISE NOTICE 'SAM 8Z6770 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('87b95db6-2d30-4f63-86ec-4d49a2c56770', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', 'สุเจริญป่าตอง', '162/143', 'ขายตรง SAM อาคารพาณิชย์ 4 ชั้น สุเจริญป่าตอง ภูเก็ต 18.3 ตร.ว.', 'อาคารพาณิชย์ 4 ชั้น เลขที่ 162/143 โครงการสุเจริญป่าตอง ถนนผังเมืองสาย ก. ตำบลป่าตอง อำเภอกะทู้ จังหวัดภูเก็ต โฉนดเลขที่ 12588 จำนวน 1 ฉบับ เนื้อที่ 18.3 ตร.ว. (73.2 ตร.ม.) ต้นทางระบุ 5 ห้องนอน 7 ห้องน้ำ ราคาประกาศขายจาก SAM 6,886,000 บาท รหัสทรัพย์ 8Z6770

รายการรับโอนกรรมสิทธิ์ระบุเป็นอาคารพาณิชย์ 4 ชั้น เลขที่ 162/143 ที่ดินรูปสี่เหลี่ยมผืนผ้า ขนาดแปลงในรายละเอียดและผัง SAM ระบุด้านทิศเหนือติดถนนกว้างประมาณ 4 เมตร ลึกประมาณ 18 เมตร แต่ช่องสรุปหน้าเว็บระบุหน้ากว้าง 6 เมตร ลึก 9 เมตร ข้อมูลสองส่วนไม่ตรงกัน ต้องตรวจโฉนด ผังและขนาดจริงก่อนซื้อ โดยพื้นที่ดินใช้ 18.3 ตร.ว. ตามต้นทาง

สิทธิทางเข้าและค่าส่วนกลาง: SAM ระบุว่าทางเข้าเป็นแปลงคงเหลือโฉนด 11996 ซึ่งเดิมอยู่ภายใต้การจัดสรร ก่อนแบ่งเป็นแปลงทรัพย์โฉนด 12588 และยังใช้สิทธิเข้าออกของแปลงก่อนแบ่งแยกได้ตามข้อมูลต้นทาง หากมีการจัดตั้งนิติบุคคล ทรัพย์ต้องจ่ายค่าส่วนกลางเสมือนที่ดินภายใต้การจัดสรร ผู้ซื้อควรตรวจหลักฐานสิทธิใช้ทาง สถานะนิติบุคคล ค่าส่วนกลางและยอดค้างจริงก่อนเสนอซื้อ ต้นทางไม่ระบุอัตราหรือยอดเงิน ผิวถนนคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 9 เมตร

ต้นทางระบุเขตผังเมืองสีส้ม อยู่ในย่านที่อยู่อาศัย พาณิชยกรรมและแหล่งท่องเที่ยว ใกล้ห้างจังซีลอน หาดป่าตอง ตลาดสดบ้านข้าม และโรงพยาบาลป่าตอง ข้อมูลทำเลไม่ใช่การยืนยันใบอนุญาตโรงแรมหรือกิจการให้เช่ารายวัน และไม่ได้ประมาณรายได้หรือผลตอบแทน

การเดินทางตาม SAM: ใช้ถนนผังเมืองสาย ก. จากโรงพยาบาลป่าตองมุ่งหน้าแหลมพรหมเทพ ผ่านตลาดสดบ้านข้ามและห้างจังซีลอน เลี้ยวซ้ายเข้าโครงการสุเจริญป่าตองประมาณ 120 เมตร แล้วเลี้ยวขวาอีกประมาณ 20 เมตร ทรัพย์อยู่ด้านซ้ายมือ ต้นทางอ้างร้าน 7-Eleven และ FamilyMart เป็นจุดสังเกตปากซอย ควรใช้พิกัดประกอบเพราะร้านค้าอาจเปลี่ยนแปลง

ภาพอาคารและภายในแสดงวันที่ 10 ธันวาคม 2567 รวม 19 ภาพ มีภาพห้อง ทางเดิน ครัว ห้องน้ำ ระเบียง ทางเข้า ผังแปลงและแผนที่ ควรตรวจสภาพพื้น ผนัง ฝ้าเพดาน การรั่วซึม ระบบไฟฟ้าและประปาปัจจุบัน

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 8Z6770 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม ขนาดแปลง สิทธิใช้ทาง ค่าส่วนกลางและเงื่อนไขล่าสุด

พิกัด 7.884690, 98.297890 ดึงจากลิงก์นำทาง SAM และตรงกับ Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนที่จอดรถ อายุอาคาร สถานะผู้ครอบครอง หรือรายได้ค่าเช่า จึงต้องยืนยันกับ SAM', 6886000, false, 73.2, 4, 5, 7, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '162/143 โครงการสุเจริญป่าตอง ถนนผังเมืองสาย ก.', 'เข้าโครงการ 120 เมตร แล้วเลี้ยวขวาอีก 20 เมตร', 'ถนนผังเมืองสาย ก.', 7.88469, 98.29789, 'ภูเก็ต', 'กะทู้', 'ป่าตอง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-shophouse-su-charoen-patong-8z6770') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6886000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"8Z6770","source_page_id":15865,"project_name":"สุเจริญป่าตอง","title_document_type":"chanote","title_deed_number":"12588","title_document_count":1,"land_area_square_wah":18.3,"land_area_sqm":73.2,"plot_shape":"rectangular","detailed_north_frontage_m_approx":4,"detailed_depth_m_approx":18,"summary_frontage_m":6,"summary_depth_m":9,"source_plot_dimensions_conflict":true,"plot_measurement_verification_required":true,"planning_zone_th":"เขตสีส้ม","registered_floor_count":4,"registered_unit_number":"162/143","source_bedroom_count":5,"source_bathroom_count":7,"access_parent_title":"11996","original_subdivision_access_rights_retained_reported":true,"common_fees_if_juristic_entity_established_reported":true,"current_juristic_entity_status_not_published":true,"common_fee_amount_not_published":true,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":9,"usable_area_not_published":true,"occupancy_status_not_published":true,"rental_income_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_date":"2024-12-10","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//7.88469,98.29789","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 15865 identifies SAM as direct-sale contact for 8Z6770, four-storey shophouse 162/143 in Su Charoen Patong with source dimensional discrepancy and conditional common fees.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 8Z6770 ราคา 6,886,000 บาท', 'SAM direct purchase 8Z6770, THB 6,886,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'plot_dimensions', 'ขนาดแปลงที่ข้อมูลไม่ตรงกัน', 'Conflicting plot dimensions', 'รายละเอียดและผังประมาณ 4 × 18 ม. ช่องสรุป 6 × 9 ม. ต้องตรวจขนาดจริง', 'Detail and plan approx. 4 × 18 m; summary 6 × 9 m; verify actual dimensions', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'access_rights', 'สิทธิทางเข้า', 'Access rights', 'SAM ระบุใช้สิทธิแปลงเดิมผ่านโฉนด 11996 ต้องตรวจหลักฐานและการใช้จริง', 'SAM reports retained original-plot rights via title 11996; verify evidence and actual access', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'conditional_common_fees', 'ค่าส่วนกลางตามเงื่อนไข', 'Conditional common charges', 'หากจัดตั้งนิติบุคคลต้องจ่ายเสมือนที่ดินจัดสรร ต้องยืนยันสถานะ อัตราและยอดค้าง', 'If a juristic entity is established, subdivision-like fees apply; verify current status, rate and arrears', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารพาณิชย์ที่ประกาศขาย', 'ด้านหน้าอาคารพาณิชย์ที่ประกาศขาย', 'https://npa.sam.or.th/site/images/npa/15865/20250624132836_8Z6770P2_68.jpg', '/listing-media/sam/8z6770/01.webp', 'image/webp', 26018, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินภายใน', 'ทางเดินภายใน', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P4_68.jpg', '/listing-media/sam/8z6770/02.webp', 'image/webp', 11836, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ครัวและเคาน์เตอร์', 'ครัวและเคาน์เตอร์', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P5_68.jpg', '/listing-media/sam/8z6770/03.webp', 'image/webp', 30608, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในผนังสีเขียว', 'ห้องภายในผนังสีเขียว', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P7_68.jpg', '/listing-media/sam/8z6770/04.webp', 'image/webp', 14288, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำ', 'ห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P8_68.jpg', '/listing-media/sam/8z6770/05.webp', 'image/webp', 16122, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและประตูระเบียง', 'ห้องและประตูระเบียง', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P9_68.jpg', '/listing-media/sam/8z6770/06.webp', 'image/webp', 17368, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำอีกมุม', 'ห้องน้ำอีกมุม', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P10_68.jpg', '/listing-media/sam/8z6770/07.webp', 'image/webp', 16766, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมระเบียง', 'ห้องริมระเบียง', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P11_68.jpg', '/listing-media/sam/8z6770/08.webp', 'image/webp', 27108, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำและอ่างล้างหน้า', 'ห้องน้ำและอ่างล้างหน้า', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P12_68.jpg', '/listing-media/sam/8z6770/09.webp', 'image/webp', 18160, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องชั้นบน', 'ห้องชั้นบน', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P13_68.jpg', '/listing-media/sam/8z6770/10.webp', 'image/webp', 28362, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำชั้นบน', 'ห้องน้ำชั้นบน', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P14_68.jpg', '/listing-media/sam/8z6770/11.webp', 'image/webp', 15664, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและฝ้าเพดาน', 'ห้องและฝ้าเพดาน', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P15_68.jpg', '/listing-media/sam/8z6770/12.webp', 'image/webp', 32822, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำอีกห้อง', 'ห้องน้ำอีกห้อง', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P16_68.jpg', '/listing-media/sam/8z6770/13.webp', 'image/webp', 17632, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำมุมอ่างล้างหน้า', 'ห้องน้ำมุมอ่างล้างหน้า', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P18_68.jpg', '/listing-media/sam/8z6770/14.webp', 'image/webp', 16086, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมระเบียงอีกมุม', 'ห้องริมระเบียงอีกมุม', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P17_68.jpg', '/listing-media/sam/8z6770/15.webp', 'image/webp', 27044, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าโครงการสุเจริญป่าตอง', 'ทางเข้าโครงการสุเจริญป่าตอง', 'https://npa.sam.or.th/site/images/npa/15865/8Z6770P1_63.jpg', '/listing-media/sam/8z6770/16.webp', 'image/webp', 34880, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด 12588', 'ผังแปลงโฉนด 12588', 'https://npa.sam.or.th/site/images/npa/15865/20190107145204_8Z6770C1_61.jpg', '/listing-media/sam/8z6770/17.webp', 'image/webp', 14922, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งอาคาร 162/143', 'ผังตำแหน่งอาคาร 162/143', 'https://npa.sam.or.th/site/images/npa/15865/20190107145204_8Z6770C2_61.jpg', '/listing-media/sam/8z6770/18.webp', 'image/webp', 17488, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/15865/20190107145204_8Z6770M1_61.jpg', '/listing-media/sam/8z6770/19.webp', 'image/webp', 69234, 785, 600, 190, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=15865&keyref=6007684', '8Z6770', now(), 'Official source captured 2026-09-11. THB 6,886,000; Chanote 12588, 18.3 sq.wah; four storeys; five bedrooms/seven bathrooms. Source dimensions conflict: summary 6x9 m vs detail/plan approx 4x18 m. Retained access via parent 11996 and common fees conditional on juristic entity establishment disclosed; current fees/status not inferred. Nineteen source images dated 2024-12-10. Navigation/map agree. Nearby 8Z7193 and 8Z6607 are different properties by code/address/title/area; no exact duplicate.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: 4-Storey Su Charoen Patong Shophouse, THB 6.886M', 'Four-storey shophouse numbered 162/143 in Su Charoen Patong, Phang Mueang Sai Kor Road, Patong, Kathu, Phuket. One Chanote title, 12588, covers 18.3 sq.wah (73.2 sq.m.). SAM lists five bedrooms and seven bathrooms. Announced price THB 6,886,000; asset 8Z6770.

Registered acquisition describes a four-storey shophouse numbered 162/143. The rectangular plot has approximately four metres of northern frontage and 18 metres depth in the detailed description and plan. However, the summary fields state six metres frontage and nine metres depth. Verify this discrepancy against title, plan and actual measurements; land area is retained as the source''s 18.3 sq.wah.

SAM reports access via remaining parent title 11996, formerly under subdivision approval before the sale plot 12588 was split off, with access rights retained from the original plot. If a juristic entity is established, the property must pay common-area charges as subdivision land. Verify access evidence, current juristic-entity status, charges and arrears before offering. SAM does not state an amount. Concrete carriageway is approximately six metres wide within a nine-metre right of way.

SAM reports orange zoning and residential, commercial and tourism surroundings, near Jungceylon, Patong Beach, Ban Kham fresh market and Patong Hospital. Location does not confirm hotel or daily-rental permissions; no income or yield is inferred.

From Patong Hospital toward Laem Phromthep along Phang Mueang Sai Kor Road, pass Ban Kham market and Jungceylon, turn left into Su Charoen Patong for 120 metres, then right for 20 metres; the property is on the left. Source landmarks include 7-Eleven and FamilyMart at the entrance; use coordinates as stores may change.

Building/interior photographs display 10 December 2024. Nineteen images include rooms, corridor, kitchen, bathrooms, balconies, access, plot plans and map. Inspect current floors, walls, ceilings, leakage, electrical and plumbing systems.

SAM showed direct purchase and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 8Z6770, to confirm availability, price, viewing, dimensions, access rights, common charges and terms.

Navigation and map agree on 7.884690, 98.297890. Usable area, parking, age, occupancy and rental income are not published; confirm with SAM.', '162/143, Su Charoen Patong, Phang Mueang Sai Kor Road', '120 m into project, then right for 20 m', 'Phang Mueang Sai Kor Road', 'Patong', 'Kathu', 'Phuket', 'SAM Su Charoen Patong Shophouse — THB 6.886M', 'SAM 8Z6770: four-storey shophouse, Su Charoen Patong, 18.3 sq.wah, 5 bedrooms, 7 bathrooms, THB 6,886,000. Access and dimension discrepancy disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: 4-storey su charoen patong shophouse, thb 6.886m four-storey shophouse numbered 162/143 in su charoen patong, phang mueang sai kor road, patong, kathu, phuket. one chanote title, 12588, covers 18.3 sq.wah (73.2 sq.m.). sam lists five bedrooms and seven bathrooms. announced price thb 6,886,000; asset 8z6770.

registered acquisition describes a four-storey shophouse numbered 162/143. the rectangular plot has approximately four metres of northern frontage and 18 metres depth in the detailed description and plan. however, the summary fields state six metres frontage and nine metres depth. verify this discrepancy against title, plan and actual measurements; land area is retained as the source''s 18.3 sq.wah.

sam reports access via remaining parent title 11996, formerly under subdivision approval before the sale plot 12588 was split off, with access rights retained from the original plot. if a juristic entity is established, the property must pay common-area charges as subdivision land. verify access evidence, current juristic-entity status, charges and arrears before offering. sam does not state an amount. concrete carriageway is approximately six metres wide within a nine-metre right of way.

sam reports orange zoning and residential, commercial and tourism surroundings, near jungceylon, patong beach, ban kham fresh market and patong hospital. location does not confirm hotel or daily-rental permissions; no income or yield is inferred.

from patong hospital toward laem phromthep along phang mueang sai kor road, pass ban kham market and jungceylon, turn left into su charoen patong for 120 metres, then right for 20 metres; the property is on the left. source landmarks include 7-eleven and familymart at the entrance; use coordinates as stores may change.

building/interior photographs display 10 december 2024. nineteen images include rooms, corridor, kitchen, bathrooms, balconies, access, plot plans and map. inspect current floors, walls, ceilings, leakage, electrical and plumbing systems.

sam showed direct purchase and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 8z6770, to confirm availability, price, viewing, dimensions, access rights, common charges and terms.

navigation and map agree on 7.884690, 98.297890. usable area, parking, age, occupancy and rental income are not published; confirm with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=15865&keyref=6007684', 'Official SAM page 15865 identifies SAM as asset holder and direct-sale contact for 8Z6770.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '87b95db6-2d30-4f63-86ec-4d49a2c56770', '{"reference_code":"8Z6770","source_page_id":15865,"source_image_count":19,"coordinate_source":"sam_navigation_href","duplicate_check":"nearby 8Z7193 and 8Z6607 are different properties; no exact match"}'::jsonb) ;
END $$;
COMMIT;
