BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-18891'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A0245' OR source_url ~ '[?&]id=18891(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='90fc3f2e-d20a-49c7-80b5-4f39b56c0245' OR slug='sam-direct-sale-houses-prem-chai-rat-3-mueang-chonburi-3a0245' OR description ILIKE '%3A0245%' OR (abs(latitude-13.26666)<0.0001 AND abs(longitude-100.93867)<0.0001 AND abs(land_area_sqm-868)<1)) THEN RAISE NOTICE 'SAM 3A0245 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('90fc3f2e-d20a-49c7-80b5-4f39b56c0245', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'detached_house', 'residence', 'sale', 'whole_property', '10, 12, 12/1', 'ขายตรง SAM บ้านหลายหลัง เปรมใจราษฎร์ซอย 3 ชลบุรี ที่ดิน 217 ตร.ว.', 'กลุ่มบ้านพักอาศัยบนที่ดิน 5 แปลงติดต่อกัน เลขที่ 10, 12 และ 12/1 เปรมใจราษฎร์ซอย 3 ถนนเปรมใจราษฎร์ ตำบลเหมือง อำเภอเมืองชลบุรี จังหวัดชลบุรี โฉนดเลขที่ 76921, 85583, 86026, 108997 และ 108998 รวม 5 ฉบับ เนื้อที่ 2 งาน 17 ตร.ว. หรือ 217 ตร.ว. (868 ตร.ม.) หน้า SAM ระบุรวม 6 ห้องนอน 6 ห้องน้ำ ราคาประกาศขาย 6,750,000 บาท รหัสทรัพย์ 3A0245 เป็นการขายรวมตามรายการทรัพย์ ไม่ได้แยกราคาต่อหลัง

รายการสิ่งปลูกสร้างที่ SAM รับโอนประกอบด้วย: บ้านพักอาศัยตึก 2 ชั้น เลขที่ 12/1 ซึ่งต้นทางระบุเฉพาะหลังนี้ 2 ห้องนอน 3 ห้องน้ำ; บ้านพักอาศัยแฝดตึกชั้นเดียวเลขที่ 12; บ้านพักอาศัยแฝดตึกชั้นเดียวเลขที่ 10 พร้อมรั้วคอนกรีต; และบ้านพักอาศัยตึกชั้นเดียวไม่ระบุเลขที่พร้อมโรงจอดรถ จำนวนห้องรวม 6 ห้องนอน 6 ห้องน้ำใช้ตามช่องสรุปหน้า SAM ไม่ได้นำจำนวนของหลัง 12/1 มาบวกซ้ำ ผู้ซื้อควรตรวจผังและรายการอาคารแต่ละหลังกับ SAM

ที่ดินรูปหลายเหลี่ยม ด้านทิศเหนือติดถนน หน้ากว้างประมาณ 44.5 เมตร ลึกสุดประมาณ 26 เมตร ต้นทางระบุเขตผังเมืองสีแดงและย่านที่อยู่อาศัย

สิทธิทางเข้าต้องตรวจสอบ: SAM บรรยายเปรมใจราษฎร์ซอย 3 ว่าเป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 4 เมตร เขตทางประมาณ 7 เมตร แต่การเข้าออกแปลงทรัพย์ต้องผ่านโฉนด 191390 เลขที่ดิน 218 ซึ่งเป็นแปลงทางด้านหน้าทรัพย์ ตามเอกสารสิทธิ์ยังไม่ได้ยกเป็นทางสาธารณประโยชน์ แม้ปัจจุบันเป็นถนนคอนกรีตภายใต้การดูแลของเทศบาลแสนสุข ผู้ซื้อควรตรวจสถานะทาง หลักฐานสิทธิผ่านแปลง 191390 ขอบเขตและการใช้จริงก่อนเสนอซื้อ การดูแลโดยเทศบาลไม่ได้ยืนยันว่าที่ดินแปลงทางได้เป็นสาธารณะแล้ว

สถานที่ใกล้เคียงตาม SAM ได้แก่ สถานีตำรวจภูธรบางไทร ตลาดหนองมน วัดตาลล้อม และโรงเรียนวัดราษฎร์ศรัทธา การเดินทางใช้ถนนสุขุมวิทจากชลบุรีมุ่งหน้าพัทยา ผ่านวัดแจ้งเจริญดอนและโรงเรียนสุขุมวิทยา เลี้ยวซ้ายถนนแสนสุข–บางพระ (ทล.3144) ถึงแยกถนนเปรมใจราษฎร์ เลี้ยวขวาประมาณ 1.2 กิโลเมตร แล้วเลี้ยวซ้ายเปรมใจราษฎร์ซอย 3 ประมาณ 106 เมตร ทรัพย์อยู่ด้านขวามือ

ภาพอาคารและภายในแสดงวันที่ 22 กุมภาพันธ์ 2568 รวม 21 ภาพ มีภาพบ้าน โถง ห้อง บันได ห้องน้ำ โรงจอดรถ ผังแปลง ผังอาคารและแผนที่ ควรตรวจสภาพอาคารแต่ละหลัง ระบบไฟฟ้า ประปา หลังคาและการระบายน้ำปัจจุบัน

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A0245 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม รายการอาคาร สิทธิทางเข้าและเงื่อนไขล่าสุด

พิกัด 13.266660, 100.938670 ดึงจากลิงก์นำทาง SAM และตรงกับ Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนที่จอดรถ อายุอาคารแต่ละหลัง หรือสถานะผู้ครอบครอง จึงต้องยืนยันกับ SAM', 6750000, false, 868, 2, 6, 6, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '10, 12, 12/1 เปรมใจราษฎร์ซอย 3', 'ผ่านแปลงทางโฉนด 191390 ต้องตรวจสิทธิใช้ทาง', 'ถนนเปรมใจราษฎร์', 13.26666, 100.93867, 'ชลบุรี', 'เมืองชลบุรี', 'เหมือง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-houses-prem-chai-rat-3-mueang-chonburi-3a0245') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6750000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'detached_house', 1, '{"source_property_category":"บ้านเดี่ยว","official_page_reference_code":"3A0245","source_page_id":18891,"title_document_type":"chanote","title_deed_numbers":["76921","85583","86026","108997","108998"],"title_document_count":5,"land_area_square_wah":217,"land_area_sqm":868,"plot_shape":"polygonal","north_frontage_m_approx":44.5,"maximum_depth_m_approx":26,"front_road_width_m_approx":4,"front_right_of_way_width_m_approx":7,"access_road_title":"191390","access_road_parcel":"218","access_road_not_dedicated_public_per_source":true,"access_road_maintained_by_saen_suk_municipality_reported":true,"access_rights_verification_required":true,"planning_zone_th":"เขตสีแดง","maximum_registered_floor_count":2,"multi_building_property":true,"registered_structures":[{"description":"บ้านพักอาศัยตึกสองชั้น","number":"12/1","floors":2,"bedrooms":2,"bathrooms":3},{"description":"บ้านพักอาศัยแฝดตึกชั้นเดียว","number":"12","floors":1},{"description":"บ้านพักอาศัยแฝดตึกชั้นเดียวและรั้วคอนกรีต","number":"10","floors":1},{"description":"บ้านพักอาศัยตึกชั้นเดียวไม่ระบุเลขที่พร้อมโรงจอดรถ","floors":1}],"source_aggregate_bedroom_count":6,"source_aggregate_bathroom_count":6,"sub_building_room_counts_not_added_to_total":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_date":"2025-02-22","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.266660,100.938670","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 18891 identifies SAM as direct-sale contact for 3A0245, multiple residential buildings on five plots in Prem Chai Rat Soi 3.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 3A0245 ราคา 6,750,000 บาท ขายรวมตามรายการทรัพย์', 'SAM direct purchase 3A0245, THB 6,750,000 for the listed property group', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_buildings', 'บ้านหลายหลังตามทะเบียน', 'Registered building group', 'บ้าน 12/1 สองชั้น บ้านแฝดชั้นเดียว 10 และ 12 และบ้านชั้นเดียวไม่ระบุเลขที่พร้อมโรงจอดรถ', 'Two-storey 12/1; single-storey semi-detached 10 and 12; unnumbered single-storey home with garage', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'private_access_rights', 'สถานะแปลงทางเข้า', 'Access parcel status', 'โฉนด 191390 ยังไม่ยกเป็นทางสาธารณะตาม SAM แม้เทศบาลดูแล ต้องตรวจสิทธิผ่านทาง', 'SAM reports title 191390 not dedicated public despite municipal maintenance; verify access rights', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'room_count_scope', 'จำนวนห้องรวม', 'Room-count scope', '6 ห้องนอน 6 ห้องน้ำตามหน้าสรุป รวมข้อมูลของบ้าน 12/1 แล้ว ไม่บวกซ้ำ', 'Six bedrooms/six bathrooms from source summary; do not add the 12/1 subset again', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'บ้านพักอาศัยสองชั้น', 'บ้านพักอาศัยสองชั้น', 'https://npa.sam.or.th/site/images/npa/18891/20250908155932_3A0245P3_68.jpg', '/listing-media/sam/3a0245/01.webp', 'image/webp', 32716, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวบ้านพักอาศัยชั้นเดียว', 'แนวบ้านพักอาศัยชั้นเดียว', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P2_68.jpg', '/listing-media/sam/3a0245/02.webp', 'image/webp', 33442, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงบ้านสองชั้นและบันได', 'โถงบ้านสองชั้นและบันได', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P4_68.jpg', '/listing-media/sam/3a0245/03.webp', 'image/webp', 20620, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในอีกมุม', 'โถงภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P5_68.jpg', '/listing-media/sam/3a0245/04.webp', 'image/webp', 19894, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ครัวและทางเดิน', 'ครัวและทางเดิน', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P6_68.jpg', '/listing-media/sam/3a0245/05.webp', 'image/webp', 16276, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำชั้นล่าง', 'ห้องน้ำชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P7_68.jpg', '/listing-media/sam/3a0245/06.webp', 'image/webp', 17124, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชานบันไดชั้นบน', 'ชานบันไดชั้นบน', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P8_68.jpg', '/listing-media/sam/3a0245/07.webp', 'image/webp', 18248, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องชั้นบนริมหน้าต่าง', 'ห้องชั้นบนริมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P9_68.jpg', '/listing-media/sam/3a0245/08.webp', 'image/webp', 17606, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในผนังสีฟ้า', 'ห้องภายในผนังสีฟ้า', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P10_68.jpg', '/listing-media/sam/3a0245/09.webp', 'image/webp', 13686, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำและส่วนอาบน้ำ', 'ห้องน้ำและส่วนอาบน้ำ', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P11_68.jpg', '/listing-media/sam/3a0245/10.webp', 'image/webp', 22294, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำอีกห้อง', 'ห้องน้ำอีกห้อง', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P12_68.jpg', '/listing-media/sam/3a0245/11.webp', 'image/webp', 16980, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงบ้านชั้นเดียว', 'โถงบ้านชั้นเดียว', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P13_68.jpg', '/listing-media/sam/3a0245/12.webp', 'image/webp', 17092, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในบ้านชั้นเดียว', 'พื้นที่ภายในบ้านชั้นเดียว', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P14_68.jpg', '/listing-media/sam/3a0245/13.webp', 'image/webp', 10890, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในอีกด้าน', 'โถงภายในอีกด้าน', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P15_68.jpg', '/listing-media/sam/3a0245/14.webp', 'image/webp', 10940, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในบ้านชั้นเดียว', 'ห้องภายในบ้านชั้นเดียว', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P16_68.jpg', '/listing-media/sam/3a0245/15.webp', 'image/webp', 9136, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำบ้านชั้นเดียว', 'ห้องน้ำบ้านชั้นเดียว', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P17_68.jpg', '/listing-media/sam/3a0245/16.webp', 'image/webp', 15106, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โรงจอดรถและพื้นที่หลังคาคลุม', 'โรงจอดรถและพื้นที่หลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P18_68.jpg', '/listing-media/sam/3a0245/17.webp', 'image/webp', 22954, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าเปรมใจราษฎร์ซอย 3', 'ทางเข้าเปรมใจราษฎร์ซอย 3', 'https://npa.sam.or.th/site/images/npa/18891/3A0245P1_64.jpg', '/listing-media/sam/3a0245/18.webp', 'image/webp', 50536, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดิน 5 แปลงและแปลงทางเข้า', 'ผังที่ดิน 5 แปลงและแปลงทางเข้า', 'https://npa.sam.or.th/site/images/npa/18891/20221207153908_3A0245C1_64.jpg', '/listing-media/sam/3a0245/19.webp', 'image/webp', 30138, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งบ้านแต่ละหลัง', 'ผังตำแหน่งบ้านแต่ละหลัง', 'https://npa.sam.or.th/site/images/npa/18891/20210423110028_3A0245C2_64.jpg', '/listing-media/sam/3a0245/20.webp', 'image/webp', 24828, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/18891/20210423110028_3A0245M1_64.jpg', '/listing-media/sam/3a0245/21.webp', 'image/webp', 43678, 785, 600, 210, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=18891&keyref=6007684', '3A0245', now(), 'Official source captured 2026-09-11. THB 6,750,000; five plots 217 sq.wah; multiple registered homes. Aggregate six bedrooms/six bathrooms; house 12/1 two-bedroom/three-bathroom subset not added again. Access parcel 191390/218 not dedicated public per SAM despite municipal maintenance; disclosed. Twenty-one source images, building photos 2025-02-22. Navigation/map agree. All-status duplicate search no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Multi-House Property, Prem Chai Rat Soi 3, THB 6.75M', 'Group of residential buildings on five adjoining plots, addresses 10, 12 and 12/1, Prem Chai Rat Soi 3, Mueang subdistrict, Mueang Chon Buri district, Chon Buri. Chanote titles 76921, 85583, 86026, 108997 and 108998 total 217 sq.wah (868 sq.m.). SAM''s summary lists six bedrooms and six bathrooms for the property. Announced total price THB 6,750,000; asset 3A0245, not a per-house price.

Registered acquisition includes a two-storey house numbered 12/1 (specifically listed as two bedrooms and three bathrooms); a single-storey semi-detached residence numbered 12; a single-storey semi-detached residence numbered 10 with concrete fence; and an unnumbered single-storey house with garage. The aggregate six-bedroom/six-bathroom count is retained from SAM''s summary; the 12/1 counts are not added again. Verify each structure and the transfer schedule.

Polygonal land with approximately 44.5 metres of northern frontage and maximum depth 26 metres. SAM reports red zoning and residential surroundings.

Material access issue: SAM describes Prem Chai Rat Soi 3 as public, with approximately four metres of concrete carriageway and seven metres right of way. However, property access passes through front road title 191390, parcel 218. SAM reports that this parcel has not been dedicated as public land according to its title, although it is a concrete road maintained by Saen Suk Municipality. Verify road status, evidence of access rights over 191390, boundaries and actual use before offering. Municipal maintenance does not confirm public ownership of the road parcel.

Nearby source-listed places are Bang Sai Police Station, Nong Mon Market, Wat Tan Lom and Wat Rat Sattha School. From Chon Buri toward Pattaya on Sukhumvit, pass Wat Chaeng Charoen Don and Sukhum Witthaya School, turn left onto Highway 3144, right into Prem Chai Rat Road for 1.2 kilometres, then left into Soi 3 for 106 metres; the property is on the right.

Building/interior photos display 22 February 2025. Twenty-one images include homes, halls, rooms, stairs, bathrooms, garage, plot/building plans and map. Inspect each building''s current structure, roof, power, plumbing and drainage.

SAM showed direct purchase and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A0245, to confirm availability, price, viewing, buildings, access and terms.

Navigation and map agree on 13.266660, 100.938670. Total usable area, parking capacity, individual building ages and occupancy are not published; confirm with SAM.', '10, 12, 12/1, Prem Chai Rat Soi 3', 'Access over road title 191390 requires verification', 'Prem Chai Rat Road', 'Mueang', 'Mueang Chon Buri', 'Chon Buri', 'SAM Prem Chai Rat Multi-House Property — THB 6.75M', 'SAM 3A0245: residential buildings on five plots, 217 sq.wah, six bedrooms/six bathrooms total. THB 6,750,000; access parcel status disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: multi-house property, prem chai rat soi 3, thb 6.75m group of residential buildings on five adjoining plots, addresses 10, 12 and 12/1, prem chai rat soi 3, mueang subdistrict, mueang chon buri district, chon buri. chanote titles 76921, 85583, 86026, 108997 and 108998 total 217 sq.wah (868 sq.m.). sam''s summary lists six bedrooms and six bathrooms for the property. announced total price thb 6,750,000; asset 3a0245, not a per-house price.

registered acquisition includes a two-storey house numbered 12/1 (specifically listed as two bedrooms and three bathrooms); a single-storey semi-detached residence numbered 12; a single-storey semi-detached residence numbered 10 with concrete fence; and an unnumbered single-storey house with garage. the aggregate six-bedroom/six-bathroom count is retained from sam''s summary; the 12/1 counts are not added again. verify each structure and the transfer schedule.

polygonal land with approximately 44.5 metres of northern frontage and maximum depth 26 metres. sam reports red zoning and residential surroundings.

material access issue: sam describes prem chai rat soi 3 as public, with approximately four metres of concrete carriageway and seven metres right of way. however, property access passes through front road title 191390, parcel 218. sam reports that this parcel has not been dedicated as public land according to its title, although it is a concrete road maintained by saen suk municipality. verify road status, evidence of access rights over 191390, boundaries and actual use before offering. municipal maintenance does not confirm public ownership of the road parcel.

nearby source-listed places are bang sai police station, nong mon market, wat tan lom and wat rat sattha school. from chon buri toward pattaya on sukhumvit, pass wat chaeng charoen don and sukhum witthaya school, turn left onto highway 3144, right into prem chai rat road for 1.2 kilometres, then left into soi 3 for 106 metres; the property is on the right.

building/interior photos display 22 february 2025. twenty-one images include homes, halls, rooms, stairs, bathrooms, garage, plot/building plans and map. inspect each building''s current structure, roof, power, plumbing and drainage.

sam showed direct purchase and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a0245, to confirm availability, price, viewing, buildings, access and terms.

navigation and map agree on 13.266660, 100.938670. total usable area, parking capacity, individual building ages and occupancy are not published; confirm with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=18891&keyref=6007684', 'Official SAM page 18891 identifies SAM as asset holder and direct-sale contact for 3A0245.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '90fc3f2e-d20a-49c7-80b5-4f39b56c0245', '{"reference_code":"3A0245","source_page_id":18891,"source_image_count":21,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
