BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-23189'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='SL0148' OR source_url ~ '[?&]id=23189(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='b93cf968-17b5-4b28-a584-d8d98ea50148' OR slug='sam-direct-sale-two-shophouses-boon-raksa-pong-sl0148' OR description ILIKE '%SL0148%' OR (abs(latitude-12.950127)<0.0001 AND abs(longitude-100.981171)<0.0001 AND abs(land_area_sqm-176)<1)) THEN RAISE NOTICE 'SAM SL0148 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('b93cf968-17b5-4b28-a584-d8d98ea50148', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'shophouse', 'mixed', 'sale', 'whole_property', 'บุญรักษา', '137/5-6', 'ขายตรง SAM อาคารพาณิชย์ 3 ชั้น 2 คูหา บุญรักษา ถนนชัยพรวิถี โป่ง 44 ตร.ว.', 'อาคารพาณิชย์ 3 ชั้น 2 คูหา เลขที่ 137/5-6 โครงการบุญรักษา ถนนชัยพรวิถี (ทล.3240) ตำบลโป่ง อำเภอบางละมุง จังหวัดชลบุรี โฉนดเลขที่ 183058 จำนวน 1 ฉบับ เนื้อที่ 44 ตร.ว. (176 ตร.ม.) ต้นทางระบุรวม 4 ห้องนอน 6 ห้องน้ำ ราคาประกาศขายจาก SAM 6,721,000 บาท รหัสทรัพย์ SL0148

ที่ดินรูปสี่เหลี่ยมผืนผ้า ด้านทิศตะวันตกติดถนน หน้ากว้างประมาณ 8 เมตร ลึกประมาณ 22 เมตร รายการรับโอนกรรมสิทธิ์ระบุตึกแถว 3 ชั้น เลขที่ 137/5-6 แต่ละคูหามีบันไดขึ้นลงแยกกัน ชั้น 1 เจาะผนังทะลุถึงกัน ส่วนชั้น 2 และชั้น 3 ไม่ได้เจาะเชื่อม ผู้ซื้อควรตรวจการเชื่อมอาคาร แบบและรายการที่จะโอนให้ตรงกับสภาพจริง

ถนนหน้าทรัพย์คือถนนชัยพรวิถี (ทล.3240) เป็นทางสาธารณประโยชน์ ผิวลาดยางกว้างประมาณ 12 เมตร เขตทางประมาณ 30 เมตร ต้นทางระบุผังเมืองสีส้ม อยู่ในย่านที่อยู่อาศัยและพาณิชยกรรม พร้อมสาธารณูปโภคตามข้อมูล SAM

ประเด็นแนวถนนที่ต้องตรวจสอบ: SAM ระบุว่าทรัพย์อยู่ในแนวถนนเสนอแนะตามผังเมืองสาย ฌ14 และรายงานผลสอบถามกรมทางหลวง หมวดเขาไม้แก้ว ว่าไม่มีโครงการเวนคืนบริเวณถนนหน้าทรัพย์ในข้อมูลที่สอบถาม ข้อมูลนี้ไม่ใช่การรับรองว่าจะไม่มีการเวนคืนหรือเปลี่ยนแปลงแนวถนนในอนาคต ผู้ซื้อควรตรวจแนวถนนและสถานะโครงการล่าสุดกับหน่วยงานก่อนเสนอซื้อ

สถานที่ใกล้เคียงตาม SAM ได้แก่ วัดนพทองดีศรีพฤฒาราม (วัดโป่ง) โรงพยาบาลส่งเสริมสุขภาพตำบลโป่ง และสำนักงานเทศบาลตำบลโป่ง การเดินทางใช้ถนนบางละมุง–ระยอง (ทล.36) จากระยองมุ่งหน้าพัทยา ผ่านสวนน้ำสแปลชดาวน์พัทยา ปั๊ม SUSCO และ ปตท.โป่ง แล้วเลี้ยวซ้ายถนนชัยพรวิถีประมาณ 880 เมตร ทรัพย์อยู่ด้านซ้ายมือ

ภาพภายนอกบางภาพระบุวันที่ 20 มกราคม 2568 และภาพอาคารกับภายในชุดล่าสุดระบุวันที่ 13 พฤษภาคม 2569 รวม 19 ภาพ มีภาพพื้นที่ชั้นล่าง ชั้นบน บันได ห้องน้ำ ระเบียง ผังชั้น ผังแปลงและแผนที่ ควรตรวจสภาพพื้น ผนัง ฝ้า ระบบไฟฟ้า ประปาและการระบายน้ำปัจจุบัน

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส SL0148 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม แนวถนน รายการอาคารและเงื่อนไขล่าสุด

พิกัด 12.950127, 100.981171 ดึงจากลิงก์นำทาง SAM และตรงกับ Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงต้องยืนยันกับ SAM', 6721000, false, 176, 3, 4, 6, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '137/5-6 โครงการบุญรักษา ถนนชัยพรวิถี', 'เข้าจากทางหลวง 36 ประมาณ 880 เมตร', 'ถนนชัยพรวิถี (ทล.3240)', 12.950127, 100.981171, 'ชลบุรี', 'บางละมุง', 'โป่ง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-two-shophouses-boon-raksa-pong-sl0148') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6721000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'shophouse', 1, '{"source_property_category":"อาคารพาณิชย์","official_page_reference_code":"SL0148","source_page_id":23189,"project_name":"บุญรักษา","title_document_type":"chanote","title_deed_number":"183058","title_document_count":1,"land_area_square_wah":44,"land_area_sqm":176,"plot_shape":"rectangular","west_road_frontage_m_approx":8,"depth_m_approx":22,"front_road_width_m_approx":12,"front_right_of_way_width_m_approx":30,"front_road_status":"public","planning_zone_th":"เขตสีส้ม","registered_floor_count":3,"registered_unit_count":2,"registered_unit_numbers":["137/5","137/6"],"separate_staircases":true,"ground_floors_interconnected":true,"upper_floors_not_interconnected":[2,3],"source_bedroom_count":4,"source_bathroom_count":6,"proposed_planning_road_alignment_th":"ฌ14","within_proposed_road_alignment_reported":true,"source_enquiry_no_expropriation_project_reported":true,"current_road_project_status_requires_verification":true,"utilities_available_reported":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","source_status_at_import":"direct_purchase","status_checked_on":"2026-09-11","source_photo_dates":["2025-01-20","2026-05-13"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//12.950127,100.981171","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 23189 identifies SAM as direct-sale contact for SL0148, two three-storey shophouses in Boon Raksa, Pong.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส SL0148 ราคา 6,721,000 บาท', 'SAM direct purchase SL0148, THB 6,721,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'building_connections', 'การเชื่อมระหว่างคูหา', 'Connections between units', 'บันไดแยกแต่ละคูหา ชั้นล่างทะลุถึงกัน ชั้น 2–3 ไม่เชื่อม', 'Separate staircases; ground floors connected; floors 2–3 not connected', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'proposed_road_alignment', 'แนวถนนเสนอแนะ ฌ14', 'Proposed road alignment ฌ14', 'SAM ระบุอยู่ในแนวถนน ฌ14 และเคยสอบถามว่าไม่มีโครงการเวนคืน ต้องตรวจสถานะล่าสุด', 'SAM reports alignment ฌ14 and an enquiry stating no expropriation project; verify current status', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพปัจจุบัน', 'Current inspection', 'ภาพล่าสุด 13 พฤษภาคม 2569 ต้องตรวจสภาพและยืนยันพื้นที่ใช้สอย', 'Latest photos 13 May 2026; inspect current condition and confirm usable area', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าอาคารพาณิชย์ 2 คูหา', 'ด้านหน้าอาคารพาณิชย์ 2 คูหา', 'https://npa.sam.or.th/site/images/npa/23189/20260410102457_SL0148P1_69.jpg', '/listing-media/sam/sl0148/01.webp', 'image/webp', 26924, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารและถนนชัยพรวิถี', 'อาคารและถนนชัยพรวิถี', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P3_69.jpg', '/listing-media/sam/sl0148/02.webp', 'image/webp', 127084, 1100, 740, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านหน้าอาคารภาพล่าสุด', 'ด้านหน้าอาคารภาพล่าสุด', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P4_69.jpg', '/listing-media/sam/sl0148/03.webp', 'image/webp', 73004, 540, 720, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นล่าง', 'โถงชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P5_69.jpg', '/listing-media/sam/sl0148/04.webp', 'image/webp', 26704, 720, 540, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชั้นล่างและส่วนกั้นห้อง', 'ชั้นล่างและส่วนกั้นห้อง', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P6_69.jpg', '/listing-media/sam/sl0148/05.webp', 'image/webp', 25628, 720, 540, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดและทางเดิน', 'บันไดและทางเดิน', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P7_69.jpg', '/listing-media/sam/sl0148/06.webp', 'image/webp', 26298, 720, 540, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดอีกคูหา', 'บันไดอีกคูหา', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P8_69.jpg', '/listing-media/sam/sl0148/07.webp', 'image/webp', 32628, 720, 540, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ระเบียงหลังอาคาร', 'พื้นที่ระเบียงหลังอาคาร', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P9_69.jpg', '/listing-media/sam/sl0148/08.webp', 'image/webp', 57906, 720, 540, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ระเบียงและส่วนซักล้าง', 'ระเบียงและส่วนซักล้าง', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P10_69.jpg', '/listing-media/sam/sl0148/09.webp', 'image/webp', 80158, 720, 540, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและบันไดชั้นบน', 'โถงและบันไดชั้นบน', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P11_69.jpg', '/listing-media/sam/sl0148/10.webp', 'image/webp', 30880, 720, 540, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมระเบียง', 'ห้องริมระเบียง', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P13_69.jpg', '/listing-media/sam/sl0148/11.webp', 'image/webp', 29720, 720, 540, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ชั้นบน', 'พื้นที่ชั้นบน', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P14_69.jpg', '/listing-media/sam/sl0148/12.webp', 'image/webp', 36104, 720, 540, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องชั้นบนอีกคูหา', 'ห้องชั้นบนอีกคูหา', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P15_69.jpg', '/listing-media/sam/sl0148/13.webp', 'image/webp', 33272, 720, 540, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในด้านหลัง', 'พื้นที่ภายในด้านหลัง', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P17_69.jpg', '/listing-media/sam/sl0148/14.webp', 'image/webp', 31758, 720, 540, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำ', 'ห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/23189/SL0148P16_69.jpg', '/listing-media/sam/sl0148/15.webp', 'image/webp', 34142, 540, 720, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังชั้นอาคาร 2 คูหา', 'ผังชั้นอาคาร 2 คูหา', 'https://npa.sam.or.th/site/images/npa/23189/SL0148C3_69.jpg', '/listing-media/sam/sl0148/16.webp', 'image/webp', 54986, 785, 600, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด 183058', 'ผังแปลงโฉนด 183058', 'https://npa.sam.or.th/site/images/npa/23189/20260410102457_SL0148C1_69.jpg', '/listing-media/sam/sl0148/17.webp', 'image/webp', 10366, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งอาคาร', 'ผังตำแหน่งอาคาร', 'https://npa.sam.or.th/site/images/npa/23189/20260410102457_SL0148C2_69.jpg', '/listing-media/sam/sl0148/18.webp', 'image/webp', 14994, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/23189/20260410102457_SL0148M_69.jpg', '/listing-media/sam/sl0148/19.webp', 'image/webp', 41844, 785, 600, 190, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=23189&keyref=6007684', 'SL0148', now(), 'Official source captured 2026-09-11. THB 6,721,000; 44 sq.wah; two three-storey units, four bedrooms/six bathrooms. Separate stairs, connected ground floors only. Proposed road alignment ฌ14 and source enquiry reporting no expropriation project both disclosed with current verification required. Nineteen source photos, dates 2025-01-20 and 2026-05-13. Navigation/map agree. All-status duplicate search no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Two 3-Storey Boon Raksa Shophouses, Pong, THB 6.721M', 'Two three-storey shophouse units numbered 137/5-6, Boon Raksa project, Chaiyaphon Withi Road (Highway 3240), Pong, Bang Lamung, Chon Buri. One Chanote title, 183058, covers 44 sq.wah (176 sq.m.). SAM lists four bedrooms and six bathrooms in total. Announced sale price THB 6,721,000; asset SL0148.

Rectangular plot with approximately eight metres of western frontage and 22 metres depth. Registered acquisition describes three-storey row buildings numbered 137/5-6. Each unit has its own staircase. Ground floors are interconnected through the party wall; second and third floors are not connected. Verify alterations, plans and transfer inventory against actual condition.

Chaiyaphon Withi Road is public, with approximately 12 metres of asphalt carriageway and a 30-metre right of way. SAM reports orange zoning, residential/commercial surroundings and available utilities.

Material road-planning disclosure: SAM reports that the property lies within recommended planning-road alignment ฌ14. It also reports an enquiry to the Department of Highways'' Khao Mai Kaeo section stating no expropriation project for the road frontage at the time of that information. This is not an assurance against future expropriation or alignment changes. Verify current alignment and project status with the relevant authority before offering.

Source-listed nearby places are Wat Nop Thong Di Si Phruettharam (Wat Pong), Pong Subdistrict Health Promoting Hospital and Pong Municipality Office. From Rayong toward Pattaya on Highway 36, pass Splashdown Waterpark, SUSCO and PTT Pong, then turn left onto Highway 3240 for approximately 880 metres; the property is on the left.

Some exterior photos display 20 January 2025; the latest exterior/interior set displays 13 May 2026. Nineteen images include floors, stairs, bathrooms, balconies, floor plans, plot plans and map. Inspect current floors, walls, ceilings, power, plumbing and drainage.

SAM showed direct purchase and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting SL0148, to confirm availability, price, viewing, road alignment, buildings and terms.

Navigation and map agree on 12.950127, 100.981171. Total usable area, parking capacity, age and occupancy are not published; confirm with SAM.', '137/5-6, Boon Raksa, Chaiyaphon Withi Road', 'Approx. 880 metres from Highway 36', 'Chaiyaphon Withi Road (Highway 3240)', 'Pong', 'Bang Lamung', 'Chon Buri', 'SAM Boon Raksa Shophouses, Pong — THB 6.721M', 'SAM SL0148: two three-storey shophouses, 44 sq.wah, 4 bedrooms, 6 bathrooms, Pong. THB 6,721,000; proposed road alignment disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: two 3-storey boon raksa shophouses, pong, thb 6.721m two three-storey shophouse units numbered 137/5-6, boon raksa project, chaiyaphon withi road (highway 3240), pong, bang lamung, chon buri. one chanote title, 183058, covers 44 sq.wah (176 sq.m.). sam lists four bedrooms and six bathrooms in total. announced sale price thb 6,721,000; asset sl0148.

rectangular plot with approximately eight metres of western frontage and 22 metres depth. registered acquisition describes three-storey row buildings numbered 137/5-6. each unit has its own staircase. ground floors are interconnected through the party wall; second and third floors are not connected. verify alterations, plans and transfer inventory against actual condition.

chaiyaphon withi road is public, with approximately 12 metres of asphalt carriageway and a 30-metre right of way. sam reports orange zoning, residential/commercial surroundings and available utilities.

material road-planning disclosure: sam reports that the property lies within recommended planning-road alignment ฌ14. it also reports an enquiry to the department of highways'' khao mai kaeo section stating no expropriation project for the road frontage at the time of that information. this is not an assurance against future expropriation or alignment changes. verify current alignment and project status with the relevant authority before offering.

source-listed nearby places are wat nop thong di si phruettharam (wat pong), pong subdistrict health promoting hospital and pong municipality office. from rayong toward pattaya on highway 36, pass splashdown waterpark, susco and ptt pong, then turn left onto highway 3240 for approximately 880 metres; the property is on the left.

some exterior photos display 20 january 2025; the latest exterior/interior set displays 13 may 2026. nineteen images include floors, stairs, bathrooms, balconies, floor plans, plot plans and map. inspect current floors, walls, ceilings, power, plumbing and drainage.

sam showed direct purchase and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting sl0148, to confirm availability, price, viewing, road alignment, buildings and terms.

navigation and map agree on 12.950127, 100.981171. total usable area, parking capacity, age and occupancy are not published; confirm with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=23189&keyref=6007684', 'Official SAM page 23189 identifies SAM as asset holder and direct-sale contact for SL0148.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'b93cf968-17b5-4b28-a584-d8d98ea50148', '{"reference_code":"SL0148","source_page_id":23189,"source_image_count":19,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
