BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-22802'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='BL0048' OR source_url ~ '[?&]id=22802(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='f874438f-980b-47bd-8211-1b4e88d00048' OR slug='sam-direct-sale-factory-huai-khwang-mueang-chonburi-bl0048' OR description ILIKE '%BL0048%' OR (abs(latitude-13.26299)<0.0001 AND abs(longitude-100.954485)<0.0001 AND abs(land_area_sqm-1624)<1)) THEN RAISE NOTICE 'SAM BL0048 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('f874438f-980b-47bd-8211-1b4e88d00048', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'factory', 'business', 'sale', 'whole_property', '21/35', 'ขายตรง SAM โรงงาน/โกดัง ถนนห้วยขวาง ชลบุรี ที่ดิน 1 ไร่ 6 ตร.ว.', 'โรงงานชั้นเดียว เลขที่ 21/35 ถนนห้วยขวาง ตำบลเหมือง อำเภอเมืองชลบุรี จังหวัดชลบุรี บนที่ดิน 2 แปลงติดต่อกัน โฉนดเลขที่ 80176 และ 184671 จำนวน 2 ฉบับ เนื้อที่ 1 ไร่ 6 ตร.ว. หรือ 406 ตร.ว. (1,624 ตร.ม.) ราคาประกาศขายจาก SAM 6,535,000 บาท รหัสทรัพย์ BL0048

ที่ดินรูปสามเหลี่ยม ด้านทิศใต้ติดถนนกว้างประมาณ 42 เมตร ลึกสุดตามแนวติดทางรถไฟสายฉะเชิงเทรา–สัตหีบประมาณ 113 เมตร ถนนหน้าทรัพย์คือถนนห้วยขวาง เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 8 เมตร ควรตรวจแนวเขตด้านทางรถไฟและพื้นที่สำหรับรถที่ต้องการใช้งาน

รายการสิ่งปลูกสร้างที่ต้องตรวจสอบ: SAM รับโอนโรงงานเลขที่ 21/35 ห้องน้ำ และโรงจอดรถ 2 รายการ แต่ข้อมูลสำรวจพบโรงงานชั้นเดียว ห้องน้ำชั้นเดียว และโรงจอดรถชั้นเดียวหลังที่ 1 ผังอาคารต้นทางระบุอาคาร ค.ส.ล. ชั้นเดียวและโรงจอดรถหลังที่ 2 ว่ารื้อถอนแล้ว SAM ระบุว่าจะโอนตามรายการสิ่งปลูกสร้างที่จดทะเบียนรับโอนเท่านั้น ผู้ซื้อควรตรวจสภาพจริง รายการโอน และเอกสารรื้อถอน โดยไม่ถือว่าอาคารทุกรายการยังคงอยู่

ต้นทางระบุผังเมืองสีส้ม ย่านที่อยู่อาศัยและอุตสาหกรรม พร้อมสาธารณูปโภคตามข้อมูล SAM สถานที่ใกล้เคียง ได้แก่ ศูนย์ปรับปรุงคุณภาพปฏิกูล ตลาดพรประเสริฐ และโรงเรียนพระอริยะธรรมบาลี การใช้เป็นโรงงานต้องตรวจใบอนุญาตและข้อกำหนดของกิจการที่ต้องการก่อนซื้อ

การเดินทางตาม SAM: ใช้ถนนเลี่ยงเมืองหนองมนจากถนนข้ามหลามมุ่งหน้าถนนสุขุมวิท ผ่านแยกถนนแสนสุขและทางเข้าสำนักเรียนพระอริยธรรมบาลี เลี้ยวซ้ายถนนห้วยขวางประมาณ 1.5 กิโลเมตร ทรัพย์อยู่ด้านซ้ายมือ

ภาพอาคารและภายในแสดงวันที่ 8 กุมภาพันธ์ 2569 รวม 17 ภาพ มีภาพโรงงาน ภายใน โรงจอดรถ ห้องประกอบ พื้นที่รอบแปลง ผังอาคารและแผนที่ ภาพห้องประกอบมีแผ่นวัสดุฝ้าหลุดตกบนพื้นและพื้นที่ภายนอกมีวัชพืช ควรตรวจหลังคา ฝ้า โครงสร้าง ระบบไฟฟ้าและสภาพปัจจุบันก่อนซื้อ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส BL0048 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม รายการอาคารและเงื่อนไขล่าสุด

พิกัด 13.262990, 100.954485 ดึงจากลิงก์นำทาง SAM และตรงกับ Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวมที่ยืนยันแล้ว ความสูงเป็นเมตร น้ำหนักบรรทุกพื้น กำลังไฟฟ้า ใบอนุญาตโรงงาน เครื่องจักรที่รวมขาย ขนาดรถที่รองรับ อายุอาคาร หรือสถานะผู้ครอบครอง จึงต้องยืนยันข้อมูลเหล่านี้กับ SAM', 6535000, false, 1624, 1, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '21/35 ถนนห้วยขวาง', 'เข้าจากถนนเลี่ยงเมืองหนองมนประมาณ 1.5 กิโลเมตร', 'ถนนห้วยขวาง', 13.26299, 100.954485, 'ชลบุรี', 'เมืองชลบุรี', 'เหมือง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-factory-huai-khwang-mueang-chonburi-bl0048') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'industrial') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6535000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'factory', 1, '{"source_property_category":"โรงงาน/โกดัง","official_page_reference_code":"BL0048","source_page_id":22802,"title_document_type":"chanote","title_deed_numbers":["80176","184671"],"title_document_count":2,"land_area_square_wah":406,"land_area_sqm":1624,"plot_shape":"triangular","south_frontage_m_approx":42,"maximum_depth_m_approx":113,"railway_boundary_reported":true,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":8,"front_road_status":"public","planning_zone_th":"เขตสีส้ม","registered_structures":["โรงงาน 21/35","ห้องน้ำ","โรงจอดรถ","โรงจอดรถ"],"surveyed_structures":["โรงงานชั้นเดียว","ห้องน้ำชั้นเดียว","โรงจอดรถชั้นเดียว หลังที่ 1"],"source_plan_demolished_structures":["อาคาร ค.ส.ล. ชั้นเดียว","โรงจอดรถชั้นเดียว หลังที่ 2"],"transfer_registered_structures_only":true,"registered_and_surveyed_inventory_difference":true,"surveyed_floor_count":1,"utilities_available_reported":true,"usable_area_not_confirmed":true,"factory_licence_not_published":true,"machinery_inclusion_not_published":true,"electrical_capacity_not_published":true,"floor_loading_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","status_checked_on":"2026-09-11","source_photo_date":"2026-02-08","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.262990,100.954485","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 22802 identifies SAM as direct-sale contact for BL0048, factory 21/35 on Huai Khwang Road with registered/surveyed structure differences.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส BL0048 ราคา 6,535,000 บาท', 'SAM direct purchase BL0048, THB 6,535,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'transfer_inventory', 'รายการอาคารและการรื้อถอน', 'Building inventory and demolition', 'โอนตามทะเบียนเท่านั้น สำรวจพบโรงจอดรถ 1 หลัง ผังระบุอาคาร ค.ส.ล. และโรงจอดรถหลังที่ 2 รื้อถอนแล้ว', 'Registered inventory governs transfer; one carport surveyed; plan marks RC building and carport 2 demolished', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'railway_boundary', 'แนวเขตติดทางรถไฟ', 'Railway boundary', 'ที่ดินติดทางรถไฟฉะเชิงเทรา–สัตหีบ ต้องตรวจแนวเขตและข้อกำหนดที่เกี่ยวข้อง', 'Land adjoins Chachoengsao–Sattahip railway; verify boundary and applicable requirements', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'factory_verification', 'การใช้งานโรงงาน', 'Factory operation verification', 'ต้องตรวจใบอนุญาต กำลังไฟฟ้า น้ำหนักบรรทุกพื้น และเครื่องจักรที่รวมขาย', 'Verify licence, electrical capacity, floor loading and included machinery', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าโรงงาน', 'ด้านหน้าโรงงาน', 'https://npa.sam.or.th/site/images/npa/22802/20260619135131_BL0048P2_69.jpg', '/listing-media/sam/bl0048/01.webp', 'image/webp', 34886, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โรงงานและถนนห้วยขวาง', 'โรงงานและถนนห้วยขวาง', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P4_69.jpg', '/listing-media/sam/bl0048/02.webp', 'image/webp', 90822, 720, 540, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'มุมแปลงและแนวทางด้านข้าง', 'มุมแปลงและแนวทางด้านข้าง', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P5_69.jpg', '/listing-media/sam/bl0048/03.webp', 'image/webp', 78886, 720, 540, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โรงงานอีกด้าน', 'โรงงานอีกด้าน', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P6_69.jpg', '/listing-media/sam/bl0048/04.webp', 'image/webp', 89670, 720, 540, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารห้องน้ำและพื้นที่รอบข้าง', 'อาคารห้องน้ำและพื้นที่รอบข้าง', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P8_69.jpg', '/listing-media/sam/bl0048/05.webp', 'image/webp', 154928, 720, 540, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โรงจอดรถหลังคาคลุม', 'โรงจอดรถหลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P9_69.jpg', '/listing-media/sam/bl0048/06.webp', 'image/webp', 101308, 720, 540, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในโรงงาน', 'พื้นที่ภายในโรงงาน', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P10_69.jpg', '/listing-media/sam/bl0048/07.webp', 'image/webp', 96790, 720, 540, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในโรงงานมองสู่ทางเข้า', 'ภายในโรงงานมองสู่ทางเข้า', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P11_69.jpg', '/listing-media/sam/bl0048/08.webp', 'image/webp', 99784, 720, 540, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องประกอบและสภาพฝ้า', 'ห้องประกอบและสภาพฝ้า', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P12_69.jpg', '/listing-media/sam/bl0048/09.webp', 'image/webp', 63472, 720, 540, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องประกอบอีกมุม', 'ห้องประกอบอีกมุม', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P13_69.jpg', '/listing-media/sam/bl0048/10.webp', 'image/webp', 69992, 720, 540, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าถนนห้วยขวาง', 'ทางเข้าถนนห้วยขวาง', 'https://npa.sam.or.th/site/images/npa/22802/BL0048P1_68.jpg', '/listing-media/sam/bl0048/11.webp', 'image/webp', 24180, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังโรงงานชั้นเดียว', 'ผังโรงงานชั้นเดียว', 'https://npa.sam.or.th/site/images/npa/22802/BL0048C3_68.jpg', '/listing-media/sam/bl0048/12.webp', 'image/webp', 9470, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังอาคารห้องน้ำ', 'ผังอาคารห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/22802/BL0048C4_68.jpg', '/listing-media/sam/bl0048/13.webp', 'image/webp', 10142, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังโรงจอดรถ', 'ผังโรงจอดรถ', 'https://npa.sam.or.th/site/images/npa/22802/BL0048C5_68.jpg', '/listing-media/sam/bl0048/14.webp', 'image/webp', 4266, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดิน 2 แปลงติดทางรถไฟ', 'ผังที่ดิน 2 แปลงติดทางรถไฟ', 'https://npa.sam.or.th/site/images/npa/22802/20251106154833_BL0048C1_68.jpg', '/listing-media/sam/bl0048/15.webp', 'image/webp', 13774, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังสิ่งปลูกสร้างและรายการรื้อถอน', 'ผังสิ่งปลูกสร้างและรายการรื้อถอน', 'https://npa.sam.or.th/site/images/npa/22802/20251106154833_BL0048C2_68.jpg', '/listing-media/sam/bl0048/16.webp', 'image/webp', 19062, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/22802/20251106154833_BL0048M_68.jpg', '/listing-media/sam/bl0048/17.webp', 'image/webp', 47166, 785, 600, 170, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=22802&keyref=6007684', 'BL0048', now(), 'Official source captured 2026-09-11. THB 6,535,000; 406 sq.wah; factory 21/35. Registered/surveyed inventory difference and plan-demolished RC building/carport 2 disclosed. Registered inventory governs transfer. Railway boundary disclosed. Seventeen source images dated 2026-02-08. Navigation/map agree. All-status duplicate search no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Huai Khwang Factory, 406 Sq.Wah, THB 6.535M', 'Single-storey factory numbered 21/35 on Huai Khwang Road, Mueang subdistrict, Mueang Chon Buri district, Chon Buri. Two adjoining Chanote plots, 80176 and 184671, total 406 sq.wah (1,624 sq.m.). SAM announced price THB 6,535,000; asset BL0048.

Triangular land with approximately 42 metres of southern road frontage and maximum depth approximately 113 metres along the Chachoengsao–Sattahip railway boundary. Huai Khwang Road is public, with approximately six metres of concrete carriageway and eight metres right of way. Verify the railway-side boundary and suitability for intended vehicles.

Registered acquisition lists the factory, bathroom and two carports. The survey lists a single-storey factory, bathroom building and carport 1. The source building plan marks a single-storey reinforced-concrete building and carport 2 as demolished. SAM states that transfer follows only its registered acquisition schedule. Verify actual surviving structures, transfer inventory and demolition documents; not all listed structures are represented as still standing.

SAM reports orange zoning, residential/industrial surroundings and available utilities. Nearby places include a sanitation treatment facility, Phon Prasoet Market and Phra Ariya Tham Bali School. Verify licences and requirements for the intended industrial activity.

From Khao Lam Road toward Sukhumvit on Nong Mon bypass, pass Saen Suk intersection and the Buddhist school entrance, turn left into Huai Khwang Road for approximately 1.5 kilometres; the property is on the left.

Building/interior photos display 8 February 2026. Seventeen images include factory, interiors, carport, ancillary rooms, grounds, plans and map. Ancillary rooms show fallen ceiling panels and the grounds have vegetation. Inspect current roof, ceilings, structure and electrical systems.

SAM showed direct purchase and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting BL0048, to confirm availability, price, viewing, buildings and terms.

Navigation and map agree on 13.262990, 100.954485. Confirmed total usable area, height in metres, floor loading, electrical capacity, factory licence, included machinery, vehicle size, age and occupancy are not published; verify with SAM.', '21/35, Huai Khwang Road', 'Approx. 1.5 km from Nong Mon bypass', 'Huai Khwang Road', 'Mueang', 'Mueang Chon Buri', 'Chon Buri', 'SAM Huai Khwang Factory — THB 6.535M', 'SAM BL0048: factory on 406 sq.wah, Huai Khwang Road, Chon Buri, THB 6,535,000. Railway boundary and building inventory differences disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: huai khwang factory, 406 sq.wah, thb 6.535m single-storey factory numbered 21/35 on huai khwang road, mueang subdistrict, mueang chon buri district, chon buri. two adjoining chanote plots, 80176 and 184671, total 406 sq.wah (1,624 sq.m.). sam announced price thb 6,535,000; asset bl0048.

triangular land with approximately 42 metres of southern road frontage and maximum depth approximately 113 metres along the chachoengsao–sattahip railway boundary. huai khwang road is public, with approximately six metres of concrete carriageway and eight metres right of way. verify the railway-side boundary and suitability for intended vehicles.

registered acquisition lists the factory, bathroom and two carports. the survey lists a single-storey factory, bathroom building and carport 1. the source building plan marks a single-storey reinforced-concrete building and carport 2 as demolished. sam states that transfer follows only its registered acquisition schedule. verify actual surviving structures, transfer inventory and demolition documents; not all listed structures are represented as still standing.

sam reports orange zoning, residential/industrial surroundings and available utilities. nearby places include a sanitation treatment facility, phon prasoet market and phra ariya tham bali school. verify licences and requirements for the intended industrial activity.

from khao lam road toward sukhumvit on nong mon bypass, pass saen suk intersection and the buddhist school entrance, turn left into huai khwang road for approximately 1.5 kilometres; the property is on the left.

building/interior photos display 8 february 2026. seventeen images include factory, interiors, carport, ancillary rooms, grounds, plans and map. ancillary rooms show fallen ceiling panels and the grounds have vegetation. inspect current roof, ceilings, structure and electrical systems.

sam showed direct purchase and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting bl0048, to confirm availability, price, viewing, buildings and terms.

navigation and map agree on 13.262990, 100.954485. confirmed total usable area, height in metres, floor loading, electrical capacity, factory licence, included machinery, vehicle size, age and occupancy are not published; verify with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=22802&keyref=6007684', 'Official SAM page 22802 identifies SAM as asset holder and direct-sale contact for BL0048.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'f874438f-980b-47bd-8211-1b4e88d00048', '{"reference_code":"BL0048","source_page_id":22802,"source_image_count":17,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
