BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-13657'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='8Z6128' OR source_url ~ '[?&]id=13657(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='c5190154-ad9a-46e2-9001-adbfa2426128' OR slug='sam-direct-sale-corner-house-the-boulevard-si-racha-8z6128' OR description ILIKE '%8Z6128%' OR (abs(latitude-13.14525)<0.0001 AND abs(longitude-100.96091)<0.0001 AND abs(land_area_sqm-395.2)<1)) THEN RAISE NOTICE 'SAM 8Z6128 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('c5190154-ad9a-46e2-9001-adbfa2426128', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'detached_house', 'residence', 'sale', 'whole_property', 'เดอะบูเลอวาร์ด ศรีราชา', '188/100', 'ขายตรง SAM บ้านเดี่ยว 2 ชั้นหลังมุม เดอะบูเลอวาร์ด ศรีราชา 98.8 ตร.ว.', 'บ้านเดี่ยว 2 ชั้นหลังมุมต้นซอย เลขที่ 188/100 โครงการเดอะบูเลอวาร์ด ศรีราชา ถนนศรีราชา–หนองยายบู่ ตำบลหนองขาม อำเภอศรีราชา จังหวัดชลบุรี โฉนดเลขที่ 148015 จำนวน 1 ฉบับ เนื้อที่ 98.8 ตร.ว. (395.2 ตร.ม.) ต้นทางระบุ 4 ห้องนอน 3 ห้องน้ำ ราคาประกาศขายจาก SAM 6,492,000 บาท รหัสทรัพย์ 8Z6128

ที่ดินรูปหลายเหลี่ยม ติดถนน 2 ด้าน ด้านทิศตะวันออกกว้างประมาณ 23 เมตร และด้านทิศใต้กว้างประมาณ 27 เมตร รายการรับโอนกรรมสิทธิ์ระบุบ้านเดี่ยว 2 ชั้น เลขที่ 188/100 ถนนภายในโครงการเป็นทางในโครงการจัดสรรที่ได้รับอนุญาตแล้ว ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 8 เมตร ต้นทางระบุเขตผังเมืองสีส้ม

ค่าส่วนกลางตามข้อมูล SAM ณ วันที่ 7 พฤษภาคม 2567 ประมาณ 18,000 บาทต่อปี เป็นข้อมูลที่มีวันที่กำกับ ผู้ซื้อควรยืนยันอัตราปัจจุบัน ยอดค้าง และผู้รับผิดชอบค่าใช้จ่ายในเงื่อนไขการขายกับ SAM และนิติบุคคลก่อนตัดสินใจ

ทรัพย์อยู่ในย่านที่อยู่อาศัย ภายในโครงการขนาดใหญ่ สถานที่ใกล้เคียงตาม SAM ได้แก่ วัดเครือศรัทธาธรรมและตลาดศุภฤกษ์ การเดินทางใช้ถนนศรีราชา–หนองยายบู่ จากระยองมุ่งหน้าถนนสุขุมวิท ถึงแยกถนนกรุงเทพ–พัทยา ตรงต่อไปประมาณ 2.5 กิโลเมตร เลี้ยวซ้ายเข้าเดอะบูเลอวาร์ด ศรีราชาประมาณ 300 เมตร แล้วเลี้ยวขวาเข้าซอยอีกประมาณ 200 เมตร ทรัพย์อยู่ด้านขวามือ

ภาพอาคารและภายในแสดงวันที่ 12 ตุลาคม 2567 รวม 29 ภาพ มีภาพบ้านมุมถนน ลานหลังคาคลุม โถง ห้องภายใน ครัว บันได ห้องน้ำ ผังแปลงและแผนที่ ควรตรวจสภาพบ้าน ระบบไฟฟ้า ประปา หลังคา และรายการที่รวมในการโอนปัจจุบัน

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 8Z6128 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชม ค่าส่วนกลางและเงื่อนไขล่าสุด

พิกัด 13.145250, 100.960910 ดึงจากลิงก์นำทาง SAM และตรงกับ Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงต้องยืนยันกับ SAM', 6492000, false, 395.2, 2, 4, 3, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '188/100 เดอะบูเลอวาร์ด ศรีราชา', 'บ้านหลังมุมต้นซอยภายในโครงการ', 'ถนนศรีราชา–หนองยายบู่', 13.14525, 100.96091, 'ชลบุรี', 'ศรีราชา', 'หนองขาม', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-corner-house-the-boulevard-si-racha-8z6128') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6492000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'detached_house', 1, '{"source_property_category":"บ้านเดี่ยว","official_page_reference_code":"8Z6128","source_page_id":13657,"project_name":"เดอะบูเลอวาร์ด ศรีราชา","title_document_type":"chanote","title_deed_number":"148015","title_document_count":1,"land_area_square_wah":98.8,"land_area_sqm":395.2,"plot_shape":"polygonal","corner_plot":true,"road_frontage_sides":2,"east_frontage_m_approx":23,"south_frontage_m_approx":27,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":8,"front_road_status":"approved_subdivision_road","planning_zone_th":"เขตสีส้ม","registered_floor_count":2,"source_bedroom_count":4,"source_bathroom_count":3,"common_fee_thb_per_year_approx":18000,"common_fee_information_date":"2024-05-07","current_common_fee_and_arrears_not_confirmed":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","status_checked_on":"2026-09-11","source_photo_date":"2024-10-12","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.14525,100.96091","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 13657 identifies SAM as direct-sale contact for 8Z6128, two-storey corner house 188/100 in The Boulevard Si Racha.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 8Z6128 ราคา 6,492,000 บาท', 'SAM direct purchase 8Z6128, THB 6,492,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'dated_common_fee', 'ค่าส่วนกลางตามวันที่ต้นทาง', 'Dated common charges', 'ประมาณ 18,000 บาท/ปี ณ 7 พฤษภาคม 2567 ต้องยืนยันอัตราและยอดค้างปัจจุบัน', 'Approx. THB 18,000/year as of 7 May 2024; verify current rate and arrears', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'corner_plot', 'บ้านหลังมุมติดถนนสองด้าน', 'Corner house on two roads', 'ด้านตะวันออกประมาณ 23 ม. ด้านใต้ประมาณ 27 ม. ถนนภายในโครงการจัดสรรที่ได้รับอนุญาต', 'Approx. 23 m east and 27 m south; roads in approved subdivision', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพปัจจุบัน', 'Current inspection', 'ภาพวันที่ 12 ตุลาคม 2567 ต้องตรวจสภาพและยืนยันรายการที่โอน', 'Photos 12 October 2024; inspect current condition and transfer inventory', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าบ้านเดี่ยวสองชั้น', 'ด้านหน้าบ้านเดี่ยวสองชั้น', 'https://npa.sam.or.th/site/images/npa/13657/20250113160002_8Z6128P2_67.jpg', '/listing-media/sam/8z6128/01.webp', 'image/webp', 28502, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บ้านหลังมุมและถนนสองด้าน', 'บ้านหลังมุมและถนนสองด้าน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P3_67.jpg', '/listing-media/sam/8z6128/02.webp', 'image/webp', 30592, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานหลังคาคลุมหน้าบ้าน', 'ลานหลังคาคลุมหน้าบ้าน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P4_67.jpg', '/listing-media/sam/8z6128/03.webp', 'image/webp', 22720, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ประตูทางเข้าบ้าน', 'ประตูทางเข้าบ้าน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P5_67.jpg', '/listing-media/sam/8z6128/04.webp', 'image/webp', 21804, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงพักผ่อน', 'โถงพักผ่อน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P6_67.jpg', '/listing-media/sam/8z6128/05.webp', 'image/webp', 13830, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในอีกมุม', 'โถงภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P7_67.jpg', '/listing-media/sam/8z6128/06.webp', 'image/webp', 14450, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและทางขึ้นบันได', 'โถงและทางขึ้นบันได', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P8_67.jpg', '/listing-media/sam/8z6128/07.webp', 'image/webp', 12866, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องชั้นล่าง', 'ห้องชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P9_67.jpg', '/listing-media/sam/8z6128/08.webp', 'image/webp', 15126, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำชั้นล่าง', 'ห้องน้ำชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P10_67.jpg', '/listing-media/sam/8z6128/09.webp', 'image/webp', 12936, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดขึ้นชั้นบน', 'บันไดขึ้นชั้นบน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P11_67.jpg', '/listing-media/sam/8z6128/10.webp', 'image/webp', 12866, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นบน', 'โถงชั้นบน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P12_67.jpg', '/listing-media/sam/8z6128/11.webp', 'image/webp', 12430, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินชั้นบน', 'ทางเดินชั้นบน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P13_67.jpg', '/listing-media/sam/8z6128/12.webp', 'image/webp', 14142, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องชั้นบน', 'ห้องชั้นบน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P14_67.jpg', '/listing-media/sam/8z6128/13.webp', 'image/webp', 15412, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมระเบียง', 'ห้องริมระเบียง', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P15_67.jpg', '/listing-media/sam/8z6128/14.webp', 'image/webp', 14418, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำพร้อมอ่างอาบน้ำ', 'ห้องน้ำพร้อมอ่างอาบน้ำ', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P16_67.jpg', '/listing-media/sam/8z6128/15.webp', 'image/webp', 18528, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำอีกมุม', 'ห้องน้ำอีกมุม', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P17_67.jpg', '/listing-media/sam/8z6128/16.webp', 'image/webp', 15026, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมหน้าต่าง', 'ห้องริมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P18_67.jpg', '/listing-media/sam/8z6128/17.webp', 'image/webp', 16474, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'มุมห้องและหน้าต่าง', 'มุมห้องและหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P19_67.jpg', '/listing-media/sam/8z6128/18.webp', 'image/webp', 19506, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอีกด้าน', 'ห้องภายในอีกด้าน', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P20_67.jpg', '/listing-media/sam/8z6128/19.webp', 'image/webp', 18722, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องชั้นบนอีกห้อง', 'ห้องชั้นบนอีกห้อง', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P21_67.jpg', '/listing-media/sam/8z6128/20.webp', 'image/webp', 13414, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและประตู', 'ห้องและประตู', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P22_67.jpg', '/listing-media/sam/8z6128/21.webp', 'image/webp', 12182, 450, 450, 210, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมระเบียงอีกมุม', 'ห้องริมระเบียงอีกมุม', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P23_67.jpg', '/listing-media/sam/8z6128/22.webp', 'image/webp', 22090, 450, 450, 220, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชานบันได', 'ชานบันได', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P24_67.jpg', '/listing-media/sam/8z6128/23.webp', 'image/webp', 16248, 450, 450, 230, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในชั้นล่าง', 'ห้องภายในชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P26_67.jpg', '/listing-media/sam/8z6128/24.webp', 'image/webp', 10478, 450, 450, 240, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำอีกห้อง', 'ห้องน้ำอีกห้อง', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P27_67.jpg', '/listing-media/sam/8z6128/25.webp', 'image/webp', 16430, 450, 450, 250, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าโครงการ', 'ทางเข้าโครงการ', 'https://npa.sam.or.th/site/images/npa/13657/8Z6128P1_65.jpg', '/listing-media/sam/8z6128/26.webp', 'image/webp', 33526, 450, 449, 260, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงหลังมุม', 'ผังแปลงหลังมุม', 'https://npa.sam.or.th/site/images/npa/13657/20180316093401_8Z6128C1_61.jpg', '/listing-media/sam/8z6128/27.webp', 'image/webp', 14878, 450, 450, 270, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งบ้าน', 'ผังตำแหน่งบ้าน', 'https://npa.sam.or.th/site/images/npa/13657/20180316093401_8Z6128C2_61.jpg', '/listing-media/sam/8z6128/28.webp', 'image/webp', 17014, 450, 450, 280, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/13657/20180316093401_8Z6128M1_61.jpg', '/listing-media/sam/8z6128/29.webp', 'image/webp', 49328, 785, 600, 290, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=13657&keyref=6007684', '8Z6128', now(), 'Official source captured 2026-09-11. THB 6,492,000; 98.8 sq.wah; two-storey corner house 188/100; four bedrooms/three bathrooms. Common charges approx THB 18,000/year dated 2024-05-07, current rate and arrears not confirmed. Twenty-nine source images; building photos 2024-10-12. Navigation/map agree. All-status duplicate search no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Corner House, The Boulevard Si Racha, THB 6.492M', 'Two-storey detached corner house numbered 188/100, The Boulevard Si Racha, Si Racha–Nong Yai Bu Road, Nong Kham, Si Racha, Chon Buri. One Chanote title, 148015, covers 98.8 sq.wah (395.2 sq.m.). SAM lists four bedrooms and three bathrooms. Announced sale price THB 6,492,000; asset 8Z6128.

Polygonal plot with roads on two sides, approximately 23 metres along the east and 27 metres along the south. Registered acquisition describes the two-storey corner house. The internal road is within an approved subdivision, with approximately six metres of concrete carriageway and eight metres right of way. SAM reports orange planning zoning.

SAM reports common-area charges of approximately THB 18,000 per year as of 7 May 2024. This is dated information, not a confirmed current rate. Verify current fees, arrears and cost allocation with SAM and the juristic entity before purchase.

Residential surroundings within a large development. Source-listed nearby places are Wat Khruea Sattha Tham and Supharoek Market. From Rayong toward Sukhumvit on Si Racha–Nong Yai Bu Road, continue 2.5 kilometres after the Bangkok–Pattaya road junction, turn left into The Boulevard for 300 metres, then right into the soi for 200 metres; the property is on the right.

Building/interior photos display 12 October 2024. Twenty-nine images include street-corner views, covered yard, halls, rooms, kitchen, stairs, bathrooms, plot plans and map. Inspect current house condition, power, plumbing, roof and transfer inventory.

SAM showed direct purchase and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 8Z6128, to confirm availability, price, viewing, common charges and terms.

Navigation and map agree on 13.145250, 100.960910. Total usable area, parking capacity, building age and occupancy are not published; confirm with SAM.', '188/100, The Boulevard Si Racha', 'Corner house at the start of the internal soi', 'Si Racha–Nong Yai Bu Road', 'Nong Kham', 'Si Racha', 'Chon Buri', 'SAM The Boulevard Si Racha Corner House — THB 6.492M', 'SAM 8Z6128: two-storey corner house, The Boulevard Si Racha, 98.8 sq.wah, 4 bedrooms, 3 bathrooms. THB 6,492,000; dated common fees disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: corner house, the boulevard si racha, thb 6.492m two-storey detached corner house numbered 188/100, the boulevard si racha, si racha–nong yai bu road, nong kham, si racha, chon buri. one chanote title, 148015, covers 98.8 sq.wah (395.2 sq.m.). sam lists four bedrooms and three bathrooms. announced sale price thb 6,492,000; asset 8z6128.

polygonal plot with roads on two sides, approximately 23 metres along the east and 27 metres along the south. registered acquisition describes the two-storey corner house. the internal road is within an approved subdivision, with approximately six metres of concrete carriageway and eight metres right of way. sam reports orange planning zoning.

sam reports common-area charges of approximately thb 18,000 per year as of 7 may 2024. this is dated information, not a confirmed current rate. verify current fees, arrears and cost allocation with sam and the juristic entity before purchase.

residential surroundings within a large development. source-listed nearby places are wat khruea sattha tham and supharoek market. from rayong toward sukhumvit on si racha–nong yai bu road, continue 2.5 kilometres after the bangkok–pattaya road junction, turn left into the boulevard for 300 metres, then right into the soi for 200 metres; the property is on the right.

building/interior photos display 12 october 2024. twenty-nine images include street-corner views, covered yard, halls, rooms, kitchen, stairs, bathrooms, plot plans and map. inspect current house condition, power, plumbing, roof and transfer inventory.

sam showed direct purchase and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 8z6128, to confirm availability, price, viewing, common charges and terms.

navigation and map agree on 13.145250, 100.960910. total usable area, parking capacity, building age and occupancy are not published; confirm with sam.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=13657&keyref=6007684', 'Official SAM page 13657 identifies SAM as asset holder and direct-sale contact for 8Z6128.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'c5190154-ad9a-46e2-9001-adbfa2426128', '{"reference_code":"8Z6128","source_page_id":13657,"source_image_count":29,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
