BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20515'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A1566' OR source_url ~ '[?&]id=20515(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='bd9e1566-428e-4bcd-884f-191158be2515' OR slug='sam-direct-sale-house-wang-thong-thani-bang-lamung-3a1566' OR description ILIKE '%3A1566%' OR (abs(latitude-13.015962)<0.0001 AND abs(longitude-100.963161)<0.0001 AND abs(land_area_sqm-952)<1)) THEN RAISE NOTICE 'SAM 3A1566 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('bd9e1566-428e-4bcd-884f-191158be2515', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'detached_house', 'residence', 'sale', 'whole_property', 'วังทองธานี', '47/64', 'ขายตรง SAM บ้านเดี่ยว 2 ชั้น วังทองธานี บางละมุง 238 ตร.ว. ติดถนน 3 ด้าน', 'บ้านเดี่ยว 2 ชั้น เลขที่ 47/64 หมู่ 2 หมู่บ้านวังทองธานี ถนนสายโรงโป๊ะ–เขาไม้แก้ว ตำบลตะเคียนเตี้ย อำเภอบางละมุง จังหวัดชลบุรี เนื้อที่ 2 งาน 38 ตร.ว. รวม 238 ตร.ว. (952 ตร.ม.) โฉนดเลขที่ 116753 จำนวน 1 ฉบับ ต้นทางระบุ 3 ห้องนอน 2 ห้องน้ำ ราคาประกาศขาย SAM 6,281,000 บาท รหัสทรัพย์ 3A1566

ที่ดินรูปสี่เหลี่ยมผืนผ้า ติดถนน 3 ด้าน ด้านทิศเหนือและทิศใต้กว้างประมาณ 27 เมตร ด้านทิศตะวันตกประมาณ 34 เมตร บสส. ระบุรายการรับโอนกรรมสิทธิ์เป็นบ้านพักอาศัยตึก 2 ชั้น เลขที่ 47/64 ถนนภายในหมู่บ้านวังทองธานีตามข้อมูล SAM เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 8 เมตร ผังเมืองเขตสีเหลืองตามต้นทาง

ตั้งอยู่ในย่านที่อยู่อาศัย สถานที่ใกล้เคียงตาม SAM ได้แก่ สถานตากอากาศบางละมุง โรงเรียนอนุบาลทนาพร และตลาดโรงโป๊ะ การเดินทางจากศรีราชามุ่งหน้าพัทยาตามถนนสุขุมวิท (ทล.3) เลี้ยวซ้ายเข้าถนนบางละมุง 25 ประมาณ 3.55 กิโลเมตร แล้วเลี้ยวขวาเข้าหมู่บ้านวังทองธานีประมาณ 300 เมตร ทรัพย์อยู่ด้านขวามือ

ภาพจริงจาก SAM รวม 16 ภาพ มีภาพภายนอกบ้าน ลานรอบบ้าน โถง ห้องภายใน บันได ครัว ห้องน้ำ ผังแปลงและแผนที่ ภาพบ้านและภายในแสดงวันที่ 30 มีนาคม 2566 ควรนัดตรวจสภาพปัจจุบันและรายการสิ่งปลูกสร้างที่รวมในการโอนก่อนตัดสินใจ

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A1566 เพื่อยืนยันราคา สถานะพร้อมขาย การนัดชมและเงื่อนไขล่าสุด

พิกัด 13.015962, 100.963161 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์ Google Map ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนที่จอดรถ อายุอาคาร หรือสถานะผู้ครอบครอง จึงต้องยืนยันกับ SAM', 6281000, false, 952, 2, 3, 2, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '47/64 วังทองธานี', 'หมู่ 2 บ้านติดถนนสามด้าน', 'ถนนสายโรงโป๊ะ–เขาไม้แก้ว', 13.015962, 100.963161, 'ชลบุรี', 'บางละมุง', 'ตะเคียนเตี้ย', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-house-wang-thong-thani-bang-lamung-3a1566') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6281000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'detached_house', 1, '{"source_property_category":"บ้านเดี่ยว","official_page_reference_code":"3A1566","source_page_id":20515,"project_name":"วังทองธานี","title_document_type":"chanote","title_deed_number":"116753","title_document_count":1,"land_area_square_wah":238,"land_area_sqm":952,"plot_shape":"rectangular","road_frontage_sides":3,"north_frontage_m_approx":27,"south_frontage_m_approx":27,"west_frontage_m_approx":34,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":8,"front_road_status":"public_according_to_sam","planning_zone_th":"เขตสีเหลือง","registered_floor_count":2,"source_bedroom_count":3,"source_bathroom_count":2,"usable_area_not_published":true,"occupancy_status_not_published":true,"purchase_method":"direct_purchase_from_sam","status_checked_on":"2026-09-11","source_photo_date":"2023-03-30","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.015962,100.963161","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20515 identifies SAM as direct-sale contact for 3A1566, two-storey house 47/64 in Wang Thong Thani.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 3A1566 ราคา 6,281,000 บาท', 'SAM direct purchase 3A1566, THB 6,281,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_buildings', 'สิ่งปลูกสร้างตามรายการรับโอน', 'Registered building', 'บ้านพักอาศัยตึก 2 ชั้น เลขที่ 47/64 โฉนด 116753', 'Two-storey house 47/64; Chanote 116753', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_frontage', 'ถนนและขนาดแปลง', 'Road and plot', 'ติดถนน 3 ด้าน เหนือและใต้ประมาณ 27 ม. ตะวันตกประมาณ 34 ม. ถนนสาธารณประโยชน์ตาม SAM', 'Three road frontages: north/south approx. 27 m, west 34 m; public road according to SAM', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพปัจจุบัน', 'Current inspection', 'ภาพบ้านวันที่ 30 มีนาคม 2566 ควรตรวจสภาพและรายการที่รวมในการโอน', 'House photos dated 30 March 2023; inspect current condition and transfer inventory', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'บ้านเดี่ยวสองชั้นและแนวถนน', 'บ้านเดี่ยวสองชั้นและแนวถนน', 'https://npa.sam.or.th/site/images/npa/20515/20230502151757_P1_66.jpg', '/listing-media/sam/3a1566/01.webp', 'image/webp', 30744, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านหน้าบ้านและลานทางเข้า', 'ด้านหน้าบ้านและลานทางเข้า', 'https://npa.sam.or.th/site/images/npa/20515/P2_66.jpg', '/listing-media/sam/3a1566/02.webp', 'image/webp', 34112, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'เฉลียงข้างบ้าน', 'เฉลียงข้างบ้าน', 'https://npa.sam.or.th/site/images/npa/20515/P3_66.jpg', '/listing-media/sam/3a1566/03.webp', 'image/webp', 25440, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ประตูกระจกทางเข้าบ้าน', 'ประตูกระจกทางเข้าบ้าน', 'https://npa.sam.or.th/site/images/npa/20515/P4_66.jpg', '/listing-media/sam/3a1566/04.webp', 'image/webp', 19526, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในบ้าน', 'โถงภายในบ้าน', 'https://npa.sam.or.th/site/images/npa/20515/P5_66.jpg', '/listing-media/sam/3a1566/05.webp', 'image/webp', 21026, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในชั้นล่าง', 'ห้องภายในชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/20515/P6_66.jpg', '/listing-media/sam/3a1566/06.webp', 'image/webp', 17634, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดภายในบ้าน', 'บันไดภายในบ้าน', 'https://npa.sam.or.th/site/images/npa/20515/P7_66.jpg', '/listing-media/sam/3a1566/07.webp', 'image/webp', 16316, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องผนังสีฟ้า', 'ห้องผนังสีฟ้า', 'https://npa.sam.or.th/site/images/npa/20515/P10_66.jpg', '/listing-media/sam/3a1566/08.webp', 'image/webp', 16324, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมหน้าต่าง', 'ห้องริมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/20515/P12_66.jpg', '/listing-media/sam/3a1566/09.webp', 'image/webp', 17180, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ครัวและเคาน์เตอร์', 'ครัวและเคาน์เตอร์', 'https://npa.sam.or.th/site/images/npa/20515/P8_66.jpg', '/listing-media/sam/3a1566/10.webp', 'image/webp', 21744, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ครัวอีกมุม', 'ครัวอีกมุม', 'https://npa.sam.or.th/site/images/npa/20515/P9_66.jpg', '/listing-media/sam/3a1566/11.webp', 'image/webp', 17458, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำ', 'ห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/20515/P11_66.jpg', '/listing-media/sam/3a1566/12.webp', 'image/webp', 15616, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ถนนสายโรงโป๊ะ–เขาไม้แก้วและทางเข้าหมู่บ้าน', 'ถนนสายโรงโป๊ะ–เขาไม้แก้วและทางเข้าหมู่บ้าน', 'https://npa.sam.or.th/site/images/npa/20515/3A1566P1_65.jpg', '/listing-media/sam/3a1566/13.webp', 'image/webp', 42086, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงติดถนนสามด้าน', 'ผังแปลงติดถนนสามด้าน', 'https://npa.sam.or.th/site/images/npa/20515/20221018092410_3A1566C1_65.jpg', '/listing-media/sam/3a1566/14.webp', 'image/webp', 12150, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งบ้านสองชั้น', 'ผังตำแหน่งบ้านสองชั้น', 'https://npa.sam.or.th/site/images/npa/20515/20221018092410_3A1566C2_65.jpg', '/listing-media/sam/3a1566/15.webp', 'image/webp', 16564, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/20515/20221018092410_3A1566M1_65.jpg', '/listing-media/sam/3a1566/16.webp', 'image/webp', 59316, 785, 600, 160, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20515&keyref=6007684', '3A1566', now(), 'Official source captured 2026-09-11. Direct sale THB 6,281,000; two-storey house 47/64 Wang Thong Thani; 238 sq.wah; three bedrooms/two bathrooms. Roads on three sides; public according to SAM. Sixteen source images; house photos dated 2023-03-30. Navigation/map agree. All-status duplicate search by code, page, title, address and nearby coordinates found no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Wang Thong Thani House, Bang Lamung, THB 6.281M', 'Two-storey detached house numbered 47/64, Moo 2, Wang Thong Thani, Rong Po–Khao Mai Kaeo Road, Takhian Tia, Bang Lamung, Chon Buri. Land totals 238 sq.wah (952 sq.m.), one Chanote title 116753. SAM lists three bedrooms and two bathrooms. Announced direct-sale price THB 6,281,000; asset 3A1566.

Rectangular plot with roads on three sides, approximately 27 metres north and south and 34 metres west. SAM''s registered acquisition describes the two-storey house 47/64. SAM describes the internal village road as public, with approximately six metres of concrete carriageway and eight metres right of way, and reports yellow planning zoning.

Residential surroundings. Source-listed nearby places are Bang Lamung holiday resort, Thanaphon Kindergarten and Rong Po Market. From Si Racha toward Pattaya on Sukhumvit Road (Highway 3), turn left into Bang Lamung 25 for approximately 3.55 kilometres, then right into Wang Thong Thani for 300 metres; the property is on the right.

Sixteen original source images include exterior, yard, halls, rooms, stairs, kitchen, bathroom, plot plans and map. House and interior photos display 30 March 2023. Inspect current condition and confirm the transfer inventory.

SAM showed direct purchase and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline, quoting 3A1566, to confirm availability, price, viewing and terms. Navigation and map agree on 13.015962, 100.963161. Total usable area, parking capacity, building age and occupancy are not published.', '47/64 Moo 2, Wang Thong Thani', 'Road frontage on three sides', 'Rong Po–Khao Mai Kaeo Road', 'Takhian Tia', 'Bang Lamung', 'Chon Buri', 'SAM Direct Sale: Wang Thong Thani House, Bang Lamung, THB 6.281M', 'SAM 3A1566: two-storey detached house, Wang Thong Thani, 238 sq.wah, 3 bedrooms, 2 bathrooms, THB 6,281,000.', 'published', 'ai_assisted', now(), 'sam direct sale: wang thong thani house, bang lamung, thb 6.281m two-storey detached house numbered 47/64, moo 2, wang thong thani, rong po–khao mai kaeo road, takhian tia, bang lamung, chon buri. land totals 238 sq.wah (952 sq.m.), one chanote title 116753. sam lists three bedrooms and two bathrooms. announced direct-sale price thb 6,281,000; asset 3a1566.

rectangular plot with roads on three sides, approximately 27 metres north and south and 34 metres west. sam''s registered acquisition describes the two-storey house 47/64. sam describes the internal village road as public, with approximately six metres of concrete carriageway and eight metres right of way, and reports yellow planning zoning.

residential surroundings. source-listed nearby places are bang lamung holiday resort, thanaphon kindergarten and rong po market. from si racha toward pattaya on sukhumvit road (highway 3), turn left into bang lamung 25 for approximately 3.55 kilometres, then right into wang thong thani for 300 metres; the property is on the right.

sixteen original source images include exterior, yard, halls, rooms, stairs, kitchen, bathroom, plot plans and map. house and interior photos display 30 march 2023. inspect current condition and confirm the transfer inventory.

sam showed direct purchase and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline, quoting 3a1566, to confirm availability, price, viewing and terms. navigation and map agree on 13.015962, 100.963161. total usable area, parking capacity, building age and occupancy are not published.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20515&keyref=6007684', 'Official SAM page 20515 identifies SAM as asset holder and direct-sale contact for 3A1566.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'bd9e1566-428e-4bcd-884f-191158be2515', '{"reference_code":"3A1566","source_page_id":20515,"source_image_count":16,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
