BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-21284'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A2163' OR source_url ~ '[?&]id=21284(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='adab2163-e175-4c55-baa2-841966fab212' OR slug='sam-direct-sale-ten-room-building-bang-sai-3a2163' OR description ILIKE '%3A2163%' OR (abs(latitude-13.378166)<0.0001 AND abs(longitude-100.984942)<0.0001 AND abs(land_area_sqm-770)<1)) THEN RAISE NOTICE 'SAM 3A2163 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, accommodation_model, usage_type, listing_type, listing_scope, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, bedroom_count, bathroom_count, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('adab2163-e175-4c55-baa2-841966fab212', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'apartment', 'standard', 'residence', 'sale', 'whole_property', '197/7', 'ขายตรง SAM อาคารพักอาศัยชั้นเดียว 10 ห้อง บางทราย ชลบุรี 192.5 ตร.ว.', 'ขายอาคารห้องแถวพักอาศัยชั้นเดียว 10 ห้อง พร้อมโรงจอดรถ เลขที่ 197/7 หมู่ 1 ซอยเทศบาลสมมุติ เข้าจากถนนพิพิธ ตำบลบางทราย อำเภอเมืองชลบุรี จังหวัดชลบุรี เนื้อที่ 1 งาน 92.5 ตร.ว. รวม 192.5 ตร.ว. (770 ตร.ม.) โฉนดเลขที่ 48649, 48650 และ 48651 รวม 3 ฉบับ ต้นทางระบุ 10 ห้องนอน 10 ห้องน้ำ ราคาประกาศขาย SAM 6,087,000 บาท รหัสทรัพย์ 3A2163 เป็นการขายทั้งทรัพย์

ข้อควรทราบเรื่องการใช้ที่ดิน: SAM ระบุว่าที่ดินบางส่วนของโฉนด 48651 มีลักษณะเป็นทางเข้าออกของแปลงข้างเคียง กว้างประมาณ 2 เมตร ยาวประมาณ 40 เมตร คิดเป็นเนื้อที่ประมาณ 20.5 ตร.ว. พื้นที่ดังกล่าวรวมอยู่ในเนื้อที่ทั้งหมดข้างต้น ผู้สนใจควรตรวจแนวเขต การใช้ทางและสิทธิที่เกี่ยวข้องก่อนเสนอซื้อ ต้นทางไม่ได้ยืนยันรายละเอียดการจดทะเบียนภาระจำยอม

แปลงรูปหลายเหลี่ยม ด้านทิศตะวันออกติดถนนกว้างประมาณ 15 เมตร ลึกสุดประมาณ 41 เมตร บสส. รับโอนกรรมสิทธิ์สิ่งปลูกสร้างเป็นห้องแถวตึกชั้นเดียวเลขที่ 197/7 และโรงจอดรถไม่มีเลขที่ การสำรวจระบุอาคารห้องแถวชั้นเดียว 10 ห้องและโรงจอดรถ ถนนหน้าทรัพย์คือซอยเทศบาลสมมุติ ตาม SAM เป็นทางสาธารณประโยชน์ ผิวคอนกรีตกว้างประมาณ 6 เมตร เขตทางประมาณ 8 เมตร

SAM ระบุเขตสีส้ม และพื้นที่ประเภทชุมชนเมืองตามข้อบังคับผังเมืองรวมเขตพัฒนาพิเศษภาคตะวันออก ตั้งอยู่ในย่านที่อยู่อาศัยและพาณิชยกรรม ใกล้วัดช่องลม บางทราย ศาลเจ้าพ่อหลักเมืองชลบุรี และศาลจังหวัดชลบุรี การเดินทางใช้ถนนพิพิธจากบางทรายมุ่งหน้าเทศบาลเมืองชลบุรี ถึงวัดช่องลมเลี้ยวซ้ายเข้าซอยเทศบาลสมมุติประมาณ 370 เมตร ทรัพย์อยู่ซ้ายมือ

ภาพจริงจาก SAM รวม 19 ภาพ มีภาพแนวอาคาร ห้องภายใน ห้องน้ำ โรงจอดรถ ผังแปลง ผังทางเข้าออกของแปลงข้างเคียงและแผนที่ ภาพอาคารและภายในแสดงวันที่ 16 มิถุนายน 2568 ควรตรวจสภาพปัจจุบัน รวมถึงหลังคา ฝ้า ระบบไฟฟ้าและประปา ต้นทางไม่เผยแพร่รายได้ค่าเช่า รายชื่อผู้เช่า อัตราเข้าพัก พื้นที่ใช้สอยรวม หรือจำนวนช่องจอดรถ จึงต้องยืนยันกับ SAM

หน้า SAM แสดงสถานะซื้อตรงและราคาข้างต้น ณ วันที่ 11 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A2163 เพื่อยืนยันสถานะพร้อมขาย ราคา การนัดชมและเงื่อนไขล่าสุด พิกัด 13.378166, 100.984942 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์ Google Map', 6087000, false, 770, 1, 10, 10, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '197/7 หมู่ 1 ซอยเทศบาลสมมุติ', 'เข้าจากถนนพิพิธประมาณ 370 เมตร', 'ซอยเทศบาลสมมุติ ถนนพิพิธ', 13.378166, 100.984942, 'ชลบุรี', 'เมืองชลบุรี', 'บางทราย', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-direct-sale-ten-room-building-bang-sai-3a2163') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 6087000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'homes', 'editorial', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'apartment', 1, '{"source_property_category":"อาคารพักอาศัย","official_page_reference_code":"3A2163","source_page_id":21284,"accommodation_model":"standard","title_document_type":"chanote","title_deed_numbers":["48649","48650","48651"],"title_document_count":3,"land_area_square_wah":192.5,"land_area_sqm":770,"registered_floor_count":1,"source_bedroom_count":10,"source_bathroom_count":10,"surveyed_rental_room_count":10,"room_count":10,"registered_structures":["ห้องแถวตึกชั้นเดียว 197/7","โรงจอดรถ ไม่มีเลขที่"],"plot_shape":"polygonal","east_frontage_m_approx":15,"maximum_depth_m_approx":41,"front_road_width_m_approx":6,"front_right_of_way_width_m_approx":8,"front_road_status":"public_according_to_sam","planning_zone_th":"เขตสีส้ม","eec_planning_land_type_th":"ชุมชนเมือง","neighbouring_access_title_deed":"48651","neighbouring_access_width_m_approx":2,"neighbouring_access_length_m_approx":40,"neighbouring_access_area_square_wah_approx":20.5,"neighbouring_access_area_included_in_total":true,"registered_easement_details_not_confirmed":true,"usable_area_not_published":true,"occupancy_status_not_published":true,"rental_income_not_published":true,"rent_roll_not_published":true,"purchase_method":"direct_purchase_from_sam","status_checked_on":"2026-09-11","source_photo_date":"2025-06-16","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.378166,100.984942","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 21284 identifies SAM as direct-sale contact for 3A2163, single-storey ten-room residential building and carport in Bang Sai.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ ซื้อตรง SAM รหัส 3A2163 ราคา 6,087,000 บาท', 'Whole property, SAM direct purchase 3A2163, THB 6,087,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'neighbouring_access', 'ที่ดินบางส่วนเป็นทางของแปลงข้างเคียง', 'Neighbouring access across the property', 'โฉนด 48651 บางส่วนเป็นทางเข้าออกแปลงข้างเคียง ประมาณ 2 × 40 ม. เนื้อที่ประมาณ 20.5 ตร.ว. รวมในพื้นที่ทั้งหมด ต้องตรวจสิทธิและแนวเขต', 'Part of deed 48651 is neighbouring access, approx. 2 × 40 m and 20.5 sq.wah, included in total; verify rights and boundaries', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_buildings', 'สิ่งปลูกสร้างตามรายการรับโอน', 'Registered buildings', 'ห้องแถวตึกชั้นเดียวเลขที่ 197/7 และโรงจอดรถไม่มีเลขที่ สำรวจพบ 10 ห้อง', 'Single-storey row building 197/7 and unnumbered carport; ten rooms surveyed', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_inspection', 'ตรวจสภาพและข้อมูลผู้เช่า', 'Condition and tenancy', 'ภาพวันที่ 16 มิถุนายน 2568 ไม่มีข้อมูลรายได้ค่าเช่าหรือผู้เช่าปัจจุบันจากต้นทาง', 'Photos dated 16 June 2025; rental income and current tenant data not published', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'อาคารพักอาศัยและทางเข้าจากซอย', 'อาคารพักอาศัยและทางเข้าจากซอย', 'https://npa.sam.or.th/site/images/npa/21284/20251121155550_3A2163P2_68.jpg', '/listing-media/sam/3a2163/01.webp', 'image/webp', 24094, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวอาคารห้องแถวชั้นเดียว', 'แนวอาคารห้องแถวชั้นเดียว', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P3_68.jpg', '/listing-media/sam/3a2163/02.webp', 'image/webp', 27658, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ด้านข้างอาคาร', 'พื้นที่ด้านข้างอาคาร', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P4_68.jpg', '/listing-media/sam/3a2163/03.webp', 'image/webp', 34426, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โรงจอดรถหลังคาคลุม', 'โรงจอดรถหลังคาคลุม', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P5_68.jpg', '/listing-media/sam/3a2163/04.webp', 'image/webp', 27128, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอาคาร', 'ห้องภายในอาคาร', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P6_68.jpg', '/listing-media/sam/3a2163/05.webp', 'image/webp', 11778, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในมองสู่ทางเข้า', 'ห้องภายในมองสู่ทางเข้า', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P7_68.jpg', '/listing-media/sam/3a2163/06.webp', 'image/webp', 16534, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องและประตูด้านหลัง', 'ห้องและประตูด้านหลัง', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P9_68.jpg', '/listing-media/sam/3a2163/07.webp', 'image/webp', 13414, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมหน้าต่าง', 'ห้องริมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P10_68.jpg', '/listing-media/sam/3a2163/08.webp', 'image/webp', 14634, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอีกห้อง', 'ห้องภายในอีกห้อง', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P12_68.jpg', '/listing-media/sam/3a2163/09.webp', 'image/webp', 13030, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพห้องและฝ้าเพดาน', 'สภาพห้องและฝ้าเพดาน', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P14_68.jpg', '/listing-media/sam/3a2163/10.webp', 'image/webp', 12244, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอีกมุม', 'ห้องภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P16_68.jpg', '/listing-media/sam/3a2163/11.webp', 'image/webp', 11546, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพร้อมช่องประตู', 'ห้องพร้อมช่องประตู', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P18_68.jpg', '/listing-media/sam/3a2163/12.webp', 'image/webp', 14468, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในมองสู่หน้าต่าง', 'ภายในมองสู่หน้าต่าง', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P19_68.jpg', '/listing-media/sam/3a2163/13.webp', 'image/webp', 16326, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำ', 'ห้องน้ำ', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P15_68.jpg', '/listing-media/sam/3a2163/14.webp', 'image/webp', 13620, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ถนนพิพิธและทางเข้าซอยเทศบาลสมมุติ', 'ถนนพิพิธและทางเข้าซอยเทศบาลสมมุติ', 'https://npa.sam.or.th/site/images/npa/21284/3A2163P1_66.jpg', '/listing-media/sam/3a2163/15.webp', 'image/webp', 31004, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งแปลงโฉนดทั้งสาม', 'ผังตำแหน่งแปลงโฉนดทั้งสาม', 'https://npa.sam.or.th/site/images/npa/21284/3A2163C1_66.jpg', '/listing-media/sam/3a2163/16.webp', 'image/webp', 28058, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังขนาดแปลงที่ดิน', 'ผังขนาดแปลงที่ดิน', 'https://npa.sam.or.th/site/images/npa/21284/20231018100540_3A2163C2_66.jpg', '/listing-media/sam/3a2163/17.webp', 'image/webp', 15474, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังอาคารและส่วนที่เป็นทางเข้าออกแปลงข้างเคียง', 'ผังอาคารและส่วนที่เป็นทางเข้าออกแปลงข้างเคียง', 'https://npa.sam.or.th/site/images/npa/21284/20231018100540_3A2163C3_66.jpg', '/listing-media/sam/3a2163/18.webp', 'image/webp', 27510, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/21284/20231018100540_3A2163M1_66.jpg', '/listing-media/sam/3a2163/19.webp', 'image/webp', 47918, 785, 600, 190, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=21284&keyref=6007684', '3A2163', now(), 'Official source captured 2026-09-11. THB 6,087,000; 192.5 sq.wah; single-storey residential row building 197/7 with ten rooms and carport. Part of deed 48651 used as neighbouring access, approx 20.5 sq.wah included in total. Nineteen source images; building photos dated 2025-06-16. Navigation/map agree. All-status duplicate search by code/page/deeds/address/nearby coordinates found no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'SAM Direct Sale: Ten-Room Residential Building, Bang Sai, THB 6.087M', 'Whole-property sale of a single-storey residential row building surveyed as ten rooms, with a carport, numbered 197/7 Moo 1, Soi Thetsaban Sommut off Phiphit Road, Bang Sai, Mueang Chon Buri, Chon Buri. Three Chanote titles 48649, 48650 and 48651 total 192.5 sq.wah (770 sq.m.). SAM lists ten bedrooms and ten bathrooms. Announced price THB 6,087,000; asset 3A2163.

Material land-use disclosure: SAM reports that part of title 48651 is used as access for neighbouring plots, approximately 2 metres wide and 40 metres long, with a reported area of approximately 20.5 sq.wah. This is included in the total land area. Verify boundaries, access use and associated rights before offering; the source does not confirm registered easement details.

Polygonal plot with approximately 15 metres of eastern road frontage and maximum depth 41 metres. Registered acquisition describes a single-storey row building 197/7 and an unnumbered carport; the survey identifies ten rooms. SAM describes Soi Thetsaban Sommut as public, with approximately six metres concrete carriageway and eight metres right of way. SAM reports orange zoning and urban-community land under the Eastern Economic Corridor comprehensive planning rules.

Residential and commercial surroundings near Wat Chong Lom Bang Sai, Chonburi City Pillar Shrine and Chonburi Provincial Court. Follow Phiphit Road from Bang Sai toward Chonburi Municipality; at Wat Chong Lom turn left into Soi Thetsaban Sommut for approximately 370 metres, property on the left.

Nineteen source images include the building, interiors, bathroom, carport, plot plans, neighbouring access strip and map. Building/interior photos display 16 June 2025. Inspect current roof, ceilings, electrical and plumbing condition. Rental income, tenant roll, occupancy, total usable area and parking capacity are not published.

SAM showed direct purchase and this price on 11 September 2026. Contact 02-686-1888, sales@sam.or.th or LINE @samline quoting 3A2163 to confirm availability, price, viewing and terms. Navigation and map agree on 13.378166, 100.984942.', '197/7 Moo 1, Soi Thetsaban Sommut', 'Approx. 370 metres from Phiphit Road', 'Soi Thetsaban Sommut, Phiphit Road', 'Bang Sai', 'Mueang Chon Buri', 'Chon Buri', 'SAM Direct Sale: Ten-Room Residential Building, Bang Sai, THB 6.087M', 'SAM 3A2163: single-storey ten-room residential building and carport, 192.5 sq.wah, THB 6,087,000. Neighbouring access strip disclosed.', 'published', 'ai_assisted', now(), 'sam direct sale: ten-room residential building, bang sai, thb 6.087m whole-property sale of a single-storey residential row building surveyed as ten rooms, with a carport, numbered 197/7 moo 1, soi thetsaban sommut off phiphit road, bang sai, mueang chon buri, chon buri. three chanote titles 48649, 48650 and 48651 total 192.5 sq.wah (770 sq.m.). sam lists ten bedrooms and ten bathrooms. announced price thb 6,087,000; asset 3a2163.

material land-use disclosure: sam reports that part of title 48651 is used as access for neighbouring plots, approximately 2 metres wide and 40 metres long, with a reported area of approximately 20.5 sq.wah. this is included in the total land area. verify boundaries, access use and associated rights before offering; the source does not confirm registered easement details.

polygonal plot with approximately 15 metres of eastern road frontage and maximum depth 41 metres. registered acquisition describes a single-storey row building 197/7 and an unnumbered carport; the survey identifies ten rooms. sam describes soi thetsaban sommut as public, with approximately six metres concrete carriageway and eight metres right of way. sam reports orange zoning and urban-community land under the eastern economic corridor comprehensive planning rules.

residential and commercial surroundings near wat chong lom bang sai, chonburi city pillar shrine and chonburi provincial court. follow phiphit road from bang sai toward chonburi municipality; at wat chong lom turn left into soi thetsaban sommut for approximately 370 metres, property on the left.

nineteen source images include the building, interiors, bathroom, carport, plot plans, neighbouring access strip and map. building/interior photos display 16 june 2025. inspect current roof, ceilings, electrical and plumbing condition. rental income, tenant roll, occupancy, total usable area and parking capacity are not published.

sam showed direct purchase and this price on 11 september 2026. contact 02-686-1888, sales@sam.or.th or line @samline quoting 3a2163 to confirm availability, price, viewing and terms. navigation and map agree on 13.378166, 100.984942.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=21284&keyref=6007684', 'Official SAM page 21284 identifies SAM as asset holder and direct-sale contact for 3A2163.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'adab2163-e175-4c55-baa2-841966fab212', '{"reference_code":"3A2163","source_page_id":21284,"source_image_count":19,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
