BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20241'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A0424' OR source_url ~ '[?&]id=20241(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='6407ed72-884a-4ac2-b2ca-16643118c424' OR slug='sam-saeng-rung-interpark-hotel-buriram-3a0424' OR description ILIKE '%3A0424%' OR (abs(latitude-14.98964)<0.0001 AND abs(longitude-103.11155)<0.0001 AND abs(land_area_sqm-31588.4)<1)) THEN RAISE NOTICE 'SAM 3A0424 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, custom_unit_number, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('6407ed72-884a-4ac2-b2ca-16643118c424', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'hotel_resort', 'business', 'sale', 'whole_property', 'โรงแรมแสงรุ้ง อินเตอร์ปาร์ค', '38', 'โรงแรมแสงรุ้ง อินเตอร์ปาร์ค บุรีรัมย์ 253 ห้อง · หยุดกิจการ · ขายควบอุปกรณ์', 'รายละเอียดทรัพย์

โรงแรมแสงรุ้ง อินเตอร์ปาร์ค เลขที่ 38 หมู่ 1 ตำบลอิสาณ อำเภอเมืองบุรีรัมย์ จังหวัดบุรีรัมย์ ติดถนนเลี่ยงเมืองบุรีรัมย์ (ทล.288) อาคารโรงแรม 13 ชั้น มีชั้นใต้ดินและชั้นลอย ห้องพักตามข้อมูลสำรวจ 253 ห้อง บนที่ดิน 4 แปลง รวม 19 ไร่ 2 งาน 97.1 ตร.ว. (31,588.4 ตร.ม.) เอกสารสิทธิ์เป็นโฉนดเลขที่ 3331 และ น.ส.3 เลขที่ 207, 281, 282

ราคาและเงื่อนไขซื้อควบ

ราคาที่แสดงในเว็บนี้ 316,811,200 บาท เป็นผลรวมราคาขั้นต่ำ 2 รหัสที่ SAM กำหนดให้ผู้ซื้อคนเดียวกันเสนอซื้อพร้อมกัน ได้แก่ 3A0424 ที่ดินและสิ่งปลูกสร้าง 316,424,000 บาท และ 3A1498 เครื่องจักรพร้อมอุปกรณ์โรงแรม 387,200 บาท โดยราคาอุปกรณ์ยังไม่รวม VAT ซึ่งผู้ซื้อรับผิดชอบทั้งจำนวน ยอดรวมนี้ยังไม่รวม VAT ของอุปกรณ์และค่าใช้จ่ายอื่นตามเงื่อนไข SAM

สถานะและสิ่งปลูกสร้าง

SAM ระบุว่าโรงแรมหยุดดำเนินกิจการ อาคารชำรุดทรุดโทรม ข้อมูลสำรวจระบุอาคารโรงแรมก่อสร้างแล้วเสร็จประมาณ 80% และอาคารสระว่ายน้ำ 2 ชั้นแล้วเสร็จประมาณ 21% จึงไม่ใช่โรงแรมพร้อมเปิดบริการ ห้องพัก 253 ห้องเป็นจำนวนตามสำรวจ ไม่ใช่จำนวนห้องพร้อมขาย ข้อมูลรายได้และใบอนุญาตประกอบกิจการปัจจุบันยังไม่ได้รับการยืนยัน

รายการรับโอนบนโฉนด 3331 เป็นโรงแรม 13 ชั้นเลขที่ 38 บน น.ส.3 เลขที่ 207 เป็นลานจอดรถคอนกรีตและลานซีแพค และบน น.ส.3 เลขที่ 281, 282 เป็นสระว่ายน้ำ พื้นที่ตามสำรวจมีส่วนต้อนรับ ห้องอาหาร ห้องประชุม สำนักงาน พื้นที่บริการและห้องเครื่อง ชั้น 3 มีห้องพัก 29 ห้อง ชั้น 4–11 ชั้นละ 28 ห้อง ชั้น 12 มีแทงค์น้ำ ห้องอเนกประสงค์และดาดฟ้า ชั้น 13 เป็นพื้นที่ห้องอาหาร SKY Lounge ทั้งหมดเป็นลักษณะพื้นที่เดิมตามสำรวจ ไม่ได้รับรองการใช้งานปัจจุบัน

ข้อควรทราบเรื่องแนวเขต

SAM รายงานว่าด้านเหนืออยู่ติดเขตที่ราชพัสดุบริเวณโบราณสถานคูเมืองกำแพงเมือง และบางส่วนเข้าสำรวจไม่ได้เพราะต้นไม้และวัชพืชหนาแน่น เอกสาร น.ส.3 ทั้งสามฉบับไม่มีรูปแปลงและตำแหน่งในระวางที่จะโยงยึดด้วยเอกสารราชการได้ จึงต้องรังวัดสอบเขตเพื่อยืนยันแนวเขตว่าติดคลองสาธารณะ ที่ราชพัสดุหรือใกล้โบราณสถานอย่างไร การรังวัดหรือเปลี่ยนเป็นโฉนดอาจทำให้เนื้อที่เพิ่มหรือลดอย่างมีนัยสำคัญ

ตามข้อมูล SAM น.ส.3 เลขที่ 207 ออกวันที่ 29 ธันวาคม 2514 และเลขที่ 281, 282 ออกวันที่ 15 พฤษภาคม 2515 ก่อนประกาศขึ้นทะเบียนโบราณสถานวันที่ 4 มิถุนายน 2523 ข้อมูลวันที่นี้ไม่ได้ยืนยันว่าไม่มีข้อจำกัดหรือข้อพิพาท ควรตรวจแนวเขตและเอกสารกับหน่วยงานที่เกี่ยวข้องก่อนเสนอซื้อ ภาพสวนและสระด้านหลังเป็นภาพบริเวณโดยรอบจาก SAM ไม่ถือเป็นหลักฐานว่าพื้นที่ทั้งหมดอยู่ในรายการขาย

อุปกรณ์ที่ต้องซื้อพร้อมกัน

SAM อ้างอิงรายการรับโอนสังหาริมทรัพย์ 584 รายการตามประกาศเจ้าพนักงานพิทักษ์ทรัพย์วันที่ 23 มิถุนายน 2557 แบ่งเป็นประเภทเสื่อมสภาพ 577 รายการ และประเภทมีสภาพใช้การได้และยังมีราคา 7 รายการตามเอกสารในขณะนั้น ขายตามสภาพและรายการที่ตรวจพบ ผู้ซื้อต้องตรวจนับและตรวจสภาพจริง ไม่ถือเป็นการรับรองว่ายังคงมีครบหรือใช้งานได้ในปัจจุบัน

ทำเลและการเดินทาง

ที่ดินรูปหลายเหลี่ยม หน้ากว้างด้านใต้ประมาณ 140 เมตร ลึกสุดประมาณ 276 เมตร ถนน ทล.288 ตาม SAM เป็นทางสาธารณะ ผิวลาดยางประมาณ 12 เมตร เขตทางประมาณ 60 เมตร ผังเมืองสีชมพูตามต้นทาง ใกล้วัดกลาง ตลาดไนท์บาร์ซาร์และมหาวิทยาลัยราชภัฏบุรีรัมย์ จากวงเวียนอนุสาวรีย์ ร.1 ไปทางอำเภอสตึกประมาณ 750 เมตร ทรัพย์อยู่ซ้ายมือ

ภาพและการติดต่อ

ภาพจริงและผังจาก SAM รวม 29 ภาพ มีภาพต่างช่วงปี 2565–2567 ควรตรวจสภาพปัจจุบัน ราคาและสถานะซื้อตรงตรวจจากหน้า SAM วันที่ 15 กันยายน 2569 ติดต่อ 02-686-1888, sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A0424 และ 3A1498 พิกัด 14.989640, 103.111550 มาจากลิงก์นำทางและตรงกับลิงก์แผนที่ SAM เป็นตำแหน่งอ้างอิง ไม่ใช่แนวเขตที่ดิน', 316811200, false, 31588.4, 13, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '38 หมู่ 1 โรงแรมแสงรุ้ง อินเตอร์ปาร์ค', 'ถนนเลี่ยงเมืองบุรีรัมย์ ทล.288', 'ถนนเลี่ยงเมืองบุรีรัมย์ (ทล.288)', 14.98964, 103.11155, 'บุรีรัมย์', 'เมืองบุรีรัมย์', 'อิสาณ', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-saeng-rung-interpark-hotel-buriram-3a0424') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'hospitality') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 316811200, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'hotel_resort', 1, '{"source_property_category":"โรงแรม/รีสอร์ท","official_page_reference_code":"3A0424","source_page_id":20241,"mandatory_companion_reference_code":"3A1498","same_buyer_simultaneous_offers_required":true,"land_building_minimum_price_thb":316424000,"equipment_minimum_price_thb":387200,"combined_minimum_price_before_equipment_vat_thb":316811200,"equipment_vat_payer":"buyer","title_documents":[{"type":"chanote","number":"3331"},{"type":"nor_sor_3","number":"207"},{"type":"nor_sor_3","number":"281"},{"type":"nor_sor_3","number":"282"}],"title_document_count":4,"land_area_square_wah":7897.1,"land_area_sqm":31588.4,"surveyed_guest_room_count":253,"room_count":253,"registered_floor_count":13,"has_basement":true,"has_mezzanine":true,"operation_status":"ceased_operations_according_to_sam","hotel_completion_percent_approx":80,"pool_building_completion_percent_approx":21,"pool_building_floor_count":2,"condition":"dilapidated","south_frontage_m_approx":140,"maximum_depth_m_approx":276,"road_width_m_approx":12,"right_of_way_width_m_approx":60,"planning_zone_th":"สีชมพู","northern_government_land_and_historic_site_boundary_uncertain":true,"boundary_survey_required":true,"nor_sor_3_area_may_change_materially":true,"rear_surroundings_photos_not_boundary_evidence":true,"equipment_historic_inventory_count":584,"equipment_inventory_reference_date":"2014-06-23","current_equipment_inventory_not_confirmed":true,"current_income_and_operating_licence_unconfirmed":true,"usable_area_not_published":true,"status_checked_on":"2026-09-15","source_photo_years":[2022,2023,2024],"equipment_document_url":"https://npa.sam.or.th/site/attach/npa/20241/3A1498-edit.pdf","floor_plan_document_url":"https://npa.sam.or.th/site/attach/npa/20241/Plan.pdf","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//14.98964,103.11155","map_link_agrees":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20241 identifies SAM as direct-sale contact for 3A0424, closed Saeng Rung Interpark Hotel in Buriram, mandatory combined purchase with equipment 3A1498.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'mandatory_bundle', 'ต้องซื้อสองรหัสพร้อมกัน', 'Mandatory combined purchase', '3A0424 ราคา 316,424,000 บาท + 3A1498 ราคา 387,200 บาท รวม 316,811,200 บาท ผู้ซื้อคนเดียวกันเสนอพร้อมกัน', 'Same buyer must offer for both assets simultaneously; combined minimum THB 316,811,200', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'equipment_vat', 'VAT อุปกรณ์เพิ่มเติม', 'Additional equipment VAT', 'ราคาอุปกรณ์ 387,200 บาทยังไม่รวม VAT ผู้ซื้อชำระทั้งจำนวน', 'Equipment THB 387,200 excludes VAT, fully payable by buyer', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'closed_incomplete', 'หยุดกิจการและก่อสร้างไม่ครบ', 'Closed and incomplete', 'โรงแรมทรุดโทรม สำรวจแล้วเสร็จประมาณ 80% อาคารสระว่ายน้ำประมาณ 21%', 'Closed, dilapidated; hotel approx 80% complete, pool building 21%', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'boundary_survey', 'ต้องรังวัดสอบเขต', 'Boundary survey required', 'น.ส.3 ไม่มีตำแหน่งในระวาง แนวเหนือเกี่ยวข้องกับที่ราชพัสดุ/โบราณสถาน เนื้อที่อาจเปลี่ยนอย่างมีนัยสำคัญ', 'NS3 unplotted; northern government/historic-site boundary uncertain; area may change materially', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'equipment_inventory', 'ตรวจนับสังหาริมทรัพย์', 'Verify equipment inventory', '584 รายการตามเอกสารปี 2557 ขายตามสภาพและรายการที่ตรวจพบ ไม่รับรองจำนวนหรือสภาพปัจจุบัน', 'Historic 2014 inventory of 584; as-is, verify current existence and condition', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'โรงแรมแสงรุ้งและถนนเลี่ยงเมือง', 'โรงแรมแสงรุ้งและถนนเลี่ยงเมือง', 'https://npa.sam.or.th/site/images/npa/20241/20240425165132_P1_67.jpg', '/listing-media/sam/3a0424/01.webp', 'image/webp', 23026, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารโรงแรมด้านข้าง', 'อาคารโรงแรมด้านข้าง', 'https://npa.sam.or.th/site/images/npa/20241/P4_66.jpg', '/listing-media/sam/3a0424/02.webp', 'image/webp', 40220, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารโรงแรมด้านหน้า', 'อาคารโรงแรมด้านหน้า', 'https://npa.sam.or.th/site/images/npa/20241/P1_66.jpg', '/listing-media/sam/3a0424/03.webp', 'image/webp', 38074, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในตามสภาพ', 'โถงภายในตามสภาพ', 'https://npa.sam.or.th/site/images/npa/20241/P92_67.jpg', '/listing-media/sam/3a0424/04.webp', 'image/webp', 26772, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในอาคาร', 'พื้นที่ภายในอาคาร', 'https://npa.sam.or.th/site/images/npa/20241/P93_67.jpg', '/listing-media/sam/3a0424/05.webp', 'image/webp', 24636, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและแนวหน้าต่าง', 'โถงและแนวหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/20241/P95_67.jpg', '/listing-media/sam/3a0424/06.webp', 'image/webp', 21266, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ห้องโถง', 'พื้นที่ห้องโถง', 'https://npa.sam.or.th/site/images/npa/20241/P96_67.jpg', '/listing-media/sam/3a0424/07.webp', 'image/webp', 28700, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในอีกมุม', 'โถงภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/20241/P94_67.jpg', '/listing-media/sam/3a0424/08.webp', 'image/webp', 31062, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในภาพเก่า', 'ห้องภายในภาพเก่า', 'https://npa.sam.or.th/site/images/npa/20241/3A0424P333_65.jpg', '/listing-media/sam/3a0424/09.webp', 'image/webp', 30108, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอีกด้านภาพเก่า', 'ห้องภายในอีกด้านภาพเก่า', 'https://npa.sam.or.th/site/images/npa/20241/3A0424P55_65.jpg', '/listing-media/sam/3a0424/10.webp', 'image/webp', 26574, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมหน้าต่างภาพเก่า', 'ห้องริมหน้าต่างภาพเก่า', 'https://npa.sam.or.th/site/images/npa/20241/3A0424P44_65.jpg', '/listing-media/sam/3a0424/11.webp', 'image/webp', 22828, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ชั้นล่างตามสภาพ', 'พื้นที่ชั้นล่างตามสภาพ', 'https://npa.sam.or.th/site/images/npa/20241/3A0424P77_65.jpg', '/listing-media/sam/3a0424/12.webp', 'image/webp', 30658, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินชำรุด', 'ทางเดินชำรุด', 'https://npa.sam.or.th/site/images/npa/20241/3A0424P99_65.jpg', '/listing-media/sam/3a0424/13.webp', 'image/webp', 18090, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและโครงสร้างภายใน', 'โถงและโครงสร้างภายใน', 'https://npa.sam.or.th/site/images/npa/20241/3A0424P88_65.jpg', '/listing-media/sam/3a0424/14.webp', 'image/webp', 33964, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงสูงภายในโรงแรม', 'โถงสูงภายในโรงแรม', 'https://npa.sam.or.th/site/images/npa/20241/P1_67.jpg', '/listing-media/sam/3a0424/15.webp', 'image/webp', 31970, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 1', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 1', 'https://npa.sam.or.th/site/images/npa/20241/P18_07-67.jpg', '/listing-media/sam/3a0424/16.webp', 'image/webp', 33638, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 2', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 2', 'https://npa.sam.or.th/site/images/npa/20241/P19-07-67.jpg', '/listing-media/sam/3a0424/17.webp', 'image/webp', 46416, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 3', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 3', 'https://npa.sam.or.th/site/images/npa/20241/P20-07-67.jpg', '/listing-media/sam/3a0424/18.webp', 'image/webp', 42052, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 4', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 4', 'https://npa.sam.or.th/site/images/npa/20241/P21-07_67.jpg', '/listing-media/sam/3a0424/19.webp', 'image/webp', 46556, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 5', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 5', 'https://npa.sam.or.th/site/images/npa/20241/P22-07-67.jpg', '/listing-media/sam/3a0424/20.webp', 'image/webp', 51940, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 6', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 6', 'https://npa.sam.or.th/site/images/npa/20241/P23-07-67.jpg', '/listing-media/sam/3a0424/21.webp', 'image/webp', 45538, 450, 450, 210, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 7', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 7', 'https://npa.sam.or.th/site/images/npa/20241/P24-07-67.jpg', '/listing-media/sam/3a0424/22.webp', 'image/webp', 52594, 450, 450, 220, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 8', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 8', 'https://npa.sam.or.th/site/images/npa/20241/P25-07-67.jpg', '/listing-media/sam/3a0424/23.webp', 'image/webp', 47218, 450, 450, 230, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 9', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 9', 'https://npa.sam.or.th/site/images/npa/20241/P26-07-67.jpg', '/listing-media/sam/3a0424/24.webp', 'image/webp', 44846, 450, 450, 240, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 10', 'บริเวณสวน/สระด้านหลังจาก SAM ไม่ใช่หลักฐานแนวเขตขาย ภาพ 10', 'https://npa.sam.or.th/site/images/npa/20241/P27-07_67.jpg', '/listing-media/sam/3a0424/25.webp', 'image/webp', 41318, 450, 450, 250, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารโรงแรมภาพเก่า', 'อาคารโรงแรมภาพเก่า', 'https://npa.sam.or.th/site/images/npa/20241/3A0424P1_65.jpg', '/listing-media/sam/3a0424/26.webp', 'image/webp', 24300, 450, 450, 260, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังเอกสารสิทธิ์ 4 แปลง', 'ผังเอกสารสิทธิ์ 4 แปลง', 'https://npa.sam.or.th/site/images/npa/20241/20250421141307_3A0424C1_67.jpg', '/listing-media/sam/3a0424/27.webp', 'image/webp', 25434, 450, 450, 270, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งโรงแรมและสระว่ายน้ำ', 'ผังตำแหน่งโรงแรมและสระว่ายน้ำ', 'https://npa.sam.or.th/site/images/npa/20241/20221130093032_3A0424C2_65.jpg', '/listing-media/sam/3a0424/28.webp', 'image/webp', 18494, 450, 450, 280, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/20241/20250421143717_3A0424M1n_67.jpg', '/listing-media/sam/3a0424/29.webp', 'image/webp', 50352, 785, 600, 290, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20241&keyref=', '3A0424', now(), 'Official page checked 2026-09-15. Displayed price sums mandatory bundle 3A0424 THB316424000 and 3A1498 THB387200; equipment VAT extra payable by buyer. Closed hotel, 253 surveyed rooms, incomplete/dilapidated. NS3 boundary and material area uncertainty disclosed. Historic 584-item equipment inventory unconfirmed today. 29 authentic images; surrounding park not asserted included. No all-status duplicate matches by both references, page, title/deed and nearby coordinates.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Saeng Rung Interpark Hotel, Buriram — Closed Hotel and Mandatory Equipment Package', 'Saeng Rung Interpark Hotel, 38 Moo 1, Isan, Mueang Buri Ram, Buri Ram, on Buri Ram Bypass Highway 288. A 13-storey hotel with basement and mezzanine; survey reports 253 guest rooms. Four adjoining plots total 19 rai 2 ngan 97.1 sq.wah (31,588.4 sq.m.), comprising Chanote 3331 and Nor Sor 3 certificates 207, 281 and 282.

Mandatory combined purchase: displayed THB 316,811,200 is the sum of SAM''s minimum prices for land/buildings 3A0424 at THB 316,424,000 and machinery/hotel equipment 3A1498 at THB 387,200. The same buyer must submit offers for both together. Equipment VAT is additional and entirely payable by the buyer; other transaction costs are not included.

SAM reports the hotel has ceased operations and is dilapidated. Surveyed construction completion is approximately 80% for the hotel and 21% for the two-storey pool building. The 253 rooms are a survey count, not operational rooms. Current income and operating licences are unconfirmed. Registered structures are the 13-storey hotel on Chanote 3331, paved parking on NS3 207 and a swimming pool on NS3 281/282. Survey describes former reception, restaurants, meeting rooms, offices and service areas. Floor 3 has 29 guest rooms and floors 4–11 have 28 each; floor 12 has water tanks, multipurpose space and roof terrace, floor 13 the former SKY Lounge. These are surveyed layouts, not verified working amenities.

Material boundary uncertainty: SAM reports government land and the historic moat/city-wall area to the north, with dense vegetation preventing full inspection. The three NS3 certificates lack plotted cadastral positions that can be tied to official maps. A boundary survey is required to clarify adjacency to public canal, government land and the historic site. Survey or conversion to Chanote may materially increase or decrease area. SAM dates NS3 207 to 29 December 1971 and NS3 281/282 to 15 May 1972, before historic-site registration on 4 June 1980; this does not establish freedom from restrictions or disputes. Rear park/pond photos show source-documented surroundings, not proof that all depicted land is included.

The equipment acquisition inventory references 584 items in a receiver notice dated 23 June 2014: 577 classified deteriorated and seven classified usable/valuable at that time. Sale is as-is against items actually found; inspect and count current inventory. Historic classification does not guarantee present existence or usability.

Polygonal land, approximately 140 m southern frontage and 276 m maximum depth. Highway 288 is public according to SAM, with 12 m paved carriageway and 60 m right of way; source reports pink zoning. Near Wat Klang, Night Bazaar and Buri Ram Rajabhat University, approximately 750 m from the King Rama I roundabout toward Satuek, on the left.

Twenty-nine authentic source photos/plans include images from 2022–2024. Price/direct-sale status checked 15 September 2026. Contact SAM 02-686-1888, sales@sam.or.th or LINE @samline quoting both 3A0424 and 3A1498. Navigation/map agree on 14.989640, 103.111550; this is a location pin, not a surveyed boundary.', '38 Moo 1, Saeng Rung Interpark Hotel', 'Buri Ram Bypass, Highway 288', 'Buri Ram Bypass (Highway 288)', 'Isan', 'Mueang Buri Ram', 'Buri Ram', 'Saeng Rung Interpark Hotel, Buriram — Closed Hotel and Mandatory Equipment Package', 'Closed 253-room hotel in Buriram; mandatory land/building and equipment purchase THB316811200 before equipment VAT. Boundary survey required.', 'published', 'ai_assisted', now(), 'saeng rung interpark hotel, buriram — closed hotel and mandatory equipment package saeng rung interpark hotel, 38 moo 1, isan, mueang buri ram, buri ram, on buri ram bypass highway 288. a 13-storey hotel with basement and mezzanine; survey reports 253 guest rooms. four adjoining plots total 19 rai 2 ngan 97.1 sq.wah (31,588.4 sq.m.), comprising chanote 3331 and nor sor 3 certificates 207, 281 and 282.

mandatory combined purchase: displayed thb 316,811,200 is the sum of sam''s minimum prices for land/buildings 3a0424 at thb 316,424,000 and machinery/hotel equipment 3a1498 at thb 387,200. the same buyer must submit offers for both together. equipment vat is additional and entirely payable by the buyer; other transaction costs are not included.

sam reports the hotel has ceased operations and is dilapidated. surveyed construction completion is approximately 80% for the hotel and 21% for the two-storey pool building. the 253 rooms are a survey count, not operational rooms. current income and operating licences are unconfirmed. registered structures are the 13-storey hotel on chanote 3331, paved parking on ns3 207 and a swimming pool on ns3 281/282. survey describes former reception, restaurants, meeting rooms, offices and service areas. floor 3 has 29 guest rooms and floors 4–11 have 28 each; floor 12 has water tanks, multipurpose space and roof terrace, floor 13 the former sky lounge. these are surveyed layouts, not verified working amenities.

material boundary uncertainty: sam reports government land and the historic moat/city-wall area to the north, with dense vegetation preventing full inspection. the three ns3 certificates lack plotted cadastral positions that can be tied to official maps. a boundary survey is required to clarify adjacency to public canal, government land and the historic site. survey or conversion to chanote may materially increase or decrease area. sam dates ns3 207 to 29 december 1971 and ns3 281/282 to 15 may 1972, before historic-site registration on 4 june 1980; this does not establish freedom from restrictions or disputes. rear park/pond photos show source-documented surroundings, not proof that all depicted land is included.

the equipment acquisition inventory references 584 items in a receiver notice dated 23 june 2014: 577 classified deteriorated and seven classified usable/valuable at that time. sale is as-is against items actually found; inspect and count current inventory. historic classification does not guarantee present existence or usability.

polygonal land, approximately 140 m southern frontage and 276 m maximum depth. highway 288 is public according to sam, with 12 m paved carriageway and 60 m right of way; source reports pink zoning. near wat klang, night bazaar and buri ram rajabhat university, approximately 750 m from the king rama i roundabout toward satuek, on the left.

twenty-nine authentic source photos/plans include images from 2022–2024. price/direct-sale status checked 15 september 2026. contact sam 02-686-1888, sales@sam.or.th or line @samline quoting both 3a0424 and 3a1498. navigation/map agree on 14.989640, 103.111550; this is a location pin, not a surveyed boundary.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20241&keyref=', 'Official SAM page 20241 identifies SAM as asset holder and direct-sale contact for 3A0424.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '6407ed72-884a-4ac2-b2ca-16643118c424', '{"reference_code":"3A0424","source_page_id":20241,"source_image_count":29,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
