BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-12478'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='1T2834' OR source_url ~ '[?&]id=12478(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='dc5b2834-1349-4a08-911b-41fdee312478' OR slug='sam-bigland-factory-land-113-plots-1t2834' OR (abs(latitude-14.113101)<0.0001 AND abs(longitude-100.61449)<0.0001 AND abs(land_area_sqm-43788)<1)) THEN RAISE NOTICE 'SAM 1T2834 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, custom_project_name, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('dc5b2834-1349-4a08-911b-41fdee312478', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'บิ๊กแลนด์ แฟคตอรี่', 'ที่ดินบิ๊กแลนด์ แฟคตอรี่ คลองหลวง 113 แปลง รวม 27 ไร่ 1 งาน 47 ตร.ว.', 'รายละเอียดทรัพย์

ที่ดินเปล่าภายในโครงการบิ๊กแลนด์ แฟคตอรี่ ตำบลคลองหนึ่ง อำเภอคลองหลวง จังหวัดปทุมธานี เข้าจากถนนพหลโยธิน (ทล.1) ผ่านซอยสามารถ รวม 113 แปลง เนื้อที่ 27 ไร่ 1 งาน 47 ตร.ว. หรือ 10,947 ตร.ว. (43,788 ตร.ม.) ราคาประกาศขาย SAM 244,558,000 บาท รหัส 1T2834 ต้นทางแสดงราคาประมาณ 22,340 บาท/ตร.ว. ใช้ราคารวมเป็นหลัก

ลักษณะที่ดิน

เป็นแปลงย่อยภายในโครงการ ไม่ใช่ที่ดินผืนเดียวติดต่อกันทั้งหมด เนื่องจากมีถนนภายในโครงการคั่นระหว่างแปลง ขนาดแต่ละแปลงตั้งแต่ 23.7 ถึง 980.8 ตร.ว. โฉนดเลขที่ 44969–44972, 85388–85423, 85570–85607, 85699–85732 และ 85773 รวม 113 ฉบับ SAM ระบุผังเมืองสีม่วง ควรตรวจข้อกำหนดการใช้ประโยชน์ให้ตรงกับกิจการที่จะดำเนินการ

ข้อควรทราบเกี่ยวกับทรัพย์

SAM ระบุว่าทรัพย์อยู่ใกล้แนวสายไฟฟ้าแรงสูง 230,000 โวลต์ โดยมีระยะร่นจากจุดศูนย์กลางข้างละ 20.5 เมตร ผู้สนใจควรตรวจแนวสายไฟ พื้นที่ที่ได้รับผลกระทบและข้อกำหนดการใช้ประโยชน์กับหน่วยงานที่เกี่ยวข้องก่อนเสนอซื้อ ข้อมูลนี้ไม่ได้ยืนยันว่าทุกแปลงได้รับผลกระทบเท่ากัน

โฉนดเลขที่ 85773 เนื้อที่ 206.3 ตร.ว. ซึ่งรวมอยู่ในเนื้อที่ทั้งหมด ถูกจัดสรรไว้เป็นสาธารณูปโภคภายในโครงการประเภทโรงเรียนอนุบาล จึงไม่ควรนับเป็นพื้นที่พัฒนาได้โดยไม่มีข้อจำกัด

ทางเข้าซอยสามารถเป็นถนนส่วนบุคคลบนโฉนดเลขที่ 355 โดย SAM ระบุว่าจดภาระจำยอมให้แปลงทรัพย์แล้ว ผิวคอนกรีตกว้างประมาณ 16 เมตร เขตทางประมาณ 30 เมตร ส่วนถนนภายในโครงการมีเขตทางประมาณ 10 และ 14 เมตร แต่ต้นทางระบุว่าไม่มีสภาพทาง ผู้สนใจควรตรวจตำแหน่งแปลง สิทธิในการใช้ทางและสภาพการเข้าถึงแต่ละแปลงก่อนเสนอซื้อ

SAM มีทรัพย์รหัส 1T2428, 1T2831 และ 1T2833 ภายในโครงการเดียวกันด้วย ผังรวมแสดงหลายรหัส ประกาศนี้เฉพาะรหัส 1T2834 ไม่รวมที่ดินของรหัสอื่น

ทำเลและการเดินทาง

อยู่ในย่านที่อยู่อาศัย พาณิชยกรรมและอุตสาหกรรม สถานที่ใกล้เคียงตาม SAM ได้แก่ นิคมอุตสาหกรรมนวนคร โลตัส บิ๊กซีนวนคร โรงพยาบาลนวนคร ตลาดไทและมหาวิทยาลัยธรรมศาสตร์ จากรังสิตมุ่งหน้าวังน้อยบนถนนพหลโยธิน ถึงโชว์รูมโตโยต้า เฟรนส์ชิบช่วง กม.45–46 เลี้ยวซ้ายเข้าซอยสามารถประมาณ 400 เมตร ทรัพย์อยู่ภายในโครงการด้านซ้ายมือ

ภาพและข้อมูลต้นทาง

รูปจริงและผังจาก SAM รวม 9 ภาพหลังตัดรูปซ้ำ ภาพภาคสนามหลายภาพแสดงวันที่ 28 พฤษภาคม 2564 และ 20 เมษายน 2565 ควรตรวจสภาพปัจจุบัน พิกัด 14.113101, 100.614490 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์แผนที่ เป็นจุดอ้างอิงของกลุ่มทรัพย์ ไม่ใช่พิกัดขอบเขตของทุกแปลง

ราคาและสถานะซื้อตรงตรวจจากหน้า SAM วันที่ 15 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 1T2834 เพื่อยืนยันรายการโฉนด ราคา สถานะพร้อมขาย การนัดชมและเงื่อนไขล่าสุด', 244558000, false, 43788, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'โครงการบิ๊กแลนด์ แฟคตอรี่ ซอยสามารถ', 'เข้าจากถนนพหลโยธินประมาณ 400 เมตร', 'ซอยสามารถ ถนนพหลโยธิน (ทล.1)', 14.113101, 100.61449, 'ปทุมธานี', 'คลองหลวง', 'คลองหนึ่ง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-bigland-factory-land-113-plots-1t2834') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'industrial') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 244558000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"ที่ดินเปล่า","official_page_reference_code":"1T2834","source_page_id":12478,"project_name":"บิ๊กแลนด์ แฟคตอรี่","title_document_type":"chanote","title_deed_ranges":["44969-44972","85388-85423","85570-85607","85699-85732","85773"],"title_document_count":113,"plot_count":113,"non_contiguous_plots":true,"land_area_square_wah":10947,"land_area_sqm":43788,"subplot_min_square_wah":23.7,"subplot_max_square_wah":980.8,"source_price_per_square_wah_thb":22340,"planning_zone_th":"สีม่วง","near_high_voltage_line_according_to_sam":true,"transmission_voltage_volts":230000,"source_setback_each_side_from_centre_m":20.5,"affected_parcels_and_restrictions_require_verification":true,"public_utility_kindergarten_deed":"85773","public_utility_kindergarten_area_square_wah":206.3,"utility_plot_included_in_total":true,"private_access_road_deed":"355","registered_access_easement_according_to_sam":true,"access_road_width_m_approx":16,"access_right_of_way_m_approx":30,"internal_right_of_way_widths_m":[10,14],"internal_roads_not_formed_according_to_sam":true,"other_project_assets_not_included":["1T2428","1T2831","1T2833"],"purchase_method":"direct_purchase_from_sam","status_checked_on":"2026-09-15","source_field_photo_dates":["2021-05-28","2022-04-20"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//14.113101,100.614490","map_link_agrees":true,"coordinates_are_group_reference_not_plot_boundaries":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 12478 identifies SAM as direct-sale contact for 1T2834, 113 non-contiguous land plots in Bigland Factory.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'power_line', 'แนวสายไฟฟ้าแรงสูง', 'High-voltage corridor', 'SAM ระบุแนวสายไฟ 230,000 โวลต์ ระยะร่นจากศูนย์กลางข้างละ 20.5 ม. ต้องตรวจแนวและผลกระทบแต่ละแปลง', 'SAM reports 230kV line, 20.5m setback each side from centre; verify corridor and affected plots', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 1T2834 ราคา 244,558,000 บาท', 'SAM direct purchase1T2834 THB244558000', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'utility_plot', 'แปลงสาธารณูปโภคโรงเรียนอนุบาล', 'Kindergarten utility plot', 'โฉนด 85773 จำนวน 206.3 ตร.ว. รวมในพื้นที่ทั้งหมด จัดสรรเป็นสาธารณูปโภคโรงเรียนอนุบาล', 'Deed85773,206.3 sq.wah included in total, allocated kindergarten utility', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'access_condition', 'สิทธิและสภาพทางเข้า', 'Access rights and condition', 'ซอยสามารถโฉนด 355 มีภาระจำยอมตาม SAM ถนนภายในเขตทาง 10/14 ม. ไม่มีสภาพทาง ต้องตรวจแต่ละแปลง', 'SAM reports easement on deed355; internal10/14m rights of way have no formed road; verify each plot', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'non_contiguous', 'แปลงย่อยไม่ติดต่อกัน', 'Non-contiguous plots', '113 แปลงมีถนนคั่น ไม่รวมทรัพย์รหัสอื่นในผังโครงการ', '113 plots separated by roads; other asset references excluded', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'บริเวณที่ดินตามภาพต้นทาง ไม่ระบุวันที่', 'บริเวณที่ดินตามภาพต้นทาง ไม่ระบุวันที่', 'https://npa.sam.or.th/site/images/npa/12478/20240815083709_P1_61.jpg', '/listing-media/sam/1t2834/01.webp', 'image/webp', 28398, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวที่ดินและถนน ภาพ 28 พฤษภาคม 2564', 'แนวที่ดินและถนน ภาพ 28 พฤษภาคม 2564', 'https://npa.sam.or.th/site/images/npa/12478/1T2834P4_65.jpg', '/listing-media/sam/1t2834/03.webp', 'image/webp', 26870, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ที่ดินหัวมุม ภาพ 28 พฤษภาคม 2564', 'ที่ดินหัวมุม ภาพ 28 พฤษภาคม 2564', 'https://npa.sam.or.th/site/images/npa/12478/1T2834P6_65.jpg', '/listing-media/sam/1t2834/04.webp', 'image/webp', 18534, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'มุมทางเข้า ภาพ 28 พฤษภาคม 2564', 'มุมทางเข้า ภาพ 28 พฤษภาคม 2564', 'https://npa.sam.or.th/site/images/npa/12478/1T2834P7_65.jpg', '/listing-media/sam/1t2834/05.webp', 'image/webp', 27210, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวถนนและสายไฟ ภาพ 20 เมษายน 2565', 'แนวถนนและสายไฟ ภาพ 20 เมษายน 2565', 'https://npa.sam.or.th/site/images/npa/12478/1T2834P9_65.jpg', '/listing-media/sam/1t2834/06.webp', 'image/webp', 61160, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพต้นไม้ภายใน ภาพ 20 เมษายน 2565', 'สภาพต้นไม้ภายใน ภาพ 20 เมษายน 2565', 'https://npa.sam.or.th/site/images/npa/12478/1T2834P10_65.jpg', '/listing-media/sam/1t2834/07.webp', 'image/webp', 77758, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลง 1T2834 และแปลงโรงเรียนอนุบาล', 'ผังแปลง 1T2834 และแปลงโรงเรียนอนุบาล', 'https://npa.sam.or.th/site/images/npa/12478/20180913154543_1T2834C_61.jpg', '/listing-media/sam/1t2834/08.webp', 'image/webp', 30914, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังโครงการหลายรหัส ประกาศนี้เฉพาะ 1T2834', 'ผังโครงการหลายรหัส ประกาศนี้เฉพาะ 1T2834', 'https://npa.sam.or.th/site/images/npa/12478/20180913154543_1T2834C2_61.jpg', '/listing-media/sam/1t2834/09.webp', 'image/webp', 23076, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่จาก SAM', 'แผนที่จาก SAM', 'https://npa.sam.or.th/site/images/npa/12478/20180912140359_1T2834M1_61.jpg', '/listing-media/sam/1t2834/10.webp', 'image/webp', 51256, 785, 600, 90, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=12478&keyref=', '1T2834', now(), 'Source checked2026-09-15. THB244558000;113 non-contiguous plots,total43788sqm. Utility kindergarten deed85773 206.3 sq.wah included. Private road355 easement according to SAM; internal roads unformed. Other project asset codes excluded.9 unique photos/plans after removing exact duplicate; field photos dated 2021-05-28 and 2022-04-20. Navigation/map agree. All-status query returned nearby listing1376 / 1T2428 only, a different disjoint deed set and area; no duplicate for 1T2834. SAM reports 230kV corridor and20.5m setback each side; verify affected parcels.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Bigland Factory Land, Khlong Luang — 113 Plots, THB244.558M', 'Vacant land in Bigland Factory, Khlong Nueng, Khlong Luang, Pathum Thani, accessed from Phahonyothin Highway 1 via Soi Samat. The 113 plots total 27 rai 1 ngan 47 sq.wah, or 10,947 sq.wah (43,788 sq.m.). SAM announced price THB244,558,000, asset1T2834. Source unit price is approximately THB22,340/sq.wah; the total price governs.

These are separate subplots divided by internal project roads, not one continuous site. Individual plots range from 23.7 to 980.8 sq.wah. Chanote ranges44969–44972, 85388–85423, 85570–85607, 85699–85732 and 85773 total113 certificates. SAM reports purple zoning; verify permitted use for the intended activity.

Material restrictions: SAM reports a nearby 230,000-volt transmission line and a setback of 20.5 metres on each side of its centreline. Verify the corridor, affected parcels and applicable restrictions before offering; this does not imply every plot is equally affected. deed85773,206.3 sq.wah included in the total, was allocated as a project public-utility kindergarten plot. Do not treat it as unrestricted development land. Soi Samat is private road deed355; SAM reports a registered easement benefiting the property, approximately16m concrete carriageway and30m right of way. Internal project rights of way are10m and14m, but SAM says they have no formed road condition. Verify each plot''s access, rights and boundaries before offering.

Other SAM assets 1T2428, 1T2831 and 1T2833 appear in the same project/master plan; this listing includes only1T2834.

Residential, commercial and industrial surroundings near Nava Nakorn Industrial Estate, Lotus''s, Big C Nava Nakorn, Nava Nakorn Hospital, Talad Thai and Thammasat University. From Rangsit toward Wang Noi on Phahonyothin, at Toyota Friendship around km45–46 turn left into Soi Samat for400m; the plots are within the project on the left.

Nine authentic source photos/plans after removing one exact duplicate. Several field photos display28 May 2021 and 20 April 2022; inspect current condition. Navigation/map agree14.113101, 100.614490; a reference pin for the asset group, not individual plot boundaries. Price/direct-sale status checked15September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting1T2834 to confirm deed inventory, price, availability, viewing and terms.', 'Bigland Factory, Soi Samat', 'Approximately400m from Phahonyothin Road', 'Soi Samat, Phahonyothin Highway1', 'Khlong Nueng', 'Khlong Luang', 'Pathum Thani', 'Bigland Factory Land, Khlong Luang — 113 Plots, THB244.558M', '113 separate Bigland Factory land plots,43788sqm,THB244558000. Kindergarten utility plot and internal road limitations disclosed.', 'published', 'ai_assisted', now(), 'bigland factory land, khlong luang — 113 plots, thb244.558m vacant land in bigland factory, khlong nueng, khlong luang, pathum thani, accessed from phahonyothin highway 1 via soi samat. the 113 plots total 27 rai 1 ngan 47 sq.wah, or 10,947 sq.wah (43,788 sq.m.). sam announced price thb244,558,000, asset1t2834. source unit price is approximately thb22,340/sq.wah; the total price governs.

these are separate subplots divided by internal project roads, not one continuous site. individual plots range from 23.7 to 980.8 sq.wah. chanote ranges44969–44972, 85388–85423, 85570–85607, 85699–85732 and 85773 total113 certificates. sam reports purple zoning; verify permitted use for the intended activity.

material restrictions: sam reports a nearby 230,000-volt transmission line and a setback of 20.5 metres on each side of its centreline. verify the corridor, affected parcels and applicable restrictions before offering; this does not imply every plot is equally affected. deed85773,206.3 sq.wah included in the total, was allocated as a project public-utility kindergarten plot. do not treat it as unrestricted development land. soi samat is private road deed355; sam reports a registered easement benefiting the property, approximately16m concrete carriageway and30m right of way. internal project rights of way are10m and14m, but sam says they have no formed road condition. verify each plot''s access, rights and boundaries before offering.

other sam assets 1t2428, 1t2831 and 1t2833 appear in the same project/master plan; this listing includes only1t2834.

residential, commercial and industrial surroundings near nava nakorn industrial estate, lotus''s, big c nava nakorn, nava nakorn hospital, talad thai and thammasat university. from rangsit toward wang noi on phahonyothin, at toyota friendship around km45–46 turn left into soi samat for400m; the plots are within the project on the left.

nine authentic source photos/plans after removing one exact duplicate. several field photos display28 may 2021 and 20 april 2022; inspect current condition. navigation/map agree14.113101, 100.614490; a reference pin for the asset group, not individual plot boundaries. price/direct-sale status checked15september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting1t2834 to confirm deed inventory, price, availability, viewing and terms.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=12478&keyref=', 'Official SAM page 12478 identifies SAM as asset holder and direct-sale contact for 1T2834.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'dc5b2834-1349-4a08-911b-41fdee312478', '{"reference_code":"1T2834","source_page_id":12478,"source_image_count":9,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
