BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20239'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='4T0975' OR source_url ~ '[?&]id=20239(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='f66b0975-ab2b-4a37-86da-715694020239' OR slug='sam-suksawat-76-2-land-bang-chak-4t0975' OR (abs(latitude-13.614898)<0.0001 AND abs(longitude-100.542541)<0.0001 AND abs(land_area_sqm-33476)<1)) THEN RAISE NOTICE 'SAM 4T0975 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('f66b0975-ab2b-4a37-86da-715694020239', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'ที่ดินสุขสวัสดิ์ 76/2 พระประแดง 7 แปลงติดกัน รวม 20 ไร่ 3 งาน 69 ตร.ว.', 'รายละเอียดทรัพย์

ที่ดิน 7 แปลงติดกัน ซอยสุขสวัสดิ์ 76/2 ตำบลบางจาก อำเภอพระประแดง จังหวัดสมุทรปราการ รวม 20 ไร่ 3 งาน 69 ตร.ว. หรือ 8,369 ตร.ว. (33,476 ตร.ม.) โฉนดเลขที่ 3756, 3759, 3761, 28477, 28478, 31396 และ 37850 ราคาประกาศขาย SAM 197,764,000 บาท รหัส 4T0975 ต้นทางแสดงราคาประมาณ 23,631 บาท/ตร.ว. ใช้ราคารวมเป็นหลัก

แปลงรูปหลายเหลี่ยม ด้านทิศใต้ติดถนนกว้างประมาณ 151 เมตร ลึกสุดประมาณ 329 เมตร SAM จัดหมวดเป็นที่ดินเปล่า แต่ข้อมูลสำรวจระบุมีอาคารสำนักงานชั้นเดียวสภาพทรุดโทรมและบางส่วนถูกรื้อถอน ไม่รับรองว่าอาคารพร้อมใช้งานหรือรวมในการโอนทั้งหมด ต้องยืนยันรายการสิ่งปลูกสร้างกับ SAM

ข้อควรทราบเกี่ยวกับทรัพย์

ด้านใต้มีแนวสายไฟฟ้าแรงสูง 230,000 โวลต์ ตาม SAM มีระยะร่นห้ามก่อสร้างอาคารจากจุดกึ่งกลางเสาด้านละ 20 เมตร รวม 40 เมตร ควรตรวจแนวสายไฟและขอบเขตพื้นที่ที่ได้รับผลกระทบก่อนวางแผนพัฒนา

ซอยสุขสวัสดิ์ 76/2 เป็นถนนส่วนบุคคล ผ่านโฉนดเลขที่ 8644, 3757, 3758, 31434, 31433, 30475 และ 30477 โดย SAM ระบุว่าจดภาระจำยอมเรื่องทางเดินและทางรถยนต์ให้ทรัพย์แล้ว ผิวคอนกรีตกว้างประมาณ 8 เมตร เขตทางประมาณ 12 เมตร ผู้สนใจควรตรวจสิทธิและแนวทางเข้าจริงเพิ่มเติม นอกจากนี้โฉนด 3756 มีภาระจำยอมบางส่วนเรื่องทางเดินและทางรถยนต์ให้โฉนด 3759 ซึ่งทั้งสองอยู่ในชุดทรัพย์นี้

ด้านเหนือและตะวันตกติดคลองบางจาก SAM ระบุว่าอาจมีที่งอก แต่เอกสารสิทธิ์เดิมออกเมื่อ ร.ศ.127 (พ.ศ.2451) ไม่สามารถระบุรูปแปลงได้ชัดเจน จึงใช้เนื้อที่ตามเอกสาร 20 ไร่ 3 งาน 69 ตร.ว. โดยไม่บวกพื้นที่งอกที่ยังไม่ยืนยัน ควรรังวัดสอบเขตเพื่อทราบแนวเขตและพื้นที่ที่แน่นอนก่อนเสนอซื้อ

ทำเลและการเดินทาง

SAM ระบุผังเมืองสีม่วง อยู่ในย่านที่อยู่อาศัย พาณิชยกรรมและอุตสาหกรรม ใกล้สถานีย่อยการไฟฟ้าบางปลากด โรงพยาบาลเปาโลพระประแดง และโรงเรียนบ้านบางจาก จากพระสมุทรเจดีย์มุ่งหน้าสามแยกพระประแดงบนถนนสุขสวัสดิ์ ผ่านคลองสองพี่น้องและคลองท่าเกวียน เลี้ยวซ้ายเข้าซอยสุขสวัสดิ์ 76/2 ประมาณ 265 เมตร ทรัพย์อยู่ด้านขวามือ

ภาพและข้อมูลต้นทาง

ภาพจริงและผังจาก SAM รวม 18 ภาพหลังตัดรูปซ้ำ มีภาพอาคารเดิม พื้นที่ภายใน แนวสายไฟ ถนน ผังภาระจำยอม ผังเมืองและแผนที่ ภาพภาคสนามหลายภาพแสดงวันที่ 1 มิถุนายน 2565 ควรตรวจสภาพปัจจุบัน พิกัด 13.614898, 100.542541 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์แผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด

ราคาและสถานะซื้อตรงตรวจจากหน้า SAM วันที่ 15 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 4T0975 เพื่อยืนยันราคา สถานะพร้อมขาย การนัดชม เอกสารสิทธิ์และเงื่อนไขล่าสุด', 197764000, false, 33476, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ซอยสุขสวัสดิ์ 76/2', 'เข้าจากถนนสุขสวัสดิ์ประมาณ 265 เมตร', 'ซอยสุขสวัสดิ์ 76/2', 13.614898, 100.542541, 'สมุทรปราการ', 'พระประแดง', 'บางจาก', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-suksawat-76-2-land-bang-chak-4t0975') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'industrial') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 197764000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"ที่ดินเปล่า","official_page_reference_code":"4T0975","source_page_id":20239,"title_document_type":"chanote","title_deed_numbers":["3756","3759","3761","28477","28478","31396","37850"],"title_document_count":7,"plot_count":7,"adjoining_plots":true,"land_area_square_wah":8369,"land_area_sqm":33476,"source_price_per_square_wah_thb":23631,"plot_shape":"polygonal","south_frontage_m_approx":151,"maximum_depth_m_approx":329,"planning_zone_th":"สีม่วง","surveyed_structure":"dilapidated_single_storey_office_partly_demolished","transfer_inventory_requires_confirmation":true,"private_access_road_deeds":["8644","3757","3758","31434","31433","30475","30477"],"registered_pedestrian_vehicle_easement_according_to_sam":true,"access_road_width_m_approx":8,"access_right_of_way_m_approx":12,"internal_easement_servient_deed":"3756","internal_easement_dominant_deed":"3759","south_transmission_voltage_volts":230000,"source_no_build_setback_each_side_m":20,"source_no_build_corridor_total_m":40,"north_west_boundary_canal":"คลองบางจาก","possible_accretion_unconfirmed":true,"unconfirmed_accretion_not_added_to_area":true,"historic_title_year_be":2451,"boundary_survey_recommended":true,"status_checked_on":"2026-09-15","source_field_photo_date":"2022-06-01","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.614898,100.542541","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20239 identifies SAM as direct-sale contact for 4T0975, seven adjoining plots in Suksawat 76/2, with a dilapidated office reported by survey.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 4T0975 ราคา 197,764,000 บาท', 'SAM direct purchase 4T0975 THB 197,764,000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'power_line', 'แนวสายไฟฟ้าแรงสูง', 'High-voltage corridor', 'SAM ระบุสายไฟ 230,000 โวลต์ด้านใต้ ห้ามก่อสร้างจากกึ่งกลางเสาข้างละ 20 ม. รวม 40 ม.', 'SAM reports 230kV south line, no-building setback 20m each side,40m total', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'access_easements', 'ภาระจำยอมทางเข้าและภายใน', 'Access and internal easements', 'ถนนส่วนบุคคลมีภาระจำยอมทางเดิน/รถยนต์ตาม SAM และโฉนด 3756 ให้ทางแก่โฉนด 3759', 'Private access pedestrian/vehicle easements per SAM; deed3756 grants access to3759', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'boundary_survey', 'แนวเขตติดคลองและที่งอก', 'Canal boundary and possible accretion', 'เอกสารเดิม พ.ศ.2451 รูปแปลงไม่ชัด ต้องรังวัดสอบเขต ไม่เพิ่มที่งอกที่ยังไม่ยืนยันในพื้นที่ขาย', 'Historic1908 titles,unclear shape; survey required; unconfirmed accretion not added', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'existing_structure', 'สภาพอาคารเดิม', 'Existing structure', 'สำรวจพบสำนักงานชั้นเดียวทรุดโทรม รื้อถอนบางส่วน ต้องยืนยันรายการโอน', 'Survey reports dilapidated single-storey office,partly demolished; confirm transfer inventory', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ทางเข้าที่ดินและซอยสุขสวัสดิ์ 76/2', 'ทางเข้าที่ดินและซอยสุขสวัสดิ์ 76/2', 'https://npa.sam.or.th/site/images/npa/20239/20250821091815_4T0975P3_65.jpg', '/listing-media/sam/4t0975/01.webp', 'image/webp', 22224, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ประตูทางเข้าทรัพย์', 'ประตูทางเข้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P2_65.jpg', '/listing-media/sam/4t0975/03.webp', 'image/webp', 30210, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารเดิมตามสภาพ', 'อาคารเดิมตามสภาพ', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P4_65.jpg', '/listing-media/sam/4t0975/04.webp', 'image/webp', 37370, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารสำนักงานเดิม', 'อาคารสำนักงานเดิม', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P5_65.jpg', '/listing-media/sam/4t0975/05.webp', 'image/webp', 41168, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในอาคารตามสภาพ', 'ภายในอาคารตามสภาพ', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P6_65.jpg', '/listing-media/sam/4t0975/06.webp', 'image/webp', 20812, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่และแนวสายไฟแรงสูง', 'พื้นที่และแนวสายไฟแรงสูง', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P7_65.jpg', '/listing-media/sam/4t0975/07.webp', 'image/webp', 31738, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานที่ดินภายใน', 'ลานที่ดินภายใน', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P8_65.jpg', '/listing-media/sam/4t0975/08.webp', 'image/webp', 27868, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินและอาคารเดิม', 'ทางเดินและอาคารเดิม', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P9_65.jpg', '/listing-media/sam/4t0975/09.webp', 'image/webp', 27932, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในอีกมุม', 'พื้นที่ภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P10_65.jpg', '/listing-media/sam/4t0975/10.webp', 'image/webp', 37986, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ที่ดินด้านใน', 'ที่ดินด้านใน', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P11_65.jpg', '/listing-media/sam/4t0975/11.webp', 'image/webp', 37370, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้ามองจากภายใน', 'ทางเข้ามองจากภายใน', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P12_65.jpg', '/listing-media/sam/4t0975/12.webp', 'image/webp', 43718, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ถนนสุขสวัสดิ์และทางเข้าซอย', 'ถนนสุขสวัสดิ์และทางเข้าซอย', 'https://npa.sam.or.th/site/images/npa/20239/4T0975P1_65.jpg', '/listing-media/sam/4t0975/13.webp', 'image/webp', 30424, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพการสัญจรในซอยจากต้นทาง', 'สภาพการสัญจรในซอยจากต้นทาง', 'https://npa.sam.or.th/site/images/npa/20239/4T0975NEW.jpg', '/listing-media/sam/4t0975/14.webp', 'image/webp', 35226, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังเมืองจาก SAM', 'ผังเมืองจาก SAM', 'https://npa.sam.or.th/site/images/npa/20239/4T0975C3.1_65.jpg', '/listing-media/sam/4t0975/15.webp', 'image/webp', 236644, 1120, 892, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ภาพถ่ายดาวเทียมพร้อมแนวอ้างอิงจาก SAM', 'ภาพถ่ายดาวเทียมพร้อมแนวอ้างอิงจาก SAM', 'https://npa.sam.or.th/site/images/npa/20239/4T0975C4.1_65.jpg', '/listing-media/sam/4t0975/16.webp', 'image/webp', 96710, 597, 569, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดินและแนวภาระจำยอม', 'ผังที่ดินและแนวภาระจำยอม', 'https://npa.sam.or.th/site/images/npa/20239/20220719115729_4T0975C1_65.jpg', '/listing-media/sam/4t0975/17.webp', 'image/webp', 61776, 785, 600, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังสิ่งปลูกสร้างและแนวสายไฟ', 'ผังสิ่งปลูกสร้างและแนวสายไฟ', 'https://npa.sam.or.th/site/images/npa/20239/20220719115729_4T0975C2_65.jpg', '/listing-media/sam/4t0975/18.webp', 'image/webp', 59908, 785, 600, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/20239/20220719115729_4T0975M_65.jpg', '/listing-media/sam/4t0975/19.webp', 'image/webp', 58476, 785, 600, 180, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20239&keyref=', '4T0975', now(), 'Checked2026-09-15. THB197764000,7 adjoining deeds,33476sqm. SAM vacant land category; survey reports dilapidated partly-demolished office. Private access easements and3756/3759 internal easement disclosed.230kV corridor20m each side; historic1908 titles and possible canal accretion require survey, no unconfirmed area added.18 unique images,field photos2022-06-01. Navigation/map agree. All-status code/page/deed/nearby query returned no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Suksawat 76/2 Land, Phra Pradaeng — Seven Adjoining Plots, THB 197.764M', 'Seven adjoining land plots in Soi Suksawat 76/2, Bang Chak, Phra Pradaeng, Samut Prakan. Total 20 rai 3 ngan 69 sq.wah, or 8,369 sq.wah (33,476 sq.m.), Chanote titles 3756, 3759, 3761, 28477, 28478, 31396 and 37850. SAM announced price THB 197,764,000, asset 4T0975; source unit price approximately THB 23,631/sq.wah, with total price governing.

Polygonal site, approximately 151 m southern road frontage and 329 m maximum depth. SAM categorises it as vacant land, but its survey reports a dilapidated single-storey office, partly demolished. Current usability and transfer inventory must be confirmed.

Material restrictions: SAM reports a 230,000-volt line along the south and a no-building setback 20 m each side from the pole centre, 40 m total. Verify the corridor and affected area before planning development.

Private access via Soi Suksawat 76/2 crosses deeds 8644, 3757, 3758, 31434, 31433, 30475 and 30477. SAM reports registered pedestrian/vehicle easements benefiting the property, approximately 8 m concrete carriageway and 12 m right of way. Verify access rights and alignment. Part of deed 3756 also grants pedestrian/vehicle access to deed 3759; both are included in this sale.

The north and west adjoin Khlong Bang Chak. SAM reports possible accretion, but historic title documents issued in Rattanakosin Era 127 (B.E.2451 /1908) do not establish a clear plot shape. Area is stated from title documents only, with no addition for unconfirmed accreted land. A boundary survey is recommended to establish exact boundaries and area before offering.

SAM reports purple zoning, residential/commercial/industrial surroundings, near Bang Pla Kot electricity substation, Paolo Phra Pradaeng Hospital and Ban Bang Chak School. From Phra Samut Chedi toward Phra Pradaeng junction on Suksawat Road, cross Song Phi Nong and Tha Kwian canals, then turn left into Soi 76/2 for approximately 265 m; property on the right.

Eighteen authentic source photos/plans after removing one exact duplicate. Several field images display 1 June 2022; inspect current condition. Navigation/map agree on 13.614898,100.542541, a reference pin rather than a surveyed boundary. Price/direct-sale status checked 15 September 2026. Contact SAM 02-686-1888, sales@sam.or.th or LINE @samline quoting 4T0975.', 'Soi Suksawat 76/2', 'Approximately 265 metres from Suksawat Road', 'Soi Suksawat 76/2', 'Bang Chak', 'Phra Pradaeng', 'Samut Prakan', 'Suksawat 76/2 Land, Phra Pradaeng — Seven Adjoining Plots, THB 197.764M', 'Seven adjoining plots,33,476sqm,THB197,764,000; private access, power corridor and canal-boundary survey disclosures.', 'published', 'ai_assisted', now(), 'suksawat 76/2 land, phra pradaeng — seven adjoining plots, thb 197.764m seven adjoining land plots in soi suksawat 76/2, bang chak, phra pradaeng, samut prakan. total 20 rai 3 ngan 69 sq.wah, or 8,369 sq.wah (33,476 sq.m.), chanote titles 3756, 3759, 3761, 28477, 28478, 31396 and 37850. sam announced price thb 197,764,000, asset 4t0975; source unit price approximately thb 23,631/sq.wah, with total price governing.

polygonal site, approximately 151 m southern road frontage and 329 m maximum depth. sam categorises it as vacant land, but its survey reports a dilapidated single-storey office, partly demolished. current usability and transfer inventory must be confirmed.

material restrictions: sam reports a 230,000-volt line along the south and a no-building setback 20 m each side from the pole centre, 40 m total. verify the corridor and affected area before planning development.

private access via soi suksawat 76/2 crosses deeds 8644, 3757, 3758, 31434, 31433, 30475 and 30477. sam reports registered pedestrian/vehicle easements benefiting the property, approximately 8 m concrete carriageway and 12 m right of way. verify access rights and alignment. part of deed 3756 also grants pedestrian/vehicle access to deed 3759; both are included in this sale.

the north and west adjoin khlong bang chak. sam reports possible accretion, but historic title documents issued in rattanakosin era 127 (b.e.2451 /1908) do not establish a clear plot shape. area is stated from title documents only, with no addition for unconfirmed accreted land. a boundary survey is recommended to establish exact boundaries and area before offering.

sam reports purple zoning, residential/commercial/industrial surroundings, near bang pla kot electricity substation, paolo phra pradaeng hospital and ban bang chak school. from phra samut chedi toward phra pradaeng junction on suksawat road, cross song phi nong and tha kwian canals, then turn left into soi 76/2 for approximately 265 m; property on the right.

eighteen authentic source photos/plans after removing one exact duplicate. several field images display 1 june 2022; inspect current condition. navigation/map agree on 13.614898,100.542541, a reference pin rather than a surveyed boundary. price/direct-sale status checked 15 september 2026. contact sam 02-686-1888, sales@sam.or.th or line @samline quoting 4t0975.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20239&keyref=', 'Official SAM page 20239 identifies SAM as asset holder and direct-sale contact for 4T0975.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'f66b0975-ab2b-4a37-86da-715694020239', '{"reference_code":"4T0975","source_page_id":20239,"source_image_count":18,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
