BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-22697'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='BL0067' OR source_url ~ '[?&]id=22697(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='c52b0067-d5bd-4e64-aefb-153065822697' OR slug='sam-rat-uthit-hat-yai-land-bl0067' OR (abs(latitude-7.009376)<0.0001 AND abs(longitude-100.458554)<0.0001 AND abs(land_area_sqm-11869.6)<1)) THEN RAISE NOTICE 'SAM BL0067 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('c52b0067-d5bd-4e64-aefb-153065822697', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'ที่ดินถนนราษฎร์อุทิศ หาดใหญ่ ติดถนน 2 ด้าน 7 ไร่ 1 งาน 67.4 ตร.ว.', 'รายละเอียดทรัพย์

ที่ดินติดถนนราษฎร์อุทิศ ตำบลหาดใหญ่ อำเภอหาดใหญ่ จังหวัดสงขลา จำนวน 10 แปลงติดกัน รวม 7 ไร่ 1 งาน 67.4 ตร.ว. หรือ 2,967.4 ตร.ว. (11,869.6 ตร.ม.) โฉนดเลขที่ 1277, 13640, 13641, 13642 และ 43178–43183 ราคาประกาศขาย SAM 193,756,000 บาท รหัส BL0067 ต้นทางแสดงราคาประมาณ 65,295 บาท/ตร.ว. ใช้ราคารวมเป็นหลัก

ที่ดินรูปหลายเหลี่ยม ติดถนน 2 ด้าน ด้านตะวันออกกว้างประมาณ 35 เมตร ด้านตะวันตกประมาณ 62 เมตร ลึกประมาณ 205 เมตร SAM ระบุผังเมืองสีชมพู ถนนราษฎร์อุทิศเป็นทางสาธารณประโยชน์ตามต้นทาง ผิวลาดยางกว้างประมาณ 18 เมตร เขตทางประมาณ 30 เมตร

ข้อควรทราบเกี่ยวกับทรัพย์

ที่ดินบางส่วนของโฉนด 1277 มีสภาพเป็นถนนราษฎร์อุทิศ เนื้อที่ประมาณ 1 งาน 63 ตร.ว. หรือ 163 ตร.ว. ซึ่งรวมในพื้นที่ทั้งหมดข้างต้น ขนาดด้านเหนือประมาณ 28.5 เมตร ด้านใต้ 23 เมตร ด้านตะวันตก 12 เมตร และด้านตะวันออก 17 เมตร ผู้สนใจควรตรวจแนวเขต สถานะสิทธิและพื้นที่ใช้งานจริงก่อนเสนอซื้อ ไม่ควรถือว่าพื้นที่ทั้งหมดสามารถพัฒนาได้โดยไม่มีข้อจำกัด

แม้ SAM จัดหมวดประชาสัมพันธ์เป็นที่ดินเปล่า ผู้ซื้อต้องรับโอนกรรมสิทธิ์สิ่งปลูกสร้างตามรายการที่ SAM รับโอน คืออาคารร้านอาหารชั้นเดียวไม่มีเลขที่ ข้อมูลสำรวจในคำบรรยายระบุร้านค้าชั้นเดียว ส่วนโล่งหลังคาคลุม 1 หลังและซุ้มขายน้ำ ลักษณะไม่มั่นคงถาวรและรื้อถอนได้ง่าย

รูปจาก SAM วันที่ 20 กุมภาพันธ์ 2569 แสดงพื้นที่เปิดและเศษวัสดุรื้อถอนจำนวนมาก ซึ่งต่างจากรายการสิ่งปลูกสร้างในคำบรรยาย จึงต้องยืนยันสภาพปัจจุบัน รายการที่ต้องรับโอน และผู้รับผิดชอบการขนย้ายเศษวัสดุกับ SAM ไม่ถือว่ารูปถ่ายยกเลิกหน้าที่รับโอนตามเงื่อนไขต้นทาง

ทำเลและการเดินทาง

อยู่ในย่านที่อยู่อาศัยและพาณิชยกรรม ใกล้วัดโคกสมานคุณ โรงเรียนวัดโคกสมานคุณและตลาดกิมหยง ตามข้อมูล SAM จากแยกต่างระดับควนลังมุ่งหน้าเมืองหาดใหญ่บนถนนเพชรเกษม (ทล.4) ผ่านการไฟฟ้าส่วนภูมิภาค ที่ว่าการอำเภอหาดใหญ่และโรงเรียนพลวิทยา เลี้ยวซ้ายเข้าถนนราษฎร์อุทิศประมาณ 540 เมตร ทรัพย์อยู่ซ้ายมือ

ภาพและข้อมูลต้นทาง

ภาพจริงและผังจาก SAM รวม 15 ภาพ พร้อมผังส่วนที่เป็นถนน พิกัด 7.009376, 100.458554 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์แผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด

ราคาและสถานะซื้อตรงตรวจจากหน้า SAM วันที่ 15 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส BL0067 เพื่อยืนยันราคา สถานะพร้อมขาย การนัดชม สิ่งปลูกสร้างและเงื่อนไขล่าสุด', 193756000, false, 11869.6, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ถนนราษฎร์อุทิศ', 'เข้าจากถนนเพชรเกษมประมาณ 540 เมตร', 'ถนนราษฎร์อุทิศ', 7.009376, 100.458554, 'สงขลา', 'หาดใหญ่', 'หาดใหญ่', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-rat-uthit-hat-yai-land-bl0067') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'retail') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 193756000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"ที่ดินเปล่า","official_page_reference_code":"BL0067","source_page_id":22697,"title_document_type":"chanote","title_deed_numbers":["1277","13640","13641","13642","43178","43179","43180","43181","43182","43183"],"title_document_count":10,"plot_count":10,"adjoining_plots":true,"land_area_square_wah":2967.4,"land_area_sqm":11869.6,"source_price_per_square_wah_thb":65295,"plot_shape":"polygonal","road_frontage_sides":2,"east_frontage_m_approx":35,"west_frontage_m_approx":62,"depth_m_approx":205,"planning_zone_th":"สีชมพู","public_road_according_to_sam":true,"road_width_m_approx":18,"right_of_way_m_approx":30,"road_occupied_deed":"1277","road_occupied_area_square_wah_approx":163,"road_occupied_area_included_in_total":true,"registered_structure":"อาคารร้านอาหารชั้นเดียว ไม่ปรากฏเลขที่","registered_structure_transfer_required":true,"textual_survey_structures":["ร้านค้าชั้นเดียว","ส่วนโล่งหลังคาคลุม 1 หลัง","ซุ้มขายน้ำ"],"source_photos_show_open_ground_and_demolition_debris":true,"current_structure_inventory_requires_confirmation":true,"debris_removal_responsibility_unconfirmed":true,"status_checked_on":"2026-09-15","source_field_photo_date":"2026-02-20","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//7.009376,100.458554","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 22697 identifies SAM as direct-sale contact for BL0067, ten adjoining land plots on Rat Uthit Road, Hat Yai, with mandatory registered structure transfer.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส BL0067 ราคา 193,756,000 บาท', 'SAM direct purchase BL0067 THB193756000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_occupied_land', 'ที่ดินส่วนที่เป็นถนน', 'Road-occupied title area', 'โฉนด 1277 บางส่วนเป็นถนนราษฎร์อุทิศประมาณ 163 ตร.ว. รวมในพื้นที่ทั้งหมด', 'Part of deed1277 forms Rat Uthit Road,approx163sq.wah included in total', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'mandatory_structure_transfer', 'ต้องรับโอนสิ่งปลูกสร้าง', 'Mandatory structure transfer', 'ต้องรับโอนอาคารร้านอาหารชั้นเดียวไม่มีเลขที่ตามทะเบียน แม้จัดหมวดที่ดินเปล่า', 'Must accept registered unnumbered single-storey restaurant despite vacant-land marketing category', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'current_condition', 'ยืนยันสภาพและรายการโอน', 'Confirm condition and inventory', 'รูป 20 กุมภาพันธ์ 2569 เห็นเศษวัสดุรื้อถอน ต้องยืนยันสิ่งปลูกสร้างและความรับผิดชอบขนย้ายกับ SAM', 'Photos20Feb2026 show debris; confirm structures and removal responsibility with SAM', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ที่ดินและถนนราษฎร์อุทิศ', 'ที่ดินและถนนราษฎร์อุทิศ', 'https://npa.sam.or.th/site/images/npa/22697/20260220163623_BL0067P1_69.jpg', '/listing-media/sam/bl0067/01.webp', 'image/webp', 35868, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวหน้าที่ดินตามสภาพ', 'แนวหน้าที่ดินตามสภาพ', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P2_69.jpg', '/listing-media/sam/bl0067/02.webp', 'image/webp', 41274, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ที่ดินและถนนอีกด้าน', 'ที่ดินและถนนอีกด้าน', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P3_69.jpg', '/listing-media/sam/bl0067/03.webp', 'image/webp', 36406, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'มุมถนนข้างทรัพย์', 'มุมถนนข้างทรัพย์', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P4_69.jpg', '/listing-media/sam/bl0067/04.webp', 'image/webp', 39406, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพพื้นที่ตามแนวถนน', 'สภาพพื้นที่ตามแนวถนน', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P5_69.jpg', '/listing-media/sam/bl0067/05.webp', 'image/webp', 44988, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินและเศษวัสดุ', 'ทางเดินและเศษวัสดุ', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P6_69.jpg', '/listing-media/sam/bl0067/06.webp', 'image/webp', 65432, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในทรัพย์', 'พื้นที่ภายในทรัพย์', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P7_69.jpg', '/listing-media/sam/bl0067/07.webp', 'image/webp', 57472, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานและเศษวัสดุรื้อถอน', 'ลานและเศษวัสดุรื้อถอน', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P8_69.jpg', '/listing-media/sam/bl0067/08.webp', 'image/webp', 53148, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ใต้ต้นไม้', 'พื้นที่ใต้ต้นไม้', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P9_69.jpg', '/listing-media/sam/bl0067/09.webp', 'image/webp', 61522, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพเศษวัสดุภายใน', 'สภาพเศษวัสดุภายใน', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P10_69.jpg', '/listing-media/sam/bl0067/10.webp', 'image/webp', 47560, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานภายในอีกมุม', 'ลานภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P11_69.jpg', '/listing-media/sam/bl0067/11.webp', 'image/webp', 48118, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ด้านในตามสภาพ', 'พื้นที่ด้านในตามสภาพ', 'https://npa.sam.or.th/site/images/npa/22697/BL0067P12_69.jpg', '/listing-media/sam/bl0067/12.webp', 'image/webp', 47746, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังโฉนดทั้ง 10 แปลง', 'ผังโฉนดทั้ง 10 แปลง', 'https://npa.sam.or.th/site/images/npa/22697/20250918114008_BL0067C2_68.jpg', '/listing-media/sam/bl0067/13.webp', 'image/webp', 24550, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังสิ่งปลูกสร้างเดิมและส่วนที่เป็นถนน', 'ผังสิ่งปลูกสร้างเดิมและส่วนที่เป็นถนน', 'https://npa.sam.or.th/site/images/npa/22697/20250918114008_BL0067C1_68.jpg', '/listing-media/sam/bl0067/14.webp', 'image/webp', 29210, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/22697/20250918114008_BL0067M_68.jpg', '/listing-media/sam/bl0067/15.webp', 'image/webp', 72166, 785, 600, 150, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=22697&keyref=', 'BL0067', now(), 'Checked2026-09-15. THB193756000,10 adjoining deeds,11869.6sqm. Road-occupied deed1277 portion163sq.wah included. Mandatory registered restaurant transfer retained despite vacant-land category and photos showing open ground/debris. Text/photo inventory difference and removal responsibility disclosed.15 original images; field date2026-02-20. Navigation/map agree. All-status code/page/deed/nearby query returned no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Rat Uthit Road Land, Hat Yai — Two Road Frontages, THB 193.756M', 'Ten adjoining land plots on Rat Uthit Road, Hat Yai, Hat Yai District, Songkhla, totalling 7 rai 1 ngan 67.4 sq.wah, or 2,967.4 sq.wah (11,869.6 sq.m.). Chanote titles 1277, 13640, 13641, 13642 and 43178–43183. SAM announced price THB 193,756,000, asset BL0067; source unit price approximately THB 65,295/sq.wah, with total price governing.

Polygonal site with roads on two sides, approximately 35 m eastern frontage,62 m western frontage and205 m depth. SAM reports pink zoning. Rat Uthit Road is public according to SAM, with approximately18 m paved carriageway and30 m right of way.

Material disclosure: part of deed1277 physically forms Rat Uthit Road, approximately163 sq.wah included in the total land area. Source dimensions approximately28.5 m north,23 m south,12 m west and17 m east. Verify boundaries, rights and usable area; total title area is not unrestricted development area.

SAM labels the property vacant land for marketing/search purposes but expressly requires the buyer to accept transfer of the registered structure: an unnumbered single-storey restaurant. The textual survey describes a single-storey shop, one open covered structure and a drinks kiosk, of non-permanent,easily removable construction.

SAM photos dated20 February2026 show open ground and substantial demolition debris, differing from the written structure inventory. Confirm present condition, mandatory transfer inventory and responsibility for debris removal with SAM. Photos do not cancel the source''s structure-transfer requirement.

Residential/commercial surroundings near Wat Khok Saman Khun,its school and Kim Yong Market. From Khuan Lang interchange toward Hat Yai on Phetkasem Highway4,pass the electricity authority,district office and Pholwitthaya School,then turn left into Rat Uthit Road for approximately540 m; property on the left.

Fifteen authentic source photos/plans including the road-occupied portion. Navigation/map agree7.009376,100.458554,a reference pin rather than a surveyed boundary. Price/direct-sale status checked15 September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting BL0067 to confirm availability,price,viewing,structures and terms.', 'Rat Uthit Road', 'Approximately540 metres from Phetkasem Road', 'Rat Uthit Road', 'Hat Yai', 'Hat Yai', 'Songkhla', 'Rat Uthit Road Land, Hat Yai — Two Road Frontages, THB 193.756M', 'Ten adjoining plots,11869.6sqm,THB193756000. Road-occupied area and mandatory registered structure transfer disclosed.', 'published', 'ai_assisted', now(), 'rat uthit road land, hat yai — two road frontages, thb 193.756m ten adjoining land plots on rat uthit road, hat yai, hat yai district, songkhla, totalling 7 rai 1 ngan 67.4 sq.wah, or 2,967.4 sq.wah (11,869.6 sq.m.). chanote titles 1277, 13640, 13641, 13642 and 43178–43183. sam announced price thb 193,756,000, asset bl0067; source unit price approximately thb 65,295/sq.wah, with total price governing.

polygonal site with roads on two sides, approximately 35 m eastern frontage,62 m western frontage and205 m depth. sam reports pink zoning. rat uthit road is public according to sam, with approximately18 m paved carriageway and30 m right of way.

material disclosure: part of deed1277 physically forms rat uthit road, approximately163 sq.wah included in the total land area. source dimensions approximately28.5 m north,23 m south,12 m west and17 m east. verify boundaries, rights and usable area; total title area is not unrestricted development area.

sam labels the property vacant land for marketing/search purposes but expressly requires the buyer to accept transfer of the registered structure: an unnumbered single-storey restaurant. the textual survey describes a single-storey shop, one open covered structure and a drinks kiosk, of non-permanent,easily removable construction.

sam photos dated20 february2026 show open ground and substantial demolition debris, differing from the written structure inventory. confirm present condition, mandatory transfer inventory and responsibility for debris removal with sam. photos do not cancel the source''s structure-transfer requirement.

residential/commercial surroundings near wat khok saman khun,its school and kim yong market. from khuan lang interchange toward hat yai on phetkasem highway4,pass the electricity authority,district office and pholwitthaya school,then turn left into rat uthit road for approximately540 m; property on the left.

fifteen authentic source photos/plans including the road-occupied portion. navigation/map agree7.009376,100.458554,a reference pin rather than a surveyed boundary. price/direct-sale status checked15 september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting bl0067 to confirm availability,price,viewing,structures and terms.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=22697&keyref=', 'Official SAM page 22697 identifies SAM as asset holder and direct-sale contact for BL0067.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'c52b0067-d5bd-4e64-aefb-153065822697', '{"reference_code":"BL0067","source_page_id":22697,"source_image_count":15,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
