BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20128'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='4T0953' OR source_url ~ '[?&]id=20128(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='dbc20953-5a21-46bc-aae5-941268820128' OR slug='sam-sarika-nakhon-nayok-land-three-groups-4t0953' OR (abs(latitude-14.28784)<0.0001 AND abs(longitude-101.27852)<0.0001 AND abs(land_area_sqm-265357.2)<1)) THEN RAISE NOTICE 'SAM 4T0953 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('dbc20953-5a21-46bc-aae5-941268820128', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'ที่ดินสาริกา นครนายก 10 แปลง 3 กลุ่ม รวม 165 ไร่ 3 งาน 39.3 ตร.ว.', 'รายละเอียดทรัพย์

ที่ดินตำบลสาริกา อำเภอเมืองนครนายก จังหวัดนครนายก บริเวณถนนนครนายก–นางรอง (ทล.3049) และถนนทางเข้าน้ำตกสาริกา (ทล.3050) รวม 10 แปลง เนื้อที่ 165 ไร่ 3 งาน 39.3 ตร.ว. หรือ 66,339.3 ตร.ว. (265,357.2 ตร.ม.) ราคาประกาศขาย SAM 187,909,000 บาท รหัส 4T0953 ต้นทางแสดงราคาประมาณ 2,833 บาท/ตร.ว. ใช้ราคารวมเป็นหลัก

เอกสารสิทธิ์มีโฉนดตราจองเลขที่ 120 จำนวน 1 ฉบับ และโฉนดที่ดินเลขที่ 9597, 9598, 10206, 10394, 10395, 10404, 13239, 13240 และ 16669 จำนวน 9 ฉบับ รวม 10 ฉบับ ไม่ใช่โฉนดที่ดินประเภทเดียวกันทั้งหมด

การแบ่งกลุ่มที่ดิน

กลุ่มที่ 1: 6 แปลง รวม 92 ไร่ 3 งาน 58 ตร.ว. ด้านใต้ติดถนน ทล.3049 กว้างประมาณ 124 เมตร ลึกสุดประมาณ 880 เมตร ด้านตะวันตกติดคลองเรือและคลองสาริกาประมาณ 810 เมตร ระดับที่ดินสูงต่ำตามภูมิประเทศ SAM ระบุมีสาธารณูปโภคพื้นฐานครบ ถนนสาธารณะลาดยาง 4 ช่องจราจร พร้อมไหล่ทางและช่องจักรยาน 1 ช่อง กว้างประมาณ 18–20 เมตร

กลุ่มที่ 2: 2 แปลง รวม 8 ไร่ 84 ตร.ว. ด้านตะวันตกติดถนนทางเข้าน้ำตกสาริกา ทล.3050 กว้างประมาณ 240 เมตร ลึกสุดประมาณ 48 เมตร ด้านเหนือและตะวันออกติดคลองสาริกา ระดับที่ดินสูงต่ำตามภูมิประเทศ SAM ระบุมีสาธารณูปโภคพื้นฐานครบ ถนนสาธารณะลาดยาง 2 ช่องจราจรพร้อมไหล่ทาง กว้างประมาณ 10 เมตร

กลุ่มที่ 3: 2 แปลง รวม 64 ไร่ 2 งาน 97.3 ตร.ว. ไม่มีพื้นที่ติดถนน มีคลองเรือและคลองสาริกาคั่นจากกลุ่มที่ 1 และ 2 และ SAM ระบุว่ายังไม่มีสะพานข้าม ด้านเหนือติดคลองเรือประมาณ 320 เมตร ด้านใต้ประมาณ 110 เมตร ด้านตะวันออกประมาณ 710 เมตร ด้านตะวันตกติดคลองและแปลงข้างเคียงประมาณ 645 เมตร ระดับที่ดินสูงต่ำตามภูมิประเทศ อยู่ห่างจุดสาธารณูปโภคประมาณ 100 เมตร

ข้อควรทราบเกี่ยวกับการเข้าถึง

ที่ดินอยู่ใกล้กันแต่ไม่ได้ต่อเนื่องเป็นผืนเดียวทั้งหมด การมีหน้าถนนและสาธารณูปโภคของกลุ่มที่ 1 และ 2 ไม่ได้หมายความว่ากลุ่มที่ 3 เข้าถึงได้แบบเดียวกัน ควรตรวจสิทธิและวิธีเข้าถึงกลุ่มที่ 3 รวมถึงเงื่อนไขที่เกี่ยวข้องหากจะทำทางข้ามคลองกับหน่วยงานที่รับผิดชอบก่อนเสนอซื้อ ไม่ถือว่ามีสิทธิสร้างสะพานหรือทางข้ามได้โดยอัตโนมัติ

ทำเลและการเดินทาง

SAM ระบุผังเมืองสีเขียว อยู่ในย่านเกษตรกรรมและแหล่งท่องเที่ยว ใกล้น้ำตกสาริกา น้ำตกวังตะไคร้ เขื่อนขุนด่านปราการชลและที่ทำการ อบต.สาริกา จากน้ำตกนางรองมุ่งหน้าน้ำตกสาริกาบนถนน ทล.3049 ผ่านวัดสวนหงษ์ ถึงประมาณ กม.11+500 ทรัพย์อยู่ขวามือ ควรตรวจข้อกำหนดการใช้ประโยชน์ให้ตรงกับแผนงานของผู้ซื้อ

ภาพและข้อมูลต้นทาง

ภาพจริงและผังจาก SAM รวม 15 ภาพ มีภาพลงวันที่ 5 เมษายน 2565 และ 30 พฤษภาคม 2565 ควรตรวจสภาพปัจจุบัน พิกัด 14.287840, 101.278520 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์แผนที่ เป็นจุดอ้างอิงของชุดทรัพย์ ไม่ใช่แนวเขตแต่ละกลุ่ม

ราคาและสถานะซื้อตรงตรวจจากหน้า SAM วันที่ 15 กันยายน 2569 ติดต่อ SAM โทร 02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 4T0953 เพื่อยืนยันราคา สถานะพร้อมขาย การนัดชม เอกสารสิทธิ์และเงื่อนไขล่าสุด', 187909000, false, 265357.2, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'บริเวณถนนนครนายก–นางรอง ทล.3049 กม.11+500', 'ที่ดิน 3 กลุ่มใกล้ทางเข้าน้ำตกสาริกา ทล.3050', 'ถนนนครนายก–นางรอง (ทล.3049)', 14.28784, 101.27852, 'นครนายก', 'เมืองนครนายก', 'สาริกา', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-sarika-nakhon-nayok-land-three-groups-4t0953') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'agriculture') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 187909000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"ที่ดินเปล่า","official_page_reference_code":"4T0953","source_page_id":20128,"title_document_count":10,"chanote_tra_chong_number":"120","chanote_numbers":["9597","9598","10206","10394","10395","10404","13239","13240","16669"],"mixed_title_document_types":true,"plot_count":10,"group_count":3,"non_contiguous_groups":true,"land_area_square_wah":66339.3,"land_area_sqm":265357.2,"source_price_per_square_wah_thb":2833,"planning_zone_th":"สีเขียว","groups":[{"number":1,"plot_count":6,"area_square_wah":37158,"road":"3049","south_frontage_m":124,"max_depth_m":880,"west_canal_frontage_m":810,"basic_utilities_according_to_sam":true},{"number":2,"plot_count":2,"area_square_wah":3284,"road":"3050","west_frontage_m":240,"max_depth_m":48,"basic_utilities_according_to_sam":true},{"number":3,"plot_count":2,"area_square_wah":25897.3,"no_road_frontage":true,"no_bridge_according_to_sam":true,"utility_distance_m_approx":100,"north_m":320,"south_m":110,"east_m":710,"west_m":645}],"separating_canals":["คลองเรือ","คลองสาริกา"],"group3_access_requires_verification":true,"uneven_natural_terrain":true,"status_checked_on":"2026-09-15","source_field_photo_dates":["2022-04-05","2022-05-30"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//14.28784,101.27852","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20128 identifies SAM as direct-sale contact for 4T0953, ten plots in three canal-separated groups in Sarika, including group3 without road frontage or bridge.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM รหัส 4T0953 ราคา 187,909,000 บาท', 'SAM direct purchase4T0953 THB187909000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'group3_access', 'กลุ่มที่ 3 ไม่มีหน้าถนนและสะพาน', 'Group3 has no road frontage or bridge', '64 ไร่ 2 งาน 97.3 ตร.ว. มีคลองคั่นจากกลุ่ม 1/2 ไม่มีสะพานข้ามตาม SAM ต้องตรวจการเข้าถึง', '64rai2ngan97.3sq.wah separated by canals; no bridge according to SAM; verify access', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'mixed_titles', 'ประเภทเอกสารสิทธิ์', 'Mixed title documents', 'โฉนดตราจอง 120 จำนวน 1 ฉบับ และโฉนดที่ดิน 9 ฉบับ', 'One Chanote Tra Chong120 and nine Chanote titles', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'group_utilities', 'สาธารณูปโภคแยกตามกลุ่ม', 'Utilities by group', 'กลุ่ม 1/2 มีสาธารณูปโภคตาม SAM กลุ่ม 3 ห่างจุดสาธารณูปโภคประมาณ 100 ม.', 'SAM reports utilities for groups1/2; group3 approximately100m from utilities', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ที่ดินด้านถนนนครนายก–นางรอง', 'ที่ดินด้านถนนนครนายก–นางรอง', 'https://npa.sam.or.th/site/images/npa/20128/20220616104756_4T0953P19_65.jpg', '/listing-media/sam/4t0953/01.webp', 'image/webp', 41828, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'หน้าที่ดินบน ทล.3049', 'หน้าที่ดินบน ทล.3049', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P18_65.jpg', '/listing-media/sam/4t0953/02.webp', 'image/webp', 38910, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'มุมที่ดินติดถนน', 'มุมที่ดินติดถนน', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P12_65.jpg', '/listing-media/sam/4t0953/03.webp', 'image/webp', 36752, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวที่ดินด้านทางเข้าน้ำตกสาริกา', 'แนวที่ดินด้านทางเข้าน้ำตกสาริกา', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P13_65.jpg', '/listing-media/sam/4t0953/04.webp', 'image/webp', 31970, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ที่ดินและถนน ทล.3050', 'ที่ดินและถนน ทล.3050', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P11_65.jpg', '/listing-media/sam/4t0953/05.webp', 'image/webp', 34400, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพสวนภายใน', 'สภาพสวนภายใน', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P10_65.jpg', '/listing-media/sam/4t0953/06.webp', 'image/webp', 41466, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ต้นไม้และระดับพื้นที่', 'ต้นไม้และระดับพื้นที่', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P6_65.jpg', '/listing-media/sam/4t0953/07.webp', 'image/webp', 43172, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'คลองเรือที่คั่นกลุ่มทรัพย์', 'คลองเรือที่คั่นกลุ่มทรัพย์', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P7_65.jpg', '/listing-media/sam/4t0953/08.webp', 'image/webp', 40644, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่บริเวณคลอง', 'พื้นที่บริเวณคลอง', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P8_65.jpg', '/listing-media/sam/4t0953/09.webp', 'image/webp', 44628, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพภายในอีกมุม', 'สภาพภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P14_65.jpg', '/listing-media/sam/4t0953/10.webp', 'image/webp', 39928, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินและพืชพรรณ', 'ทางเดินและพืชพรรณ', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P15_65.jpg', '/listing-media/sam/4t0953/11.webp', 'image/webp', 44038, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'คลองสาริกาและแนวอ้างอิง', 'คลองสาริกาและแนวอ้างอิง', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P17_65.jpg', '/listing-media/sam/4t0953/12.webp', 'image/webp', 47148, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'คลองที่คั่นระหว่างกลุ่ม', 'คลองที่คั่นระหว่างกลุ่ม', 'https://npa.sam.or.th/site/images/npa/20128/4T0953P16_65.jpg', '/listing-media/sam/4t0953/13.webp', 'image/webp', 38082, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดิน 3 กลุ่มและคลอง', 'ผังที่ดิน 3 กลุ่มและคลอง', 'https://npa.sam.or.th/site/images/npa/20128/20220602110335_4T0953C1_65.jpg', '/listing-media/sam/4t0953/14.webp', 'image/webp', 30570, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/20128/20220602110335_4T0953M1_65.jpg', '/listing-media/sam/4t0953/15.webp', 'image/webp', 45482, 785, 600, 150, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20128&keyref=', '4T0953', now(), 'Checked2026-09-15. THB187909000,10plots/3groups,265357.2sqm; mixed Chanote/ChanoteTraChong120. Group3 no road frontage,canal-separated without bridge,utilities100m away per SAM. Do not attribute groups1/2 frontage/utilities to group3.15 authentic photos/plans,dates2022-04-05/2022-05-30. Navigation/map agree. All-status source/page/deed/nearby query no matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Sarika Land, Nakhon Nayok — Ten Plots in Three Groups, THB187.909M', 'Ten land plots in Sarika, Mueang Nakhon Nayok, Nakhon Nayok, near Highways3049 and3050. Total165 rai3 ngan39.3 sq.wah, or66,339.3 sq.wah (265,357.2 sq.m.). SAM announced price THB187,909,000, asset4T0953; approximate source unit price THB2,833/sq.wah, total price governing. Documents comprise one Chanote Tra Chong certificate120 and nine Chanote titles9597,9598,10206,10394,10395,10404,13239,13240,16669; not all the same title type.

Group1: six plots,92 rai3 ngan58 sq.wah. Approximately124m southern frontage on public Highway3049, maximum depth880m, western canal frontage810m along Khlong Ruea and Khlong Sarika. Uneven natural terrain. SAM reports basic utilities available. Highway3049 has four lanes, shoulders and a bicycle lane, approximately18–20m wide.

Group2: two plots,8 rai84 sq.wah. Approximately240m western frontage on public Highway3050 to Sarika Waterfall, depth48m; north/east adjoin Khlong Sarika. Uneven terrain, basic utilities according to SAM. Two-lane paved road with shoulders, approximately10m wide.

Group3: two plots,64 rai2 ngan97.3 sq.wah. No road frontage. Khlong Ruea and Khlong Sarika separate it from groups1/2, and SAM reports no bridge crossing. Approximate boundaries320m north along Khlong Ruea,110m south,710m east and645m west along canals/neighbouring land. Uneven terrain; approximately100m from utilities.

The three groups are nearby but not one continuous accessible site. Road frontage and utilities of groups1/2 must not be attributed to group3. Verify legal and practical access to group3 and relevant permissions for any proposed canal crossing; no automatic bridge-building right is assumed.

SAM reports green zoning, agricultural/tourism surroundings near Sarika Waterfall,Wang Takhrai Waterfall,Khun Dan Prakan Chon Dam and Sarika local administration office. From Nang Rong Waterfall toward Sarika on Highway3049,pass Wat Suan Hong to approximatelykm11+500; land on the right. Verify permitted use for the proposed development.

Fifteen authentic source photos/plans include dates5 April2022 and30 May2022. Inspect present condition. Navigation/map agree14.287840,101.278520,a reference point for the asset set rather than individual group boundaries. Price/direct-sale status checked15 September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting4T0953.', 'Nakhon Nayok–Nang Rong Highway3049,km11+500 area', 'Three groups near Sarika Waterfall access Highway3050', 'Nakhon Nayok–Nang Rong Highway3049', 'Sarika', 'Mueang Nakhon Nayok', 'Nakhon Nayok', 'Sarika Land, Nakhon Nayok — Ten Plots in Three Groups, THB187.909M', 'Ten plots in three groups,265357.2sqm,THB187909000;group3 has no road frontage or bridge, mixed title documents disclosed.', 'published', 'ai_assisted', now(), 'sarika land, nakhon nayok — ten plots in three groups, thb187.909m ten land plots in sarika, mueang nakhon nayok, nakhon nayok, near highways3049 and3050. total165 rai3 ngan39.3 sq.wah, or66,339.3 sq.wah (265,357.2 sq.m.). sam announced price thb187,909,000, asset4t0953; approximate source unit price thb2,833/sq.wah, total price governing. documents comprise one chanote tra chong certificate120 and nine chanote titles9597,9598,10206,10394,10395,10404,13239,13240,16669; not all the same title type.

group1: six plots,92 rai3 ngan58 sq.wah. approximately124m southern frontage on public highway3049, maximum depth880m, western canal frontage810m along khlong ruea and khlong sarika. uneven natural terrain. sam reports basic utilities available. highway3049 has four lanes, shoulders and a bicycle lane, approximately18–20m wide.

group2: two plots,8 rai84 sq.wah. approximately240m western frontage on public highway3050 to sarika waterfall, depth48m; north/east adjoin khlong sarika. uneven terrain, basic utilities according to sam. two-lane paved road with shoulders, approximately10m wide.

group3: two plots,64 rai2 ngan97.3 sq.wah. no road frontage. khlong ruea and khlong sarika separate it from groups1/2, and sam reports no bridge crossing. approximate boundaries320m north along khlong ruea,110m south,710m east and645m west along canals/neighbouring land. uneven terrain; approximately100m from utilities.

the three groups are nearby but not one continuous accessible site. road frontage and utilities of groups1/2 must not be attributed to group3. verify legal and practical access to group3 and relevant permissions for any proposed canal crossing; no automatic bridge-building right is assumed.

sam reports green zoning, agricultural/tourism surroundings near sarika waterfall,wang takhrai waterfall,khun dan prakan chon dam and sarika local administration office. from nang rong waterfall toward sarika on highway3049,pass wat suan hong to approximatelykm11+500; land on the right. verify permitted use for the proposed development.

fifteen authentic source photos/plans include dates5 april2022 and30 may2022. inspect present condition. navigation/map agree14.287840,101.278520,a reference point for the asset set rather than individual group boundaries. price/direct-sale status checked15 september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting4t0953.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20128&keyref=', 'Official SAM page 20128 identifies SAM as asset holder and direct-sale contact for 4T0953.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'dbc20953-5a21-46bc-aae5-941268820128', '{"reference_code":"4T0953","source_page_id":20128,"source_image_count":15,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
