BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-22102'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='BTR001' OR source_url ~ '[?&]id=22102(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='7c12b001-b8ac-49fb-9a37-553071322102' OR slug='sam-former-factory-setthakit-1-om-noi-btr001' OR (abs(latitude-13.68212)<0.0001 AND abs(longitude-100.288101)<0.0001 AND abs(land_area_sqm-25360)<1)) THEN RAISE NOTICE 'SAM BTR001 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('7c12b001-b8ac-49fb-9a37-553071322102', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'factory', 'business', 'sale', 'whole_property', 'โรงงานเดิมถนนเศรษฐกิจ 1 อ้อมน้อย 15 ไร่ 3 งาน 40 ตร.ว. · รื้อถอนส่วนใหญ่', 'รายละเอียดทรัพย์

ทรัพย์โรงงานเดิม เลขที่ 116 ถนนเศรษฐกิจ 1 (ทล.3091) ตำบลอ้อมน้อย อำเภอกระทุ่มแบน จังหวัดสมุทรสาคร ที่ดินโฉนดเลขที่ 48274 และ 53224 รวม 15 ไร่ 3 งาน 40 ตร.ว. หรือ 6,340 ตร.ว. (25,360 ตร.ม.) ราคาประกาศขาย SAM 173,853,000 บาท รหัส BTR001

แปลงรูปหลายเหลี่ยม ด้านตะวันตกกว้างประมาณ 212 เมตร โดยมีส่วนติดถนนประมาณ 158 เมตร ลึกสุดประมาณ 178 เมตร ถนนเศรษฐกิจ 1 ตาม SAM เป็นทางสาธารณประโยชน์ ผิวลาดยางกว้างประมาณ 18 เมตร เขตทางประมาณ 30 เมตร

สภาพและรายการสิ่งปลูกสร้าง

SAM จัดหมวดโรงงาน/โกดัง แต่ระบุว่าอาคารส่วนใหญ่ทรุดโทรมและถูกรื้อถอน สำรวจพบสิ่งปลูกสร้างเหลือเพียงรายการที่ 1 และ 14 โดยรายการที่ 1 ตามทะเบียนรับโอนเป็นสำนักงาน 3 ชั้นเลขที่ 116 แต่ในข้อความสำรวจเรียกว่าอาคารพักอาศัย 3 ชั้น ส่วนรายการที่ 14 เป็นอาคารหอพัก 4 ชั้น จึงควรยืนยันการใช้ประโยชน์และสภาพอาคารจริง ไม่ถือเป็นโรงงานพร้อมดำเนินกิจการ

ทะเบียนรับโอนมี 14 รายการ ได้แก่ สำนักงาน 3 ชั้น, โรงจอดรถชั้นเดียว 2 หลัง, โรงงานปั๊มเหล็กรางลูกฟูก, อาคารโพลียูรีเทน, หอพักหญิง 2 ชั้น, โรงงานตาข่ายหกเหลี่ยม, อาคารเก็บของ, ป้อมยาม, โรงงานตาข่ายสี่เหลี่ยม, สำนักงาน 2 ชั้น, โรงงานตาข่ายเทพื้น, โรงงานชุบลวดสังกะสี/รีดเหล็ก, โรงงานรีดใหญ่ และหอพักชาย 4 ชั้น เป็นรายการตามทะเบียนเดิม ไม่ใช่การรับรองว่าสิ่งปลูกสร้างทุกหลังยังอยู่ครบ

ภาพจาก SAM วันที่ 16 พฤษภาคม 2568 แสดงเศษวัสดุรื้อถอน ผนังและโครงหลังคาบางส่วน ควรตรวจโครงสร้างที่เหลือ รายการที่รวมในการโอน และความรับผิดชอบเรื่องรื้อถอนหรือขนย้ายเศษวัสดุก่อนเสนอซื้อ ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนห้อง หรือใบอนุญาตโรงงานปัจจุบัน

ข้อควรทราบเรื่องภาระจำยอมและผังเมือง

โฉนด 48274 (เลขเดิม 12527) บางส่วนตกอยู่ในบังคับภาระจำยอมของโฉนด 30584 ตามข้อมูล SAM เป็นแนวด้านใต้กว้างประมาณ 6 เมตรตลอดแนว รวมประมาณ 2 งาน 67 ตร.ว. หรือ 267 ตร.ว. ซึ่งรวมในพื้นที่ทั้งหมด ต้องตรวจขอบเขตและเงื่อนไขภาระจำยอมก่อนวางแผนใช้ที่ดิน

แม้หัวข้อสรุป SAM แสดงสีม่วง รายละเอียดระบุผังเมืองรวมเมืองกระทุ่มแบน พ.ศ.2562 ครอบคลุมทั้งสีม่วงบริเวณ อ.2-3 (อุตสาหกรรมและคลังสินค้า) และสีเขียวอ่อนบริเวณ ล.2-9 (พื้นที่โล่งเพื่อนันทนาการและการรักษาคุณภาพสิ่งแวดล้อม) จึงไม่ควรถือว่าทั้งแปลงใช้ทำอุตสาหกรรมได้เหมือนกัน

สำหรับส่วนสีเขียวอ่อน SAM ระบุการใช้ประโยชน์เพื่อนันทนาการ ส่งเสริมรักษาคุณภาพสิ่งแวดล้อม บ้านเดี่ยว สถาบันราชการ สาธารณูปโภคและสาธารณูปการ อัตราส่วนพื้นที่อาคารรวมต่อที่ดินไม่เกิน 1.5:1 และที่ว่างปราศจากอาคารไม่น้อยกว่า 40% ข้อมูลนี้เป็นข้อกำหนดที่ SAM อ้างจากผังปี 2562 ผู้สนใจควรตรวจผังปัจจุบัน แนวแบ่งสีและข้อกำหนดกับหน่วยงานก่อนตัดสินใจ

ทำเลและการเดินทาง

อยู่ในย่านที่อยู่อาศัยและอุตสาหกรรม ใกล้สำนักงานตรวจคนเข้าเมืองกระทุ่มแบน สนามกีฬาเทศบาลนครอ้อมน้อยคลังทองและสำนักงานประกันสังคม จากหนองแขมมุ่งหน้าสามพรานบนถนนเพชรเกษม ผ่านโรงพยาบาลมหาชัย 2 และไทวัสดุ เลี้ยวซ้ายเข้าถนนเศรษฐกิจ 1 ผ่านตลาดเทศบาลอ้อมน้อยถึงประมาณ กม.3 ทรัพย์อยู่ซ้ายมือ

ภาพและข้อมูลต้นทาง

ภาพจริงและผังจาก SAM รวม 17 ภาพ พิกัด 13.682120, 100.288101 ดึงจากลิงก์นำทางและตรงกับลิงก์แผนที่ SAM เป็นตำแหน่งอ้างอิง ไม่ใช่แนวเขตรังวัด ราคาและสถานะซื้อตรงตรวจวันที่ 15 กันยายน 2569 ติดต่อ SAM 02-686-1888, sales@sam.or.th หรือ LINE @samline แจ้งรหัส BTR001 เพื่อยืนยันสถานะ ราคา สภาพและเงื่อนไขล่าสุด', 173853000, false, 25360, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '116 ถนนเศรษฐกิจ 1', 'บริเวณ ทล.3091 กม.3', 'ถนนเศรษฐกิจ 1 (ทล.3091)', 13.68212, 100.288101, 'สมุทรสาคร', 'กระทุ่มแบน', 'อ้อมน้อย', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-former-factory-setthakit-1-om-noi-btr001') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'industrial') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 173853000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'factory', 1, '{"source_property_category":"โรงงาน/โกดัง","official_page_reference_code":"BTR001","source_page_id":22102,"map_filename_alternate_reference":"3A0721","title_document_type":"chanote","title_deed_numbers":["48274","53224"],"title_document_count":2,"land_area_square_wah":6340,"land_area_sqm":25360,"west_side_m_approx":212,"road_frontage_m_approx":158,"max_depth_m_approx":178,"road_width_m_approx":18,"right_of_way_m_approx":30,"condition":"mostly_demolished_dilapidated","historic_registered_inventory_entries":14,"survey_remaining_inventory_entries":[1,14],"remaining_structure_floor_counts":[3,4],"item1_registered_use":"office","item1_survey_use":"residential","use_discrepancy_requires_confirmation":true,"transfer_inventory_and_debris_responsibility_unconfirmed":true,"easement_servient_deed":"48274","easement_former_deed":"12527","easement_dominant_deed":"30584","south_easement_width_m_approx":6,"easement_area_square_wah_approx":267,"easement_area_included_in_total":true,"mixed_zoning_according_to_sam":true,"zoning_plan_year_be":2562,"zones":[{"colour":"purple","code":"อ.2-3","use":"industrial_warehouse"},{"colour":"light_green","code":"ล.2-9","use":"recreation_environmental_open_space","source_max_far":1.5,"source_min_building_free_percent":40}],"current_zoning_boundaries_require_verification":true,"usable_area_and_current_factory_licence_not_published":true,"status_checked_on":"2026-09-15","source_field_photo_date":"2025-05-16","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.68212,100.288101","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 22102 identifies SAM as direct-sale contact for BTR001, former factory116 on Setthakit1,mostly demolished with two remaining inventory entries according to survey.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ซื้อตรง SAM BTR001 ราคา 173,853,000 บาท', 'SAM direct purchase BTR001 THB173853000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'demolished_inventory', 'รื้อถอนส่วนใหญ่', 'Mostly demolished', 'ทะเบียนเดิม 14 รายการ สำรวจเหลือรายการ 1 และ 14 อาคาร 3 ชั้นและหอพัก 4 ชั้น ต้องตรวจสภาพจริง', 'Historic14 entries;survey says only items1/14 remain,3-storey building and4-storey dormitory', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'southern_easement', 'ภาระจำยอมด้านใต้', 'Southern easement', 'โฉนด48274 ให้ประโยชน์โฉนด30584 แนวกว้างประมาณ6ม. พื้นที่ประมาณ267ตร.ว. รวมในเนื้อที่ขาย', 'Deed48274 burdened for30584,approx6m wide and267sq.wah included', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'mixed_zoning', 'ผังเมืองสองประเภท', 'Mixed zoning', 'SAM อ้างผังปี2562 สีม่วง อ.2-3 และสีเขียวอ่อน ล.2-9 ต้องตรวจแนวแบ่งและผังปัจจุบัน', 'SAM cites2019 purple อ.2-3 and light-green ล.2-9;verify current map and boundaries', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'light_green_rules', 'ข้อกำหนดสีเขียวอ่อนตาม SAM', 'Source light-green rules', 'SAM ระบุ FARไม่เกิน1.5:1 และที่ว่างไม่น้อยกว่า40% พร้อมจำกัดการใช้ประโยชน์', 'SAM reports FAR≤1.5:1 and≥40% building-free land with restricted uses;verify current rules', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ภาพมุมสูงทรัพย์โรงงานเดิม', 'ภาพมุมสูงทรัพย์โรงงานเดิม', 'https://npa.sam.or.th/site/images/npa/22102/20250623143627_BTR001P19_68.jpg', '/listing-media/sam/btr001/01.webp', 'image/webp', 66010, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารและลานตามสภาพ', 'อาคารและลานตามสภาพ', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P5_68.jpg', '/listing-media/sam/btr001/02.webp', 'image/webp', 30994, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โครงอาคารและต้นไม้', 'โครงอาคารและต้นไม้', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P6_68.jpg', '/listing-media/sam/btr001/03.webp', 'image/webp', 70392, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในโครงหลังคาที่เหลือ', 'ภายในโครงหลังคาที่เหลือ', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P7_68.jpg', '/listing-media/sam/btr001/04.webp', 'image/webp', 56848, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โครงหลังคาชำรุด', 'โครงหลังคาชำรุด', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P8_68.jpg', '/listing-media/sam/btr001/05.webp', 'image/webp', 50208, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารและโครงสร้างตามสภาพ', 'อาคารและโครงสร้างตามสภาพ', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P9_68.jpg', '/listing-media/sam/btr001/06.webp', 'image/webp', 47458, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่รื้อถอนและเศษวัสดุ', 'พื้นที่รื้อถอนและเศษวัสดุ', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P10_68.jpg', '/listing-media/sam/btr001/07.webp', 'image/webp', 52448, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ผนังเดิมและพื้นที่รื้อถอน', 'ผนังเดิมและพื้นที่รื้อถอน', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P12_68.jpg', '/listing-media/sam/btr001/08.webp', 'image/webp', 47830, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางภายในและเศษวัสดุ', 'ทางภายในและเศษวัสดุ', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P13_68.jpg', '/listing-media/sam/btr001/09.webp', 'image/webp', 51270, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่โรงงานเดิม', 'พื้นที่โรงงานเดิม', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P14_68.jpg', '/listing-media/sam/btr001/10.webp', 'image/webp', 48560, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานรื้อถอนอีกมุม', 'ลานรื้อถอนอีกมุม', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P15_68.jpg', '/listing-media/sam/btr001/11.webp', 'image/webp', 49364, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ผนังเดิมตามสภาพ', 'ผนังเดิมตามสภาพ', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P16_68.jpg', '/listing-media/sam/btr001/12.webp', 'image/webp', 48462, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานเศษวัสดุ', 'ลานเศษวัสดุ', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P17_68.jpg', '/listing-media/sam/btr001/13.webp', 'image/webp', 40758, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณอาคารที่เหลือ', 'บริเวณอาคารที่เหลือ', 'https://npa.sam.or.th/site/images/npa/22102/BTR001P18_68.jpg', '/listing-media/sam/btr001/14.webp', 'image/webp', 55856, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดินและภาระจำยอม', 'ผังที่ดินและภาระจำยอม', 'https://npa.sam.or.th/site/images/npa/22102/20241030150152_BTR001C2_67.jpg', '/listing-media/sam/btr001/15.webp', 'image/webp', 19814, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังรายการสิ่งปลูกสร้างเดิม ไม่ยืนยันว่าคงอยู่ครบ', 'ผังรายการสิ่งปลูกสร้างเดิม ไม่ยืนยันว่าคงอยู่ครบ', 'https://npa.sam.or.th/site/images/npa/22102/20241030150152_BTR001C1_67.jpg', '/listing-media/sam/btr001/16.webp', 'image/webp', 26964, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่จาก SAM', 'แผนที่จาก SAM', 'https://npa.sam.or.th/site/images/npa/22102/20241030150152_BTR001M_67(3A0721).jpg', '/listing-media/sam/btr001/17.webp', 'image/webp', 46400, 785, 600, 170, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=22102&keyref=', 'BTR001', now(), 'Checked2026-09-15. THB173853000,25360sqm. Factory mostly demolished;historic14 entries,survey remaining1/14 with office/residential naming discrepancy.267sq.wah southern easement included. Mixed purple/light-green2019 source zoning and restrictions require current verification.17 authentic images dated2025-05-16;navigation/map agree. No all-status source/page/deed/nearby matches;additional map-filename3A0721 search empty.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Former Factory, Setthakit1 Om Noi — Mostly Demolished, THB173.853M', 'Former factory property numbered116 on Setthakit1 Road (Highway3091), Om Noi, Krathum Baen, Samut Sakhon. Chanote titles48274 and53224 total15 rai3 ngan40 sq.wah, or6,340 sq.wah (25,360 sq.m.). SAM announced price THB173,853,000, asset BTR001. Polygonal site,212m western side with158m road frontage and178m maximum depth. Public road per SAM,18m paved carriageway and30m right of way.

Condition: SAM categorises it factory/warehouse but reports most structures dilapidated and demolished. Survey says only registered items1 and14 remain. Item1 is a three-storey office116 in the acquisition register but called a three-storey residential building in the survey; item14 is a four-storey dormitory. Verify actual use and condition; not advertised as an operational factory.

The historic register lists14 entries: three-storey office,two single-storey carports,corrugated-steel forming factory,polyurethane building,two-storey female dormitory,hexagonal-mesh factory,store,guardhouse,square-mesh factory,two-storey office,floor-mesh factory,wire galvanising/steel rolling factory,large rolling factory and four-storey male dormitory. This is a historic inventory,not confirmation all survive. Photos dated16 May2025 show demolition debris,walls and partial roof structures. Verify structural condition,transfer inventory and demolition/debris-removal responsibility. Total usable area,room counts and current factory licence are not published.

Material easement: part of deed48274 (formerly12527) is burdened in favour of deed30584,according to SAM,along the southern side approximately6m wide,area267sq.wah included in total. Check exact scope and terms.

Mixed zoning: although the summary says purple,SAM''s detailed text cites the2019 Krathum Baen comprehensive plan with purple industrial/warehouse area อ.2-3 and light-green recreation/environmental open-space area ล.2-9. Do not treat the whole site as unrestricted industrial land. For light-green land,SAM reports recreation,environmental protection,detached housing,government institutions and public utilities/facilities as uses,maximum FAR1.5:1 and minimum40% building-free land. These are source-attributed2019 rules; verify current zoning boundaries and requirements with the authority before purchase.

Residential/industrial surroundings near Krathum Baen Immigration,Om Noi Khlang Thong municipal sports ground and Social Security Office. From Nong Khaem toward Sam Phran on Phetkasem,pass Mahachai2 Hospital and Thai Watsadu,turn left into Setthakit1 past Om Noi municipal market to aroundkm3,property left.

Seventeen authentic source images/plans. Navigation/map agree13.682120,100.288101,reference pin not surveyed boundary. Price/direct-sale status checked15 September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting BTR001.', '116 Setthakit1 Road', 'Highway3091 aroundkm3', 'Setthakit1 Road (Highway3091)', 'Om Noi', 'Krathum Baen', 'Samut Sakhon', 'Former Factory, Setthakit1 Om Noi — Mostly Demolished, THB173.853M', 'Former factory25360sqm,THB173853000,mostly demolished;267sq.wah easement and mixed purple/light-green zoning disclosed.', 'published', 'ai_assisted', now(), 'former factory, setthakit1 om noi — mostly demolished, thb173.853m former factory property numbered116 on setthakit1 road (highway3091), om noi, krathum baen, samut sakhon. chanote titles48274 and53224 total15 rai3 ngan40 sq.wah, or6,340 sq.wah (25,360 sq.m.). sam announced price thb173,853,000, asset btr001. polygonal site,212m western side with158m road frontage and178m maximum depth. public road per sam,18m paved carriageway and30m right of way.

condition: sam categorises it factory/warehouse but reports most structures dilapidated and demolished. survey says only registered items1 and14 remain. item1 is a three-storey office116 in the acquisition register but called a three-storey residential building in the survey; item14 is a four-storey dormitory. verify actual use and condition; not advertised as an operational factory.

the historic register lists14 entries: three-storey office,two single-storey carports,corrugated-steel forming factory,polyurethane building,two-storey female dormitory,hexagonal-mesh factory,store,guardhouse,square-mesh factory,two-storey office,floor-mesh factory,wire galvanising/steel rolling factory,large rolling factory and four-storey male dormitory. this is a historic inventory,not confirmation all survive. photos dated16 may2025 show demolition debris,walls and partial roof structures. verify structural condition,transfer inventory and demolition/debris-removal responsibility. total usable area,room counts and current factory licence are not published.

material easement: part of deed48274 (formerly12527) is burdened in favour of deed30584,according to sam,along the southern side approximately6m wide,area267sq.wah included in total. check exact scope and terms.

mixed zoning: although the summary says purple,sam''s detailed text cites the2019 krathum baen comprehensive plan with purple industrial/warehouse area อ.2-3 and light-green recreation/environmental open-space area ล.2-9. do not treat the whole site as unrestricted industrial land. for light-green land,sam reports recreation,environmental protection,detached housing,government institutions and public utilities/facilities as uses,maximum far1.5:1 and minimum40% building-free land. these are source-attributed2019 rules; verify current zoning boundaries and requirements with the authority before purchase.

residential/industrial surroundings near krathum baen immigration,om noi khlang thong municipal sports ground and social security office. from nong khaem toward sam phran on phetkasem,pass mahachai2 hospital and thai watsadu,turn left into setthakit1 past om noi municipal market to aroundkm3,property left.

seventeen authentic source images/plans. navigation/map agree13.682120,100.288101,reference pin not surveyed boundary. price/direct-sale status checked15 september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting btr001.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=22102&keyref=', 'Official SAM page 22102 identifies SAM as asset holder and direct-sale contact for BTR001.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '7c12b001-b8ac-49fb-9a37-553071322102', '{"reference_code":"BTR001","source_page_id":22102,"source_image_count":17,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
