BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-19956'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A1407' OR source_url ~ '[?&]id=19956(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='edbd1407-4cac-4385-8f19-537806719956' OR slug='sam-blue-sky-patong-hotel-105-rooms-3a1407' OR (abs(latitude-7.897332)<0.0001 AND abs(longitude-98.302809)<0.0001 AND abs(land_area_sqm-776)<1)) THEN RAISE NOTICE 'SAM 3A1407 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, total_floors, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, custom_project_name, custom_unit_number, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('edbd1407-4cac-4385-8f19-537806719956', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'hotel_resort', 'business', 'sale', 'whole_property', 'โรงแรมบลูสกาย ป่าตอง 105 ห้อง อาคาร 7 ชั้น · ปิดกิจการ', 'รายละเอียดทรัพย์

โรงแรมบลูสกาย ป่าตอง เลขที่ 236/1–4 ถนนผังเมือง ก. ตำบลป่าตอง อำเภอกะทู้ จังหวัดภูเก็ต ที่ดิน 4 แปลงติดกัน รวม 1 งาน 94 ตร.ว. หรือ 194 ตร.ว. (776 ตร.ม.) เอกสารสิทธิ์ น.ส.3ก. เลขที่ 7664, 7665, 7666 และ 7667 จำนวน 4 ฉบับ ราคาประกาศขาย SAM 167,848,000 บาท รหัส 3A1407 เป็นการขายทั้งทรัพย์

SAM ระบุอาคารดัดแปลงเป็นโรงแรมให้เช่ารายวันชื่อบลูสกาย ป่าตอง มีห้องพัก 105 ห้อง พร้อมพื้นที่ฟิตเนส สระว่ายน้ำและห้องอาหาร แต่ปัจจุบันตามหน้า SAM ปิดกิจการและไม่มีการใช้ประโยชน์ จำนวนห้องและสิ่งอำนวยความสะดวกเป็นข้อมูลตามสำรวจ ไม่ใช่การรับรองว่าพร้อมเปิดบริการ รายได้ ผู้ครอบครอง ใบอนุญาตโรงแรมและสภาพระบบปัจจุบันต้องยืนยันเพิ่มเติม

สิ่งปลูกสร้างและแนวที่ดิน

ทะเบียนรับโอนระบุโรงแรมความสูงเกิน 5 ชั้น เลขที่ 236/1, 236/2, 236/3 และ 236/4 ส่วนข้อมูลสำรวจระบุอาคารพาณิชย์ 7 ชั้น 10 คูหาติดต่อกัน ภายในเจาะทะลุใช้ประโยชน์ร่วมกัน ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนห้องน้ำหรือจำนวนที่จอดรถ จึงไม่ประมาณตัวเลขเหล่านี้

ที่ดินรูปหลายเหลี่ยม ด้านตะวันตกกว้างประมาณ 45.54 เมตรติดลำรางสาธารณประโยชน์ ลึกสุดประมาณ 25.4 เมตร แม้ข้อมูลสรุปแสดงหัวข้อหน้ากว้างติดถนน แต่คำบรรยายและผังระบุว่ามีลำรางอยู่ด้านนี้ จึงควรตรวจแนวเขตและสิทธิทางเข้าออกข้ามลำรางตามเอกสารจริง ถนนผังเมือง ก. ตาม SAM เป็นทางสาธารณะ ผิวคอนกรีตกว้างประมาณ 16 เมตร เขตทางประมาณ 20 เมตร

ข้อควรทราบเกี่ยวกับอาคาร

SAM ระบุผังเมืองสีส้ม และอ้างประกาศกระทรวงทรัพยากรธรรมชาติและสิ่งแวดล้อมปี 2560 สำหรับพื้นที่บริเวณที่ 8 ว่าการดัดแปลงปลูกสร้างทำได้เฉพาะอาคารสูงไม่เกิน 23 เมตร พร้อมที่ว่างไม่น้อยกว่า 30% สำหรับบ้านเดี่ยว บ้านแฝด อาคารสาธารณะ อาคารอยู่อาศัยรวมหรือสำนักงาน และไม่น้อยกว่า 10% สำหรับห้องแถว ตึกแถว บ้านแถวหรืออาคารพาณิชย์

ข้อกำหนดข้างต้นเป็นข้อมูลที่ SAM อ้างถึง ไม่ใช่การยืนยันว่าอาคาร 7 ชั้นนี้ผ่านข้อกำหนดหรือได้รับอนุญาตแล้ว ผู้สนใจควรตรวจประเภทการใช้อาคาร ใบอนุญาตก่อสร้าง/ดัดแปลง ใบอนุญาตโรงแรม และข้อกำหนดปัจจุบันก่อนเสนอซื้อหรือวางแผนเปิดกิจการ

ทำเลและการเดินทาง

อยู่ในย่านโรงแรมและธุรกิจเกี่ยวเนื่องการท่องเที่ยว ใกล้จังซีลอน ถนนบางลาและชายหาดป่าตองตามข้อมูล SAM จากถนนพระบารมี (ทล.4029) มุ่งหน้าหาดป่าตอง ผ่านโรงเรียนสุวรรณคีรีวงศ์ เลี้ยวซ้ายเข้าถนนผังเมือง ก. ผ่านแยกถนนราชปาทานุสรณ์ ตรงไปทรัพย์อยู่ซ้ายมือ

ภาพและข้อมูลต้นทาง

ภาพจริงและผังจาก SAM รวม 23 ภาพ เป็นภาพต่างช่วงปี 2564–2565 ควรตรวจสภาพปัจจุบัน พิกัด 7.897332, 98.302809 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์แผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ราคาและสถานะซื้อตรงตรวจวันที่ 15 กันยายน 2569 ติดต่อ SAM 02-686-1888, sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A1407 เพื่อยืนยันราคา สถานะและเงื่อนไขล่าสุด', 167848000, false, 776, 7, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'โรงแรมบลูสกาย ป่าตอง', '236/1–4', '236/1–4 โรงแรมบลูสกาย ป่าตอง', 'ถนนผังเมือง ก.', 'ถนนผังเมือง ก.', 7.897332, 98.302809, 'ภูเก็ต', 'กะทู้', 'ป่าตอง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-blue-sky-patong-hotel-105-rooms-3a1407') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'hospitality') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 167848000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'hotel_resort', 1, '{"source_property_category":"โรงแรม/รีสอร์ท","official_page_reference_code":"3A1407","source_page_id":19956,"title_document_type":"nor_sor_3_gor","title_document_numbers":["7664","7665","7666","7667"],"title_document_count":4,"adjoining_plots":true,"land_area_square_wah":194,"land_area_sqm":776,"surveyed_guest_room_count":105,"room_count":105,"surveyed_floor_count":7,"connected_shophouse_unit_count":10,"registered_description":"hotel_over_five_storeys","operation_status":"closed_unused_according_to_sam","surveyed_facilities":["fitness","pool","restaurant"],"facilities_operability_not_confirmed":true,"west_side_m_approx":45.54,"west_boundary":"public_drainage_channel","maximum_depth_m_approx":25.4,"access_across_channel_requires_verification":true,"road_width_m_approx":16,"right_of_way_m_approx":20,"planning_zone_th":"สีส้ม","source_environmental_notice_year_be":2560,"source_environmental_area":8,"source_height_limit_m":23,"source_min_open_space_percent_by_building_type":{"detached_semi_detached_public_collective_residential_office":30,"rowhouse_shophouse_commercial":10},"current_rules_and_existing_compliance_not_confirmed":true,"current_hotel_licence_not_confirmed":true,"usable_area_bathrooms_parking_not_published":true,"status_checked_on":"2026-09-15","source_photo_years":[2021,2022],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//7.897332,98.302809","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 19956 identifies SAM as direct-sale contact for 3A1407, closed Blue Sky Patong Hotel with105 surveyed rooms.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ ซื้อตรง SAM3A1407 ราคา167,848,000บาท', 'Whole property,SAM3A1407 THB167848000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'closed_hotel', 'โรงแรมปิดกิจการ', 'Closed hotel', '105ห้องตามสำรวจ ปิดกิจการไม่มีการใช้ประโยชน์ตาม SAM ต้องตรวจใบอนุญาตและสภาพก่อนเปิด', '105surveyed rooms;closed/unused per SAM;verify licence and condition', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'title_type', 'เอกสารสิทธิ์', 'Title type', 'น.ส.3ก.7664–7667 จำนวน4ฉบับ รวม194ตร.ว.', 'Four Nor Sor3 Gor certificates7664–7667,total194sq.wah', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'source_building_rules', 'ข้อกำหนดอาคารที่ SAM อ้าง', 'Source building rules', 'ประกาศปี2560 บริเวณ8 สูงไม่เกิน23ม. ที่ว่าง30%หรือ10%ตามประเภทอาคาร ต้องตรวจข้อกำหนดปัจจุบัน', 'SAM cites2017 Area8,height23m,open space30% or10% by building type;verify current rules/compliance', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'drainage_frontage', 'แนวลำรางหน้าทรัพย์', 'Drainage-channel boundary', 'ด้านตะวันตก45.54ม.ติดลำรางสาธารณะ ต้องตรวจแนวเขตและสิทธิทางเข้า', 'West45.54m adjoins public drainage channel;verify boundary and access', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ด้านหน้าโรงแรมบลูสกาย ป่าตอง', 'ด้านหน้าโรงแรมบลูสกาย ป่าตอง', 'https://npa.sam.or.th/site/images/npa/19956/20260105110648_P1_65.jpg', '/listing-media/sam/3a1407/01.webp', 'image/webp', 43444, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารโรงแรมและถนน', 'อาคารโรงแรมและถนน', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P1_65.jpg', '/listing-media/sam/3a1407/02.webp', 'image/webp', 38796, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'มุมอาคารจากถนน', 'มุมอาคารจากถนน', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P2_65.jpg', '/listing-media/sam/3a1407/03.webp', 'image/webp', 34394, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลำรางสาธารณะด้านหน้า', 'ลำรางสาธารณะด้านหน้า', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P4_65.jpg', '/listing-media/sam/3a1407/04.webp', 'image/webp', 48500, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวหน้าอาคาร', 'แนวหน้าอาคาร', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P8_65.jpg', '/listing-media/sam/3a1407/05.webp', 'image/webp', 52946, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าอาคาร', 'ทางเข้าอาคาร', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P9_65.jpg', '/listing-media/sam/3a1407/06.webp', 'image/webp', 44496, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณลำรางและทางเข้า', 'บริเวณลำรางและทางเข้า', 'https://npa.sam.or.th/site/images/npa/19956/P2_65.jpg', '/listing-media/sam/3a1407/07.webp', 'image/webp', 69552, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ด้านหน้าโรงแรม', 'พื้นที่ด้านหน้าโรงแรม', 'https://npa.sam.or.th/site/images/npa/19956/P3_65.jpg', '/listing-media/sam/3a1407/08.webp', 'image/webp', 61380, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงชั้นล่าง', 'โถงชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/19956/P4_65.jpg', '/listing-media/sam/3a1407/09.webp', 'image/webp', 25154, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าภายใน', 'ทางเข้าภายใน', 'https://npa.sam.or.th/site/images/npa/19956/P5_65.jpg', '/listing-media/sam/3a1407/10.webp', 'image/webp', 26634, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'เฉลียงทางเข้า', 'เฉลียงทางเข้า', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P12_65.jpg', '/listing-media/sam/3a1407/11.webp', 'image/webp', 34200, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'เคาน์เตอร์ต้อนรับเดิม', 'เคาน์เตอร์ต้อนรับเดิม', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P14_65.jpg', '/listing-media/sam/3a1407/12.webp', 'image/webp', 18268, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักตามสภาพ', 'ห้องพักตามสภาพ', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P15_65.jpg', '/listing-media/sam/3a1407/13.webp', 'image/webp', 18200, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักและระเบียง', 'ห้องพักและระเบียง', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P16_65.jpg', '/listing-media/sam/3a1407/14.webp', 'image/webp', 17434, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องริมหน้าต่าง', 'ห้องริมหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/19956/3A1407P17_65.jpg', '/listing-media/sam/3a1407/15.webp', 'image/webp', 24012, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินภายใน', 'ทางเดินภายใน', 'https://npa.sam.or.th/site/images/npa/19956/P6_65.jpg', '/listing-media/sam/3a1407/16.webp', 'image/webp', 13664, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักอีกห้อง', 'ห้องพักอีกห้อง', 'https://npa.sam.or.th/site/images/npa/19956/P7_65.jpg', '/listing-media/sam/3a1407/17.webp', 'image/webp', 21062, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในห้องพักอีกมุม', 'ภายในห้องพักอีกมุม', 'https://npa.sam.or.th/site/images/npa/19956/P9_65.jpg', '/listing-media/sam/3a1407/18.webp', 'image/webp', 17740, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเชื่อมระหว่างห้อง', 'ทางเชื่อมระหว่างห้อง', 'https://npa.sam.or.th/site/images/npa/19956/P12_65.jpg', '/listing-media/sam/3a1407/19.webp', 'image/webp', 15824, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักริมถนน', 'ห้องพักริมถนน', 'https://npa.sam.or.th/site/images/npa/19956/P11_65.jpg', '/listing-media/sam/3a1407/20.webp', 'image/webp', 29754, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังเอกสารสิทธิ์ทั้ง4แปลง', 'ผังเอกสารสิทธิ์ทั้ง4แปลง', 'https://npa.sam.or.th/site/images/npa/19956/20220506100837_3A1407C1_65.jpg', '/listing-media/sam/3a1407/21.webp', 'image/webp', 16436, 450, 450, 210, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังอาคารเชื่อมกัน10คูหา', 'ผังอาคารเชื่อมกัน10คูหา', 'https://npa.sam.or.th/site/images/npa/19956/20220506100837_3A1407C2_65.jpg', '/listing-media/sam/3a1407/22.webp', 'image/webp', 23662, 450, 450, 220, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่จาก SAM', 'แผนที่จาก SAM', 'https://npa.sam.or.th/site/images/npa/19956/20220506100837_3A1407M1_65.jpg', '/listing-media/sam/3a1407/23.webp', 'image/webp', 55638, 785, 600, 230, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=19956&keyref=', '3A1407', now(), 'Checked2026-09-15. THB167848000,194sq.wah,4NS3Gor titles. Closed Blue Sky Patong,105surveyed rooms,7floors/10connected units. Public drain at west boundary,not unrestricted road frontage.2017 source building rules attributed;current compliance/licence not confirmed.23authentic images2021–2022,navigation/map agree. Duplicate query found only nearby distinct shophouses1283/1352;no matching asset.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Blue Sky Patong Hotel — 105 Rooms, Closed Business, THB167.848M', 'Blue Sky Patong Hotel,236/1–4 Phang Mueang Kor Road,Patong,Kathu,Phuket. Four adjoining plots total194sq.wah (776sq.m.),under Nor Sor3 Gor certificates7664,7665,7666 and7667. SAM announced whole-property sale price THB167,848,000,asset3A1407.

SAM describes conversion to a daily-rental hotel with105 guest rooms,fitness area,pool and restaurant,but expressly reports the business closed and unused. Room count and facilities are survey information,not confirmation of operational readiness. Current income,occupancy,hotel licence and building systems require verification.

Registered acquisition describes a hotel over five storeys at236/1,236/2,236/3,236/4. Survey describes ten connected seven-storey shophouse units with interconnected interiors. Total usable area,bathroom count and parking capacity are not published.

Polygonal plot,western side approximately45.54m adjoining a public drainage channel,maximum depth25.4m. Although the summary labels this road frontage,the detailed text and plan place a drainage channel on that side. Verify boundaries and legal access across the channel. Phang Mueang Kor Road is public according to SAM,approximately16m concrete carriageway and20m right of way.

SAM reports orange zoning and cites a2017 Ministry of Natural Resources and Environment notice for Area8:construction/alterations limited to23m height,minimum30% open space for detached/semi-detached houses,public buildings,collective residential or office buildings,and10% for rowhouses/shophouses/commercial buildings. These are source-attributed rules,not confirmation that the existing seven-storey hotel complies or has approvals. Verify current rules,building use,construction/alteration permits and hotel licence before purchase or reopening.

Tourism/hotel surroundings near Jungceylon,Bangla Road and Patong Beach per SAM. From Phra Barami Highway4029 toward the beach,pass Suwan Khiri Wong School,turn left into Phang Mueang Kor Road and continue past Ratchapathanuson junction;property on the left.

Twenty-three authentic source photos/plans from2021–2022;inspect current condition. Navigation/map agree7.897332,98.302809,reference pin not surveyed boundary. Price/direct-sale status checked15September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting3A1407.', '236/1–4 Blue Sky Patong Hotel', 'Phang Mueang Kor Road', 'Phang Mueang Kor Road', 'Patong', 'Kathu', 'Phuket', 'Blue Sky Patong Hotel — 105 Rooms, Closed Business, THB167.848M', 'Closed105-room Blue Sky Patong Hotel,776sqm land,THB167848000;NS3Gor titles,source building constraints and drainage boundary disclosed.', 'published', 'ai_assisted', now(), 'blue sky patong hotel — 105 rooms, closed business, thb167.848m blue sky patong hotel,236/1–4 phang mueang kor road,patong,kathu,phuket. four adjoining plots total194sq.wah (776sq.m.),under nor sor3 gor certificates7664,7665,7666 and7667. sam announced whole-property sale price thb167,848,000,asset3a1407.

sam describes conversion to a daily-rental hotel with105 guest rooms,fitness area,pool and restaurant,but expressly reports the business closed and unused. room count and facilities are survey information,not confirmation of operational readiness. current income,occupancy,hotel licence and building systems require verification.

registered acquisition describes a hotel over five storeys at236/1,236/2,236/3,236/4. survey describes ten connected seven-storey shophouse units with interconnected interiors. total usable area,bathroom count and parking capacity are not published.

polygonal plot,western side approximately45.54m adjoining a public drainage channel,maximum depth25.4m. although the summary labels this road frontage,the detailed text and plan place a drainage channel on that side. verify boundaries and legal access across the channel. phang mueang kor road is public according to sam,approximately16m concrete carriageway and20m right of way.

sam reports orange zoning and cites a2017 ministry of natural resources and environment notice for area8:construction/alterations limited to23m height,minimum30% open space for detached/semi-detached houses,public buildings,collective residential or office buildings,and10% for rowhouses/shophouses/commercial buildings. these are source-attributed rules,not confirmation that the existing seven-storey hotel complies or has approvals. verify current rules,building use,construction/alteration permits and hotel licence before purchase or reopening.

tourism/hotel surroundings near jungceylon,bangla road and patong beach per sam. from phra barami highway4029 toward the beach,pass suwan khiri wong school,turn left into phang mueang kor road and continue past ratchapathanuson junction;property on the left.

twenty-three authentic source photos/plans from2021–2022;inspect current condition. navigation/map agree7.897332,98.302809,reference pin not surveyed boundary. price/direct-sale status checked15september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting3a1407.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=19956&keyref=', 'Official SAM page 19956 identifies SAM as asset holder and direct-sale contact for 3A1407.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'edbd1407-4cac-4385-8f19-537806719956', '{"reference_code":"3A1407","source_page_id":19956,"source_image_count":23,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
