BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-22718'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='BTR003' OR source_url ~ '[?&]id=22718(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='821ab003-5ec8-4de4-b05e-409047622718' OR slug='sam-kham-ngern-holiday-homes-cha-am-btr003' OR (abs(latitude-12.780596)<0.0001 AND abs(longitude-99.978297)<0.0001 AND abs(land_area_sqm-8640)<1)) THEN RAISE NOTICE 'SAM BTR003 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, custom_project_name, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('821ab003-5ec8-4de4-b05e-409047622718', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'hotel_resort', 'business', 'sale', 'whole_property', 'บ้านพักขามเงิน ชะอำ ติดถนน 2 ด้าน 5 ไร่ 1 งาน 60 ตร.ว.', 'รายละเอียดทรัพย์

บ้านพักตากอากาศขามเงิน ถนนร่วมจิตต์ ตำบลชะอำ อำเภอชะอำ จังหวัดเพชรบุรี เนื้อที่รวมตามหน้า SAM 5 ไร่ 1 งาน 60 ตร.ว. หรือ 2,160 ตร.ว. (8,640 ตร.ม.) ราคาประกาศขาย SAM 167,244,000 บาท รหัส BTR003 เป็นการขายทั้งทรัพย์

ส่วนสรุปเอกสารสิทธิ์ระบุโฉนด 9029, 9030, 44861, 44862 และ 44863 รวม 5 ฉบับ แต่คำบรรยายระบุที่ดิน 8 แปลงติดกัน และมีเลข 44962 ในรายการสิ่งปลูกสร้าง ซึ่งต่างจากเลข 44862 ในส่วนสรุป จึงแสดงรายการโฉนดตามส่วนสรุปโดยไม่เพิ่มเลขที่ไม่ยืนยัน ผู้สนใจต้องยืนยันจำนวนแปลง เลขโฉนดและพื้นที่กับ SAM ก่อนเสนอซื้อ

ที่ดินตามคำบรรยายเป็นรูปสี่เหลี่ยมผืนผ้า ติดถนน 2 ด้าน ด้านตะวันออกและตะวันตกกว้างประมาณด้านละ 50 เมตร ลึกประมาณ 165 เมตร ด้านหน้าถนนร่วมจิตต์อยู่ฝั่งตรงข้ามชายหาดตามผัง SAM ไม่ใช่การขายชายหาดส่วนตัว ถนนร่วมจิตต์ตาม SAM เป็นทางสาธารณะ ผิวลาดยางกว้างประมาณ 8 เมตร เขตทางประมาณ 12 เมตร อีกด้านตามภาพเป็นถนนเจ้าลาย

สิ่งปลูกสร้างและเงื่อนไขการโอน

คำบรรยายสำรวจระบุบ้านพักตากอากาศชื่อบ้านพักขามเงิน รวม 13 หลัง ตัวเลขนี้เป็นจำนวนบ้านพักตามสำรวจ ไม่ใช่จำนวนห้องนอน และไม่ใช่การยืนยันว่าทุกหลังอยู่ในรายการโอน

รายการรับโอนบนโฉนด 9029 เป็นร้านอาหารและบ้านพักอาศัยชั้นเดียวที่ใช้เป็นร้านกาแฟสด บนโฉนด 9030 เป็นบ้านพักอาศัยชั้นเดียว 8 หลังและบ้านพักอาศัยชั้นเดียวอีก 1 หลัง บนโฉนด 44863 เป็นบ้านพักอาศัยชั้นเดียว ส่วนคำบรรยายระบุโฉนด 44861 และ 44962 ไม่มีสิ่งปลูกสร้าง โดยเลข 44962 ต้องตรวจสอบเทียบกับส่วนสรุปดังกล่าว

SAM กำหนดว่าจะโอนสิ่งปลูกสร้างตามรายการที่จดทะเบียนรับโอนเท่านั้น ผังสิ่งปลูกสร้างมีหลายรายการและระบุบางรายการรื้อถอนแล้ว จึงควรตรวจเทียบทะเบียน ผัง และสภาพจริงก่อนเสนอซื้อ ต้นทางไม่ยืนยันสถานะเปิดกิจการ รายได้ จำนวนห้องพัก ใบอนุญาตหรือสภาพภายในปัจจุบัน

ข้อควรทราบเรื่องการก่อสร้าง

SAM ระบุผังเมืองสีชมพู และอ้างประกาศกระทรวงทรัพยากรธรรมชาติและสิ่งแวดล้อม พ.ศ.2561 ว่าทรัพย์อยู่ในเขตควบคุมการก่อสร้างริมทะเลชะอำ ปลูกสร้างได้สูงไม่เกิน 12 เมตร ข้อมูลนี้เป็นข้อกำหนดที่ต้นทางอ้าง ไม่ใช่การยืนยันการอนุญาตก่อสร้าง ผู้สนใจควรตรวจข้อกำหนดปัจจุบัน แนวเขตและแผนพัฒนากับหน่วยงานก่อนตัดสินใจ

ทำเลและการเดินทาง

อยู่ในย่านที่อยู่อาศัยและแหล่งท่องเที่ยว ใกล้ชายหาดชะอำ โรงพยาบาลชะอำ โรงเรียนเทศบาล 8 สวนสนชะอำและคริสตจักรชะอำ ตาม SAM จากท่ายางมุ่งหน้าหัวหินบนถนนเพชรเกษม (ทล.4) ผ่านวนอุทยานชะอำ เลี้ยวซ้ายเข้าถนนหนองแจงไปทางชายหาด แล้วเลี้ยวซ้ายเข้าถนนร่วมจิตต์ ผ่านซอยชะอำใต้ 6 ทรัพย์อยู่ซ้ายมือ

ภาพและข้อมูลต้นทาง

ภาพจริงและผังจาก SAM รวม 9 ภาพ ภาพภายนอกแสดงวันที่ 28 กุมภาพันธ์ 2568 ควรตรวจสภาพปัจจุบัน พิกัด 12.780596, 99.978297 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์แผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ราคาและสถานะซื้อตรงตรวจวันที่ 15 กันยายน 2569 ติดต่อ SAM 02-686-1888, sales@sam.or.th หรือ LINE @samline แจ้งรหัส BTR003 เพื่อยืนยันเอกสารสิทธิ์ สิ่งปลูกสร้าง ราคาและเงื่อนไขล่าสุด', 167244000, false, 8640, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'บ้านพักขามเงิน', 'บ้านพักขามเงิน ถนนร่วมจิตต์', 'อีกด้านติดถนนเจ้าลายตามภาพต้นทาง', 'ถนนร่วมจิตต์', 12.780596, 99.978297, 'เพชรบุรี', 'ชะอำ', 'ชะอำ', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-kham-ngern-holiday-homes-cha-am-btr003') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'hospitality') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 167244000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'hotel_resort', 1, '{"source_property_category":"โรงแรม/รีสอร์ท","official_page_reference_code":"BTR003","source_page_id":22718,"map_filename_alternate_reference":"LL0052","title_document_type":"chanote","summary_title_document_numbers":["9029","9030","44861","44862","44863"],"summary_document_count":5,"narrative_plot_count":8,"source_plot_count_conflict":true,"narrative_unconfirmed_deed_number":"44962","summary_corresponding_deed_number":"44862","source_deed_number_conflict":true,"land_area_square_wah":2160,"land_area_sqm":8640,"surveyed_holiday_house_count":13,"guest_room_count_not_published":true,"bedroom_count_not_published":true,"registered_inventory_only_transfer":true,"plan_has_demolished_structures":true,"current_operating_status_not_confirmed":true,"road_frontage_sides":2,"east_frontage_m_approx":50,"west_frontage_m_approx":50,"depth_m_approx":165,"beach_separated_by_public_road":true,"road_width_m_approx":8,"right_of_way_m_approx":12,"planning_zone_th":"สีชมพู","source_environmental_notice_year_be":2561,"source_building_height_limit_m":12,"current_rules_require_verification":true,"status_checked_on":"2026-09-15","source_field_photo_date":"2025-02-28","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//12.780596,99.978297","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 22718 identifies SAM as direct-sale contact for BTR003, Kham Ngern holiday homes in Cha-am,registered-inventory-only transfer.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ ซื้อตรง SAM BTR003 ราคา167,244,000บาท', 'Whole property SAM BTR003 THB167244000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'source_discrepancies', 'ตรวจสอบข้อมูลโฉนดที่ไม่ตรงกัน', 'Source title discrepancies', 'สรุป5ฉบับแต่คำบรรยาย8แปลง และ44862/44962ไม่ตรงกัน ต้องยืนยันกับ SAM', 'Summary5titles vs narrative8plots;44862/44962 mismatch,verify with SAM', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_inventory_only', 'โอนเฉพาะตามทะเบียน', 'Registered inventory only', 'สำรวจบ้านพัก13หลัง แต่โอนเฉพาะรายการที่ SAM จดทะเบียนรับโอน', '13houses surveyed;only registered acquisition structures transferred', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'source_height_limit', 'ข้อจำกัดความสูงตามต้นทาง', 'Source height restriction', 'SAM อ้างประกาศปี2561 สูงไม่เกิน12ม. ต้องตรวจข้อกำหนดปัจจุบัน', 'SAM cites2018 coastal notice,height≤12m;verify current rules', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'บ้านพักขามเงินด้านถนนร่วมจิตต์', 'บ้านพักขามเงินด้านถนนร่วมจิตต์', 'https://npa.sam.or.th/site/images/npa/22718/20250926094453_BTR003P3_68.jpg', '/listing-media/sam/btr003/01.webp', 'image/webp', 35694, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวหน้าทรัพย์ริมถนนร่วมจิตต์', 'แนวหน้าทรัพย์ริมถนนร่วมจิตต์', 'https://npa.sam.or.th/site/images/npa/22718/BTR003P1_68.jpg', '/listing-media/sam/btr003/02.webp', 'image/webp', 26750, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ด้านหน้าทรัพย์อีกมุม', 'ด้านหน้าทรัพย์อีกมุม', 'https://npa.sam.or.th/site/images/npa/22718/BTR003P2_68.jpg', '/listing-media/sam/btr003/03.webp', 'image/webp', 32426, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวทรัพย์ติดถนนเจ้าลาย', 'แนวทรัพย์ติดถนนเจ้าลาย', 'https://npa.sam.or.th/site/images/npa/22718/BTR003P4_68.jpg', '/listing-media/sam/btr003/04.webp', 'image/webp', 33850, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'มุมทางเข้าด้านถนนเจ้าลาย', 'มุมทางเข้าด้านถนนเจ้าลาย', 'https://npa.sam.or.th/site/images/npa/22718/BTR003P5_68.jpg', '/listing-media/sam/btr003/05.webp', 'image/webp', 31788, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'กำแพงและแนวถนนอีกด้าน', 'กำแพงและแนวถนนอีกด้าน', 'https://npa.sam.or.th/site/images/npa/22718/BTR003P6_68.jpg', '/listing-media/sam/btr003/06.webp', 'image/webp', 21044, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดินและถนนคั่นชายหาดจาก SAM', 'ผังที่ดินและถนนคั่นชายหาดจาก SAM', 'https://npa.sam.or.th/site/images/npa/22718/20250926094453_BTR003C2_68.jpg', '/listing-media/sam/btr003/07.webp', 'image/webp', 29132, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังสิ่งปลูกสร้าง มีรายการรื้อถอน ไม่ยืนยันว่าโอนครบ', 'ผังสิ่งปลูกสร้าง มีรายการรื้อถอน ไม่ยืนยันว่าโอนครบ', 'https://npa.sam.or.th/site/images/npa/22718/20250926094453_BTR003C1_68.jpg', '/listing-media/sam/btr003/08.webp', 'image/webp', 41350, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่จาก SAM', 'แผนที่จาก SAM', 'https://npa.sam.or.th/site/images/npa/22718/20250926094453_BTR003M_68(LL0052).jpg', '/listing-media/sam/btr003/09.webp', 'image/webp', 58570, 785, 600, 90, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=22718&keyref=', 'BTR003', now(), 'Checked2026-09-15. THB167244000,8640sqm. Summary5titles vs narrative8plots;44862/44962 mismatch retained for verification.13surveyed houses not room count;registered inventory only transfer. Coastal2018 source height12m,current rules unconfirmed.9authentic photos/plans,field date2025-02-28. Navigation/map agree. Source/page/deed/nearby duplicate query and map filenameLL0052 alias search empty.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Kham Ngern Holiday Homes, Cha-am — Two Road Frontages, THB167.244M', 'Kham Ngern holiday-home property on Ruam Chit Road,Cha-am,Phetchaburi. SAM summary area5 rai1 ngan60sq.wah,or2,160sq.wah (8,640sq.m.). Whole-property announced price THB167,244,000,asset BTR003.

Source discrepancy: summary lists five Chanote certificates9029,9030,44861,44862,44863,while narrative says eight adjoining plots and mentions44962 instead of44862 in the building inventory. Listed title numbers follow the summary; no unconfirmed title is added. Verify plot count,title numbers and area with SAM.

Narrative describes a rectangular site with roads on two sides,approximately50m east/west frontage and165m depth. The source plan places Ruam Chit Road between the property and beach; no private-beach ownership is claimed. SAM describes Ruam Chit as public,8m paved carriageway and12m right of way. The opposite road is labelled Chao Lai in source photos.

Survey describes13 holiday houses called Kham Ngern. This is a house count,not bedroom/guest-room count or confirmation all are transferred. Registered inventory: restaurant and single-storey house used as coffee shop on9029;eight single-storey houses plus another single-storey house on9030;one single-storey house on44863. Narrative says44861 and44962 have no buildings,the latter requiring reconciliation with summary44862.

SAM explicitly transfers only structures in its registered acquisition inventory. The building plan lists multiple structures,some labelled demolished. Reconcile registration,plan and current condition before purchase. Current operating status,income,room count,licences and interior condition are not confirmed by source.

SAM reports pink zoning and cites a2018 environmental-protection notice for Cha-am coastal construction limiting height to12m. This is source-attributed information,not confirmation of permission;verify current rules,boundaries and proposed development with authorities.

Residential/tourism surroundings near Cha-am Beach,Cha-am Hospital,municipal school8 Suan Son and Cha-am church. From Tha Yang toward Hua Hin on Phetkasem Highway4,past Cha-am Forest Park,turn left into Nong Chaeng Road toward the beach,then left into Ruam Chit Road,past Cha-am Tai6;property left.

Nine authentic source images/plans,exterior photos dated28 February2025. Navigation/map agree12.780596,99.978297,reference pin not surveyed boundary. Price/direct-sale status checked15 September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting BTR003 to confirm deeds,structures,price and terms.', 'Kham Ngern Holiday Homes, Ruam Chit Road', 'Opposite side on Chao Lai Road per source photos', 'Ruam Chit Road', 'Cha-am', 'Cha-am', 'Phetchaburi', 'Kham Ngern Holiday Homes, Cha-am — Two Road Frontages, THB167.244M', 'Kham Ngern holiday homes8640sqm,THB167244000;title discrepancies,registered-only transfer and source coastal height restriction disclosed.', 'published', 'ai_assisted', now(), 'kham ngern holiday homes, cha-am — two road frontages, thb167.244m kham ngern holiday-home property on ruam chit road,cha-am,phetchaburi. sam summary area5 rai1 ngan60sq.wah,or2,160sq.wah (8,640sq.m.). whole-property announced price thb167,244,000,asset btr003.

source discrepancy: summary lists five chanote certificates9029,9030,44861,44862,44863,while narrative says eight adjoining plots and mentions44962 instead of44862 in the building inventory. listed title numbers follow the summary; no unconfirmed title is added. verify plot count,title numbers and area with sam.

narrative describes a rectangular site with roads on two sides,approximately50m east/west frontage and165m depth. the source plan places ruam chit road between the property and beach; no private-beach ownership is claimed. sam describes ruam chit as public,8m paved carriageway and12m right of way. the opposite road is labelled chao lai in source photos.

survey describes13 holiday houses called kham ngern. this is a house count,not bedroom/guest-room count or confirmation all are transferred. registered inventory: restaurant and single-storey house used as coffee shop on9029;eight single-storey houses plus another single-storey house on9030;one single-storey house on44863. narrative says44861 and44962 have no buildings,the latter requiring reconciliation with summary44862.

sam explicitly transfers only structures in its registered acquisition inventory. the building plan lists multiple structures,some labelled demolished. reconcile registration,plan and current condition before purchase. current operating status,income,room count,licences and interior condition are not confirmed by source.

sam reports pink zoning and cites a2018 environmental-protection notice for cha-am coastal construction limiting height to12m. this is source-attributed information,not confirmation of permission;verify current rules,boundaries and proposed development with authorities.

residential/tourism surroundings near cha-am beach,cha-am hospital,municipal school8 suan son and cha-am church. from tha yang toward hua hin on phetkasem highway4,past cha-am forest park,turn left into nong chaeng road toward the beach,then left into ruam chit road,past cha-am tai6;property left.

nine authentic source images/plans,exterior photos dated28 february2025. navigation/map agree12.780596,99.978297,reference pin not surveyed boundary. price/direct-sale status checked15 september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting btr003 to confirm deeds,structures,price and terms.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=22718&keyref=', 'Official SAM page 22718 identifies SAM as asset holder and direct-sale contact for BTR003.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', '821ab003-5ec8-4de4-b05e-409047622718', '{"reference_code":"BTR003","source_page_id":22718,"source_image_count":9,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
