BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20532'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A1464' OR source_url ~ '[?&]id=20532(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='f1451464-505a-418b-b2ef-691548920532' OR slug='sam-thanarat-pak-chong-resort-79-rooms-3a1464' OR (abs(latitude-14.611394)<0.0001 AND abs(longitude-101.405673)<0.0001 AND abs(land_area_sqm-16484)<1)) THEN RAISE NOTICE 'SAM 3A1464 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, custom_unit_number, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('f1451464-505a-418b-b2ef-691548920532', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'hotel_resort', 'business', 'sale', 'whole_property', 'ทรัพย์ที่พักถนนธนะรัชต์ ปากช่อง 79 ห้องตามสำรวจ 10 ไร่ 1 งาน 21 ตร.ว.', 'รายละเอียดทรัพย์

ทรัพย์โรงแรม/รีสอร์ท เลขที่ 135/1 หมู่ 6 ถนนธนะรัชต์ (ทล.2090) ตำบลหนองน้ำแดง อำเภอปากช่อง จังหวัดนครราชสีมา โฉนดเลขที่ 62953 จำนวน 1 ฉบับ เนื้อที่ 10 ไร่ 1 งาน 21 ตร.ว. หรือ 4,121 ตร.ว. (16,484 ตร.ม.) ราคาประกาศขาย SAM 164,455,000 บาท รหัส 3A1464 เป็นการขายทั้งทรัพย์

ข้อมูลสำรวจระบุห้องพักรวม 79 ห้อง แบ่งเป็นห้องแอร์เล็ก 16 ห้อง ห้องแอร์มาตรฐาน 23 ห้อง Deluxe 26 ห้อง และ Grand Deluxe 14 ห้อง เป็นจำนวนตามสำรวจ ไม่ใช่การรับรองสภาพพร้อมให้บริการ ต้นทางไม่ยืนยันสถานะเปิดกิจการ รายได้ ผู้เช่า ใบอนุญาตโรงแรม หรือพื้นที่ใช้สอยรวมปัจจุบัน

สิ่งปลูกสร้างและที่ดิน

ทะเบียนรับโอนระบุสิ่งปลูกสร้าง 26 รายการ ประกอบด้วยบ้านพักอาศัย 1–2 ชั้นหลายหลัง รวมอาคารร้านอาหารและห้องพัก 2 ชั้น อาคารพักอาศัยรวม 3 ชั้น ห้องน้ำรวม ศาลาอเนกประสงค์ ศาลาพักผ่อน สระว่ายน้ำ ป้อมยาม และลานคอนกรีต/ถนน ไม่ควรตีความเป็นบ้านพัก 26 หลัง เนื่องจากรายการรวมสาธารณูปโภคและพื้นที่ภายนอกด้วย

แปลงรูปคล้ายสี่เหลี่ยมผืนผ้า ด้านตะวันตกติดถนนกว้างประมาณ 48 เมตร ลึกประมาณ 344 เมตร ถนนธนะรัชต์ตาม SAM เป็นทางสาธารณะ ผิวลาดยางกว้างประมาณ 16 เมตร เขตทางประมาณ 60 เมตร ควรตรวจสภาพอาคาร ระบบไฟฟ้า ประปา สระว่ายน้ำและรายการที่รวมในการโอนจริงก่อนเสนอซื้อ

ข้อควรทราบเกี่ยวกับเอกสารสิทธิ์

SAM ระบุว่าทรัพย์ตั้งอยู่ในเขตพื้นที่ ส.ป.ก. ตามพระราชกฤษฎีกาวันที่ 8 ธันวาคม 2534 และมีที่มาจาก น.ส.3 เลขที่ 5 หน้า 188 หมู่ 6 ออกวันที่ 15 มีนาคม 2509 ซึ่งก่อนการประกาศเขตดังกล่าว ปัจจุบันส่วนสรุประบุเอกสารเป็นโฉนดเลขที่ 62953 ข้อมูลลำดับวันที่นี้ไม่ใช่การยืนยันว่าทรัพย์ไม่มีข้อจำกัดหรือข้อพิพาท ผู้สนใจควรตรวจที่มาของโฉนด แนวเขต สถานะสิทธิและข้อกำหนดการใช้ประโยชน์กับหน่วยงานที่เกี่ยวข้องก่อนเสนอซื้อ

สีผังเมืองตามหัวข้อ SAM ระบุสีขาวมีกรอบและเส้นทแยงสีเขียว ควรตรวจประเภทและข้อกำหนดตามผังปัจจุบัน ไม่อนุมานสิทธิประกอบกิจการโรงแรมจากการจัดหมวดประกาศเพียงอย่างเดียว

ทำเลและการเดินทาง

ตั้งอยู่ในย่านที่อยู่อาศัย พาณิชยกรรมและแหล่งท่องเที่ยว ใกล้อุทยานแห่งชาติเขาใหญ่ ที่ว่าการอำเภอปากช่อง วัดโป่งกะสังและ อบต.หนองน้ำแดง ตามข้อมูล SAM จากถนนมิตรภาพเข้าถนนธนะรัชต์มุ่งหน้าเขาใหญ่ ผ่านไทวัสดุ แม็คโคร อบต.หนองน้ำแดง วัดบ้านนาและโรงเรียนเซนต์สตีเฟ่น อินเตอร์ฯ ถึงประมาณ กม.7 ทรัพย์อยู่ซ้ายมือ

ภาพและข้อมูลต้นทาง

ภาพจริงและผังจาก SAM รวม 20 ภาพ เป็นภาพต่างช่วงปี 2565–2566 มีภาพอาคาร พื้นที่สวน ห้องน้ำ สระว่ายน้ำ ผังสิ่งปลูกสร้างและแผนที่ ควรตรวจสภาพปัจจุบัน ภาพด้านข้างที่ติดปั๊มน้ำมันเป็นบริเวณโดยรอบ ไม่รวมปั๊มน้ำมันในรายการขาย

พิกัด 14.611394, 101.405673 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์แผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ราคาและสถานะซื้อตรงตรวจวันที่ 15 กันยายน 2569 ติดต่อ SAM 02-686-1888, sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A1464 เพื่อยืนยันเอกสารสิทธิ์ ราคา สภาพและเงื่อนไขล่าสุด', 164455000, false, 16484, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '135/1', '135/1 หมู่ 6 ถนนธนะรัชต์', 'บริเวณ ทล.2090 กม.7', 'ถนนธนะรัชต์ (ทล.2090)', 14.611394, 101.405673, 'นครราชสีมา', 'ปากช่อง', 'หนองน้ำแดง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-thanarat-pak-chong-resort-79-rooms-3a1464') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'hospitality') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 164455000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'hotel_resort', 1, '{"source_property_category":"โรงแรม/รีสอร์ท","official_page_reference_code":"3A1464","source_page_id":20532,"title_document_type":"chanote","title_deed_number":"62953","title_document_count":1,"land_area_square_wah":4121,"land_area_sqm":16484,"surveyed_guest_room_count":79,"room_count":79,"surveyed_room_types":{"small_aircon":16,"standard_aircon":23,"deluxe_aircon":26,"grand_deluxe_aircon":14},"registered_inventory_entry_count":26,"inventory_includes_non_accommodation_structures":true,"current_operating_status_not_confirmed":true,"current_hotel_licence_and_income_not_confirmed":true,"west_frontage_m_approx":48,"depth_m_approx":344,"road_width_m_approx":16,"right_of_way_m_approx":60,"planning_colour_source_th":"สีขาวมีกรอบมีเส้นทะแยงสีเขียว","agricultural_land_reform_area_according_to_sam":true,"land_reform_decree_date":"1991-12-08","predecessor_document_type":"nor_sor_3","predecessor_document_number":"5","predecessor_document_page":188,"predecessor_document_moo":6,"predecessor_document_date":"1966-03-15","current_title_rights_require_verification":true,"neighbouring_petrol_station_not_included":true,"status_checked_on":"2026-09-15","source_photo_years":[2022,2023],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//14.611394,101.405673","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20532 identifies SAM as direct-sale contact for 3A1464, Thanarat Road hotel/resort property with79surveyed rooms in Pak Chong.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ SAM3A1464 ราคา164,455,000บาท', 'Whole property SAM3A1464 THB164455000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'land_reform_area', 'ประเด็นเขต ส.ป.ก.', 'Land-reform area disclosure', 'SAM ระบุเขตตามพระราชกฤษฎีกา8ธ.ค.2534 มีที่มาจาก น.ส.3 ออก15มี.ค.2509 ต้องตรวจสิทธิและข้อจำกัด', 'SAM cites1991 land-reform area and1966 predecessorNS3;verify rights/restrictions', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'surveyed_rooms', 'จำนวนห้องตามสำรวจ', 'Surveyed room count', '79ห้อง:เล็ก16 มาตรฐาน23 Deluxe26 Grand Deluxe14 ไม่รับรองความพร้อมเปิด', '79surveyed rooms:16small,23standard,26Deluxe,14GrandDeluxe;readiness unconfirmed', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_inventory', 'สิ่งปลูกสร้างตามทะเบียน', 'Registered inventory', '26รายการรวมอาคาร สระ ศาลา ห้องน้ำ ป้อมยามและลาน/ถนน ไม่ใช่บ้านพัก26หลัง', '26entries include buildings,pool,pavilions,toilets,guardhouse andyard/roads;not26guest houses', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'หน้าทรัพย์ติดถนนธนะรัชต์', 'หน้าทรัพย์ติดถนนธนะรัชต์', 'https://npa.sam.or.th/site/images/npa/20532/20260105110858_P1_66.jpg', '/listing-media/sam/3a1464/01.webp', 'image/webp', 43928, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวถนนและหน้าทรัพย์', 'แนวถนนและหน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/20532/P2_66.jpg', '/listing-media/sam/3a1464/02.webp', 'image/webp', 31226, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าและอาคารด้านหน้า', 'ทางเข้าและอาคารด้านหน้า', 'https://npa.sam.or.th/site/images/npa/20532/P3_66.jpg', '/listing-media/sam/3a1464/03.webp', 'image/webp', 43530, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำรวมตามสภาพ', 'ห้องน้ำรวมตามสภาพ', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P6_65.jpg', '/listing-media/sam/3a1464/04.webp', 'image/webp', 41382, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บ้านพักชั้นเดียว', 'บ้านพักชั้นเดียว', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P8_65.jpg', '/listing-media/sam/3a1464/05.webp', 'image/webp', 65022, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารที่พักด้านหน้า', 'อาคารที่พักด้านหน้า', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P9_65.jpg', '/listing-media/sam/3a1464/06.webp', 'image/webp', 60028, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำภายใน', 'ห้องน้ำภายใน', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P11_65.jpg', '/listing-media/sam/3a1464/07.webp', 'image/webp', 17866, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บ้านพักและทางเดิน', 'บ้านพักและทางเดิน', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P12_65.jpg', '/listing-media/sam/3a1464/08.webp', 'image/webp', 51216, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารและแนวทางเดิน', 'อาคารและแนวทางเดิน', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P13_65.jpg', '/listing-media/sam/3a1464/09.webp', 'image/webp', 53908, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารที่พักสองชั้น', 'อาคารที่พักสองชั้น', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P14_65.jpg', '/listing-media/sam/3a1464/10.webp', 'image/webp', 51994, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บ้านพักและเฉลียง', 'บ้านพักและเฉลียง', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P15_65.jpg', '/listing-media/sam/3a1464/11.webp', 'image/webp', 47724, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ศาลาและบริเวณสระ', 'ศาลาและบริเวณสระ', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P16_65.jpg', '/listing-media/sam/3a1464/12.webp', 'image/webp', 60926, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณสระตามสภาพ', 'บริเวณสระตามสภาพ', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P17_65.jpg', '/listing-media/sam/3a1464/13.webp', 'image/webp', 50388, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บ้านพักอีกหลัง', 'บ้านพักอีกหลัง', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P18_65.jpg', '/listing-media/sam/3a1464/14.webp', 'image/webp', 56014, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารที่พักอีกมุม', 'อาคารที่พักอีกมุม', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P19_65.jpg', '/listing-media/sam/3a1464/15.webp', 'image/webp', 47766, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารด้านใน', 'อาคารด้านใน', 'https://npa.sam.or.th/site/images/npa/20532/3A1464P20_65.jpg', '/listing-media/sam/3a1464/16.webp', 'image/webp', 54490, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณข้างทรัพย์ติดปั๊มน้ำมัน ไม่รวมปั๊มในรายการขาย', 'บริเวณข้างทรัพย์ติดปั๊มน้ำมัน ไม่รวมปั๊มในรายการขาย', 'https://npa.sam.or.th/site/images/npa/20532/P4_66.jpg', '/listing-media/sam/3a1464/17.webp', 'image/webp', 28120, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด62953', 'ผังแปลงโฉนด62953', 'https://npa.sam.or.th/site/images/npa/20532/20221129135442_3A1464C1_65.jpg', '/listing-media/sam/3a1464/18.webp', 'image/webp', 14428, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังสิ่งปลูกสร้าง26รายการ', 'ผังสิ่งปลูกสร้าง26รายการ', 'https://npa.sam.or.th/site/images/npa/20532/20221129135442_3A1464C2_65.jpg', '/listing-media/sam/3a1464/19.webp', 'image/webp', 37646, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่จาก SAM', 'แผนที่จาก SAM', 'https://npa.sam.or.th/site/images/npa/20532/20221129135442_3A1464M_65.jpg', '/listing-media/sam/3a1464/20.webp', 'image/webp', 41414, 785, 600, 200, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20532&keyref=', '3A1464', now(), 'Checked2026-09-15. THB164455000,Chanote62953,16484sqm,79surveyed rooms(16+23+26+14),26registered entries including non-guest structures. SAM land-reform area1991/predecessorNS3issued1966 disclosed without certifying rights. Operating status/licence/income unconfirmed.20authentic images2022–2023,navigation/map agree. No all-status source/page/deed/nearby duplicate matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Thanarat Road Resort Property, Pak Chong — 79 Surveyed Rooms, THB164.455M', 'Hotel/resort property135/1 Moo6,Thanarat Road (Highway2090),Nong Nam Daeng,Pak Chong,Nakhon Ratchasima. One Chanote62953,total10 rai1 ngan21sq.wah,or4,121sq.wah (16,484sq.m.). SAM announced whole-property price THB164,455,000,asset3A1464.

Survey reports79 rooms:16 small air-conditioned,23 standard,26 Deluxe and14 Grand Deluxe. These are surveyed counts,not operational readiness. Current opening status,income,occupancy,hotel licence and total usable area are not confirmed by source.

Registered acquisition comprises26 entries including multiple one/two-storey residential buildings,a two-storey restaurant/rooms building,a three-storey collective residential building,shared toilets,multipurpose/rest pavilions,pool,guardhouse and concrete yard/roads. This is not26 guest houses;inventory includes facilities and external areas. Roughly rectangular plot,48m western road frontage and344m depth. SAM describes public Thanarat Road,16m paved carriageway and60m right of way. Inspect buildings,utilities,pool and transfer inventory.

Material title disclosure: SAM reports the site lies within an agricultural land-reform area under a Royal Decree dated8 December1991. Its predecessor document was NS3 number5,page188,Moo6,issued15 March1966,before that designation. Current summary lists Chanote62953. This chronology does not confirm absence of restrictions/disputes. Verify title provenance,boundaries,rights and permitted use with relevant authorities before purchase. Source zoning colour is white with green border/diagonal lines;confirm current classification and rules. Hotel marketing category does not itself establish operating permission.

Residential/commercial/tourism surroundings near Khao Yai National Park,Pak Chong district office,Wat Pong Kasang and Nong Nam Daeng local administration. From Mittraphap Road toward Khao Yai along Thanarat,pass Thai Watsadu,Makro,local administration,Wat Ban Na and St.Stephen''s International School to aroundkm7,property left.

Twenty authentic source photos/plans from2022–2023. Neighbouring petrol-station photo is context,not inclusion in sale. Navigation/map agree14.611394,101.405673,reference point not surveyed boundary. Price/direct-sale status checked15 September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting3A1464.', '135/1 Moo6, Thanarat Road', 'Highway2090 aroundkm7', 'Thanarat Road (Highway2090)', 'Nong Nam Daeng', 'Pak Chong', 'Nakhon Ratchasima', 'Thanarat Road Resort Property, Pak Chong — 79 Surveyed Rooms, THB164.455M', 'Thanarat Road resort property79surveyed rooms,16484sqm,THB164455000;land-reform area and predecessor title disclosed.', 'published', 'ai_assisted', now(), 'thanarat road resort property, pak chong — 79 surveyed rooms, thb164.455m hotel/resort property135/1 moo6,thanarat road (highway2090),nong nam daeng,pak chong,nakhon ratchasima. one chanote62953,total10 rai1 ngan21sq.wah,or4,121sq.wah (16,484sq.m.). sam announced whole-property price thb164,455,000,asset3a1464.

survey reports79 rooms:16 small air-conditioned,23 standard,26 deluxe and14 grand deluxe. these are surveyed counts,not operational readiness. current opening status,income,occupancy,hotel licence and total usable area are not confirmed by source.

registered acquisition comprises26 entries including multiple one/two-storey residential buildings,a two-storey restaurant/rooms building,a three-storey collective residential building,shared toilets,multipurpose/rest pavilions,pool,guardhouse and concrete yard/roads. this is not26 guest houses;inventory includes facilities and external areas. roughly rectangular plot,48m western road frontage and344m depth. sam describes public thanarat road,16m paved carriageway and60m right of way. inspect buildings,utilities,pool and transfer inventory.

material title disclosure: sam reports the site lies within an agricultural land-reform area under a royal decree dated8 december1991. its predecessor document was ns3 number5,page188,moo6,issued15 march1966,before that designation. current summary lists chanote62953. this chronology does not confirm absence of restrictions/disputes. verify title provenance,boundaries,rights and permitted use with relevant authorities before purchase. source zoning colour is white with green border/diagonal lines;confirm current classification and rules. hotel marketing category does not itself establish operating permission.

residential/commercial/tourism surroundings near khao yai national park,pak chong district office,wat pong kasang and nong nam daeng local administration. from mittraphap road toward khao yai along thanarat,pass thai watsadu,makro,local administration,wat ban na and st.stephen''s international school to aroundkm7,property left.

twenty authentic source photos/plans from2022–2023. neighbouring petrol-station photo is context,not inclusion in sale. navigation/map agree14.611394,101.405673,reference point not surveyed boundary. price/direct-sale status checked15 september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting3a1464.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20532&keyref=', 'Official SAM page 20532 identifies SAM as asset holder and direct-sale contact for 3A1464.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'f1451464-505a-418b-b2ef-691548920532', '{"reference_code":"3A1464","source_page_id":20532,"source_image_count":20,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
