BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-19806'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A0407' OR source_url ~ '[?&]id=19806(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='c5400407-69dd-45a6-977c-618665519806' OR slug='sam-na-san-phra-phrom-land-59-rai-3a0407' OR (abs(latitude-8.376831)<0.0001 AND abs(longitude-99.92149)<0.0001 AND abs(land_area_sqm-95820)<1)) THEN RAISE NOTICE 'SAM 3A0407 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('c5400407-69dd-45a6-977c-618665519806', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'ที่ดิน 59 ไร่ 3 งาน 55 ตร.ว. ติด ทล.4103 นาสาร พระพรหม', 'รายละเอียดทรัพย์

ที่ดินเปล่า 11 แปลงติดต่อกัน ถนนสายนาพรุ–ปากพูน (ทล.4103) ตำบลนาสาร อำเภอพระพรหม จังหวัดนครศรีธรรมราช เนื้อที่รวม 59 ไร่ 3 งาน 55 ตร.ว. หรือ 23,955 ตร.ว. (95,820 ตร.ม.) ราคาประกาศขายทั้งทรัพย์ 123,129,000 บาท รหัส SAM 3A0407 เอกสารสิทธิ์โฉนดเลขที่ 23020, 23021, 23022, 23026, 23028, 23029, 23030, 23328, 25580, 26146 และ 28889 รวม 11 ฉบับ

ลักษณะที่ดินและการเข้าถึง

แปลงรวมรูปหลายเหลี่ยม ด้านตะวันออกติดถนนกว้างประมาณ 190 เมตร ลึกสุดประมาณ 557 เมตร ระดับที่ดินต่ำกว่าถนนประมาณ 1 เมตร ภายในมีบ่อน้ำขนาดประมาณ 18 × 60 เมตร ลึกประมาณ 1.5–2 เมตร SAM ระบุพื้นที่บ่อประมาณ 2 งาน 71 ตร.ว. ตัวเลขขนาดและพื้นที่เป็นค่าประมาณจากต้นทาง ควรตรวจสภาพ ระดับดิน การระบายน้ำและเนื้อที่ใช้งานจริง

ถนนหน้าทรัพย์เป็นทางสาธารณประโยชน์ ผิวลาดยางกว้างประมาณ 18 เมตร เขตทางประมาณ 100 เมตร ตาม SAM ตั้งอยู่ในย่านที่อยู่อาศัยและอุตสาหกรรม จากอำเภอหัวไทรมุ่งหน้าท่าศาลาทาง ทล.4103 ขึ้นสะพานข้ามแยกนาพรุ ตรงไปประมาณ 3.4 กม. ถึงบริเวณ กม.21 ทรัพย์อยู่ซ้ายมือ

ข้อควรทราบก่อนเสนอซื้อ

ที่ตั้งในส่วนสรุปประกาศ SAM ระบุอำเภอพระพรหม แต่หน้าโฉนดระบุอำเภอเมืองนครศรีธรรมราช ตำบลนาสาร จังหวัดนครศรีธรรมราช ควรตรวจความสอดคล้องของเอกสารกับเขตปกครองและแนวเขตปัจจุบัน

SAM ระบุสีผังเมืองเป็นสีขาวมีกรอบและเส้นทแยงสีเขียว และระบุข้อบังคับควบคุมอาคารเรื่องระยะร่นจากเขตทางหลวงไม่น้อยกว่า 6 เมตร รวมถึงเทศบัญญัติเทศบาลตำบลนาสาร ข้อมูลนี้เป็นข้อระบุของต้นทาง ไม่ใช่การยืนยันสิทธิพัฒนาหรืออนุญาตก่อสร้าง ผู้สนใจควรตรวจผังเมือง ระยะร่นและข้อกำหนดที่ใช้บังคับปัจจุบันกับหน่วยงานที่เกี่ยวข้องตามโครงการที่ต้องการทำ

ภาพและการติดต่อ

ภาพจริงและผังจาก SAM คัดไม่ซ้ำ 10 ภาพ มีภาพลงวันที่ 24 มกราคม 2564 และ 24 มกราคม 2565 แสดงหน้าที่ดิน สภาพภายใน บ่อน้ำ ผังแปลงและแผนที่ ควรนัดดูสภาพปัจจุบัน ต้นทางไม่ยืนยันผู้ใช้ประโยชน์ ภาระผูกพันปัจจุบันหรือระบบสาธารณูปโภคภายในครบถ้วน

พิกัด 8.376831, 99.921490 ดึงจากลิงก์นำทาง SAM และตรงกับลิงก์แผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ตรวจราคาและสถานะซื้อตรงวันที่ 15 กันยายน 2569 ติดต่อ SAM โทร.02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A0407 เพื่อยืนยันราคา เอกสาร เนื้อที่และเงื่อนไขล่าสุด', 123129000, false, 95820, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ถนนสายนาพรุ–ปากพูน ทล.4103 กม.21', 'ที่ดิน 11 แปลงติดต่อกัน', 'ถนนสายนาพรุ–ปากพูน (ทล.4103)', 8.376831, 99.92149, 'นครศรีธรรมราช', 'พระพรหม', 'นาสาร', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-na-san-phra-phrom-land-59-rai-3a0407') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'agriculture') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 123129000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"ที่ดินเปล่า","official_page_reference_code":"3A0407","source_page_id":19806,"title_document_type":"chanote","title_document_count":11,"title_deed_numbers":["23020","23021","23022","23026","23028","23029","23030","23328","25580","26146","28889"],"plot_count":11,"adjoining_plots":true,"land_area_square_wah":23955,"land_area_sqm":95820,"source_price_per_square_wah_thb":5140,"east_frontage_m_approx":190,"max_depth_m_approx":557,"below_road_level_m_approx":1,"pond_width_m_approx":18,"pond_length_m_approx":60,"pond_depth_m_min_approx":1.5,"pond_depth_m_max_approx":2,"pond_area_square_wah_source":271,"road_width_m_approx":18,"right_of_way_m_approx":100,"source_highway_setback_m_min":6,"planning_colour_source_th":"สีขาวมีกรอบมีเส้นทแยงสีเขียว","title_address_district_th":"เมืองนครศรีธรรมราช","current_source_district_th":"พระพรหม","title_address_difference_disclosed":true,"current_planning_and_setbacks_require_verification":true,"status_checked_on":"2026-09-15","source_field_photo_dates":["2021-01-24","2022-01-24"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//8.376831,99.921490","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 19806 identifies SAM as direct-sale contact for 3A0407, Eleven adjoining land plots in Na San, Phra Phrom.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ SAM 3A0407 ราคา 123,129,000 บาท', 'Whole property SAM 3A0407 THB 123129000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'ground_and_pond', 'ระดับที่ดินและบ่อน้ำ', 'Ground level and pond', 'ต่ำกว่าถนนประมาณ 1 เมตร มีบ่อน้ำประมาณ 18×60 เมตร ลึก 1.5–2 เมตร ตาม SAM', 'Approximately 1 m below road; pond 18×60 m, depth 1.5–2 m per SAM', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'title_address', 'ที่ตั้งหน้าโฉนดต่างจากส่วนสรุป', 'Title address differs from summary', 'หน้าโฉนดระบุอำเภอเมืองนครศรีธรรมราช ส่วนสรุประบุอำเภอพระพรหม ควรตรวจข้อมูลปัจจุบัน', 'Title says Mueang Nakhon Si Thammarat; summary says Phra Phrom; verify current records', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'highway_setback', 'ข้อกำหนดระยะร่นตาม SAM', 'Source highway setback', 'SAM ระบุไม่น้อยกว่า 6 เมตรจากเขตทางหลวง และเทศบัญญัตินาสาร ต้องตรวจข้อกำหนดปัจจุบัน', 'SAM states at least 6 m from highway boundary and Na San ordinances; verify current rules', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'หน้าที่ดินติดถนนนาพรุ–ปากพูน', 'หน้าที่ดินติดถนนนาพรุ–ปากพูน', 'https://npa.sam.or.th/site/images/npa/19806/20231227153733_5_65.jpg', '/listing-media/sam/3a0407/01.webp', 'image/webp', 43110, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ป้ายทรัพย์และพื้นที่ด้านหน้า', 'ป้ายทรัพย์และพื้นที่ด้านหน้า', 'https://npa.sam.or.th/site/images/npa/19806/1.jpg', '/listing-media/sam/3a0407/02.webp', 'image/webp', 48532, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าที่ดินตามภาพต้นทาง', 'ทางเข้าที่ดินตามภาพต้นทาง', 'https://npa.sam.or.th/site/images/npa/19806/2.jpg', '/listing-media/sam/3a0407/03.webp', 'image/webp', 39380, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวถนนหน้าทรัพย์', 'แนวถนนหน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/19806/3.jpg', '/listing-media/sam/3a0407/04.webp', 'image/webp', 38236, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพภายในและแนวร่องน้ำ', 'สภาพภายในและแนวร่องน้ำ', 'https://npa.sam.or.th/site/images/npa/19806/6.jpg', '/listing-media/sam/3a0407/06.webp', 'image/webp', 81052, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในและพืชพรรณ', 'พื้นที่ภายในและพืชพรรณ', 'https://npa.sam.or.th/site/images/npa/19806/7.jpg', '/listing-media/sam/3a0407/07.webp', 'image/webp', 38302, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บ่อน้ำภายในที่ดิน', 'บ่อน้ำภายในที่ดิน', 'https://npa.sam.or.th/site/images/npa/19806/8.jpg', '/listing-media/sam/3a0407/08.webp', 'image/webp', 51238, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังโฉนด 11 แปลง', 'ผังโฉนด 11 แปลง', 'https://npa.sam.or.th/site/images/npa/19806/20230321140517_3A0407C2_65.jpg', '/listing-media/sam/3a0407/09.webp', 'image/webp', 25850, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังตำแหน่งบ่อน้ำ', 'ผังตำแหน่งบ่อน้ำ', 'https://npa.sam.or.th/site/images/npa/19806/20230607103407_3A0407C1_64.jpg', '/listing-media/sam/3a0407/10.webp', 'image/webp', 26632, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/19806/20211029230300_3A0407M_64.jpg', '/listing-media/sam/3a0407/11.webp', 'image/webp', 50276, 785, 600, 100, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=19806&keyref=', '3A0407', now(), 'Checked 2026-09-15. THB123129000,95820sqm,11adjoining Chanote plots. Land 1m below road; pond18x60m/depth1.5–2m, source area271sqwah. Title district Mueang versus summary Phra Phrom disclosed. Source highway setback6m and Na San ordinances require current verification.10unique original images/plans,photo dates2021-01-24/2022-01-24. Navigation/map agree. All-status source/code/page/deed/nearby duplicate search empty.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', '59 Rai Land on Highway 4103, Na San, Phra Phrom', 'Eleven adjoining vacant land plots on Na Phru–Pak Phun Road (Highway 4103), Na San, Phra Phrom, Nakhon Si Thammarat. Total 59 rai 3 ngan 55 sq.wah, or 23,955 sq.wah (95,820 sq.m.). SAM whole-property asking price THB 123,129,000, reference 3A0407. Eleven Chanote titles: 23020, 23021, 23022, 23026, 23028, 23029, 23030, 23328, 25580, 26146 and 28889.

Irregular combined plot with approximately 190 m eastern road frontage and maximum depth 557 m. Land is approximately 1 m below road level. Pond approximately 18 by 60 m, 1.5–2 m deep; SAM states approximately 271 sq.wah. Measurements are approximate; inspect actual usable area, ground levels and drainage. SAM describes a public paved road, approximately 18 m carriageway and 100 m right of way, in residential/industrial surroundings. From Hua Sai toward Tha Sala on Highway 4103, cross Na Phru junction flyover and continue approximately 3.4 km to km 21; property on left.

Source summary uses Phra Phrom district, whereas the title address states Mueang Nakhon Si Thammarat district, Na San. Verify documents against current administrative boundaries. SAM lists white zoning with green border and diagonal lines, a minimum 6 m building setback from the highway boundary and Na San municipal ordinances. These are source-attributed statements, not confirmation of development permission. Check current planning, setbacks and project-specific requirements with authorities.

Ten unique authentic source photos/plans include photos dated 24 January 2021 and 24 January 2022. Current occupancy, encumbrances and full on-site utilities are unconfirmed. Navigation and map agree at 8.376831, 99.921490, a reference point rather than surveyed boundaries. Direct-sale price/status checked 15 September 2026. Contact SAM at 02-686-1888, sales@sam.or.th or LINE @samline quoting 3A0407.', 'Na Phru–Pak Phun Highway 4103, km21', 'Eleven adjoining land plots', 'Na Phru–Pak Phun Highway 4103', 'Na San', 'Phra Phrom', 'Nakhon Si Thammarat', '59 Rai Land on Highway 4103, Na San, Phra Phrom', 'Eleven adjoining plots,95820sqm,THB123129000; pond, ground levels, title address difference and source setback disclosed.', 'published', 'ai_assisted', now(), '59 rai land on highway 4103, na san, phra phrom eleven adjoining vacant land plots on na phru–pak phun road (highway 4103), na san, phra phrom, nakhon si thammarat. total 59 rai 3 ngan 55 sq.wah, or 23,955 sq.wah (95,820 sq.m.). sam whole-property asking price thb 123,129,000, reference 3a0407. eleven chanote titles: 23020, 23021, 23022, 23026, 23028, 23029, 23030, 23328, 25580, 26146 and 28889.

irregular combined plot with approximately 190 m eastern road frontage and maximum depth 557 m. land is approximately 1 m below road level. pond approximately 18 by 60 m, 1.5–2 m deep; sam states approximately 271 sq.wah. measurements are approximate; inspect actual usable area, ground levels and drainage. sam describes a public paved road, approximately 18 m carriageway and 100 m right of way, in residential/industrial surroundings. from hua sai toward tha sala on highway 4103, cross na phru junction flyover and continue approximately 3.4 km to km 21; property on left.

source summary uses phra phrom district, whereas the title address states mueang nakhon si thammarat district, na san. verify documents against current administrative boundaries. sam lists white zoning with green border and diagonal lines, a minimum 6 m building setback from the highway boundary and na san municipal ordinances. these are source-attributed statements, not confirmation of development permission. check current planning, setbacks and project-specific requirements with authorities.

ten unique authentic source photos/plans include photos dated 24 january 2021 and 24 january 2022. current occupancy, encumbrances and full on-site utilities are unconfirmed. navigation and map agree at 8.376831, 99.921490, a reference point rather than surveyed boundaries. direct-sale price/status checked 15 september 2026. contact sam at 02-686-1888, sales@sam.or.th or line @samline quoting 3a0407.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=19806&keyref=', 'Official SAM page 19806 identifies SAM as asset holder and direct-sale contact for 3A0407.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'c5400407-69dd-45a6-977c-618665519806', '{"reference_code":"3A0407","source_page_id":19806,"source_image_count":10,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
