BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-5125'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='2T0797' OR source_url ~ '[?&]id=5125(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='d9000797-bb50-4371-ab7a-519316005125' OR slug='sam-ngamwongwan-26-land-buildings-2t0797' OR (abs(latitude-13.851588)<0.0001 AND abs(longitude-100.545763)<0.0001 AND abs(land_area_sqm-8692)<1)) THEN RAISE NOTICE 'SAM 2T0797 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('d9000797-bb50-4371-ab7a-519316005125', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'ที่ดินพร้อมกลุ่มอาคาร 5 ไร่ 1 งาน 73 ตร.ว. งามวงศ์วาน 26 หลักสี่', 'รายละเอียดทรัพย์

ที่ดินพร้อมกลุ่มอาคารและสิ่งปลูกสร้าง ซอยงามวงศ์วาน 26 แยก 3-4 แขวงทุ่งสองห้อง เขตหลักสี่ กรุงเทพมหานคร โฉนดเลขที่ 3369 จำนวน 1 ฉบับ เนื้อที่ 5 ไร่ 1 งาน 73 ตร.ว. หรือ 2,173 ตร.ว. (8,692 ตร.ม.) ราคาประกาศขายทั้งทรัพย์ 121,474,000 บาท รหัส SAM 2T0797 ต้นทางจัดเป็นอสังหาริมทรัพย์อื่นๆ ในเว็บนี้จัดเป็นที่ดินพร้อมสิ่งปลูกสร้าง

แปลงรูปคล้ายสี่เหลี่ยมผืนผ้า ด้านเหนือกว้างประมาณ 86 เมตร โดยส่วนติดถนนกว้างประมาณ 59 เมตร ลึกสุดประมาณ 124 เมตร ด้านใต้ติดคลองบางเขนประมาณ 72 เมตร มีสาธารณูปโภคผ่านหน้าทรัพย์ตาม SAM

สิ่งปลูกสร้างตามทะเบียนรับโอน

SAM ระบุสิ่งปลูกสร้าง 13 รายการ ได้แก่ อาคารพักอาศัย 4.5 ชั้น 1 หลัง อาคารพักอาศัย 3 ชั้น 2 หลัง อาคารพักอาศัย 2.5 ชั้น 3 หลัง บ้านพักคนงานชั้นเดียว 1 หลัง บ้านพักคนงาน 2 ชั้น 1 หลัง อาคารชั้นเดียว (หอพระ) 1 หลัง อาคารแปดเหลี่ยม 3 ชั้น 1 หลัง อาคาร 2 ชั้นพร้อมที่จอดรถ 1 หลัง ศาลาพักผ่อนรูปโดม 1 รายการ และอาคารรูปทรงกลม 5 ชั้น 1 หลัง

จำนวน 13 รายการรวมศาลาและอาคารหลายรูปแบบ ไม่ใช่จำนวนห้องนอน ต้นทางไม่ระบุพื้นที่ใช้สอยรวม จำนวนห้องนอน ห้องน้ำ รายได้หรือสถานะผู้ใช้ประโยชน์ปัจจุบัน ควรตรวจโครงสร้าง ระบบอาคาร สภาพภายในและรายการที่จะโอนจริงก่อนเสนอซื้อ

ทางเข้าและข้อควรทราบ

ซอยงามวงศ์วาน 26 แยก 3-4 หน้าทรัพย์เป็นทางส่วนบุคคล SAM ระบุว่าเปิดให้ใช้เข้าออกโดยเปิดเผยและกรุงเทพมหานครดูแลปรับปรุง ผิวลาดยางกว้างประมาณ 5 เมตร เขตทางประมาณ 6 เมตร ข้อมูลการเปิดใช้และการดูแลไม่ใช่การยืนยันว่าเป็นทางสาธารณะหรือมีสิทธิใช้ทางจดทะเบียน ผู้สนใจต้องตรวจเจ้าของทาง ภาระจำยอมและสิทธิใช้ทางก่อนเสนอซื้อ

ที่ตั้งหน้าโฉนดระบุตำบลทุ่งสองห้อง อำเภอดอนเมือง กรุงเทพมหานคร ขณะที่ส่วนสรุปประกาศระบุแขวงทุ่งสองห้อง เขตหลักสี่ ควรตรวจเอกสารกับข้อมูลเขตปกครองปัจจุบัน SAM ระบุสีผังเมืองเป็นสีแดง ควรตรวจผังเมือง ข้อกำหนดการใช้ประโยชน์และแนวเขต/ระยะร่นริมคลองสำหรับกิจกรรมที่ต้องการ ไม่ถือว่าการมีอาคารเดิมเป็นการยืนยันสิทธิดัดแปลงหรือก่อสร้างเพิ่มเติม

ทำเลและการเดินทาง

ย่านที่อยู่อาศัย ใกล้เดอะมอลล์งามวงศ์วาน โรงพยาบาลนนทเวช และบริเวณพงษ์เพชร–ประชาชื่น ตามข้อมูลต้นทาง จากถนนงามวงศ์วานมุ่งหน้าแคราย เลี้ยวซ้ายที่แยกพงษ์เพชรเข้าประชาชื่นประมาณ 420 เมตร เลี้ยวซ้ายข้ามคลองประปา เข้าถนนเทศบาลรังสรรค์เหนือประมาณ 170 เมตร แล้วเข้าซอยงามวงศ์วาน 26 แยก 3 และแยก 3-4 รวมประมาณ 255 เมตร ถึงทรัพย์

ภาพและการติดต่อ

ภาพจริงและผังจาก SAM คัดไม่ซ้ำ 20 ภาพ ภาพอาคารและภายในส่วนใหญ่ลงวันที่ 10 เมษายน 2567 มีภาพถนนโดยรอบและผังต้นทางประกอบ ภาพไม่ใช่การยืนยันสภาพปัจจุบันหรือรวมทรัพย์ข้างเคียงไว้ในการขาย

พิกัด 13.851588, 100.545763 ดึงจากลิงก์นำทาง SAM และตรงกับแผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ตรวจราคาและสถานะซื้อตรงวันที่ 15 กันยายน 2569 ติดต่อ SAM โทร.02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 2T0797 เพื่อยืนยันเอกสาร ราคา สิทธิใช้ทางและเงื่อนไขล่าสุด', 121474000, false, 8692, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ซอยงามวงศ์วาน 26 แยก 3-4', 'ด้านใต้ติดคลองบางเขน', 'ถนนงามวงศ์วาน', 13.851588, 100.545763, 'กรุงเทพมหานคร', 'หลักสี่', 'ทุ่งสองห้อง', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-ngamwongwan-26-land-buildings-2t0797') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'residential') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 121474000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"อสังหาริมทรัพย์อื่นๆ","official_page_reference_code":"2T0797","source_page_id":5125,"title_document_type":"chanote","title_document_count":1,"title_deed_number":"3369","plot_count":1,"land_area_square_wah":2173,"land_area_sqm":8692,"existing_structures":true,"registered_inventory_entry_count":13,"inventory_includes_pavilion":true,"registered_residential_building_storeys":[4.5,3,3,2.5,2.5,2.5],"worker_house_storeys":[1,2],"shrine_building_storeys":1,"octagonal_building_storeys":3,"building_with_parking_storeys":2,"circular_building_storeys":5,"north_width_m_approx":86,"road_frontage_m_approx":59,"max_depth_m_approx":124,"south_canal_frontage_m_approx":72,"canal_name_th":"คลองบางเขน","access_road_private":true,"open_access_and_bma_maintenance_according_to_sam":true,"legal_access_rights_require_verification":true,"road_width_m_approx":5,"right_of_way_m_approx":6,"planning_colour_source_th":"สีแดง","title_address_district_th":"ดอนเมือง","current_source_district_th":"หลักสี่","title_address_difference_disclosed":true,"current_occupancy_and_usable_area_not_confirmed":true,"status_checked_on":"2026-09-15","main_source_field_photo_date":"2024-04-10","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.851588,100.545763","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 5125 identifies SAM as direct-sale contact for 2T0797, Land with13registered inventory entries at Ngam Wong Wan26, Lak Si.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ SAM 2T0797 ราคา 121,474,000 บาท', 'Whole property SAM 2T0797 THB121474000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'private_road_access', 'ทางเข้าเป็นถนนส่วนบุคคล', 'Private access road', 'SAM ระบุเปิดใช้และ กทม.ดูแล แต่ต้องตรวจเจ้าของทาง ภาระจำยอมและสิทธิใช้ทาง', 'SAM reports open use/BMA maintenance; verify ownership, easements and legal access', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_inventory', 'สิ่งปลูกสร้างตามทะเบียน', 'Registered structures', '13รายการรวมอาคารและศาลา ไม่ใช่จำนวนห้องนอน ต้องตรวจรายการโอนจริง', '13entries including buildings and pavilion, not bedrooms; verify transfer inventory', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'title_address', 'เขตในหน้าโฉนด', 'Title address district', 'โฉนดระบุดอนเมือง ส่วนสรุปประกาศระบุหลักสี่ ควรตรวจข้อมูลปัจจุบัน', 'Title says Don Mueang; summary says Lak Si; verify current records', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ประตูและหน้าทรัพย์', 'ประตูและหน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/5125/20260105111050_2T0797P1_67.jpg', '/listing-media/sam/2t0797/01.webp', 'image/webp', 34802, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารด้านหน้า', 'อาคารด้านหน้า', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P2_67.jpg', '/listing-media/sam/2t0797/03.webp', 'image/webp', 33720, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่สวนและกลุ่มอาคาร', 'พื้นที่สวนและกลุ่มอาคาร', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P3_67.jpg', '/listing-media/sam/2t0797/04.webp', 'image/webp', 61392, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารและพื้นที่ภายนอก', 'อาคารและพื้นที่ภายนอก', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P4_67.jpg', '/listing-media/sam/2t0797/05.webp', 'image/webp', 60798, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานและอาคารที่พัก', 'ลานและอาคารที่พัก', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P5_67.jpg', '/listing-media/sam/2t0797/06.webp', 'image/webp', 52262, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินระหว่างอาคาร', 'ทางเดินระหว่างอาคาร', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P6_67.jpg', '/listing-media/sam/2t0797/07.webp', 'image/webp', 37598, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวระเบียงและอาคาร', 'แนวระเบียงและอาคาร', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P7_67.jpg', '/listing-media/sam/2t0797/08.webp', 'image/webp', 39004, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินภายในกลุ่มอาคาร', 'ทางเดินภายในกลุ่มอาคาร', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P8_67.jpg', '/listing-media/sam/2t0797/09.webp', 'image/webp', 31976, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในตามสภาพ', 'โถงภายในตามสภาพ', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P9_67.jpg', '/listing-media/sam/2t0797/10.webp', 'image/webp', 23856, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและส่วนเชื่อมอาคาร', 'โถงและส่วนเชื่อมอาคาร', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P10_67.jpg', '/listing-media/sam/2t0797/11.webp', 'image/webp', 26542, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดภายใน', 'บันไดภายใน', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P11_67.jpg', '/listing-media/sam/2t0797/12.webp', 'image/webp', 14962, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในและช่องหน้าต่าง', 'ห้องภายในและช่องหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P12_67.jpg', '/listing-media/sam/2t0797/13.webp', 'image/webp', 33078, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพห้องภายในอีกมุม', 'สภาพห้องภายในอีกมุม', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P13_67.jpg', '/listing-media/sam/2t0797/14.webp', 'image/webp', 16084, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในอาคาร', 'พื้นที่ภายในอาคาร', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P14_67.jpg', '/listing-media/sam/2t0797/15.webp', 'image/webp', 15602, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องหน้าต่างทรงกลม', 'ห้องหน้าต่างทรงกลม', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P15_67.jpg', '/listing-media/sam/2t0797/16.webp', 'image/webp', 19934, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในอีกส่วน', 'ห้องภายในอีกส่วน', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P16_67.jpg', '/listing-media/sam/2t0797/17.webp', 'image/webp', 17022, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ถนนงามวงศ์วานบริเวณแยกเข้าซอย ไม่ใช่หน้าทรัพย์', 'ถนนงามวงศ์วานบริเวณแยกเข้าซอย ไม่ใช่หน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/5125/2T0797P2_64.jpg', '/listing-media/sam/2t0797/18.webp', 'image/webp', 37030, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด3369', 'ผังแปลงโฉนด3369', 'https://npa.sam.or.th/site/images/npa/5125/20161107215005_2T0797C1_59.jpg', '/listing-media/sam/2t0797/19.webp', 'image/webp', 23274, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังสิ่งปลูกสร้าง13รายการ', 'ผังสิ่งปลูกสร้าง13รายการ', 'https://npa.sam.or.th/site/images/npa/5125/20240724165020_2T0797C4_67.jpg', '/listing-media/sam/2t0797/20.webp', 'image/webp', 28768, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/5125/20171206144248_2T0797M1_60.jpg', '/listing-media/sam/2t0797/21.webp', 'image/webp', 51184, 785, 600, 200, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=5125&keyref=', '2T0797', now(), 'Checked2026-09-15. THB121474000,8692sqm,Chanote3369,13registered structures including pavilion. Private road5m/ROW6m openly used and BMA maintained per SAM; legal access not certified. Title Don Mueang versus summary Lak Si disclosed. Southern canal72m.20unique source images/plans, main photos2024-04-10. Navigation/map agree. All-status source/code/page/deed/nearby duplicate query empty.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Land and Buildings on Ngam Wong Wan 26, Lak Si, Bangkok', 'Land with multiple buildings at Soi Ngam Wong Wan 26, Yaek 3-4, Thung Song Hong, Lak Si, Bangkok. One Chanote title 3369. Total 5 rai 1 ngan 73 sq.wah, or 2,173 sq.wah (8,692 sq.m.). SAM whole-property asking price THB 121,474,000, reference 2T0797. Source category is other real estate; listed here as land with existing structures.

Approximately rectangular plot: 86 m northern width, including 59 m road frontage; maximum depth 124 m; approximately 72 m southern boundary along Khlong Bang Khen. Source reports utilities passing the frontage.

Registered acquisition inventory has 13 entries: one 4.5-storey residential building, two 3-storey residential buildings, three 2.5-storey residential buildings, one single-storey workers house, one 2-storey workers house, one single-storey shrine building, one 3-storey octagonal building, one 2-storey building with parking, one domed pavilion and one 5-storey circular building. The count includes a pavilion and is not a bedroom count. Total usable area, bedrooms, bathrooms, income and current occupancy are not specified. Inspect structures, systems, condition and actual transfer inventory.

Material access disclosure: frontage Soi Ngam Wong Wan 26 Yaek 3-4 is a private road. SAM says it is openly used for access and maintained by Bangkok Metropolitan Administration, with approximately 5 m paved carriageway and 6 m right of way. This does not establish public-road status or registered access rights. Verify road ownership, easements and legal access before purchase.

Title address states Thung Song Hong, Don Mueang, whereas the source summary uses Lak Si; verify current administrative records. SAM lists red zoning. Confirm current planning, proposed use and canal boundary/setback requirements. Existing buildings do not establish permission for alteration or further construction.

Residential surroundings near The Mall Ngamwongwan, Nonthavej Hospital and Phong Phet/Pracha Chuen. Source route runs via Pracha Chuen, across the waterworks canal, Thetsaban Rangsan Nuea and Soi Ngam Wong Wan 26 Yaek 3 and 3-4.

Twenty unique authentic source photos/plans. Most building/interior photos show 10 April 2024; road context and source plans are also included. Inspect current condition. Navigation/map agree at 13.851588, 100.545763, a reference point rather than surveyed boundary. Direct-sale price/status checked 15 September 2026. Contact SAM 02-686-1888, sales@sam.or.th or LINE @samline quoting 2T0797.', 'Soi Ngam Wong Wan26 Yaek3-4', 'Southern boundary along Khlong Bang Khen', 'Ngam Wong Wan Road', 'Thung Song Hong', 'Lak Si', 'Bangkok', 'Land and Buildings on Ngam Wong Wan 26, Lak Si, Bangkok', 'Land8692sqm with13registered structure entries,THB121474000. Private road access and title address difference disclosed.', 'published', 'ai_assisted', now(), 'land and buildings on ngam wong wan 26, lak si, bangkok land with multiple buildings at soi ngam wong wan 26, yaek 3-4, thung song hong, lak si, bangkok. one chanote title 3369. total 5 rai 1 ngan 73 sq.wah, or 2,173 sq.wah (8,692 sq.m.). sam whole-property asking price thb 121,474,000, reference 2t0797. source category is other real estate; listed here as land with existing structures.

approximately rectangular plot: 86 m northern width, including 59 m road frontage; maximum depth 124 m; approximately 72 m southern boundary along khlong bang khen. source reports utilities passing the frontage.

registered acquisition inventory has 13 entries: one 4.5-storey residential building, two 3-storey residential buildings, three 2.5-storey residential buildings, one single-storey workers house, one 2-storey workers house, one single-storey shrine building, one 3-storey octagonal building, one 2-storey building with parking, one domed pavilion and one 5-storey circular building. the count includes a pavilion and is not a bedroom count. total usable area, bedrooms, bathrooms, income and current occupancy are not specified. inspect structures, systems, condition and actual transfer inventory.

material access disclosure: frontage soi ngam wong wan 26 yaek 3-4 is a private road. sam says it is openly used for access and maintained by bangkok metropolitan administration, with approximately 5 m paved carriageway and 6 m right of way. this does not establish public-road status or registered access rights. verify road ownership, easements and legal access before purchase.

title address states thung song hong, don mueang, whereas the source summary uses lak si; verify current administrative records. sam lists red zoning. confirm current planning, proposed use and canal boundary/setback requirements. existing buildings do not establish permission for alteration or further construction.

residential surroundings near the mall ngamwongwan, nonthavej hospital and phong phet/pracha chuen. source route runs via pracha chuen, across the waterworks canal, thetsaban rangsan nuea and soi ngam wong wan 26 yaek 3 and 3-4.

twenty unique authentic source photos/plans. most building/interior photos show 10 april 2024; road context and source plans are also included. inspect current condition. navigation/map agree at 13.851588, 100.545763, a reference point rather than surveyed boundary. direct-sale price/status checked 15 september 2026. contact sam 02-686-1888, sales@sam.or.th or line @samline quoting 2t0797.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=5125&keyref=', 'Official SAM page 5125 identifies SAM as asset holder and direct-sale contact for 2T0797.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'd9000797-bb50-4371-ab7a-519316005125', '{"reference_code":"2T0797","source_page_id":5125,"source_image_count":20,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
