BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-13643'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='8Z5996' OR source_url ~ '[?&]id=13643(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='e1115996-2656-43c8-a9bf-190786913643' OR slug='sam-theppharat-bang-bo-restaurant-land-8z5996' OR (abs(latitude-13.585719)<0.0001 AND abs(longitude-100.851193)<0.0001 AND abs(land_area_sqm-13692)<1)) THEN RAISE NOTICE 'SAM 8Z5996 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, custom_unit_number, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('e1115996-2656-43c8-a9bf-190786913643', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'ที่ดินพร้อมอาคารภัตตาคาร 8 ไร่ 2 งาน 23 ตร.ว. ติดถนนเทพรัตน บางบ่อ', 'รายละเอียดทรัพย์

ที่ดินพร้อมอาคารภัตตาคารและสิ่งปลูกสร้าง เลขที่ 196–199 ถนนเทพรัตน (ทล.34 บางนา–ตราด) ตำบลบางบ่อ อำเภอบางบ่อ จังหวัดสมุทรปราการ โฉนดเลขที่ 4803 และ 11722 จำนวน 2 ฉบับ เนื้อที่รวม 8 ไร่ 2 งาน 23 ตร.ว. หรือ 3,423 ตร.ว. (13,692 ตร.ม.) ราคาประกาศขายทั้งทรัพย์ 114,204,000 บาท รหัส SAM 8Z5996

ที่ดิน 2 แปลงติดต่อกัน รูปหลายเหลี่ยม ติดถนน 2 ด้าน ด้านใต้ติดถนนเทพรัตนกว้างประมาณ 120 เมตร ด้านตะวันออกติดถนนเลียบคลองประมาณ 68 เมตร ลึกสุดประมาณ 120 เมตร ด้านเหนือติดคลองแยกจากคลองบางบ่อประมาณ 72 เมตร ถนนเทพรัตนตาม SAM เป็นทางสาธารณประโยชน์ ผิวลาดยางกว้างประมาณ 30 เมตร เขตทางประมาณ 90 เมตร ต้นทางไม่ได้ยืนยันสถานะสิทธิของถนนเลียบคลองด้านตะวันออกแยกต่างหาก

สิ่งปลูกสร้างและขอบเขตการโอน

SAM ระบุทะเบียนรับโอนสิ่งปลูกสร้าง 20 รายการ ประกอบด้วยภัตตาคาร 4 รายการ บ้านพักอาศัยชั้นเดียว 7 รายการ บ้านพักอาศัย 2 ชั้น 4 รายการ บ้านพักอาศัย 3 ชั้น 2 รายการ สำนักงาน 2 ชั้น 1 รายการ และห้องน้ำรวม 2 รายการ

แต่ข้อมูลสำรวจระบุ 15 รายการ ได้แก่ อาคารต้อนรับชั้นเดียว อาคารครัวชั้นเดียว อาคารห้องอาหาร 2 ชั้น อาคารจัดเลี้ยง 3 ชั้น อาคารสำนักงานและห้องพักคนงาน 3 ชั้น อาคารเรือนซีฟู๊ดชั้นเดียว อาคารร้านค้าชั้นเดียว ศาลาต้อนรับชั้นเดียว อาคารห้องอาหารชั้นเดียว อาคารห้องน้ำและห้องเก็บของ อาคารระเบียงสีทันดรชั้นเดียว อาคารระเบียงมุจลินธรชั้นเดียว บ้านพักคนงาน 2 ชั้น อาคารที่พักอาหารชั้นเดียวตามข้อความต้นทาง และอาคารพักอาศัย 2 ชั้น

จำนวนและลักษณะรายการสำรวจต่างจากทะเบียนรับโอน SAM ระบุชัดว่าการโอนให้ผู้ซื้อทำได้เฉพาะรายการที่จดทะเบียนรับโอนกรรมสิทธิ์เท่านั้น ไม่ควรถือว่ารายการสำรวจหรือทุกสิ่งที่เห็นในภาพจะโอนได้ครบ ผู้สนใจต้องตรวจรายการทะเบียนเทียบผัง อาคารจริง ใบอนุญาตและขอบเขตที่จะโอนก่อนเสนอซื้อ

ทำเลและข้อควรตรวจสอบ

อยู่บริเวณเชิงสะพานข้ามคลองพระองค์เจ้าไชยานุชิต ย่านที่อยู่อาศัย SAM ระบุมีสาธารณูปโภคครบ ใกล้สำนักงานที่ดินจังหวัดสมุทรปราการ สาขาบางพลี ที่ว่าการอำเภอบางบ่อ และโรงพยาบาลรวมใจประชารักษ์ จากบางนามุ่งหน้าบางปะกงบน ทล.34 ผ่านทางเข้าโครงการบางนาการ์เด้นและมหาวิทยาลัยอัสสัมชัญ ถึง กม.28+400 ทรัพย์อยู่ซ้ายมือ

ต้นทางระบุผังเมืองสีแดง ควรตรวจข้อกำหนดปัจจุบัน สิทธิทางเข้าออก ระยะร่นจากถนนและคลอง รวมถึงสภาพโครงสร้าง ระบบอาคารและสาธารณูปโภคจริงตามกิจกรรมที่ต้องการ ต้นทางไม่ยืนยันสถานะเปิดกิจการ รายได้ ผู้เช่า จำนวนที่นั่ง หรือพื้นที่ใช้สอยรวม จึงไม่เสนอเป็นกิจการพร้อมดำเนินงาน

ภาพและการติดต่อ

ภาพจริงและผังจาก SAM รวม 22 ภาพ ภาพหน้าทรัพย์ลงวันที่ 6 สิงหาคม 2564 และภาพภายในมีวันที่ 19 และ 22 มกราคม 2565 แสดงสภาพอาคารในขณะนั้น ควรนัดตรวจสภาพปัจจุบันก่อนเสนอซื้อ

พิกัด 13.585719, 100.851193 ดึงจากลิงก์นำทาง SAM และตรงกับแผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ตรวจราคาและสถานะซื้อตรงวันที่ 15 กันยายน 2569 ติดต่อ SAM โทร.02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 8Z5996 เพื่อยืนยันราคา รายการโอนและเงื่อนไขล่าสุด', 114204000, false, 13692, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, '196–199', '196–199 ถนนเทพรัตน (บางนา–ตราด)', 'ทล.34 กม.28+400', 'ถนนเทพรัตน (ทล.34)', 13.585719, 100.851193, 'สมุทรปราการ', 'บางบ่อ', 'บางบ่อ', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-theppharat-bang-bo-restaurant-land-8z5996') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'food_service') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 114204000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"อสังหาริมทรัพย์อื่นๆ","official_page_reference_code":"8Z5996","source_page_id":13643,"title_document_type":"chanote","title_document_count":2,"title_deed_numbers":["4803","11722"],"plot_count":2,"adjoining_plots":true,"land_area_square_wah":3423,"land_area_sqm":13692,"existing_structures":true,"registered_inventory_entry_count":20,"surveyed_structure_entry_count":15,"registered_and_surveyed_inventory_differ":true,"transfer_limited_to_registered_inventory":true,"registered_restaurant_count":4,"registered_residential_building_storeys":[1,1,1,1,1,1,1,2,2,2,2,3,3],"registered_office_storeys":2,"registered_shared_toilet_count":2,"south_road_frontage_m_approx":120,"east_road_frontage_m_approx":68,"max_depth_m_approx":120,"north_canal_frontage_m_approx":72,"main_road_public_according_to_sam":true,"east_road_legal_status_not_confirmed":true,"main_road_width_m_approx":30,"main_right_of_way_m_approx":90,"planning_colour_source_th":"สีแดง","current_operation_income_occupancy_and_usable_area_not_confirmed":true,"status_checked_on":"2026-09-15","source_field_photo_dates":["2021-08-06","2022-01-19","2022-01-22"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.585719,100.851193","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 13643 identifies SAM as direct-sale contact for 8Z5996, Restaurant buildings and land at Theppharat Road, Bang Bo.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ SAM 8Z5996 ราคา 114,204,000 บาท', 'Whole property SAM 8Z5996 THB114204000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_transfer_only', 'โอนได้เฉพาะรายการตามทะเบียน', 'Registered inventory only', 'ทะเบียนรับโอน20รายการ สำรวจ15รายการ โอนได้เฉพาะที่ SAM รับโอนทางทะเบียน ต้องตรวจเทียบรายการ', '20registered versus15surveyed entries; transfer limited to SAM registered inventory; reconcile items', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'operating_status', 'สถานะกิจการและพื้นที่ใช้สอย', 'Operations and usable area', 'ต้นทางไม่ยืนยันเปิดกิจการ รายได้ ผู้เช่า จำนวนที่นั่งหรือพื้นที่ใช้สอยรวม', 'Operations,income,tenants,seating and total usable area unconfirmed', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'east_road_access', 'ถนนเลียบคลองด้านตะวันออก', 'Eastern canal-side road', 'ต้นทางไม่ยืนยันสถานะสิทธิถนนด้านนี้แยกต่างหาก ควรตรวจสิทธิใช้ทาง', 'Source does not separately confirm legal status; verify access rights', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'หน้าทรัพย์และอาคารภัตตาคาร', 'หน้าทรัพย์และอาคารภัตตาคาร', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P1_64.jpg', '/listing-media/sam/8z5996/01.webp', 'image/webp', 36534, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงห้องอาหารตามสภาพ', 'โถงห้องอาหารตามสภาพ', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P18_65.jpg', '/listing-media/sam/8z5996/02.webp', 'image/webp', 32246, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องโถงภายใน', 'ห้องโถงภายใน', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P17_65.jpg', '/listing-media/sam/8z5996/03.webp', 'image/webp', 27938, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงและบันได', 'โถงและบันได', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P16_65.jpg', '/listing-media/sam/8z5996/04.webp', 'image/webp', 34738, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่อาคารและโครงหลังคา', 'พื้นที่อาคารและโครงหลังคา', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P1_65.jpg', '/listing-media/sam/8z5996/05.webp', 'image/webp', 46056, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวห้องอาหาร', 'แนวห้องอาหาร', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P2_65.jpg', '/listing-media/sam/8z5996/06.webp', 'image/webp', 30060, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องอาหารอีกมุม', 'ห้องอาหารอีกมุม', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P3_65.jpg', '/listing-media/sam/8z5996/07.webp', 'image/webp', 36430, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในติดหน้าต่าง', 'พื้นที่ภายในติดหน้าต่าง', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P4_65.jpg', '/listing-media/sam/8z5996/08.webp', 'image/webp', 38024, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บันไดและพื้นที่ชั้นล่าง', 'บันไดและพื้นที่ชั้นล่าง', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P5_65.jpg', '/listing-media/sam/8z5996/09.webp', 'image/webp', 34200, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงอาคารอีกส่วน', 'โถงอาคารอีกส่วน', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P6_65.jpg', '/listing-media/sam/8z5996/10.webp', 'image/webp', 37926, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่อาคารสองระดับ', 'พื้นที่อาคารสองระดับ', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P7_65.jpg', '/listing-media/sam/8z5996/11.webp', 'image/webp', 38232, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในตามสภาพ', 'ห้องภายในตามสภาพ', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P8_65.jpg', '/listing-media/sam/8z5996/12.webp', 'image/webp', 46562, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินและห้องภายใน', 'ทางเดินและห้องภายใน', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P9_65.jpg', '/listing-media/sam/8z5996/13.webp', 'image/webp', 40068, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องเดิมและสภาพผนัง', 'ห้องเดิมและสภาพผนัง', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P10_65.jpg', '/listing-media/sam/8z5996/14.webp', 'image/webp', 39130, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในที่ต้องตรวจสภาพ', 'พื้นที่ภายในที่ต้องตรวจสภาพ', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P11_65.jpg', '/listing-media/sam/8z5996/15.webp', 'image/webp', 34884, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นและผนังกั้นภายใน', 'พื้นและผนังกั้นภายใน', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P12_65.jpg', '/listing-media/sam/8z5996/16.webp', 'image/webp', 33726, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารโครงหลังคาสูง', 'อาคารโครงหลังคาสูง', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P13_65.jpg', '/listing-media/sam/8z5996/17.webp', 'image/webp', 49412, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในอาคารอีกมุม', 'ภายในอาคารอีกมุม', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P14_65.jpg', '/listing-media/sam/8z5996/18.webp', 'image/webp', 39590, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ระเบียงและพื้นที่ภายนอก', 'ระเบียงและพื้นที่ภายนอก', 'https://npa.sam.or.th/site/images/npa/13643/8Z5996P15_65.jpg', '/listing-media/sam/8z5996/19.webp', 'image/webp', 65584, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังที่ดินสองแปลง', 'ผังที่ดินสองแปลง', 'https://npa.sam.or.th/site/images/npa/13643/20190724105351_8Z5996.jpg', '/listing-media/sam/8z5996/20.webp', 'image/webp', 17016, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังสิ่งปลูกสร้างตามสำรวจ ต้องเทียบทะเบียนโอน', 'ผังสิ่งปลูกสร้างตามสำรวจ ต้องเทียบทะเบียนโอน', 'https://npa.sam.or.th/site/images/npa/13643/20190724105351_8Z5996C2.1_61.jpg', '/listing-media/sam/8z5996/21.webp', 'image/webp', 48180, 785, 785, 210, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/13643/20180228131042_8Z5996M1_61.jpg', '/listing-media/sam/8z5996/22.webp', 'image/webp', 37016, 785, 600, 220, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=13643&keyref=', '8Z5996', now(), 'Checked2026-09-15. THB114204000,13692sqm,2adjoining Chanote4803/11722.20registered inventory entries versus15surveyed; SAM explicitly transfers registered items only. Public main road versus unconfirmed eastern road legal status distinguished. Operations/income/occupancy/usable area unconfirmed.22authentic photos/plans,dates2021-08-06/2022-01-19/2022-01-22. Navigation/map agree. All-status source/code/page/deed/nearby duplicate query empty.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Restaurant Buildings and Land on Theppharat Road, Bang Bo', 'Land with restaurant buildings and other structures at 196–199 Theppharat Road (Highway 34, Bang Na–Trat), Bang Bo, Samut Prakan. Two adjoining Chanote plots, titles 4803 and 11722, totaling 8 rai 2 ngan 23 sq.wah, or 3,423 sq.wah (13,692 sq.m.). SAM whole-property asking price THB 114,204,000, reference 8Z5996.

Irregular combined site with approximately 120 m southern frontage on Theppharat Road, 68 m eastern frontage on a canal-side road, maximum depth 120 m and 72 m northern boundary on a branch of Khlong Bang Bo. SAM describes Theppharat as public, approximately 30 m paved carriageway and 90 m right of way. Legal status of the eastern canal-side road is not separately confirmed.

Material transfer restriction: registered acquisition inventory has 20 entries: four restaurants, seven single-storey residential buildings, four 2-storey residential buildings, two 3-storey residential buildings, one 2-storey office and two shared toilet buildings. Survey instead lists 15 entries: single-storey reception, kitchen, 2-storey dining building, 3-storey banquet building, 3-storey office/workers accommodation, single-storey seafood building, shop, reception pavilion, dining building, toilet/storage building, Sithandon terrace, Muchalinthon terrace, 2-storey workers accommodation, a single-storey food-holding building as worded by source, and a 2-storey residential building. Counts and descriptions differ. SAM expressly limits transfer to its registered acquisition inventory; survey items or everything pictured must not be presumed transferable. Reconcile title inventory, plans, physical buildings and permits before purchase.

Near the bridge over Khlong Phra Ong Chao Chaiyanuchit. SAM reports residential surroundings and full utilities. Nearby landmarks include Bang Phli branch land office, Bang Bo district office and Ruam Jai Pracharak Hospital. From Bang Na toward Bang Pakong on Highway 34, pass Bang Na Garden/Assumption University access to km 28+400; property on left.

Source lists red zoning. Verify current planning, access rights, road/canal setbacks, structures and actual utility condition for intended use. Current business operations, income, tenants, seating capacity and total usable area are unconfirmed; this is not represented as a ready-to-operate business.

Twenty-two authentic source photos/plans. Front photo is dated 6 August 2021; interiors include 19 and 22 January 2022. Inspect current condition. Navigation/map agree at 13.585719, 100.851193, a reference point rather than surveyed boundary. Direct-sale price/status checked 15 September 2026. Contact SAM 02-686-1888, sales@sam.or.th or LINE @samline quoting 8Z5996.', '196–199 Theppharat Road (Bang Na–Trat)', 'Highway34 km28+400', 'Theppharat Road (Highway34)', 'Bang Bo', 'Bang Bo', 'Samut Prakan', 'Restaurant Buildings and Land on Theppharat Road, Bang Bo', 'Restaurant buildings and land13692sqm,THB114204000.20registered versus15surveyed entries; registered transfer only.', 'published', 'ai_assisted', now(), 'restaurant buildings and land on theppharat road, bang bo land with restaurant buildings and other structures at 196–199 theppharat road (highway 34, bang na–trat), bang bo, samut prakan. two adjoining chanote plots, titles 4803 and 11722, totaling 8 rai 2 ngan 23 sq.wah, or 3,423 sq.wah (13,692 sq.m.). sam whole-property asking price thb 114,204,000, reference 8z5996.

irregular combined site with approximately 120 m southern frontage on theppharat road, 68 m eastern frontage on a canal-side road, maximum depth 120 m and 72 m northern boundary on a branch of khlong bang bo. sam describes theppharat as public, approximately 30 m paved carriageway and 90 m right of way. legal status of the eastern canal-side road is not separately confirmed.

material transfer restriction: registered acquisition inventory has 20 entries: four restaurants, seven single-storey residential buildings, four 2-storey residential buildings, two 3-storey residential buildings, one 2-storey office and two shared toilet buildings. survey instead lists 15 entries: single-storey reception, kitchen, 2-storey dining building, 3-storey banquet building, 3-storey office/workers accommodation, single-storey seafood building, shop, reception pavilion, dining building, toilet/storage building, sithandon terrace, muchalinthon terrace, 2-storey workers accommodation, a single-storey food-holding building as worded by source, and a 2-storey residential building. counts and descriptions differ. sam expressly limits transfer to its registered acquisition inventory; survey items or everything pictured must not be presumed transferable. reconcile title inventory, plans, physical buildings and permits before purchase.

near the bridge over khlong phra ong chao chaiyanuchit. sam reports residential surroundings and full utilities. nearby landmarks include bang phli branch land office, bang bo district office and ruam jai pracharak hospital. from bang na toward bang pakong on highway 34, pass bang na garden/assumption university access to km 28+400; property on left.

source lists red zoning. verify current planning, access rights, road/canal setbacks, structures and actual utility condition for intended use. current business operations, income, tenants, seating capacity and total usable area are unconfirmed; this is not represented as a ready-to-operate business.

twenty-two authentic source photos/plans. front photo is dated 6 august 2021; interiors include 19 and 22 january 2022. inspect current condition. navigation/map agree at 13.585719, 100.851193, a reference point rather than surveyed boundary. direct-sale price/status checked 15 september 2026. contact sam 02-686-1888, sales@sam.or.th or line @samline quoting 8z5996.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=13643&keyref=', 'Official SAM page 13643 identifies SAM as asset holder and direct-sale contact for 8Z5996.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'e1115996-2656-43c8-a9bf-190786913643', '{"reference_code":"8Z5996","source_page_id":13643,"source_image_count":22,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
