BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-14732'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='8Z6564' OR source_url ~ '[?&]id=14732(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='a9106564-0857-45f2-9f46-782065914732' OR slug='sam-the-kib-koh-kho-khao-resort-8z6564' OR (abs(latitude-8.892045)<0.0001 AND abs(longitude-98.264098)<0.0001 AND abs(land_area_sqm-24000)<1)) THEN RAISE NOTICE 'SAM 8Z6564 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, custom_project_name, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('a9106564-0857-45f2-9f46-782065914732', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'hotel_resort', 'business', 'sale', 'whole_property', 'The Kib เกาะคอเขา รีสอร์ทบนที่ดิน 15 ไร่ ตะกั่วป่า พังงา', 'รายละเอียดทรัพย์

ทรัพย์โรงแรม/รีสอร์ท The Kib เกาะคอเขา บีช รีสอร์ทแอนด์สปา ตำบลเกาะคอเขา อำเภอตะกั่วป่า จังหวัดพังงา บนถนนสายบ้านปากเกาะ–บ้านนอกนา เข้าซอยโรงเรียน โฉนดเลขที่ 15111 จำนวน 1 ฉบับ เนื้อที่ 15 ไร่ หรือ 6,000 ตร.ว. (24,000 ตร.ม.) ราคาประกาศขายทั้งทรัพย์ 98,222,000 บาท รหัส SAM 8Z6564

แปลงสี่เหลี่ยมผืนผ้า ด้านตะวันออกติดถนนกว้างประมาณ 84 เมตร ลึกประมาณ 290 เมตร ผังต้นทางแสดงด้านตะวันตกติดทะเลอันดามัน ภาพชายหาดใช้แสดงบริเวณโดยรอบ ไม่ใช่การรับรองกรรมสิทธิ์ชายหาดหรือขอบเขตที่โอน ถนนหน้าทรัพย์คือซอยโรงเรียน SAM ระบุเป็นทางสาธารณประโยชน์ ผิวลาดยางประมาณ 6 เมตร เขตทางประมาณ 8 เมตร

ห้องพักตามข้อมูลสำรวจ

วิลลาชั้นเดียว Single Private Villa Pool Access 17 หลัง, Single Private Villa Pool GV 10 หลัง และ Beach Front Villa 4 หลัง รวมวิลลา 31 หลัง แยกจากอาคารห้องพัก 2 ชั้น 5 หลัง รวม 20 ห้อง แบบ Superior ชั้นบนและ Deluxe ชั้นล่าง และอาคาร 3 ชั้น 1 หลัง รวม 24 ห้อง แบบ Grand Deluxe ไม่ใช้จำนวนหลังแทนจำนวนห้องนอน และไม่รับรองว่าพร้อมเปิดให้บริการ

ข้อมูลสำรวจยังระบุอาคารต้อนรับและสำนักงาน ภัตตาคาร สปา อาคารจัดเลี้ยงสัมมนามีชั้นใต้ดิน บีชบาร์ อาคารช่างและสำนักงาน 2 ชั้น อาคารเก็บของและห้องเครื่อง และสระว่ายน้ำ 2 สระ

รายการตามทะเบียนและขอบเขตการโอน

ทะเบียนรับโอนของ SAM มี 15 รายการ ซึ่งแต่ละรายการอาจรวมหลายหลัง ได้แก่ บังกะโลชั้นเดียว A จำนวน 14 หลัง พื้นที่ตามรายการประมาณ 59.5 ตร.ม., B จำนวน 13 หลัง ประมาณ 62.9 ตร.ม., C จำนวน 2 หลัง ประมาณ 144 ตร.ม.; บังกะโล 2 ชั้น D จำนวน 4 หลัง ประมาณ 217.35 ตร.ม. และอีก 1 หลัง ประมาณ 253.48 ตร.ม.; อาคารอเนกประสงค์ 2 ชั้น E 1 หลัง ประมาณ 133 ตร.ม.; อาคารห้องช่างและห้องเครื่อง F 90 ตร.ม.; ภัตตาคาร G 572 ตร.ม.; สปา H 112 ตร.ม.; บีชบาร์ I 48 ตร.ม.; โรงแรม 3 ชั้น K 1,852 ตร.ม.; อาคารต้อนรับ J 439 ตร.ม.; อาคารสัมมนา 2 ชั้น L 908 ตร.ม.; และสระว่ายน้ำ 92 กับ 1,298 ตร.ม. ตามต้นทาง ไม่รวมตัวเลขเหล่านี้เป็นพื้นที่ใช้สอยรวม เนื่องจากรายการและวิธีนับต่างกัน

ลักษณะและจำนวนสิ่งปลูกสร้างตามสำรวจต่างจากทะเบียน SAM ระบุว่าการโอนให้ผู้ซื้อทำได้เฉพาะรายการที่จดทะเบียนรับโอนกรรมสิทธิ์เท่านั้น ต้องเทียบทะเบียน ผังขยาย อาคารจริงและรายการที่จะโอน ไม่ถือว่าทุกสิ่งในภาพหรือรายการสำรวจรวมอยู่ในการโอนโดยอัตโนมัติ

ข้อกำหนดและสภาพกิจการ

SAM ระบุว่าทรัพย์อยู่ในพื้นที่กำหนดบริเวณห้ามก่อสร้างตามข้อกำหนด พ.ศ.2544 และ 2551 ออกตามพระราชบัญญัติควบคุมอาคาร พ.ศ.2522 และเกี่ยวข้องกับหลักเกณฑ์จัดทำรายงานผลกระทบสิ่งแวดล้อมเบื้องต้น พ.ศ.2550 ตามประกาศกระทรวงทรัพยากรธรรมชาติและสิ่งแวดล้อม สีผังเมืองตามหัวข้อ SAM เป็นสีเขียวมีกรอบและเส้นทแยงสีขาว ข้อมูลเหล่านี้เป็นข้อระบุของต้นทาง ต้องตรวจข้อกำหนดปัจจุบัน แนวเขตชายฝั่ง ระยะร่น ใบอนุญาตอาคาร/โรงแรมและข้อกำหนดสิ่งแวดล้อมก่อนวางแผนใช้ประโยชน์

ภาพรวมบรรยากาศหนึ่งภาพมีคำกำกับว่าเป็นช่วงก่อนหยุดดำเนินกิจการ จึงติดป้ายเป็นภาพในอดีต ต้นทางไม่ยืนยันสถานะเปิดดำเนินงานล่าสุด รายได้ ผู้เช่า หรือความพร้อมระบบอาคาร สระและห้องพัก ควรตรวจสภาพจริง ไม่เสนอเป็นกิจการพร้อมเปิด

การเดินทางและภาพต้นทาง

จากถนนเพชรเกษม ทล.4 ตะกั่วป่ามุ่งหน้าโคกกลอย ผ่านตลาดบางม่วงและวัดบางม่วง เข้าถนนบ้านน้ำเค็มประมาณ 3.5 กม. ถึงท่าเรือบ้านน้ำเค็ม นั่งเรือไปท่าเรือเกาะคอเขา แล้วใช้ถนนปากเกาะ–บ้านนอกนา ผ่านอาคารหลบภัยสึนามิและวัดกันตาดาราม เข้าซอยโรงเรียนบุญสูงอุปถัมภ์ประมาณ 600 เมตร ทรัพย์อยู่ซ้ายมือ การเข้าถึงตามเส้นทางนี้มีช่วงเดินทางโดยเรือ ควรตรวจบริการและเงื่อนไขการเดินทางปัจจุบัน

ใช้ภาพจริงและผังจาก SAM 22 ภาพ รวมผังขยายสิ่งปลูกสร้างจากเอกสารแนบ ภาพชายหาดมีวันที่ 1 เมษายน 2565 ส่วนภาพอื่นเป็นภาพต้นทางต่างช่วงเวลาและไม่ยืนยันวันถ่ายทั้งหมด ควรนัดดูสภาพปัจจุบัน

พิกัด 8.892045, 98.264098 ดึงจากลิงก์นำทาง SAM และตรงกับแผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ตรวจราคาและสถานะซื้อตรงวันที่ 15 กันยายน 2569 ติดต่อ SAM โทร.02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 8Z6564 เพื่อยืนยันราคา เอกสาร รายการโอนและเงื่อนไขล่าสุด', 98222000, false, 24000, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'The Kib เกาะคอเขา บีช รีสอร์ทแอนด์สปา', 'ซอยโรงเรียน ถนนบ้านปากเกาะ–บ้านนอกนา', 'เกาะคอเขา', 'ถนนบ้านปากเกาะ–บ้านนอกนา', 8.892045, 98.264098, 'พังงา', 'ตะกั่วป่า', 'เกาะคอเขา', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-the-kib-koh-kho-khao-resort-8z6564') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'hospitality') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 98222000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'hotel_resort', 1, '{"source_property_category":"โรงแรม/รีสอร์ท","official_page_reference_code":"8Z6564","source_page_id":14732,"title_document_type":"chanote","title_deed_number":"15111","title_document_count":1,"land_area_square_wah":6000,"land_area_sqm":24000,"surveyed_villa_count":31,"surveyed_villa_types":{"pool_access":17,"pool_gv":10,"beach_front":4},"surveyed_two_storey_room_buildings":5,"surveyed_superior_deluxe_rooms":20,"surveyed_grand_deluxe_buildings":1,"surveyed_grand_deluxe_rooms":24,"registered_inventory_entry_count":15,"inventory_entries_include_multiple_buildings":true,"registered_and_surveyed_inventory_differ":true,"transfer_limited_to_registered_inventory":true,"pool_count_source":2,"historical_pre_closure_montage":true,"current_operating_status_not_confirmed":true,"current_hotel_licence_income_and_usable_area_not_confirmed":true,"east_frontage_m_approx":84,"depth_m_approx":290,"road_width_m_approx":6,"right_of_way_m_approx":8,"source_map_west_boundary":"Andaman Sea","beach_ownership_not_certified":true,"planning_colour_source_th":"สีเขียวมีกรอบมีเส้นทะแยงสีขาว","source_building_restriction_years_be":[2544,2551],"source_initial_environmental_report_criteria_year_be":2550,"current_coastal_building_environmental_rules_require_verification":true,"source_route_includes_boat":true,"expanded_plan_source_url":"https://npa.sam.or.th/site/attach/npa/14732/8Z6564C2_61.jpg","status_checked_on":"2026-09-15","beach_photo_date":"2022-04-01","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//8.892045,98.264098","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 14732 identifies SAM as direct-sale contact for 8Z6564, The Kib Koh Kho Khao resort property with registered-inventory-only transfer.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ SAM8Z6564 ราคา98,222,000บาท', 'Whole property SAM8Z6564 THB98222000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_transfer_only', 'โอนได้เฉพาะรายการตามทะเบียน', 'Registered inventory only', 'ทะเบียน15รายการรวมหลายหลัง ต่างจากสำรวจ โอนได้เฉพาะรายการที่ SAM รับโอนทางทะเบียน', '15registered entries include multiple buildings; surveyed inventory differs; registered items only', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'building_environment_rules', 'ข้อกำหนดอาคารและสิ่งแวดล้อมตาม SAM', 'Source building/environment provisions', 'ต้นทางระบุข้อกำหนดห้ามก่อสร้าง2544/2551 และรายงานผลกระทบเบื้องต้น2550 ต้องตรวจปัจจุบัน', 'Source cites2001/2008building restrictions and2007initial environmental reporting; verify current rules', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'historic_operations', 'ภาพก่อนหยุดกิจการ', 'Historical operations imagery', 'ภาพบรรยากาศหนึ่งภาพเป็นก่อนหยุดดำเนินกิจการ ไม่ยืนยันสถานะเปิดล่าสุด', 'One montage predates cessation; latest operating status unconfirmed', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'island_access', 'การเดินทางข้ามเกาะ', 'Island access', 'เส้นทาง SAM มีช่วงเรือจากบ้านน้ำเค็มไปเกาะคอเขา ต้องตรวจบริการปัจจุบัน', 'Source route includes boat from Ban Nam Khem to Koh Kho Khao; verify services', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'วิลลาและสระตามภาพต้นทาง', 'วิลลาและสระตามภาพต้นทาง', 'https://npa.sam.or.th/site/images/npa/14732/20240625124726_8Z6564P19_61n.jpg', '/listing-media/sam/8z6564/01.webp', 'image/webp', 41658, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนววิลลาริมสระ', 'แนววิลลาริมสระ', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P23_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/02.webp', 'image/webp', 40424, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าและอาคารต้อนรับ', 'ทางเข้าและอาคารต้อนรับ', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P24_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/03.webp', 'image/webp', 38566, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ป้าย The Kib และบริเวณทางเข้า', 'ป้าย The Kib และบริเวณทางเข้า', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P25_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/04.webp', 'image/webp', 57008, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณอาคารต้อนรับ', 'บริเวณอาคารต้อนรับ', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P1_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/05.webp', 'image/webp', 21328, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักตามสภาพต้นทาง', 'ห้องพักตามสภาพต้นทาง', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P3_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/06.webp', 'image/webp', 16524, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ตู้และพื้นที่ภายใน', 'ตู้และพื้นที่ภายใน', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P4_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/07.webp', 'image/webp', 12818, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินอาคารห้องพัก', 'ทางเดินอาคารห้องพัก', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P5_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/08.webp', 'image/webp', 13286, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักอีกมุม', 'ห้องพักอีกมุม', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P6_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/09.webp', 'image/webp', 20836, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในห้องพักและระเบียง', 'ภายในห้องพักและระเบียง', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P7_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/10.webp', 'image/webp', 17262, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักอีกประเภท', 'ห้องพักอีกประเภท', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P8_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/11.webp', 'image/webp', 16556, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องน้ำตามสภาพ', 'ห้องน้ำตามสภาพ', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P10_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/12.webp', 'image/webp', 17338, 450, 450, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเดินบริเวณอาคารใกล้ทะเล', 'ทางเดินบริเวณอาคารใกล้ทะเล', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P11_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/13.webp', 'image/webp', 30828, 450, 450, 130, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณด้านทะเล ไม่รับรองกรรมสิทธิ์ชายหาด', 'บริเวณด้านทะเล ไม่รับรองกรรมสิทธิ์ชายหาด', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P12_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/14.webp', 'image/webp', 29376, 450, 450, 140, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงอาคารตามสภาพ', 'โถงอาคารตามสภาพ', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P13_61เพิ่มเติม.jpg', '/listing-media/sam/8z6564/15.webp', 'image/webp', 20772, 450, 450, 150, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องพักภายในอีกส่วน', 'ห้องพักภายในอีกส่วน', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P11_62.jpg', '/listing-media/sam/8z6564/16.webp', 'image/webp', 12490, 450, 450, 160, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชายหาดโดยรอบ ภาพ1เมษายน2565', 'ชายหาดโดยรอบ ภาพ1เมษายน2565', 'https://npa.sam.or.th/site/images/npa/14732/2.jpg', '/listing-media/sam/8z6564/17.webp', 'image/webp', 26474, 450, 450, 170, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ชายหาดอีกมุม ภาพ1เมษายน2565', 'ชายหาดอีกมุม ภาพ1เมษายน2565', 'https://npa.sam.or.th/site/images/npa/14732/3.jpg', '/listing-media/sam/8z6564/18.webp', 'image/webp', 29474, 450, 450, 180, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภาพบรรยากาศในอดีตก่อนหยุดดำเนินกิจการตาม SAM', 'ภาพบรรยากาศในอดีตก่อนหยุดดำเนินกิจการตาม SAM', 'https://npa.sam.or.th/site/images/npa/14732/8Z6564P7_61.jpg', '/listing-media/sam/8z6564/19.webp', 'image/webp', 41424, 450, 450, 190, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด15111', 'ผังแปลงโฉนด15111', 'https://npa.sam.or.th/site/images/npa/14732/20180905144837_8Z6564C1_61.jpg', '/listing-media/sam/8z6564/20.webp', 'image/webp', 18474, 450, 450, 200, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังขยายสิ่งปลูกสร้างตามสำรวจ ต้องเทียบทะเบียนโอน', 'ผังขยายสิ่งปลูกสร้างตามสำรวจ ต้องเทียบทะเบียนโอน', 'https://npa.sam.or.th/site/attach/npa/14732/8Z6564C2_61.jpg', '/listing-media/sam/8z6564/21.webp', 'image/webp', 97702, 1000, 1200, 210, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/14732/20180917095650_8Z6564M1_61.jpg', '/listing-media/sam/8z6564/22.webp', 'image/webp', 46162, 785, 600, 220, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=14732&keyref=', '8Z6564', now(), 'Checked2026-09-15. THB98222000,24000sqm,Chanote15111. Survey31villas plus20Superior/Deluxe rooms and24GrandDeluxe rooms; no inferred bedroom total.15registered inventory entries include multiple buildings; registered transfer only. Source building restrictions2001/2008 and environmental criteria2007 require current verification. Historical pre-closure montage labelled; current operations unconfirmed.22source images/plans including expanded attachment; beach photos2022-04-01. Navigation/map agree. No all-status source/code/page/project/deed/nearby duplicate matches.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'The Kib Koh Kho Khao Resort Property, 15 Rai, Phang Nga', 'The Kib Koh Kho Khao Beach Resort and Spa property, Koh Kho Khao, Takua Pa, Phang Nga, via Ban Pak Ko–Ban Nok Na Road and Soi Rong Rian. One Chanote15111,15rai/6000sq.wah/24000sq.m. SAM whole-property asking price THB98,222,000,reference8Z6564. Approximately rectangular,84m eastern road frontage and290m depth. Source plan shows Andaman Sea to the west; beach context does not establish private beach ownership or transfer boundaries. SAM describes public Soi Rong Rian,6m paved carriageway and8m right of way.

Survey lists31single-storey villas:17Single Private Villa Pool Access,10Single Private Villa Pool GV and4Beach Front Villa. Separately,five2-storey buildings contain20Superior/Deluxe rooms and one3-storey building contains24Grand Deluxe rooms. Building counts are not bedroom counts or confirmation of operational readiness. Other surveyed facilities include reception/office,restaurant,spa,banquet/seminar building with basement,beach bar,2-storey technical/office building,storage/plant rooms and2pools.

Registered acquisition has15inventory entries,not15buildings. Bungalows A:14at source-listed area59.5sq.m.; B:13at62.9; C:2at144; two-storey D:4at217.35 plus1at253.48. Two-storey multipurpose E:1at133; technical/plant F:90; restaurant G:572; spa H:112; beach bar I:48; three-storey hotel K:1852; reception J:439; two-storey seminar L:908; pools92and1298sq.m. These source-listed areas are not summed into total usable area. Surveyed structures differ from registered inventory. SAM expressly limits transfer to registered acquisition items. Reconcile deeds,expanded plan,actual buildings and transfer schedule; not everything pictured/surveyed is automatically transferable.

SAM cites building-prohibition-area provisions from2001and2008 under the1979Building Control Act and2007initial environmental impact reporting criteria. Source zoning colour:green with white border/diagonal lines. Verify current building/coastal/setback/environmental requirements and hotel permits; source references do not establish development permission.

One historical montage is expressly captioned as before cessation of operations. Current reopening/operations,income,occupancy and readiness of rooms,pools and systems are not confirmed. This is not marketed as a ready-to-operate business.

Source access route:Highway4 via Bang Muang to Ban Nam Khem pier,boat to Koh Kho Khao pier,then Pak Ko–Ban Nok Na Road past tsunami shelter and Wat Kantadaram,turn into Bun Sung Uppatham School soi for around600m,property left. This route includes boat travel; verify current services.

22authentic source images/plans,including expanded building plan attachment. Beach photos show1April2022; dates of all other images are not confirmed. Inspect present condition. Navigation/map agree8.892045,98.264098,reference point not surveyed boundary. Price/direct-sale status checked15September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting8Z6564.', 'Soi Rong Rian, Ban Pak Ko–Ban Nok Na Road', 'Koh Kho Khao', 'Ban Pak Ko–Ban Nok Na Road', 'Koh Kho Khao', 'Takua Pa', 'Phang Nga', 'The Kib Koh Kho Khao Resort Property, 15 Rai, Phang Nga', 'The Kib resort property15rai,THB98222000; registered transfer limits, historical operations imagery and source environmental provisions disclosed.', 'published', 'ai_assisted', now(), 'the kib koh kho khao resort property, 15 rai, phang nga the kib koh kho khao beach resort and spa property, koh kho khao, takua pa, phang nga, via ban pak ko–ban nok na road and soi rong rian. one chanote15111,15rai/6000sq.wah/24000sq.m. sam whole-property asking price thb98,222,000,reference8z6564. approximately rectangular,84m eastern road frontage and290m depth. source plan shows andaman sea to the west; beach context does not establish private beach ownership or transfer boundaries. sam describes public soi rong rian,6m paved carriageway and8m right of way.

survey lists31single-storey villas:17single private villa pool access,10single private villa pool gv and4beach front villa. separately,five2-storey buildings contain20superior/deluxe rooms and one3-storey building contains24grand deluxe rooms. building counts are not bedroom counts or confirmation of operational readiness. other surveyed facilities include reception/office,restaurant,spa,banquet/seminar building with basement,beach bar,2-storey technical/office building,storage/plant rooms and2pools.

registered acquisition has15inventory entries,not15buildings. bungalows a:14at source-listed area59.5sq.m.; b:13at62.9; c:2at144; two-storey d:4at217.35 plus1at253.48. two-storey multipurpose e:1at133; technical/plant f:90; restaurant g:572; spa h:112; beach bar i:48; three-storey hotel k:1852; reception j:439; two-storey seminar l:908; pools92and1298sq.m. these source-listed areas are not summed into total usable area. surveyed structures differ from registered inventory. sam expressly limits transfer to registered acquisition items. reconcile deeds,expanded plan,actual buildings and transfer schedule; not everything pictured/surveyed is automatically transferable.

sam cites building-prohibition-area provisions from2001and2008 under the1979building control act and2007initial environmental impact reporting criteria. source zoning colour:green with white border/diagonal lines. verify current building/coastal/setback/environmental requirements and hotel permits; source references do not establish development permission.

one historical montage is expressly captioned as before cessation of operations. current reopening/operations,income,occupancy and readiness of rooms,pools and systems are not confirmed. this is not marketed as a ready-to-operate business.

source access route:highway4 via bang muang to ban nam khem pier,boat to koh kho khao pier,then pak ko–ban nok na road past tsunami shelter and wat kantadaram,turn into bun sung uppatham school soi for around600m,property left. this route includes boat travel; verify current services.

22authentic source images/plans,including expanded building plan attachment. beach photos show1april2022; dates of all other images are not confirmed. inspect present condition. navigation/map agree8.892045,98.264098,reference point not surveyed boundary. price/direct-sale status checked15september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting8z6564.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=14732&keyref=', 'Official SAM page 14732 identifies SAM as asset holder and direct-sale contact for 8Z6564.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'a9106564-0857-45f2-9f46-782065914732', '{"reference_code":"8Z6564","source_page_id":14732,"source_image_count":22,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
