BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-11499'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='8Z3208' OR source_url ~ '[?&]id=11499(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='b9003208-a6ee-4ef4-a19e-678963011499' OR slug='sam-na-kluea-pattani-factory-8z3208' OR (abs(latitude-6.881883)<0.0001 AND abs(longitude-101.260385)<0.0001 AND abs(land_area_sqm-34407.6)<1)) THEN RAISE NOTICE 'SAM 8Z3208 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('b9003208-a6ee-4ef4-a19e-678963011499', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'factory', 'business', 'sale', 'whole_property', 'โรงงานและโกดังถนนนาเกลือ ปัตตานี 21 ไร่ 2 งาน 1.9 ตร.ว.', 'รายละเอียดทรัพย์

ที่ดินพร้อมโรงงาน โกดัง ห้องเย็นและสิ่งปลูกสร้าง ถนนนาเกลือ ตำบลบานา อำเภอเมืองปัตตานี จังหวัดปัตตานี รวม 13 โฉนด เนื้อที่ 21 ไร่ 2 งาน 1.9 ตร.ว. หรือ 8,601.9 ตร.ว. (34,407.6 ตร.ม.) ราคาประกาศขายทั้งทรัพย์ 96,597,000 บาท รหัส SAM 8Z3208

ที่ดินสองกลุ่มและการเข้าถึง

กลุ่มที่ 1 มี 12 แปลงติดต่อกัน โฉนดเลขที่ 1929, 4155, 9924, 9925, 9926, 9927, 10783, 10784, 10785, 10786, 10787 และ 11308 เนื้อที่ 13 ไร่ 38.2 ตร.ว. แปลงรวมรูปหลายเหลี่ยม ด้านตะวันออกติดถนนกว้างประมาณ 102 เมตร ลึกสุดประมาณ 221 เมตร ด้านตะวันตกติดคลองปูลาประมาณ 42 เมตร

กลุ่มที่ 2 มีโฉนดเลขที่ 9469 จำนวน 1 แปลง เนื้อที่ 8 ไร่ 1 งาน 63.7 ตร.ว. ด้านตะวันออกติดคลองปูลาประมาณ 160 เมตร ลึกสุดประมาณ 90 เมตร ด้านตะวันตกติดแม่น้ำปัตตานีประมาณ 215 เมตร ไม่มีด้านใดติดทางสาธารณประโยชน์

สองกลุ่มมีคลองปูลาคั่น ไม่ใช่ที่ดินผืนเดียวติดต่อกัน SAM ระบุว่าต้องใช้สะพานคอนกรีตข้ามคลองเพื่อเข้ากลุ่มที่ 2 และให้ตรวจสิทธิใช้ทางก่อนเสนอซื้อ ควรตรวจเจ้าของสะพาน สิทธิทางผ่าน ภาระจำยอม สภาพและความสามารถรับน้ำหนัก ไม่รับรองว่ารถบรรทุกเข้าได้หรือมีสิทธิจดทะเบียนแล้ว ถนนนาเกลือหน้ากลุ่มที่ 1 เป็นทางสาธารณประโยชน์ ผิวลาดยางประมาณ 12 เมตร เขตทางประมาณ 20 เมตร ตามต้นทาง

สิ่งปลูกสร้างและขอบเขตการโอน

SAM ระบุทะเบียนรับโอน 23 รายการ ได้แก่ ป้อมยาม โกดัง 2 รายการ อาคารรับสินค้า สำนักงาน 2 ชั้น ห้องเครื่อง 2 ชั้น ร้านค้า 3 ชั้น โรงกลึง อาคารคลุมเครื่องกำเนิดไอน้ำ ห้องน้ำพนักงาน ห้องเย็น ห้องเครื่อง โรงน้ำแข็ง แผนกปลาสด สำนักงานและห้องเย็น อาคารตรวจสอบคุณภาพ 2 ชั้น บ้านพักคนงาน แผนกบุคคล 2 ชั้น แผนกวัตถุดิบ คสล. แผนกปลาแห้งและร้านค้า โรงอาหาร อาคารเก็บอุปกรณ์ตากปลา และแผนกปลากรอบ

ผลสำรวจระบุ 25 รายการ ลักษณะต่างจากทะเบียนบางส่วน รวมป้อมยาม โรงอาหาร ห้องน้ำ แผนกปลาแห้งและร้านค้า แผนกปลาสด แผนกปลากรอบ อาคารตรวจสอบคุณภาพ 2 ชั้น แผนกวัตถุดิบ แผนกบุคคล 2 ชั้น ห้องเย็นชั้นเดียว สำนักงาน 2 ชั้นพร้อมชั้นลอย ห้องเครื่องชั้นเดียว โรงน้ำแข็ง อาคารพักอาศัย 2 ชั้นและส่วนซ่อมบำรุง โกดังชั้นเดียว ห้องเย็น 2 ชั้น อาคารรับสินค้า อาคารพักอาศัย 2 ชั้น ห้องเครื่อง 2 ชั้น ร้านค้า 3 ชั้นพร้อมส่วนโล่งหลังคาคลุม โรงกลึงและที่พักอาศัย 2 ชั้น คานเรือ บ้านพักคนงานชั้นเดียว บ่อตกตะกอน และบ่อบำบัดน้ำเสีย

ต้นทางระบุโรงอาหาร คานเรือ บ่อตกตะกอนและบ่อบำบัดน้ำเสียมีสภาพทรุดโทรม และยืนยันว่าโอนให้ผู้ซื้อได้เฉพาะรายการที่ SAM จดทะเบียนรับโอนกรรมสิทธิ์เท่านั้น ต้องเทียบรายการทะเบียนกับผังขยายและอาคารจริง ไม่ถือว่าสิ่งปลูกสร้างหรือเครื่องจักรทุกชิ้นที่สำรวจพบรวมในการขายโดยอัตโนมัติ

ทำเลและข้อควรตรวจสอบ

ตั้งอยู่ในย่านที่อยู่อาศัยและเกษตรกรรม ใกล้มัสยิดยูโย สถานีอนามัยบานาและโรงเรียนชุมชนบ้านยูโย ตาม SAM จากถนนนาเกลือฝั่งยะรังมุ่งหน้าสะพานปลา ผ่านถนนรามโกมุทและโรงเรียนเมืองปัตตานี ทรัพย์อยู่ซ้ายมือระหว่างซอยนาเกลือ 21 และ 23 ก่อนถึงถนนเกษมสำราญประมาณ 920 เมตร

SAM ระบุสีผังเมืองเป็นสีส้ม ควรตรวจประเภทกิจการที่อนุญาต ใบอนุญาตโรงงาน ระบบห้องเย็น โรงน้ำแข็ง ระบบบำบัดและข้อกำหนดริมคลอง/แม่น้ำปัจจุบัน ต้นทางไม่ยืนยันสถานะเดินเครื่อง กำลังผลิต รายได้ ผู้เช่า เครื่องจักรที่รวมขายหรือพื้นที่ใช้สอยรวม จึงไม่เสนอเป็นโรงงานพร้อมผลิต

ภาพและการติดต่อ

ภาพจริงและผังจาก SAM รวม 13 ภาพ ใช้ผังขยายแปลงและสิ่งปลูกสร้างจากเอกสารแนบ ภาพถ่ายลงวันที่ 20 กรกฎาคม 2567 ควรตรวจสภาพปัจจุบัน พิกัด 6.881883, 101.260385 ดึงจากลิงก์นำทาง SAM และตรงกับแผนที่ เป็นจุดอ้างอิงรวม ไม่ใช่แนวเขตรังวัดของแต่ละกลุ่ม

ตรวจราคาและสถานะซื้อตรงวันที่ 15 กันยายน 2569 ติดต่อ SAM โทร.02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 8Z3208 เพื่อยืนยันราคา เอกสาร สิทธิข้ามคลอง รายการโอนและเงื่อนไขล่าสุด', 96597000, false, 34407.6, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ถนนนาเกลือ ระหว่างซอย21และ23', 'ที่ดินสองกลุ่ม มีคลองปูลาคั่น', 'ถนนนาเกลือ', 6.881883, 101.260385, 'ปัตตานี', 'เมืองปัตตานี', 'บานา', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-na-kluea-pattani-factory-8z3208') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'industrial') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 96597000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'factory', 1, '{"source_property_category":"โรงงาน/โกดัง","official_page_reference_code":"8Z3208","source_page_id":11499,"title_document_type":"chanote","title_document_count":13,"title_deed_numbers":["1929","4155","9469","9924","9925","9926","9927","10783","10784","10785","10786","10787","11308"],"plot_count":13,"group_count":2,"non_contiguous_groups":true,"land_area_square_wah":8601.9,"land_area_sqm":34407.6,"group1":{"plot_count":12,"area_square_wah":5238.2,"east_road_frontage_m_approx":102,"max_depth_m_approx":221,"west_canal_frontage_m_approx":42},"group2":{"title":"9469","plot_count":1,"area_square_wah":3363.7,"no_public_road_frontage":true,"east_canal_frontage_m_approx":160,"max_depth_m_approx":90,"west_river_frontage_m_approx":215},"group2_access_via_concrete_bridge_according_to_sam":true,"bridge_access_rights_and_load_capacity_require_verification":true,"registered_inventory_entry_count":23,"surveyed_structure_entry_count":25,"registered_and_surveyed_inventory_differ":true,"transfer_limited_to_registered_inventory":true,"dilapidated_items_source":["canteen","slipway","sedimentation pond","wastewater treatment pond"],"road_width_m_approx":12,"right_of_way_m_approx":20,"planning_colour_source_th":"สีส้ม","current_operations_capacity_income_occupancy_machinery_and_usable_area_unconfirmed":true,"status_checked_on":"2026-09-15","source_field_photo_date":"2024-07-20","coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//6.881883,101.260385","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 11499 identifies SAM as direct-sale contact for 8Z3208, Factory and warehouses in two canal-separated land groups in Pattani.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ SAM8Z3208 ราคา96,597,000บาท', 'Whole property SAM8Z3208 THB96597000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'group2_bridge_access', 'กลุ่ม2ไม่มีหน้าถนนสาธารณะ', 'Group2 bridge access', 'กลุ่ม2ต้องข้ามสะพานคอนกรีตคลองปูลา ต้องตรวจสิทธิใช้ทางและสภาพสะพาน', 'Group2 requires canal bridge;verify rights and condition', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'registered_transfer_only', 'โอนได้เฉพาะรายการตามทะเบียน', 'Registered inventory only', 'ทะเบียน23รายการ สำรวจ25รายการ โอนได้เฉพาะรายการรับโอนทางทะเบียน', '23registered versus25surveyed;registered transfer only', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'dilapidated_items', 'รายการทรุดโทรมตาม SAM', 'Dilapidated source items', 'โรงอาหาร คานเรือ บ่อตกตะกอนและบ่อบำบัดน้ำเสีย', 'Canteen,slipway,sedimentation and wastewater ponds', 'unspecified', 40) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'operating_status', 'สถานะโรงงานและเครื่องจักร', 'Operations and machinery', 'ไม่ยืนยันเดินเครื่อง กำลังผลิต เครื่องจักรรวมขายหรือพื้นที่ใช้สอยรวม', 'Operations,capacity,included machinery and usable area unconfirmed', 'unspecified', 50) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'ทางเข้าและหน้าทรัพย์ถนนนาเกลือ', 'ทางเข้าและหน้าทรัพย์ถนนนาเกลือ', 'https://npa.sam.or.th/site/images/npa/11499/20250521154213_8Z3208P2_68.jpg', '/listing-media/sam/8z3208/01.webp', 'image/webp', 32380, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางภายในและกลุ่มอาคาร', 'ทางภายในและกลุ่มอาคาร', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P3_68.jpg', '/listing-media/sam/8z3208/02.webp', 'image/webp', 26250, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวอาคารโรงงาน', 'แนวอาคารโรงงาน', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P4_68.jpg', '/listing-media/sam/8z3208/03.webp', 'image/webp', 28716, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารและลานภายใน', 'อาคารและลานภายใน', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P5_68.jpg', '/listing-media/sam/8z3208/04.webp', 'image/webp', 26430, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'อาคารชั้นเดียวตามสภาพ', 'อาคารชั้นเดียวตามสภาพ', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P6_68.jpg', '/listing-media/sam/8z3208/05.webp', 'image/webp', 22118, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ลานและสภาพพื้นที่ภายใน', 'ลานและสภาพพื้นที่ภายใน', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P7_68.jpg', '/listing-media/sam/8z3208/06.webp', 'image/webp', 24278, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'โถงภายในอาคาร', 'โถงภายในอาคาร', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P8_68.jpg', '/listing-media/sam/8z3208/07.webp', 'image/webp', 15578, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ภายในอาคารอีกมุม', 'ภายในอาคารอีกมุม', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P9_68.jpg', '/listing-media/sam/8z3208/08.webp', 'image/webp', 15068, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ห้องภายในตามสภาพ', 'ห้องภายในตามสภาพ', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P10_68.jpg', '/listing-media/sam/8z3208/09.webp', 'image/webp', 12502, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่โกดังและโครงหลังคา', 'พื้นที่โกดังและโครงหลังคา', 'https://npa.sam.or.th/site/images/npa/11499/8Z3208P11_68.jpg', '/listing-media/sam/8z3208/10.webp', 'image/webp', 23330, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังขยายที่ดินสองกลุ่ม มีคลองคั่น', 'ผังขยายที่ดินสองกลุ่ม มีคลองคั่น', 'https://npa.sam.or.th/site/attach/npa/11499/8Z3208C1_62.jpg', '/listing-media/sam/8z3208/11.webp', 'image/webp', 42544, 785, 600, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/11499/20160602211315_8Z3208M_59.jpg', '/listing-media/sam/8z3208/12.webp', 'image/webp', 36026, 785, 600, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังขยายสิ่งปลูกสร้างตามสำรวจ ต้องเทียบทะเบียนโอน', 'ผังขยายสิ่งปลูกสร้างตามสำรวจ ต้องเทียบทะเบียนโอน', 'https://npa.sam.or.th/site/attach/npa/11499/8Z3208C2.1_62.jpg', '/listing-media/sam/8z3208/13.webp', 'image/webp', 49424, 785, 600, 130, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=11499&keyref=', '8Z3208', now(), 'Checked2026-09-15. THB96597000,34407.6sqm,13Chanote plots/2canal-separated groups. Group2title9469 no public frontage; concrete bridge access rights require verification.23registered versus25surveyed;registered transfer only. Dilapidated canteen/slipway/treatment ponds disclosed; current operations/machinery unconfirmed.13authentic images/plans including expanded attachments;photo date2024-07-20. Navigation/map agree. All-status source/code/page/deed/nearby duplicate search empty.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', 'Na Kluea Road Factory and Warehouses, Pattani — 21 Rai', 'Factory, warehouses, cold stores and associated structures on Na Kluea Road, Bana, Mueang Pattani, Pattani.13Chanote titles total21rai2ngan1.9sq.wah,or8601.9sq.wah(34407.6sq.m.). SAM whole-property asking price THB96,597,000,reference8Z3208.

Two non-contiguous groups separated by Khlong Pu La. Group1:12adjoining titles1929,4155,9924–9927,10783–10787,11308,total13rai38.2sq.wah. Approximately102m eastern road frontage,221m maximum depth and42m western canal boundary. Group2:single title9469,8rai1ngan63.7sq.wah,approximately160m eastern canal boundary,90m maximum depth and215m western frontage on Pattani River. Group2 has no public-road frontage.

SAM says access to group2 requires a concrete bridge over the canal and expressly calls for access-right verification. Check bridge ownership,rights/easements,condition and load capacity; truck access or registered rights are not certified. Public Na Kluea Road serves group1,approximately12m paved carriageway and20m right of way according to source.

Registered inventory23entries includes guardhouse,two warehouses,receiving building,2-storey office,2-storey plant room,3-storey shop,lathe workshop,steam-generator shelter,staff toilets,cold store,plant room,ice plant,fresh-fish section,office/cold store,2-storey quality-control building,workers housing,2-storey personnel section,raw-material building,dried-fish/shop section,canteen,fish-drying equipment store and crispy-fish section.

Survey instead lists25entries including varied cold-store/office/plant/residential buildings,a slipway,sedimentation pond and wastewater treatment pond. SAM describes canteen,slipway,sedimentation and wastewater ponds as dilapidated. Transfer is expressly limited to SAM registered acquisition inventory. Reconcile registered list,expanded plans and actual structures; surveyed items and machinery are not automatically included.

Source reports residential/agricultural surroundings near Yuyo Mosque,Bana health station and Ban Yuyo community school. From Yarang toward the fishing pier along Na Kluea Road,pass Ram Komut Road and Mueang Pattani school; property left between soi21and23,approximately920m before Kasem Samran Road.

Source zoning orange. Verify current permitted industrial use,factory licence,cold-store/ice-plant/treatment systems and canal/river requirements. Current operations,capacity,income,tenants,included machinery and usable area are unconfirmed. Not represented as production-ready.

13authentic source images/plans including expanded parcel/building attachments. Photos dated20July2024;inspect present condition. Navigation/map agree6.881883,101.260385,a general reference point not individual group boundaries. Price/direct-sale status checked15September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting8Z3208.', 'Na Kluea Road between soi21and23', 'Two groups separated by Khlong Pu La', 'Na Kluea Road', 'Bana', 'Mueang Pattani', 'Pattani', 'Na Kluea Road Factory and Warehouses, Pattani — 21 Rai', 'Factory/warehouses34407.6sqm,THB96597000;group2bridge access and registered transfer limits disclosed.', 'published', 'ai_assisted', now(), 'na kluea road factory and warehouses, pattani — 21 rai factory, warehouses, cold stores and associated structures on na kluea road, bana, mueang pattani, pattani.13chanote titles total21rai2ngan1.9sq.wah,or8601.9sq.wah(34407.6sq.m.). sam whole-property asking price thb96,597,000,reference8z3208.

two non-contiguous groups separated by khlong pu la. group1:12adjoining titles1929,4155,9924–9927,10783–10787,11308,total13rai38.2sq.wah. approximately102m eastern road frontage,221m maximum depth and42m western canal boundary. group2:single title9469,8rai1ngan63.7sq.wah,approximately160m eastern canal boundary,90m maximum depth and215m western frontage on pattani river. group2 has no public-road frontage.

sam says access to group2 requires a concrete bridge over the canal and expressly calls for access-right verification. check bridge ownership,rights/easements,condition and load capacity; truck access or registered rights are not certified. public na kluea road serves group1,approximately12m paved carriageway and20m right of way according to source.

registered inventory23entries includes guardhouse,two warehouses,receiving building,2-storey office,2-storey plant room,3-storey shop,lathe workshop,steam-generator shelter,staff toilets,cold store,plant room,ice plant,fresh-fish section,office/cold store,2-storey quality-control building,workers housing,2-storey personnel section,raw-material building,dried-fish/shop section,canteen,fish-drying equipment store and crispy-fish section.

survey instead lists25entries including varied cold-store/office/plant/residential buildings,a slipway,sedimentation pond and wastewater treatment pond. sam describes canteen,slipway,sedimentation and wastewater ponds as dilapidated. transfer is expressly limited to sam registered acquisition inventory. reconcile registered list,expanded plans and actual structures; surveyed items and machinery are not automatically included.

source reports residential/agricultural surroundings near yuyo mosque,bana health station and ban yuyo community school. from yarang toward the fishing pier along na kluea road,pass ram komut road and mueang pattani school; property left between soi21and23,approximately920m before kasem samran road.

source zoning orange. verify current permitted industrial use,factory licence,cold-store/ice-plant/treatment systems and canal/river requirements. current operations,capacity,income,tenants,included machinery and usable area are unconfirmed. not represented as production-ready.

13authentic source images/plans including expanded parcel/building attachments. photos dated20july2024;inspect present condition. navigation/map agree6.881883,101.260385,a general reference point not individual group boundaries. price/direct-sale status checked15september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting8z3208.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=11499&keyref=', 'Official SAM page 11499 identifies SAM as asset holder and direct-sale contact for 8Z3208.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'b9003208-a6ee-4ef4-a19e-678963011499', '{"reference_code":"8Z3208","source_page_id":11499,"source_image_count":13,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
