BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-20628'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='3A1735' OR source_url ~ '[?&]id=20628(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='a9501735-05cb-4e65-89ec-610971020628' OR slug='sam-saeng-chuto-wang-sala-land-33-rai-3a1735' OR (abs(latitude-13.97389)<0.0001 AND abs(longitude-99.67369)<0.0001 AND abs(land_area_sqm-52907.6)<1)) THEN RAISE NOTICE 'SAM 3A1735 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('a9501735-05cb-4e65-89ec-610971020628', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'ที่ดิน 33 ไร่ 26.9 ตร.ว. ติดถนนแสงชูโต วังศาลา ท่าม่วง', 'รายละเอียดทรัพย์

ที่ดินเปล่าถนนแสงชูโต (ทล.323) ตำบลวังศาลา อำเภอท่าม่วง จังหวัดกาญจนบุรี โฉนดเลขที่ 10122 จำนวน 1 ฉบับ เนื้อที่ 33 ไร่ 26.9 ตร.ว. หรือ 13,226.9 ตร.ว. (52,907.6 ตร.ม.) ราคาประกาศขายทั้งทรัพย์ 94,295,000 บาท รหัส SAM 3A1735 ต้นทางแสดงราคาเฉลี่ยประมาณ 7,129 บาทต่อ ตร.ว.

ลักษณะที่ดิน

แปลงรูปหลายเหลี่ยม ด้านเหนือติดถนนกว้างประมาณ 105 เมตร ลึกสุดประมาณ 445 เมตร ระดับที่ดินใกล้เคียงถนนหน้าทรัพย์ ภายในมีบ่อน้ำประมาณ 10 × 20 เมตร ลึกประมาณ 2 เมตร คิดเป็นพื้นที่ประมาณ 50 ตร.ว. ตาม SAM ควรตรวจแนวเขต ระดับดิน การระบายน้ำและพื้นที่ใช้สอยจริงก่อนเสนอซื้อ

ถนนแสงชูโตเป็นทางสาธารณประโยชน์ ผิวลาดยางกว้างประมาณ 16 เมตร SAM ระบุเขตทางรวมประมาณ 150 เมตร ซึ่งรวมเขตทางรถไฟด้วย ไม่ใช่ความกว้างผิวถนนหรือเนื้อที่ของทรัพย์ ผู้สนใจควรตรวจเขตทางและตำแหน่งทางเข้าออกสำหรับกิจกรรมที่ต้องการ

ข้อมูลผังเมืองที่ต้องตรวจสอบ

หัวข้อสรุปและข้อมูลเบื้องต้นจากเว็บไซต์กรมโยธาธิการและผังเมืองที่ SAM อ้างระบุสีม่วง แต่ข้อความสำรวจในหน้าเดียวกันระบุทั้งสีม่วงประเภทอุตสาหกรรมและคลังสินค้า และสีเขียวประเภทชนบทและเกษตรกรรม ข้อมูลจึงยังไม่ยืนยันสัดส่วนหรือแนวแบ่งสีภายในโฉนด ต้องตรวจแผนผังและข้อกำหนดฉบับปัจจุบันกับหน่วยงานที่เกี่ยวข้องก่อนตัดสินใจ ไม่รับรองว่าพื้นที่ทั้งแปลงเป็นสีม่วงหรือตั้งโรงงานได้ทุกประเภท

ทำเลและการเดินทาง

SAM ระบุทรัพย์อยู่ในย่านที่อยู่อาศัยและพาณิชยกรรม ใกล้ที่ว่าการอำเภอท่าม่วง สถานีรถไฟทุ่งทองและตลาดโรงเกลือ จากนครปฐมมุ่งหน้าตัวเมืองกาญจนบุรีทางถนนแสงชูโต ผ่านแยกหนองเสือ ถึงบริเวณ กม.41+130 ทรัพย์อยู่ซ้ายมือ

ต้นทางมีบันทึกสำรวจเดือนมกราคม 2568 กล่าวถึงแนวมอเตอร์เวย์สายบางใหญ่–กาญจนบุรี (หมายเลข81) ห่างไปทางเหนือประมาณ 3 กม. เป็นข้อมูลโครงการตามช่วงเวลาที่บันทึก ไม่ใช่ระยะถึงทางขึ้นลงหรือข้อมูลสถานะเปิดบริการปัจจุบัน

ภาพและการติดต่อ

ใช้ภาพจริงและผังจาก SAM 13 ภาพ ภาพหน้าทรัพย์มีวันที่ 10 กันยายน 2566 และภาพพื้นที่มีวันที่ 6 ตุลาคม 2565 รวมภาพบ่อน้ำ ผังแปลง ภาพผังเมืองอ้างอิงและแผนที่ ควรนัดดูสภาพปัจจุบัน อาคารข้างเคียงที่ปรากฏในภาพไม่ถือว่ารวมขาย ต้นทางไม่ยืนยันผู้ใช้ประโยชน์ ภาระผูกพันปัจจุบันหรือสาธารณูปโภคภายในครบถ้วน

พิกัด 13.97389, 99.67369 ดึงจากลิงก์นำทาง SAM และตรงกับแผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ตรวจราคาและสถานะซื้อตรงวันที่ 15 กันยายน 2569 ติดต่อ SAM โทร.02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 3A1735 เพื่อยืนยันราคา เอกสาร ผังเมืองและเงื่อนไขล่าสุด', 94295000, false, 52907.6, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ถนนแสงชูโต ทล.323 กม.41+130', 'ผ่านแยกหนองเสือมุ่งหน้ากาญจนบุรี', 'ถนนแสงชูโต (ทล.323)', 13.97389, 99.67369, 'กาญจนบุรี', 'ท่าม่วง', 'วังศาลา', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-saeng-chuto-wang-sala-land-33-rai-3a1735') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'industrial') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 94295000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"ที่ดินเปล่า","official_page_reference_code":"3A1735","source_page_id":20628,"title_document_type":"chanote","title_document_count":1,"title_deed_number":"10122","plot_count":1,"land_area_square_wah":13226.9,"land_area_sqm":52907.6,"source_price_per_square_wah_thb":7129,"north_frontage_m_approx":105,"max_depth_m_approx":445,"land_level_similar_to_road":true,"pond_width_m_approx":10,"pond_length_m_approx":20,"pond_depth_m_approx":2,"pond_area_square_wah_source":50,"road_width_m_approx":16,"combined_right_of_way_m_approx":150,"right_of_way_includes_railway":true,"summary_zoning_colour_th":"สีม่วง","survey_zoning_colours_th":["สีม่วง","สีเขียว"],"zoning_extent_conflict_disclosed":true,"current_official_zoning_requires_verification":true,"source_motorway_alignment_distance_km_approx":3,"source_motorway_direction":"north","source_motorway_note_date":"2025-01","motorway_distance_not_interchange_distance":true,"neighbouring_buildings_not_included":true,"status_checked_on":"2026-09-15","source_field_photo_dates":["2022-10-06","2023-09-10"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.97389,99.67369","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 20628 identifies SAM as direct-sale contact for 3A1735, Saeng Chuto Road land in Wang Sala, Tha Muang.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ SAM3A1735 ราคา94,295,000บาท', 'Whole property SAM3A1735 THB94295000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'zoning_conflict', 'ผังเมืองที่ต้องยืนยัน', 'Zoning uncertainty', 'สรุปสีม่วง แต่สำรวจระบุม่วงและเขียว ต้องตรวจแนวเขตและข้อกำหนดปัจจุบัน', 'Summary purple;survey purple/green;verify current boundaries and rules', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'road_rail_boundary', 'เขตทางรวมทางรถไฟ', 'Combined road and rail right of way', 'SAM ระบุเขตทาง150เมตรรวมทางรถไฟ ไม่ใช่ผิวถนนหรือเนื้อที่ขาย', 'Source150m right of way includes railway;not pavement width or sale area', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'pond', 'บ่อน้ำในแปลง', 'On-site pond', 'ประมาณ10×20เมตร ลึก2เมตร พื้นที่50ตร.ว.ตาม SAM', 'Approximately10×20m,2m deep,50sq.wah per SAM', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'หน้าที่ดินติดถนนแสงชูโต', 'หน้าที่ดินติดถนนแสงชูโต', 'https://npa.sam.or.th/site/images/npa/20628/20240815114430_3A1735P1.1_66.jpg', '/listing-media/sam/3a1735/01.webp', 'image/webp', 22942, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางเข้าและป้ายทรัพย์', 'ทางเข้าและป้ายทรัพย์', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P1.2_66.jpg', '/listing-media/sam/3a1735/02.webp', 'image/webp', 27406, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ถนนแสงชูโตหน้าทรัพย์', 'ถนนแสงชูโตหน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P2_65.jpg', '/listing-media/sam/3a1735/03.webp', 'image/webp', 23920, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวหน้าที่ดินอีกมุม', 'แนวหน้าที่ดินอีกมุม', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P3_65.jpg', '/listing-media/sam/3a1735/04.webp', 'image/webp', 19678, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางภายในและแนวต้นไม้', 'ทางภายในและแนวต้นไม้', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P4_65.jpg', '/listing-media/sam/3a1735/05.webp', 'image/webp', 34236, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพพื้นที่และแนวทางเดิน', 'สภาพพื้นที่และแนวทางเดิน', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P5_65.jpg', '/listing-media/sam/3a1735/06.webp', 'image/webp', 26922, 449, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ที่ดินภายใน อาคารข้างเคียงไม่ถือว่ารวมขาย', 'ที่ดินภายใน อาคารข้างเคียงไม่ถือว่ารวมขาย', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P6_65.jpg', '/listing-media/sam/3a1735/07.webp', 'image/webp', 29270, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บ่อน้ำภายในแปลง', 'บ่อน้ำภายในแปลง', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P7_65.jpg', '/listing-media/sam/3a1735/08.webp', 'image/webp', 29002, 450, 450, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'พื้นที่ภายในและต้นไม้', 'พื้นที่ภายในและต้นไม้', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P8_65.jpg', '/listing-media/sam/3a1735/09.webp', 'image/webp', 22578, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพที่ดินอีกมุม', 'สภาพที่ดินอีกมุม', 'https://npa.sam.or.th/site/images/npa/20628/3A1735P9_65.jpg', '/listing-media/sam/3a1735/10.webp', 'image/webp', 29852, 450, 450, 100, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงโฉนด10122และบ่อน้ำ', 'ผังแปลงโฉนด10122และบ่อน้ำ', 'https://npa.sam.or.th/site/images/npa/20628/20221207102420_3A1735C1_65.jpg', '/listing-media/sam/3a1735/11.webp', 'image/webp', 20862, 450, 450, 110, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ภาพผังเมืองอ้างอิงจาก SAM ต้องตรวจแนวเขตปัจจุบัน', 'ภาพผังเมืองอ้างอิงจาก SAM ต้องตรวจแนวเขตปัจจุบัน', 'https://npa.sam.or.th/site/images/npa/20628/20250114105729_3A1735C1.1_67.jpg', '/listing-media/sam/3a1735/12.webp', 'image/webp', 148408, 720, 720, 120, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/20628/20221207102420_3A1735M1_65.jpg', '/listing-media/sam/3a1735/13.webp', 'image/webp', 75468, 785, 600, 130, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=20628&keyref=', '3A1735', now(), 'Checked2026-09-15. THB94295000,52907.6sqm,Chanote10122. Summary purple zoning versus survey purple/green explicitly disclosed without certifying full industrial use.105m frontage,445m depth,pond10x20m/depth2m.150mROW includes railway. Motorway alignment3km north is January2025source context,not current service/interchange distance.13authentic images/plans,photo dates2022-10-06/2023-09-10. Navigation/map agree. All-status source/code/page/deed/nearby duplicate query empty.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', '33 Rai Land on Saeng Chuto Road, Wang Sala, Tha Muang', 'Vacant land on Saeng Chuto Road (Highway323),Wang Sala,Tha Muang,Kanchanaburi. One Chanote10122,total33rai26.9sq.wah,or13226.9sq.wah(52907.6sq.m.). SAM whole-property asking price THB94,295,000,reference3A1735;source approximate unit price THB7,129/sq.wah.

Irregular plot with approximately105m northern road frontage and maximum depth445m. Land level approximately similar to frontage road. Pond approximately10by20m,2m deep,50sq.wah according to SAM. Inspect boundaries,ground levels,drainage and usable area.

SAM describes public Saeng Chuto Road,approximately16m paved carriageway and150m combined right of way including railway land. The150m figure is not road pavement width or property area. Verify road/rail boundaries and access requirements.

Material zoning uncertainty: source summary and preliminary DPT website information cited by SAM show purple,whereas the same page''s survey text reports both purple industrial/warehouse and green rural/agricultural zoning. Proportions and boundaries within this title are unconfirmed. Obtain current official planning and rules; do not presume the entire site is purple or every industrial use is allowed.

Residential/commercial surroundings near Tha Muang district office,Thung Thong railway station and Rong Kluea market. From Nakhon Pathom toward Kanchanaburi on Highway323,pass Nong Suea junction to km41+130;property left. SAM''s January2025survey mentions Motorway81alignment approximately3km north. This is dated alignment context,not distance to an interchange or current service status.

13authentic source images/plans:frontage photos dated10September2023,site photos6October2022,plus pond,parcel,zoning reference and route maps. Neighbouring buildings are not presumed included. Current occupancy,encumbrances and full on-site utilities unconfirmed. Navigation/map agree13.97389,99.67369,reference point not surveyed boundaries. Price/direct-sale status checked15September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting3A1735.', 'Saeng Chuto Highway323 km41+130', 'Past Nong Suea junction toward Kanchanaburi', 'Saeng Chuto Road (Highway323)', 'Wang Sala', 'Tha Muang', 'Kanchanaburi', '33 Rai Land on Saeng Chuto Road, Wang Sala, Tha Muang', 'Land52907.6sqm,THB94295000;source purple versus purple/green zoning,pond and combined road/rail boundary disclosed.', 'published', 'ai_assisted', now(), '33 rai land on saeng chuto road, wang sala, tha muang vacant land on saeng chuto road (highway323),wang sala,tha muang,kanchanaburi. one chanote10122,total33rai26.9sq.wah,or13226.9sq.wah(52907.6sq.m.). sam whole-property asking price thb94,295,000,reference3a1735;source approximate unit price thb7,129/sq.wah.

irregular plot with approximately105m northern road frontage and maximum depth445m. land level approximately similar to frontage road. pond approximately10by20m,2m deep,50sq.wah according to sam. inspect boundaries,ground levels,drainage and usable area.

sam describes public saeng chuto road,approximately16m paved carriageway and150m combined right of way including railway land. the150m figure is not road pavement width or property area. verify road/rail boundaries and access requirements.

material zoning uncertainty: source summary and preliminary dpt website information cited by sam show purple,whereas the same page''s survey text reports both purple industrial/warehouse and green rural/agricultural zoning. proportions and boundaries within this title are unconfirmed. obtain current official planning and rules; do not presume the entire site is purple or every industrial use is allowed.

residential/commercial surroundings near tha muang district office,thung thong railway station and rong kluea market. from nakhon pathom toward kanchanaburi on highway323,pass nong suea junction to km41+130;property left. sam''s january2025survey mentions motorway81alignment approximately3km north. this is dated alignment context,not distance to an interchange or current service status.

13authentic source images/plans:frontage photos dated10september2023,site photos6october2022,plus pond,parcel,zoning reference and route maps. neighbouring buildings are not presumed included. current occupancy,encumbrances and full on-site utilities unconfirmed. navigation/map agree13.97389,99.67369,reference point not surveyed boundaries. price/direct-sale status checked15september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting3a1735.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=20628&keyref=', 'Official SAM page 20628 identifies SAM as asset holder and direct-sale contact for 3A1735.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'a9501735-05cb-4e65-89ec-610971020628', '{"reference_code":"3A1735","source_page_id":20628,"source_image_count":13,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
