BEGIN;
DO $$
DECLARE admin_user_id bigint; sam_organization_id bigint; property_listing_id bigint;
BEGIN
PERFORM pg_advisory_xact_lock(hashtext('sam-import-8412'));
IF EXISTS (SELECT 1 FROM listing_sources WHERE upper(reference_code)='1T1460' OR source_url ~ '[?&]id=8412(&|$)') OR EXISTS (SELECT 1 FROM listings WHERE public_listing_id='d3301460-44cb-4a85-af37-947116008412' OR slug='sam-sai-noi-land-54-rai-1t1460' OR (abs(latitude-13.99566)<0.0001 AND abs(longitude-100.32616)<0.0001 AND abs(land_area_sqm-87551.2)<1)) THEN RAISE NOTICE 'SAM 1T1460 exists; skipping'; RETURN; END IF;
SELECT id INTO admin_user_id FROM auth_users WHERE lower(email)='mapxprop@gmail.com' AND deleted_at IS NULL ORDER BY id LIMIT 1;
SELECT id INTO sam_organization_id FROM organizations WHERE slug='sukhumvit-asset-management-sam' AND verification_status='verified' AND is_active=true AND deleted_at IS NULL ORDER BY id LIMIT 1;
IF admin_user_id IS NULL OR sam_organization_id IS NULL THEN RAISE EXCEPTION 'Existing admin and verified SAM organization required'; END IF;
INSERT INTO public.listings (public_listing_id, user_id, organization_id, created_by_user_id, published_by_user_id, property_type_code, usage_type, listing_type, listing_scope, title, description, sale_price, price_negotiable, land_area_sqm, contact_name, contact_phone, contact_email, line_id, show_phone, show_email, address_line1, address_line2, road, latitude, longitude, province_name, district_name, subdistrict_name, listing_status, moderation_status, approved_at, published_at, moderation_submitted_at, moderated_at, is_verified, is_active, source_channel, price_unit, slug) VALUES ('d3301460-44cb-4a85-af37-947116008412', admin_user_id, sam_organization_id, admin_user_id, admin_user_id, 'land', 'business', 'sale', 'whole_property', 'ที่ดิน 54 ไร่ 2 งาน 87.8 ตร.ว. ซอย กศน.บ้านคลองห้าร้อย ไทรน้อย', 'รายละเอียดทรัพย์

ที่ดินเปล่า 2 แปลงติดกัน ตำบลไทรน้อย อำเภอไทรน้อย จังหวัดนนทบุรี โฉนดเลขที่ 4885 และ 60808 (เลขเดิม 12065) เนื้อที่รวม 54 ไร่ 2 งาน 87.8 ตร.ว. หรือ 21,887.8 ตร.ว. (87,551.2 ตร.ม.) ราคาประกาศขายทั้งทรัพย์ 89,697,000 บาท รหัส SAM 1T1460 ต้นทางแสดงราคาเฉลี่ยประมาณ 4,098 บาทต่อ ตร.ว.

หน้าทรัพย์และสภาพที่ดิน

ทรัพย์เข้าจากถนนบางกรวย–ไทรน้อย (ทล.3215) ผ่านซอย อบต.ไทรน้อยเก่า โดยถนนหน้าทรัพย์คือซอย กศน.บ้านคลองห้าร้อย ไม่ใช่หน้าถนน ทล.3215 โดยตรง แปลงรวมรูปหลายเหลี่ยม ด้านตะวันตกติดถนนประมาณ 76 เมตร ลึกสุดประมาณ 1,028 เมตร ระดับที่ดินเฉลี่ยต่ำกว่าถนนประมาณ 1.6 เมตร ตาม SAM

มีบ่อน้ำ 2 บ่อ บ่อที่ 1 ขนาดประมาณ 11 × 580 เมตร ลึก 2 เมตร บ่อที่ 2 ประมาณ 5 × 62 เมตร ลึก 1 เมตร รวมพื้นที่บ่อตามต้นทางประมาณ 4 ไร่ 72.5 ตร.ว. ซึ่งอยู่ภายในเนื้อที่รวม ไม่ใช่พื้นที่เพิ่ม ควรตรวจระดับดิน การระบายน้ำ สภาพบ่อและพื้นที่ใช้งานจริงก่อนเสนอซื้อ

ถนนซอยหน้าทรัพย์ SAM ระบุเป็นทางสาธารณประโยชน์ ผิวลาดยางประมาณ 6 เมตร เขตทางประมาณ 16 เมตร ผังต้นทางระบายสีเทาบริเวณด้านหน้าและกำกับว่า “ส่วนที่มีสภาพเป็นทาง” แต่ไม่ระบุเนื้อที่หรือรายละเอียดสิทธิทางทะเบียนไว้ในข้อความ ควรตรวจแนวเขต การใช้ทางและพื้นที่ที่จะโอนจริง ไม่ตีความภาพผังเป็นการรับรองว่ามีหรือไม่มีภาระจำยอม

เอกสารสิทธิ์และการใช้ประโยชน์

โฉนด 4885 ระบุที่ตั้งตำบลไทรน้อย อำเภอบางบัวทอง จังหวัดนนทบุรี ส่วนโฉนด 60808 (12065 เดิม) ระบุอำเภอไทรน้อย (บางบัวทอง) ตาม SAM ขณะที่ประกาศใช้ที่ตั้งปัจจุบันเป็นอำเภอไทรน้อย ควรตรวจเลขโฉนดเดิม–ใหม่และชื่อเขตปกครองกับเอกสารปัจจุบัน

SAM ระบุผังเมืองสีเขียว ควรตรวจข้อกำหนดการใช้ประโยชน์ปัจจุบันตามกิจกรรมที่ต้องการ ต้นทางไม่ยืนยันผู้ใช้ประโยชน์ ภาระผูกพันล่าสุดหรือระบบสาธารณูปโภคภายในครบถ้วน

ทำเลและการเดินทาง

ตามต้นทางห่าง กศน.ไทรน้อยประมาณ 900 เมตร และบิ๊กซีไทรน้อยประมาณ 1.4 กม. ใช้ถนนบางกรวย–ไทรน้อยจากกาญจนาภิเษก ทล.9 มุ่งหน้า ทล.346 ผ่านโรงพยาบาลไทรน้อยและสถานีตำรวจ ถึงบริเวณ กม.26+100 เลี้ยวขวาเข้าซอย อบต.ไทรน้อยเก่าประมาณ 1.4 กม. คำบรรยายการเข้าถึงของ SAM ระบุพบทรัพย์ทั้งซ้ายและขวา ควรใช้ผังและตรวจแนวเขตจริงประกอบ ไม่สรุปตำแหน่งแปลงจากคำบอกทางเพียงอย่างเดียว

ภาพและการติดต่อ

ภาพจริงและผังจาก SAM รวม 10 ภาพ ภาพหน้าทรัพย์ลงวันที่ 14 มิถุนายน 2566 และภาพแปลง/บ่อน้ำมีวันที่ 24 พฤศจิกายน 2566 รวมภาพแยกเข้าซอยซึ่งไม่ใช่หน้าทรัพย์โดยตรง ควรนัดตรวจสภาพปัจจุบัน

พิกัด 13.99566, 100.32616 ดึงจากลิงก์นำทาง SAM และตรงกับแผนที่ เป็นจุดอ้างอิง ไม่ใช่แนวเขตรังวัด ตรวจราคาและสถานะซื้อตรงวันที่ 15 กันยายน 2569 ติดต่อ SAM โทร.02-686-1888 อีเมล sales@sam.or.th หรือ LINE @samline แจ้งรหัส 1T1460 เพื่อยืนยันราคา เอกสาร แนวเขตและเงื่อนไขล่าสุด', 89697000, false, 87551.2, 'ฝ่ายขายและส่งเสริมกิจกรรมการขาย — SAM', '026861888', 'sales@sam.or.th', '@samline', true, true, 'ซอย กศน.บ้านคลองห้าร้อย', 'เข้าจากซอย อบต.ไทรน้อยเก่า ถนนบางกรวย–ไทรน้อย', 'ซอย กศน.บ้านคลองห้าร้อย', 13.99566, 100.32616, 'นนทบุรี', 'ไทรน้อย', 'ไทรน้อย', 'active', 'approved', now(), now(), now(), now(), true, true, 'editorial_import', 'total', 'sam-sai-noi-land-54-rai-1t1460') RETURNING id INTO property_listing_id;
INSERT INTO public.listing_use_cases (listing_id, use_case_code) VALUES (property_listing_id, 'agriculture') ;
INSERT INTO public.listing_offers (listing_id, offer_type, amount, price_unit, currency_code, is_negotiable) VALUES (property_listing_id, 'sale', 89697000, 'total', 'THB', false) ;
INSERT INTO public.listing_discovery_channels (listing_id, channel_code, source, is_featured) VALUES (property_listing_id, 'business', 'editorial', false) ;
INSERT INTO public.listing_category_details (listing_id, category_code, schema_version, details, is_minimum_submission) VALUES (property_listing_id, 'land', 1, '{"source_property_category":"ที่ดินเปล่า","official_page_reference_code":"1T1460","source_page_id":8412,"title_document_type":"chanote","title_document_count":2,"title_deed_numbers":["4885","60808"],"former_title_number":"12065","plot_count":2,"adjoining_plots":true,"land_area_square_wah":21887.8,"land_area_sqm":87551.2,"source_price_per_square_wah_thb":4098,"west_frontage_m_approx":76,"max_depth_m_approx":1028,"below_road_level_m_approx":1.6,"pond_count":2,"ponds":[{"width_m":11,"length_m":580,"depth_m":2},{"width_m":5,"length_m":62,"depth_m":1}],"pond_total_area_square_wah_source":1672.5,"pond_area_included_in_total":true,"frontage_on_soi_not_highway3215":true,"road_width_m_approx":6,"right_of_way_m_approx":16,"source_plan_grey_area_label_th":"ส่วนที่มีสภาพเป็นทาง","grey_road_area_and_registered_rights_not_specified":true,"title_address_district_difference_disclosed":true,"planning_colour_source_th":"สีเขียว","source_directions_both_sides_require_boundary_check":true,"status_checked_on":"2026-09-15","source_field_photo_dates":["2023-06-14","2023-11-24"],"coordinate_source":"sam_navigation_href","navigation_url":"https://www.google.com/maps/dir//13.99566,100.32616","map_link_agrees":true,"coordinates_not_surveyed_boundary":true,"administrator_coordinates_used":false}'::jsonb, true) ;
INSERT INTO public.listing_contact_profiles (listing_id, role_code, authority_source_code, organization_name, organization_registration_no, verification_status, verification_note, verified_at, verified_by_user_id, organization_id, contact_user_id) VALUES (property_listing_id, 'developer_investor_representative', 'investor_asset_holder', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', '0105543033809', 'authority_verified', 'Official SAM page 8412 identifies SAM as direct-sale contact for 1T1460, Two adjoining land plots in Sai Noi with ponds and below-road ground level.', now(), admin_user_id, sam_organization_id, NULL) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'purchase_method', 'รูปแบบการขาย', 'Sale method', 'ขายทั้งทรัพย์ SAM1T1460 ราคา89,697,000บาท', 'Whole property SAM1T1460 THB89697000', 'unspecified', 10) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'ground_and_ponds', 'ระดับที่ดินและบ่อน้ำ', 'Ground level and ponds', 'ต่ำกว่าถนนเฉลี่ย1.6เมตร บ่อ2บ่อรวม4ไร่72.5ตร.ว.อยู่ในเนื้อที่ขาย', 'Average1.6m below road;2ponds totaling4rai72.5sq.wah within sale area', 'unspecified', 20) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'frontage_and_road_area', 'หน้าซอยและส่วนที่มีสภาพเป็นทาง', 'Soi frontage and road-use area', 'ติดซอย ไม่ใช่ทล.3215โดยตรง ผังมีสีเทาแสดงสภาพเป็นทาง ต้องตรวจสิทธิ/เนื้อที่', 'Soi frontage,not3215;grey road-use portion requires rights/area verification', 'unspecified', 30) ;
INSERT INTO public.listing_transaction_terms (listing_id, term_code, label_th, label_en, value_th, value_en, payer_code, sort_order) VALUES (property_listing_id, 'title_numbers', 'เลขโฉนดและที่ตั้ง', 'Title numbers and address', '4885และ60808(เดิม12065)มีชื่ออำเภอบางบัวทอง/ไทรน้อยตามเอกสาร', '4885and60808(former12065),historic Bang Bua Thong/Sai Noi addresses', 'unspecified', 40) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'cover', 'หน้าทรัพย์ติดถนนซอย', 'หน้าทรัพย์ติดถนนซอย', 'https://npa.sam.or.th/site/images/npa/8412/20260105111126_1T1460P2_67.jpg', '/listing-media/sam/1t1460/01.webp', 'image/webp', 26832, 450, 450, 10, true, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แปลงที่ดินและแนวบ่อ', 'แปลงที่ดินและแนวบ่อ', 'https://npa.sam.or.th/site/images/npa/8412/P1 67 .jpg', '/listing-media/sam/1t1460/02.webp', 'image/webp', 22452, 450, 450, 20, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'แนวที่ดินตามภาพต้นทาง', 'แนวที่ดินตามภาพต้นทาง', 'https://npa.sam.or.th/site/images/npa/8412/P2 67.jpg', '/listing-media/sam/1t1460/03.webp', 'image/webp', 24906, 450, 450, 30, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'สภาพพื้นที่อีกมุม', 'สภาพพื้นที่อีกมุม', 'https://npa.sam.or.th/site/images/npa/8412/P3 67.jpg', '/listing-media/sam/1t1460/04.webp', 'image/webp', 19378, 450, 450, 40, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณบ่อน้ำ1ตามต้นทาง', 'บริเวณบ่อน้ำ1ตามต้นทาง', 'https://npa.sam.or.th/site/images/npa/8412/P5 67.jpg', '/listing-media/sam/1t1460/05.webp', 'image/webp', 30530, 450, 450, 50, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'บริเวณบ่อน้ำ2ตามต้นทาง', 'บริเวณบ่อน้ำ2ตามต้นทาง', 'https://npa.sam.or.th/site/images/npa/8412/P4 67.jpg', '/listing-media/sam/1t1460/06.webp', 'image/webp', 33862, 450, 450, 60, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'gallery', 'ทางแยกเข้าซอยจากทล.3215 ไม่ใช่หน้าทรัพย์', 'ทางแยกเข้าซอยจากทล.3215 ไม่ใช่หน้าทรัพย์', 'https://npa.sam.or.th/site/images/npa/8412/1T1460P1_67.jpg', '/listing-media/sam/1t1460/07.webp', 'image/webp', 36502, 450, 450, 70, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังแปลงและส่วนสีเทาที่มีสภาพเป็นทาง', 'ผังแปลงและส่วนสีเทาที่มีสภาพเป็นทาง', 'https://npa.sam.or.th/site/images/npa/8412/20240402102848_1T1460C3_67.jpg', '/listing-media/sam/1t1460/08.webp', 'image/webp', 30254, 719, 452, 80, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'site_plan', 'ผังบ่อน้ำสองบ่อภายในแปลง', 'ผังบ่อน้ำสองบ่อภายในแปลง', 'https://npa.sam.or.th/site/images/npa/8412/20240402102848_1T1460C1_67.jpg', '/listing-media/sam/1t1460/09.webp', 'image/webp', 19282, 450, 450, 90, false, true) ;
INSERT INTO public.listing_media (listing_id, media_type, source_type, role_code, title, alt_text, original_url, file_url, mime_type, file_size_bytes, width, height, sort_order, is_primary, is_active) VALUES (property_listing_id, 'image', 'editorial_import', 'map', 'แผนที่การเดินทางจาก SAM', 'แผนที่การเดินทางจาก SAM', 'https://npa.sam.or.th/site/images/npa/8412/20240404101201_1T1460M_67.jpg', '/listing-media/sam/1t1460/10.webp', 'image/webp', 62330, 785, 600, 100, false, true) ;
INSERT INTO public.listing_sources (listing_id, source_type, publisher_name, source_url, reference_code, captured_at, notes) VALUES (property_listing_id, 'editorial_import', 'บริษัท บริหารสินทรัพย์สุขุมวิท จำกัด (SAM)', 'https://www.sam.or.th/site/npa/detail.php?id=8412&keyref=', '1T1460', now(), 'Checked2026-09-15. THB89697000,87551.2sqm,titles4885/60808(former12065).Soi frontage not3215. Ground1.6m below road,two ponds1672.5sqwah within total. Grey plan portion physically road,area/registered rights unspecified. Historic district names and source both-sides directions disclosed.10authentic images/plans,photo dates2023-06-14/2023-11-24. Navigation/map agree. All-status source/code/page/deed/nearby duplicate query empty.') ;
INSERT INTO public.listing_translations (listing_id, language_code, title, description, address_line1, address_line2, road, subdistrict_name, district_name, province_name, seo_title, seo_description, translation_status, translation_source, reviewed_at, search_text) VALUES (property_listing_id, 'en', '54 Rai Land in Sai Noi, Nonthaburi', 'Two adjoining vacant land plots in Sai Noi,Nonthaburi. Chanote4885and60808(former12065),total54rai2ngan87.8sq.wah,or21887.8sq.wah(87551.2sq.m.). SAM whole-property asking price THB89,697,000,reference1T1460;source approximate unit price THB4098/sq.wah.

Access from Bang Kruai–Sai Noi Highway3215 via the former Sai Noi local administration soi. Actual frontage is Soi Ko So No Ban Khlong Ha Roi,not Highway3215 itself. Irregular combined plot,approximately76m western road frontage and1028m maximum depth. Ground averages1.6m below road according to SAM.

Two ponds:approximately11by580m,2m deep,and5by62m,1m deep. Combined source pond area4rai72.5sq.wah is within total land,not additional area. Inspect levels,drainage,ponds and usable area. Source describes public frontage soi with6m paved carriageway and16m right of way. Source plan shades a frontage portion grey as land physically used as a road;area and registered rights are unspecified. Verify boundary,use/access and transferable area;the diagram does not establish existence or absence of a registered easement.

Title4885states Bang Bua Thong district;60808(former12065)states Sai Noi(Bang Bua Thong),while current listing address is Sai Noi. Verify historic/current title numbers and administrative records. Source zoning green;confirm current permitted use. Current occupancy,encumbrances and full utilities unconfirmed.

SAM reports approximately900m from Sai Noi non-formal education centre and1.4km from Big C Sai Noi. From Highway9 along3215toward346,pass hospital/police station to km26+100,turn right into former local administration soi for1.4km. Source directions say property on both sides;use plans and field survey to confirm precise parcel placement.

Ten authentic source photos/plans. Frontage photo14June2023;parcel/pond photos24November2023. Junction photo is access context,not direct property frontage. Navigation/map agree13.99566,100.32616,reference point not surveyed boundary. Price/direct-sale status checked15September2026. Contact SAM02-686-1888,sales@sam.or.th or LINE@samline quoting1T1460.', 'Soi Ko So No Ban Khlong Ha Roi', 'Via former Sai Noi local administration soi off Highway3215', 'Soi Ko So No Ban Khlong Ha Roi', 'Sai Noi', 'Sai Noi', 'Nonthaburi', '54 Rai Land in Sai Noi, Nonthaburi', 'Sai Noi land87551.2sqm,THB89697000;two ponds,below-road levels,soi frontage and road-use area disclosed.', 'published', 'ai_assisted', now(), '54 rai land in sai noi, nonthaburi two adjoining vacant land plots in sai noi,nonthaburi. chanote4885and60808(former12065),total54rai2ngan87.8sq.wah,or21887.8sq.wah(87551.2sq.m.). sam whole-property asking price thb89,697,000,reference1t1460;source approximate unit price thb4098/sq.wah.

access from bang kruai–sai noi highway3215 via the former sai noi local administration soi. actual frontage is soi ko so no ban khlong ha roi,not highway3215 itself. irregular combined plot,approximately76m western road frontage and1028m maximum depth. ground averages1.6m below road according to sam.

two ponds:approximately11by580m,2m deep,and5by62m,1m deep. combined source pond area4rai72.5sq.wah is within total land,not additional area. inspect levels,drainage,ponds and usable area. source describes public frontage soi with6m paved carriageway and16m right of way. source plan shades a frontage portion grey as land physically used as a road;area and registered rights are unspecified. verify boundary,use/access and transferable area;the diagram does not establish existence or absence of a registered easement.

title4885states bang bua thong district;60808(former12065)states sai noi(bang bua thong),while current listing address is sai noi. verify historic/current title numbers and administrative records. source zoning green;confirm current permitted use. current occupancy,encumbrances and full utilities unconfirmed.

sam reports approximately900m from sai noi non-formal education centre and1.4km from big c sai noi. from highway9 along3215toward346,pass hospital/police station to km26+100,turn right into former local administration soi for1.4km. source directions say property on both sides;use plans and field survey to confirm precise parcel placement.

ten authentic source photos/plans. frontage photo14june2023;parcel/pond photos24november2023. junction photo is access context,not direct property frontage. navigation/map agree13.99566,100.32616,reference point not surveyed boundary. price/direct-sale status checked15september2026. contact sam02-686-1888,sales@sam.or.th or line@samline quoting1t1460.') ;
INSERT INTO public.organization_verifications (organization_id, verification_type, status, source_url, evidence_note, reviewed_by_user_id, reviewed_at) VALUES (sam_organization_id, 'listing_authority', 'verified', 'https://www.sam.or.th/site/npa/detail.php?id=8412&keyref=', 'Official SAM page 8412 identifies SAM as asset holder and direct-sale contact for 1T1460.', admin_user_id, now()) ;
INSERT INTO public.organization_audit_logs (organization_id, actor_user_id, action_code, entity_type, entity_public_id, metadata) VALUES (sam_organization_id, admin_user_id, 'listing.publisher_verified', 'listing', 'd3301460-44cb-4a85-af37-947116008412', '{"reference_code":"1T1460","source_page_id":8412,"source_image_count":10,"coordinate_source":"sam_navigation_href","duplicate_check":"no matches"}'::jsonb) ;
END $$;
COMMIT;
